invertase/react-native-firebase

- .flowconfig
- package.json
The consequence of this is that **flow will not run in this project** unless you have `flow@0.40.x` installed. One solution to this is adding `flow-bin` to this package's devDependencies.
> add version to .flowconfig

- ios/RNFirebase.xcodeproj/project.pbxproj
- lib/modules/crash/index.js
CrashReporting was not working on iOS, because the CrashReporting ios files were not included in the project and the build target. firebase.crash().log resulted in an "cannot read property 'log' of undefined" error. 
I added RNFirebaseCrash.h and RNFirebaseCrash.m to ios project and build target.
Renamed lib/modules/crash class name from Analytics to Crash
Again, since I'm no iOS dev, please have a look before you merge :)
> fixed CrashReporting on iOS

- lib/modules/database/reference.js
This is a bit of a strange one. 
I think as more of an artefact of inheritance than actual utility, the web Reference API includes a `ref` property that - from what I can gather - just returns itself.
See https://firebase.google.com/docs/reference/js/firebase.database.Reference#ref for more information.
This pull request adds that method in the interest of being consistent with the web API.
> [js][database] Add ref property for consistency with web API

- tests/.gitignore
- tests/__tests__/src/tests/pendingTestTests.js
- tests/lib/TestRun.js
- tests/lib/TestSuite.js
- tests/src/actions/TestActions.js
- tests/src/reducers/testsReducers.js
- tests/src/screens/Test.js
**Don’t run focused pending tests**
Currently pending tests that are focused are run (because being focused supersedes being marked as pending).
This pull request changes the behaviour of the test suite so focused pending tests are not run, allowing greater flexibility when focusing on specific groups of tests. 
**Show full test description on Test screen**
Currently there is no way to view the full description of tests. This can be an issue for the more specific tests, with longer descriptions. 
This pull request shows the full test description on the test screen.
> [Test Suite] Test Suite Improvements

- lib/modules/database/reference.js
- lib/utils/index.js
> Revert to old flow syntax (always named function arguments)

- android/build.gradle
There are more recent versions of the Firebase SDKs available, so this provides
a simple version bump.
To make this easier in future, I extracted the number to a variable.
> Bump the Firebase version

- lib/modules/config/index.js
There's a Flow error that I can't figure out why exactly is happening, but that can be fixed by annotating the `values` variable.
This PR annotates that variable and fixes the error.
The difference can be seen with these two examples:
- [With error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYA5gKZ4BqAhjBuQM4AUA1uQJ6MBcYAggCcBNDgB4AyngEEspAHwBKMAG9UYMDmKM8YAG50GjdQF4VAXzVgocAWGYxKYAmFMAGADRgHJU+y4A6b1I8AAsAbicwUS9yLAiCAGoEpVV1dX16JgBtP0YsggBdApdzSwt1AUoMARIMw1QzIA)
- [Without error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYA5gKZ4BqAhjBuQM4AUA1uQJ6MBcYAggCcBNDgB4AyngEEspAHwBKMAG9UYMDmKM8YAG50GPFQG1J02QF1eAeQBGAK3L4AvmAC8K52rBQ4AsMwwlGAE7mAADAA0YEEkHuxcAHSxpHgAFgDcIWCiMeRYWQQA1EVKqurq+vRMxgmMxgQWFmHKXuptYAKUGAIkVYaozkA)
> [Flow fix] Annotate `values` in RemoteConfig#getValues

- docs/migration-guide.md
after following the migration guide to the letter, i was unable to install the 11.0.0 versions of firebase packages. i checked out the official DIY guides and saw that there was a google-services bump, too.
the error message: 
```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
> Could not find com.google.firebase:firebase-core:11.0.0.
Required by:
Lifekeyrn:app:unspecified
> Could not find com.google.firebase:firebase-messaging:11.0.0.
Required by:
Lifekeyrn:app:unspecified
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 2 mins 50.32 secs
```
> adds missing android step to v1/v2 migration guide

- lib/modules/crash/index.js
* I found that `crash().report(Error)` does not work, since it returns empty when error object does not contain `code`.
* `code` is only included in `FirebaseError`. Plain `Error` object does not contain `code`.
* Thus, I removed logic to check `code` in error object in `report()` function.
> Support javascript plain error object in crash.report

- android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java
- docs/modules/storage.md
- ios/RNFirebase/storage/RNFirebaseStorage.m
This fixes issues in iOS and android and allows to specify meta data according to the corresponding [type definition](https://github.com/invertase/react-native-firebase/blob/master/index.d.ts#L198).
In iOS it wasn't working at all because they use the key "metadata" for "customMetadata" (see [here](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Storage/FIRStorageMetadata.m#L40) and [here](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Storage/FIRStorageConstants.m#L55)). I tried importing their key name from [there](https://github.com/firebase/firebase-ios-sdk/blob/master/Firebase/Storage/FIRStorageConstants.m#L55) and use it in my fix but I'm a Java/JS dev and don't know if that's possible in objective C (I think it's not).
> Fix custom metadata

- docs/modules/storage.md
Currently the docs are not in sync with the code here. When using the docs code, errors are swallowed (unhandled promise exception). I noticed that there is a [TODO](https://github.com/invertase/react-native-firebase/blob/master/android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java#L351) which would make the current docs correct but at the moment neither android nor iOS support the event error handler.
> fixed documentation of putFile with progress error handling

- docs/installation-ios.md
the `use_frameworks!` method doesn't start but ends with an exclamation mark.
> correct method name

- android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java
- index.d.ts
- ios/RNFirebase/auth/RNFirebaseAuth.m
@chrisbianca Pull request for `linkWithCredential()` capability with `PhoneAuthProvider`. (re: https://github.com/invertase/react-native-firebase/issues/119#issuecomment-326510174)
This allows someone to link a phone to a currently logged in user, or sign the user in.
To test:
```
firebase.auth().signInWithPhoneNumber(phoneNumber)
.then(confirmResult => this.setState({ confirmResult }))
```
Set the credential object with the six-digit SMS code (`codeInput`):
```
let credential = {
provider: 'phone',
token: this.state.confirmResult._verificationId,
secret: codeInput
};
```
- If there is a logged-in/anonymous user, call: `firebase.auth().currentUser.linkWithCredential(credential);`
- If no one is logged in, call: `firebase.auth().signInWithCredential(credential);`
> [auth][phone] Allow for linkWithCredential() for PhoneAuthProvider.

- ios/RNFirebase/messaging/RNFirebaseMessaging.m
Set opened_from_tray true if a local notification is clicked from notification center/tray.
Currently its only set for a remove_notification line 131.
> Set opened_from_tray for local_notification

- ios/RNFirebase/messaging/RNFirebaseMessaging.m
Set opened_from_tray true if a local notification is clicked from notification center/tray
(cherry picked from commit b7d4b3c)
> [v2.x.x] Set opened_from_tray true for local notification

- docs/installation-android.md
I ran into this problem trying to follow your installation instructions.  The build kept failing with errors stating that it was unable to resolve the firebase packages. 
I could see that the 11.2.x packages weren't included in the latest Google Repository (58) and the latest release notes (https://developers.google.com/android/guides/releases) state that "Google Play services dependencies are now available via maven.google.com", so I added the Google Maven reference to the root build.gradle and it resolved the problem.
> Update with Google Maven reference

- lib/modules/auth/user.js
> [auth][unlink] Call native function instead of 'FirebaseAuth'

- lib/modules/firestore/DocumentSnapshot.js
> [firestore] Fix _metadata not defined error in DocumentSnapshot

- ios/RNFirebase.xcodeproj/project.pbxproj
If you install the library from `master` it causes compilation issues (missing `RNFirebaseStorage.m`).
`storage` and `Products` had the same id of `134814211AA4EA7D00B7C361`.
I re-added the `storage` directory to the project in order to fix this issue.
> Fix compilation issue on iOS on `master`

- ios/RNFirebase.xcodeproj/project.pbxproj
Allows using `react-native-firebase` without CocoaPods. Instead Frameworks can be added manually in `/ios/Firebase` without having to mock an `/ios/Pods` directory.
Related to: https://github.com/invertase/react-native-firebase/issues/153
> Add search paths for ios/Firebase when not using CocoaPods

- lib/modules/database/reference.js
Right now the following code will be broken under v3.x.x:
```
async function() {
await ref.transaction(
function(foo) {
// deal with foo
},
function(error, committed, ss) { 
// additional work on complete callback
},
true     
);
// NOTE: Code from here will never execute because promise above never gets resolved
}
```
v2 will work because the promise is always resolved, v3 does not because it now depends on whether the promise is resolved in the completion callback
@kurtvan
> Make sure the promise is resolved/rejected for transaction

- android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdMobUtils.java
- ios/RNFirebase/admob/RNFirebaseAdMob.m
Smart Banner Landscape on iOS should have a height of 32 points in landscape.
For this purpose we need to use "kGADAdSizeSmartBannerLandscape" when the Screen is in Landscape mode.
https://developers.google.com/mobile-ads-sdk/docs/dfp/ios/banner
> add smartbanner landscape for iOS

- ios/RNFirebase/links/RNFirebaseLinks.m
Fixes #661 on iOS.
Problem was due to not handling Firebase calling onOpen instead of iOS.
See: [https://stackoverflow.com/questions/45415731/firebase-dynamic-links-not-survive-installation](https://stackoverflow.com/questions/45415731/firebase-dynamic-links-not-survive-installation)
Steps to reproduce.
1. Uninstall App
2. Create Dynamic Link in Firebase Console
3. Click on Dynamic Link on real device.
4. Install App. (via Xcode)
5. Dynamic Link not returned when calling _getInitialLink()_ on first open after install.
> iOS Dynamic Links now 'Survive' installation.

- lib/index.d.ts
The typescript typings for Crashlytics related functions are missing now. So this PR adds them.
Thanks for this library!
> [typings][typescript] Add missing types for Crashlytics

- ios/RNFirebase/storage/RNFirebaseStorage.m
Made change requested by @chrisbianca via Discord chat. New versions of react-native require that all NSNumber arguments are explicitly marked as `nonnull` to ensure compatibility with Android.
Only changed for a few storage methods. The other method exports with NSNumber will probably need to be updated as well, but I did not have a project setup to test them.
> Set NSNumber to nonnull for storage config calls

- ios/RNFirebase/links/RNFirebaseLinks.m
- lib/modules/links/index.js
Relates to #717 
There was a missing else in the short dynamic link creation of the ios native module, which in case of error, caused to resolve to be called after reject.
Regarding try/catch in the javascript module: they are essential since the are thrown exceptions from the input validation functions.
> Fix short link crash

- package.json
https://github.com/opencollective/opencollective-postinstall
Why || exit 0 in scripts.postinstall?
Since we are adding the dependency in devDependencies, the script ./node_modules/.bin/opencollective-postinstall won't be installed in production. Therefore, the postinstall script will return an error and will interrupt the npm install process. Adding || exit 0 makes sure that this postinstall script always returns true.
> Add '|| exit' 0 to opencollective

- ios/RNFirebase/links/RNFirebaseLinks.m
Fixed the issue that was causing a crash in my application:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
0   CoreFoundation                      0x000000011310e12b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00000001127a6f41 objc_exception_throw + 48
2   CoreFoundation                      0x000000011314e0cc _CFThrowFormattedException + 194
3   CoreFoundation                      0x0000000113022951 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
4   CoreFoundation                      0x00000001130227db +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
5 …
```
> Fixed: attempt to insert nil object from objects[0]

- lib/index.d.ts
Fixes #774 
Have kept this commit small and only touched the parts of the code that needed to change in order to resolve the linked issue. Can now access `auth` (and other modules) using this syntax:
```
import firebase from 'react-native-firebase';
firebase.auth().signInAnonymously().then(........);
```
The current method of access is still supported:
```
import firebase from 'react-native-firebase';
firebase.app().auth().signInAnonymously().then(........);
```
> [typings][Typescript] Fix TS definitions so modules can be accessed from the default export

- lib/index.d.ts
- package.json
- tsconfig.json
I've noticed that there were some lingering errors in the typescript declaration file and that it's really easy to make these small syntax errors when editing the file.
When you then try to use this project in a TypeScript application you will have a lot of trouble because your TypeScript compiler (`tsc`) will always throw them as errors. 
This PR introduces typescript as a devDependency and adds a `tsconfig.json` to configure the compiler to be fairly strict and only look at `lib/index.d.ts` without scanning for other files.
Further, a new npm task is added to `package.json` called `validate-ts-declarations` which just starts `tsc` with the options specified in tsconfig.json.
The validate-ts-declarations command is also added as a prerequisite for `build-lib`. This means that generating …
> TypeScript compiler validation of lib/index.d.ts

- lib/modules/config/index.js
- lib/utils/emitter/EventEmitter.js
- lib/utils/index.js
I understand that you are working on improving the Flow types and doing some rewriting. But I think I found a long hanging fruit, that I tried to fix.
A few places `react-native-firebase` is not using literal values (`string`) for Flow strings types, but object wrapper (`String`). This seems like a bug to me... And this actually causes a project using  remote config to fail Flow validation:
```
Error: src/main.js:139
139:         .getValue('hasExperimentalFeature')
^^^^^^^^^^^^^^^^^^^^^^^^ string. This type is incompatible with the expected param type of
126:   getValue(key: String) {
^^^^^^ String. See: node_modules/react-native-firebase/dist/modules/config/index.js.flow:126
```
https://flow.org/en/docs/types/primitives/
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5g4CMAXIXgE4CWWA …
> Flow: Use literal values for strings 

- ios/RNFirebase/config/RNFirebaseRemoteConfig.m
In case the app is offline and the consumer of this library is using Remote Config, it is perfectly fine to get a [`FIRRemoteConfigErrorInternalError`](https://firebase.google.com/docs/reference/ios/firebaseremoteconfig/api/reference/Enums/FIRRemoteConfigError) error, but there is really no reason to show a red error while developing.
Instead, we should leave it up to the consumer of this library to handle any errors.
It seems that only that only `RNFirebaseRemoteConfig.m` should be fixed to not use `RCTLogError` where we also reject.
`RNFirebaseMessaging.m` is also using `RCTLogError` but actual errors where `here is no completion handler with completionHandlerId`.
> Remove error log from RNFirebaseRemoteConfig

- lib/modules/database/Reference.js
Currently `ref.once()` don't reject properly when a firebase call fails. This pull request fixes this and allows developers to properly handle those cases.
It could probably easiest be demonstrated by disallowing a path in in the database rules and than try a query like this:
```js
firebase.database()
.ref(`not/allowed/path`)
.once('value')
.then(snap => {
console.log(snap instanceof Error); // true
console.log(snap.val); // undefined (because it is not a snapshot...)
})
.catch(err => {
// Never called, but is expected to be called
});
```
This pull request aline with the behavior of the firebase web sdk.
> [database][js] Reject promise instead of resolving an error object

- lib/modules/config/index.js
In https://github.com/invertase/react-native-firebase/pull/832 I fixed some incorrect usage of not using the literal values (`string`) for Flow strings types, but object wrapper (`String`) inside the remote config code.
Turns out I clearly missed two cased. : )
> [types] Use literal values for strings

- lib/index.d.ts
Currently returns void rather than a promise which causes TypeScript compilation to fail.
> FIX: Types for requestPermissions on iOS

- tests/README.md
- tests/package.json
One link was pointing to a `react-native-firebase-tests` repo and the other to the old site.
> Fix broken link for test documentation

- ios/RNFirebase/analytics/RNFirebaseAnalytics.m
In newer versions of react-native `dispatch_async` in `setCurrentScreen` causes mixed order. It's obvious if you make several calls of `setCurrentScreen` and `logEvent` in a small amount of time.
See: https://github.com/facebook/react-native/blob/0.54-stable/React/Base/RCTBridgeModule.h#L112
> fixes races bug in react-native > 0.52

- android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdMobUtils.java
The request checked if the `contentUrl` key was present but then tried to get the `setContentUrl` key which caused a crash.
> Fix contentUrl in AdRequest on Android

- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java
I noticed that firebase.notifications().cancelAllNotifications() has no effect on android phones. All scheduled notifications still appear. The propsed change fixes this. It was "inspired" by https://stackoverflow.com/questions/35341682/cancel-the-scheduled-android-notification/35342066#35342066
> fix cancelAlarm on android

- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java
when allowing users to pick a sound from RingtoneManager, RNFirebaseNotification should detect we are passing a Uri instead of trying to load this file from our bundle.
> allow using ringtones from RingtoneManager

- android/build.gradle
React Native projects with multiple native dependencies often end up unintentionally relying on a variety of Android SDK versions, which can lead to unpredictable build-time failures or even run-time crashes. Many libraries (see, e.g., react-community/react-native-maps#2047) have been moving to a system of allowing the solution [recommended by google](https://developer.android.com/studio/build/gradle-tips.html#configure-project-wide-properties) of having the root project set properties with the desired dependency versions. This PR implements that solution for `react-native-firebase`.
> android: allow root project to specify dependency versions

- ios/RNFirebase.podspec
Not sure when this broke, but this fixes compilation when used in a
project that pulls the dependency using CocoaPods and Xcode 9.3
Otherwise I was getting the following error:
`'Firebase.h' file not found with <angled> include; use "quotes" instead in RNFirebaseUtil.h`
This is the content of the `Podfile`
```ruby
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
```
> Fix podspec so compilation works when RNFirebase is set in the Podfile

- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java
ClassCastException was thrown on Android 8.1 while trying to schedule
local notification. Use try-catch approach instead of relaying on the
default parse value.
> Fix ClassCastException while parsing fireDate

- android/src/main/java/io/invertase/firebase/notifications/DisplayNotificationTask.java
- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseBackgroundNotificationActionReceiver.java
- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseBackgroundNotificationActionsService.java
- lib/index.d.ts
- lib/modules/notifications/AndroidAction.js
- lib/modules/notifications/types.js
There are some cases when local notification action should be handled in
background eg. snoozing the reminder. In case of it launching app UI is
not necessary and would be confusing for the end user.
Therefore there should be a way to handle local notification action in
background.
For this reason new property 'runInBackground' was added to the
AndroidAction class and TypeScript type.
Also new broadcast receiver and service were implemented to handle
properly background actions.
In order to run particular action in background user need to set its
'runInBackground' property to 'true', eg:
```js
...
.android.addAction(new firebase.notifications.Android.Action("snooze",
"ic_snooze", "Snooze").setRunInBackground(true))
```
Then create a background asynchronous handler:
```js
const …
```
> Implement handling of Android actions in background

- android/src/main/java/io/invertase/firebase/notifications/DisplayNotificationTask.java
Once the notification is created the promise was not being resolved so in a situation where the user is waiting on the promise to complete, they would not get a callback and in case a user used async/await this would cause the app to get stuck at that point.
> Resolve display notification promise

- ios/RNFirebase/RNFirebase.m
- ios/RNFirebase/analytics/RNFirebaseAnalytics.m
- ios/RNFirebase/storage/RNFirebaseStorage.m
Trying to upload an image in a detached [ExpoKit](https://github.com/expo/expo) project will deadlock from thread issues.
---
I've replaced `dispatch_sync(dispatch_get_main_queue(), ^{});`  with `RCTUnsafeExecuteOnMainQueueSync(^{});` to fix this.
I only hit the error in the `RNFirebaseStorage.m` but it seems like the `RNFirebaseAnalytics.m` and `RNFirebase.m` modules could also have the same issue.
`RCTUnsafeExecuteOnMainQueueSync` checks to see if the method is being executed on the main thread before trying to sync to the main thread. 
If you try to sync on the main thread while on the main thread, you hit a deadlock.
You can read more about it here: [StackOverflow](https://stackoverflow.com/questions/12379059/why-is-this-dispatch-sync-call-freezing?utm_medium=organic&utm_source=google_ …
> Fixed Deadlock

- lib/modules/notifications/AndroidNotification.js
This commit adds a missing method to `firebase.notifications.AndroidNotification`.
> Closes #1216 : AndroidNotification.setVisibility does not exists

- lib/modules/notifications/types.js
This commit changes `firebase.notifications.Android.Importance.None` to the value specified by Google reference [here](https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_NONE).
> Closes #1213 : Incorrect definition of Android.Importance.None

- android/src/main/java/io/invertase/firebase/notifications/DisplayNotificationTask.java
@chrisbianca ,
Currently, RNF does not support __drawable__ resources for images passed to the `setBigPicture` and `setLargeIcon` methods of AndroidNotification. On the other hand, RN does not support __mipmap__ resources as Image.source uri, which means duplicating these resources in both folders.
The icon in this notification is set through `.android.setLargeIcon('ai_medical')` (mipmap resource):
This icon in this card is set by `Image source={ uri: ic_medical }` (drawable resource):
This commit adds support for "drawable" to the `setBigPicture` and `setLargeIcon` methods.
Not sure if RN determine the correct folder/size of the result, but at least `BitmapFactory.decodeResource (getResources(), drawableId)` can decode drawables (I don't know how you make a test for this).
Platform: …
> Adds support for drawable resources to AndroidNotification

- android/src/main/java/io/invertase/firebase/instanceid/RNFirebaseInstanceId.java
- ios/RNFirebase/instanceid/RNFirebaseInstanceId.m
- lib/index.d.ts
- lib/modules/iid/index.js
- tests/ios/Podfile.lock
- tests/src/tests/iid/iidTests.js
- tests/src/tests/iid/index.js
- tests/src/tests/index.js
I've added support for `deleteToken()` as well as the other form of `getToken()`. This allows for someone to request or delete FCM tokens for sender IDs other than the default senderid. I also added some tests for instanceId methods - they don't do much but at least will break if someone broke the native implementations.
* [deleteToken](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#deleteToken(java.lang.String,%20java.lang.String))
* [getToken](https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceId.html#getToken(java.lang.String,%20java.lang.String))
> adds support for getToken(string,string) and deleteToken()

- android/src/main/java/io/invertase/firebase/notifications/DisplayNotificationTask.java
This fix makes defaults option work in Android as intended, and this makes function calls more flexible.
```js
const notification = new firebase.notifications.Notification();
// It works
notification.android.setDefaults(firebase.notifications.Android.Defaults.All);
// It works too
notification.android.setDefaults([
firebase.notifications.Android.Defaults.Sound, 
firebase.notifications.Android.Defaults.Vibrate
]);
```
I hope this helps.
> [Android] Fix setDefaults in Notifications.

- android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabase.java
Updated RNFirebaseDatabase.java to use appName if provided.
To test:
Create android app without google-services.json and call initializeApp() in JS code.
> Allow Android apps to use initializeApp() to configure firebase database

- ios/RNFirebase/admob/BannerComponent.m
https://github.com/invertase/react-native-firebase/issues/437
This disables bannerAds on 32bit devices. But this is far better than letting them  crash.
> Prevent crashes on 32bit devices

- android/build.gradle
- bridge/android/build.gradle
- tests/android/build.gradle
Build failed for Android, need to update fabric tools version.
`The minimum supported version of the Crashlytics plugin (io.fabric.tools:gradle) is 1.25.4. Project 'react-native-firebase' is using version 1.25.1. See https://issuetracker.google.com/79997489 for details.`
Environment
Application Target Platform: Android
Development Operating System: macOS High Sierra
Build Tools: gradle 4.8
React Native version: 0.53.3
React Native Firebase Version: 4.2.0
Firebase Module: Crashlytics
> Update fabric tools version to 1.25.4

- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java
When I try to use scheduling notifications, If `fireDate` is in the past, the notification is displayed immediately. This is probably not the intended operation. especially, in the process of rebooting.
```
1) 2018-07-05 10:00:00 => OK
2) 2018-07-06 10:00:00 => OK
3) rebooting and register alarm in past time (2018-07-04 10:00:00)
4) 2018-07-06 10:05:00 => Wrong
```
So time adjustment is required for proper operation.
I hope this helps.
> [Android] Fix for setting past time in the scheduling.

- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotifications.java
this is a follow-up on https://github.com/invertase/react-native-firebase/pull/1337: I somehow missed out that we can do the following simplification since `notification.getBody()` and `notification.getTitle()` both return null if none are specified. If somebody isn't sure if those calls return null, there is still the `@Nullable` annotation that tells that.
> simplify obtaining notification title and body

- src/index.d.ts
- src/index.js
- src/modules/core/firebase.js
*I will be happy to add tests. Unfortunately, I can't find any documentation for testing / testing types, and I'm not really sure what to add to test types. http://invertase.io/react-native-firebase/#/contributing/testing no longer seems to link to the right place.*
This is an update to the firebase exports to allow importing individual firebase modules. This allows you to do things like `import { database } from 'react-native-firebase';` instead of having to do `import firebase from 'react-native-firebase';` and then `firebase.database()`, etc.
Additionally, separate modules have been created for TypeScript importing to match the original firebase sdk. This allows you to do things like:
```
import { database } from 'react-native-firebase';
import { DataSnapshot } from …
```
> Improving type definitions to better match firebase-js-sdk

- ios/RNFirebase/links/RNFirebaseLinks.m
This PR fixes getInitialLink to resolve to null value in case of custom url. After briefly debugging, it seems firebase handleUniversalLink completion block is never called causing unresolved promise.
> [iOS] Fix getInitialLink to handle unresolved url

- src/index.d.ts
The token (or idToken) can be also be null on the credential method. Modifies the signature of the method to allow for that.
https://firebase.google.com/docs/reference/js/firebase.auth.GoogleAuthProvider#.credential
> Type declaration of AuthProvider.credential allows null token

- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotifications.java
Issue: https://github.com/invertase/react-native-firebase/issues/1462
Fixes naming issue that causes android native method to error
> BUGFIX: ReactMethod createChannelGroups() name fix

- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotifications.java
This pull request is for https://github.com/invertase/react-native-firebase/issues/1478
Fixes Android Oreo & higher devices that experience NPE when trying to delete a channelGroupId that is unknown to the system.
> Guard against NPE in deleteChannelGroup

- android/src/main/java/io/invertase/firebase/Utils.java
Prior to this change, this utility in some rare cases would return true that Activity was in the foreground, however, React Native was still in the process of resuming, this, for example, led to crashes in HeadlessJS Notification tasks: "Tried to start task RNFirebaseBackgroundMessage while in foreground, but this is not allowed."
---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:
- 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
- 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
- 👉  Star this repo on GitHub ⭐️
> [android][utils] `isAppInForeground` not accounting for React Native LifecycleState

- android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java
- ios/RNFirebase/auth/RNFirebaseAuth.m
- src/index.d.ts
- src/modules/auth/User.js
- tests/e2e/auth/user.e2e.js
Regarding the `updatePhoneNumber` method, the documentation states 
>The following methods are not supported in RNFirebase as they cannot work in the React Native environment or have a different implementation.
I didn't see any reason why we couldn't support it, so went ahead and made an implementation. 
I've tried it manually on iOS and Android but didn't include any E2E tests as it requires some changed settings in the firebase account and could see phone auth is absent from current E2E suite. Please advice on how to proceed or if they should stay omitted for now.
> [auth] Support updatePhoneNumber

- android/src/main/java/io/invertase/firebase/invites/RNFirebaseInvites.java
changed REQUEST_INVITE to value below 2^16 to fix error requestCode must be in 16 bits error
Issue is here: https://github.com/invertase/react-native-firebase/issues/1458
> Fix for Invites Module error requestCode must be in 16 bits

- src/index.d.ts
'createShortDynamicLink' should accept a link as well as a type parameter, similar to 'createDynamicLink'. 
See documentation here: https://rnfirebase.io/docs/v4.3.x/links/reference/links#createShortDynamicLink
> Fix typings to for `createShortDynamicLink`

- android/build.gradle
CI build was failing on this error
```
* What went wrong:
A problem occurred configuring project ':react-native-firebase'.
> Could not resolve all files for configuration ':react-native-firebase:classpath'.
> Could not resolve io.fabric.tools:gradle:1.25.4.
Required by:
project :react-native-firebase
> Could not resolve io.fabric.tools:gradle:1.25.4.
> Could not get resource 'https://jcenter.bintray.com/io/fabric/tools/gradle/1.25.4/gradle-1.25.4.pom'.
> Could not GET 'https://jcenter.bintray.com/io/fabric/tools/gradle/1.25.4/gradle-1.25.4.pom'.
> Read timed out
```
https://docs.fabric.io/android/changelog.html#fabric-gradle-plugin
> Update Fabric gradle plugin version

- android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java
- tests/e2e/storage/storage.e2e.js
solves: #1591 using the first solution:
> 1. Still consider the invocation a success, providing downloadURL as null.
Can some maintainer help me with the new test case? I need a file with permission to upload but not to download.
> Returning null as downloadUrl in upload task

- android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java
- ios/RNFirebase/firestore/RNFirebaseFirestoreDocumentReference.m
- src/index.d.ts
- src/modules/firestore/FieldValue.js
- src/modules/firestore/utils/any.js
- src/modules/firestore/utils/serialize.js
- tests/e2e/firestore/fieldValue.e2e.js
Add methods arrayRemove and arrayUnion to work with arrays in firestore.
Fixes #1389
https://github.com/invertase/react-native-firebase-docs/pull/134
> [Android][IOS][Firestore] add arrayRemove and arrayUnion to FieldValue 

- android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessaging.java
- ios/RNFirebase/messaging/RNFirebaseMessaging.m
- src/index.d.ts
- src/modules/messaging/IOSMessaging.js
- src/modules/messaging/index.js
Fixes #1511
The user should have the freedom when to call the registerForRemoteNotifications from application instance as described in firebase doc https://firebase.google.com/docs/cloud-messaging/ios/client#register_for_remote_notifications
And expose APNS token is very handy for debugging device token sync issue in iOS. This is not a standard firebase method.
- invertase/react-native-firebase-docs#137
N/A
[IOS] [FEATURE] [MESSAGING] - Add IOSMessaging module for APNS specific methods.
--- …
> Add IOSMessaging module for APNS specific methods

- src/index.d.ts
Ran prettier on index.d.ts and added AuthListenerCallback to typescript declaration file and pass it to auth listeners
[TYPES][ENHANCEMENT] [AUTHENTICATION] - Update TS types for auth listeners
---
> Run prettier on index.d.ts & Add auth listener callback type

- ios/RNFirebase/auth/RNFirebaseAuth.m
- It closes #1677.
- `onAuthStateChanged` sometimes is not fired after app is reloaded on iOS.
- I checked it on `v5.1.0`.
- I found followings on debugging.
- When the app is reloaded, `dealloc` sometimes is not called. So, deallocation task does not work.
- iOS native callback addAuthStateDidChangeListener works well.  
- `emitter.bridge` is null when JS `onAuthStateChanged` is not fired.
- I added deallocation task using `RCTInvalidating`.
- ref: https://stackoverflow.com/a/38161889
- How to reproduce
- https://github.com/invertase/react-native-firebase/issues/1677#issuecomment-440154916
[IOS][BUGFIX] [FirebaseModule] - Fix authStateChanged is not called after app is reloaded 
---
Think `react-native-firebase` is great? Please consider supporting the project …
> Fix authStateChanged after app is reloaded (fixes #1677)

- src/modules/notifications/IOSNotifications.js
There is a typo in IOSNotifications.backgroundFetchResult.failure which causes calling IOSNotification.complete with notifications.ios.backgroundFetchResult.failure to throw an error:
"Argument 1 () of RNFirebaseNotifications.complete could not be processed. Aborting method call."
Constant exposed from native module is backgroundFetchResultFailed and not backgroundFetchResultFailure.
- [ x] Supports `iOS`
NA
[JS] [BUGFIX] [NOTIFICATIONS] - Fix backgroundFetchResult.failure
--- …
> Fixes #1772

- ios/RNFirebase.xcodeproj/project.pbxproj
React Native dropped support on iOS 8 since 0.56
Without this, it'll fail on Release with error:
`Could not build module 'Darwin'` etc
---
> Upgrade iOS version to iOS9

- ios/RNFirebase/firestore/RNFirebaseFirestoreDocumentReference.m
There was a minor error in the iOS logs which showed that newer versions of the iOS Firebase SDK were returning `NSNull` instead of `nil`. (See #1788 for info.) This small PR adds a check for `NSNull` on top of `nil`, and the log error does not show up any more. 
- (n/a) Supports `Android`
- (n/a) Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
- (n/a) Flow types updated
- (n/a) Typescript types updated
Tested by:
1. Updated the line of code in react-native-firebase, and copied that change to an existing project I have which utilizes react-native-firebase
2. Observed the native iOS logs, and the error message no longer showed up. Previously, a couple hundred lines of this error would display.
[IOS][BUGFIX] [Firestore] - Fixed iOS log …
> Fixes #1788 NSNull vs nil issue

- ios/RNFirebase/notifications/RNFirebaseNotifications.m
Currently only didReceiveRemoteNotification: fetchCompletionHandler: are handle async by the JS complete method. This allows some time to perform tasks in background however the userNotificationCenter: didReceiveNotificationResponse: withCompletionHandler completion handler is called immediately which means not much time to perform tasks in background (about 1 sec from my experience) and calling complete from JS is meaningless.
This enhancement handles the NSUserNotificationCenter completionHandler in a similar way the  fetchCompletionHandler is handled.
- [x ] Supports `iOS`
[IOS][ENHANCEMENT] [NOTIFICATIONS] - handle NSUserNotificationCenter completion handlers
---
Think `react-native-firebase` is great? Please consider supporting the project with any of the …
> Handle UNUserNotificationCenter completionHandlers

- android/src/main/java/io/invertase/firebase/messaging/RNFirebaseInstanceIdService.java
- android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessaging.java
- android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessagingService.java
- ios/RNFirebase/messaging/RNFirebaseMessaging.m
- src/modules/messaging/index.js
- tests/android/app/src/main/AndroidManifest.xml
- tests/e2e/messaging/messaging.e2e.js
- tests/index.android.js
- tests/package.json
Closes #1510, #1754 
- https://github.com/invertase/react-native-firebase-docs/pull/155
- [IOS] [BUGFIX] [MESSAGING] fix getToken() always returning initialToken (#1510)
- [ANDROID] [NOTICE] [MESSAGING] deprecate `RNFirebaseInstanceIdService` in favour of `FirebaseMessagingService`s onNewToken event. Remove this service from your `AndroidManifest.xml`
- [IOS] [ANDROID] [INTERNAL] [MESSAGING] `getToken` & `deleteToken` now use Firebase InstanceID token management apis (with an `FCM` scope).
--- …
> [messaging] getToken/deleteToken/onTokenRefresh improvements

- ios/RNFirebase/links/RNFirebaseLinks.m
I ran into the issue described in https://github.com/invertase/react-native-firebase/issues/1589 ; specifically, a ECONNABORTED when returning to my app (while the app was in the background) from a click on a dynamic link (in my case, it was specifically a password-less email login link).
The comments in that issue pointed to some suggested workarounds present in a discussion on AFNetworking; I specifically read through this comment https://github.com/AFNetworking/AFNetworking/issues/4279#issuecomment-447108981 and implemented suggested workaround (B) which was to, in the case of this specific error condition, retry the request.
I'm not sure if this should be against a point-release branch instead of master, please forgive me if it's pointing to the wrong branch.
- [N/A] Supports …
> [IOS][BUGFIX] [DynamicLinks] Retry resolving the dynamic link once when the error is an ECONNABORTED

- src/index.d.ts
It improves `httpsCallable` interface by allowing to specify shape of input output with generics.
If none specified it will default to `any` (current implementation).
> adds option to specify shape of callable function params and result

- packages/analytics/lib/index.js.flow
Does not match the documentation and reality https://rnfirebase.io/docs/v5.x.x/analytics/reference/analytics#setCurrentScreen
```js
// @flow
import firebase from 'react-native-firebase';
firebase.analytics().setCurrentScreen('test') // error currently
```
[TYPES] [ENHANCEMENT] [ANALYTICS] - Make second argument for `.setCurrentScreen(screenName, screenClassOverride)` optional (Flow.js)
> Update flow type for analytics.setCurrentScreen()

- docs/analytics/ios.md
Per discussion on #2071 - added a note about the cocoapod required for automatic audience metric collection on iOS
I will send a separate one to v5
I am skipping the template, this is a docs change as discussed already, please don't shoot me :pray:
> docs: noted iOS pod needed for iOS audience stats

- src/index.d.ts
- src/modules/auth/phone/PhoneAuthListener.js
Fixes #2041
As mentioned in #2041 I *believe* there is a type error in PhoneAuthSnapshot.
I wasn't able to successfully use Typescript to extract the phone auth error code until I started using this patch (via patch-package)
I've been using it in production for a few weeks now so I could do i18n on phone auth messages by using the code as an i18n lookup key
I do not know or use Flow. I am not sure if flow types are affected but it stands to reason they would be?
I am not pleased that the NativeError type already existed in a deeper hierarchy and I copied it up here, but it does work. If I were better at creating type definitions I'd generalize it
The linked bug has all the data that led me to this conclusion, and using this patch in production with standard …
> [TYPES][BUGFIX][AUTHENTICATION] - Change type PhoneAuthSnapshot.Error to NativeError

- android/src/main/java/io/invertase/firebase/messaging/RNFirebaseMessagingService.java
- android/src/main/java/io/invertase/firebase/notifications/RNFirebaseBackgroundNotificationActionReceiver.java
The Message module and Notification module will accidentally acquire a `PARTIAL_WAKE_LOCK` by calling `HeadlessJsTaskService.acquireWakeLockNow()`, and this lock will always hold if no js tasks to consume it. This will drain off user phones' battery.
This happens when you init the Message module without the optional step of adding `RNFirebaseBackgroundMessagingService` to the `AndroidManifest.xml`.
The `context.startService()` will not throw on unregistered service, [it just `return null`](https://developer.android.com/reference/android/content/Context.html#startService(android.content.Intent)). Adding a null check will handle the cases.
On the Notification module, the service is undocumented, should have fewer people using it.
Tested on a private production …
> [Messaging] Add null check to acquire WakeLock on Android

- tests/README.md
- tests/android/build.gradle
- tests/ios/Podfile.lock
- tests/ios/testing.xcodeproj/project.pbxproj
- tests/manual-patches/detox+9.1.2-no-extract.patch
- tests/manual-patches/detox+9.1.2.patch
- tests/package.json
- tests/patches/detox+9.1.2.patch
- tests/yarn.lock
As near as I can tell the v5.x.x branch does not currently build (it certainly doesn't pass CircleCI) owing to various areas of bitrot
This PR aims to start with the v5.3.1 tag (the most recent release tag? maybe I missed one) and simply get it working before building on it for future releases
The change involved patching:
- detox: manually on the existing dependency so that XCode 10.2 may be used (even though you fixed CircleCI to 10.1, can't test it locally without this). Was just a 'SWIFT_VERSION' change
- detox: via patch-package so that gradle versions will work with RN0.59 (android API 28)
- jet: a branch off the v0.3.0 tag from jet to allow gradle overrides (android API 28 here too)
All of that is just toolchain work, nothing semantic was done.
Android and iOS installs and builds …
> [GENERAL][BUGFIX][build] - patch v5 build toolchains for XCode10.2 & RN0.59 compatibility

- src/index.d.ts
- src/modules/firestore/Query.js
- tests/e2e/firestore/query.e2e.js
Added `.isEqual` method to Query instances so that `useCollection` from `react-firebase-hooks/firestore` works with firestore queries, as it does on web. This is PR is in the same vein as #2077.
I ran my newly-added tests on iOS and Android and they're passing when I run them as the only tests using `.only`. For some reason when running all of the tests it is failing at the crashlytics tests, even before applying my changes:
```
1) crashlytics()
log()
should set a string value:
You attempted to use a firebase module that's not installed natively on your iOS project by calling firebase.crashlytics().
Ensure you have the required Firebase iOS SDK pod for this module included in your Podfile, in this instance confirm you've added "pod 'undefined'" to your Podfile
See …
```
> [JS][FEATURE][FIRESTORE] - Implement isEqual in Query

- android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdMobRewardedVideo.java
- android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdmobInterstitial.java
Fixes #1792
There is a problem that UnityAds does not work with Admob Mediation.
It seems some mediation adapters such as UnityAds, adcolony, appodeal require ActivityContext.
This PR fixes the issue.
* [ x] Supports `Android`
* **LINK TO DOCS PR HERE**
My fork is already released for my games in production.
I started seeing getting a traffic to UnityAds via AdmobMediation which used to be zero.
So far I am not seeing any obvious bug due to this change, but I have no idea how to make sure this change won't introduce any regression.
[ANDROID][BUGFIX][ADMOB] - Fixed an issue UnityAds wasn't working with Admob Mediation due to the lack of ActivityContext
> [ANDROID][BUGFIX][ADMOB] Fix Admob crash from UnityAds with Admob Mediation

- android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestore.java
- ios/RNFirebase/firestore/RNFirebaseFirestore.m
- src/index.d.ts
- src/modules/firestore/index.js
- src/utils/index.js
- tests/e2e/firestore/firestore.e2e.js
The cacheSizeBytes prop could now be set from the client applications.
```jsx
firebase.firestore().settings({cacheSizeBytes: 10000000})
```
- **https://github.com/invertase/react-native-firebase-docs/pull/185**
> [FEATURE][FIRESTORE][cacheSizeBytes]: expose SDK cacheSizeBytes prop

- package.json
As discussed with you guys, and paired with the docs PR here https://github.com/invertase/react-native-firebase-docs/pull/187 - I want to give the installed base a big heads-up that we may issue breaking releases in v5 minor releases during the transition to v6
I don't intend to propose anything crazy but sometimes maintenance requires a break when you are dependent on underlying libraries out of your control, and this gives us the space to break if we need to
This completes the effort to notify - we notify on package install, in the install docs, and in the release notes now, no one can say we didn't try, and the community should be able to self-resolve issues so it doesn't cause a support burden
I worked on it until it displayed correctly on install, it looks like this:
This can be …
> docs: add breaking change notice to postinstall

- .gitignore
- RELEASE_PROCESS.md
- android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java
- ios/RNFirebase/RNFirebase.m
- package.json
This one needs more than review, it needs collaboration or I'm lost :-) - you might want to do this (assuming my commands are correct, in an attempt to make this copy-pastable):
```shell
git remote add mikehardy git@github.com:mikehardy/react-native-firebase.git
git fetch mikehardy
git co mikehardy/release-process-5.4.3
```
...so it is easy to edit and just type away then push to this branch in my repo, I'm fine rebasing etc to collaborate and that way you/we just type once?
The idea is:
* bump the versions as requested
* figure out how to actually turn the crank on this thing
I did not edit package.json or anything as I'm not sure what release machinery you've already built
---
- 👉 …
> [RELEASE][VERSIONS][DOCS] - bump versions to 5.4.3, document release process

- src/index.d.ts
I looked in all the official firebase SDKs for different platforms and they all say that ID is guarranteed to be as string. Also, it seems that when the typescript definitions were added, they followed the flow types which also said id could be null, but the flow types have since changed to correctly reflect the official SDKs, while the TS types remained as they were.
Links to SDKs:
https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentReference.html#id
https://firebase.google.com/docs/reference/js/firebase.firestore.DocumentSnapshot.html#id
https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference/Classes/DocumentReference#/c:objc(cs)FIRDocumentReference(py)documentID
https://firebase.google.com/docs/reference/swift/firebasefirestore/api/reference …
> [BREAKING CHANGE][TYPES][Firestore] Document id can't be null

- RELEASE_PROCESS.md
- android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java
- ios/RNFirebase/RNFirebase.m
- ios/RNFirebase/analytics/RNFirebaseAnalytics.m
- package.json
- src/modules/links/DynamicLink.js
- src/modules/links/types.js
The 5.5.0 release had a crashlytics compile bug that slipped through because of a combination of problems allowing that chunk of code to not even attempt compilation in CI
The 5.5.1 release includes a PR #2256 from @maxkomarychev that fixed the compile issue *and* (important for the future) fixed the podfile issue that allowed it to slip through and re-enabled v5 crashlytics for iOS in CI
The 5.5.0 and 5.5.1 release still had a compile error for Analytics #2259 - I'm still combing through release docs on the pods but analytics isn't in CI (:scream:) which is the same way the crashlytics error slipped through. I'll work on that later
And now 5.5.3 fixes issue #2262 with the new domainURIPrefix links parameter - I didn't plumb that breaking change correctly, this one isn't in my app yet so …
> [BUGFIX] - patch releases to 5.5.3

- ios/RNFirebase.podspec
Ref https://github.com/invertase/react-native-firebase/issues/252#issuecomment-501692286
I tested this  like that:
- installed rnfirebase v5 via yarn
- modified podspec in `node_modules/react-native-firebase/ios` after install (as in the pr)
- run `pod install` (cocoapods read the podspec)
- I can build my app without the 3 tricks mentionned in https://github.com/invertase/react-native-firebase/issues/252#issuecomment-501692286
[IOS][BUGFIX] [ios/RNFirebase.podspec] - Allows react-native-firebase to be used via Podfile with use_frameworks!
--- …
> Allows react-native-firebase to be used via Podfile with use_frameworks!

- src/index.d.ts
close #2302
The type of storage task event is wrong.
---
> [STORAGE][TYPES][BUGFIX] TaskEvent was incorrectly typed TaskState

- packages/storage/package.json
rnpm options are not needed, even breaking `react-native link` command execution.
[ANDROID] [BUGFIX] [STORAGE]
> [v6] Removed rnpm options from @react-native-firebase/storage package.json

- package.json
This partially reverts #2335 so that link works on react-native 0.59
Someone mentioned they were having problems and when I checked my demonstrator app I noticed the same thing. New react-native-firebase links on react-native 0.59 fail now
They generate an import of `io.invertase.firebase.RNFirebaseAdMobPackage` (which does not exist) instead of the RNFirebasePackage, so the build then fails
There must be an underlying reason but I haven't investigated, as a partial revert so that the rnpm block is there works for now
My demonstrator app fails if I just use react-native-firebase@5.5.5 directly, but if I add 5.5.4, do the link, then add '5' (which brings in 5.5.5) the link works. 
I further tested it locally by doing 5.5.5 directly, adding this patch, then doing …
> [ANDROID][BUGFIX][link] - react-native@0.59 still needs rnpm

- src/index.d.ts
Fix notification data TypeScript type to `{ [key: string]: string }`
instead of `any` matching the flow type https://github.com/invertase/react-native-firebase/blob/e411598315a395d339c9a80cdc58538942277329/src/modules/notifications/types.js#L219
Documentation should also be updated here
https://rnfirebase.io/docs/v5.x.x/notifications/reference/Notification#data
N/A
[TYPES] [BUGFIX] [NOTIFICATIONS] - Change notification data type definition to `{ [key: string]: string }`
> Fix notification data type definition

- packages/app/android/src/main/java/io/invertase/firebase/common/UniversalFirebasePreferences.java
- packages/app/ios/RNFBApp/RNFBPreferences.m
- packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreCommon.java
- packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreModule.java
- packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreStatics.java
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCollectionModule.h
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCollectionModule.m
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.h
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.m
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreDocumentModule.h
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreDocumentModule.m
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreModule.m
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreTransactionModule.h
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreTransactionModule.m
Currently calling settings multiple times or after usage throws an error/warning. This moves it off to shared prefs and sets the latest settings the first time the app is requested.
> Move Firestore settings to share preferences

- android/build.gradle
I needed this in my project to successfully use this with modern (divergent) numbers for the support libraries - core is at 1.0.2 but support-v4 is at 1.0.0 and media is at 1.0.1 etc.
use 'supportV4Version' in your ext{} block in build.gradle to use it
Assuming this passes CI and is good to go, I'll update the docs repo for changelogs for a 5.5.7 release etc (and I'm traveling back from vacation right now, I could work to shape up a 5.5.7 release and release it if that helps)
This was supposed to be in #2445 but I didn't make a feature branch and clobbered the change 🤦‍♂ I am using this locally in production though
---
- 👉 …
> [BUGFIX][Compile][Android] - backwards-compatible AndroidX dependency

- pages/migrating-to-v6.md
The module links in the v6 migration page did not work. Clicking them returned Page not found. Adding `v6/` to them should fix the issue.
[GENERAL][BUGFIX] - Fix module links in the v6 migration page
> Fix module links

- android/build.gradle
I'm not too familiar with Gradle/Groovy, but this line was giving me errors when I tried to leave both `supportLibVersion` and `supportV4Version` unspecified.  I think there were multiple issues with the way it's written:
1. It refers to `supportVersion` which isn't specified anywhere (probably meant `supportLibVersion`?)
2. No need for a `safeExtGet` for that value as it's already done a few lines above.
3. The fallback value is getting recognised as literally `$supportVersion`, without substitution, because it's wrapped in single quotes rather than double.
> Fix v5.x.x build.gradle fallback

- packages/ml-vision/ios/RNFBMLVision/RNFBMLVisionBarcodeDetectorModule.m
Most of the barcode types have nullable properties, which were returning as `nil`, causing the app to crash if it hit them. This PR forces a check and returns `null` if they do not exist.
> fix(vision): Improve null checks on iOS #2744

- docs/crashlytics/ios.md
Changed the name of a Pod that the Crashlytics iOS installation guide references to be the correct one. I assume this was caused by copy-and-pasting.
---
> Fix incorrect pod name in documentation.

- packages/database/ios/RNFBDatabase/RNFBDatabaseQuery.m
An exception is raised when removing listeners on iOS, for example onAuthChanged listener. This causes a crash when reloading application using the built-in reloading feature in React Native. The issue has been traced down to the following method: -[RNFBDatabaseQuery removeAllEventListeners]. Currently, this is what the code looks like:
```Objective-C
@interface RNFBDatabaseQuery
@property NSMutableDictionary *listeners;
/* ... */
@implementation RNFBDatabaseQuery
- (void)removeEventListener:(NSString *)eventRegistrationKey {
FIRDatabaseHandle handle = (FIRDatabaseHandle)[_listeners[eventRegistrationKey] integerValue];
if (handle) {
[_query removeObserverWithHandle:handle];
[_listeners removeObjectForKey:eventRegistrationKey]; // <= removes the value while still being in the 'for loop' in …
```
> fix(database): Fix crash when removing listeners at RN reload

- docs/ml-vision/android.md
The package name is incorrect for this import.
Just a faulty import statement. Note that several other errors prevent the ml vision kit from working as intended, but this will fix the package not found error.
Look at node_modules/@react-native-firebase/ml-vision/android/src/reactnative and check the package names.
Just merge, should be no issue
-----
> docs(vision): Fix incorrect Android package name

- docs/remote-config/ios.md
replaced the correct podspec `RNFBRemoteConfig`
```
[!] No podspec found for `RNFBConfig` in `../node_modules/@react-native-firebase/remote-config`
```
---
> docs(remote-config): fix a typo in doc RNFBRemoteConfig manual install

- docs/in-app-messaging/ios.md
replaced the correct podspec `RNFBInAppMessaging`
```
[!] No podspec found for `RNFBFiam` in `../node_modules/@react-native-firebase/in-app-messaging`
```
---
> docs(in-app-messaging): fix typo in doc ios manual install

- docs/messaging/ios.md
iOS Manual Linking for RNFBMessaging
Was missing
---
> iOS Manual Linking for RNFBMessaging

- packages/auth/lib/PhoneAuthListener.js
Fixes #2639
promiseDefer was incorrectly used in PhoneAuthListener, causing an error reported by https://github.com/invertase/react-native-firebase/issues/2639#issuecomment-539963660
- [x ] Supports `Android`
- [ x] Supports `iOS`
> fix(auth): Fix exception in PhoneAuthListener

- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.m
Fixes an iOS issue where Firestore settings are incorrectly set multiple times instead of once, as highlighted in #2866
> fix(firestore,ios): Settings incorrectly set multiple times

- packages/analytics/lib/index.js
triggering analytics().logAddToCart firebase event resulted in sending "addPaymentInfo" event to firebase analytics
After inspecting source code its clear this was almost a "typo"  as "add_payment_info" is defined few lines above and it was probably a simple omission.
This is a simple bug - but crucial for anyone who tries to use more advanced ecommerce pre-defined firebase events (like adding/removing from cart etc. ecommerce funnels etc.).
Tested on Android - with my fix I can now send correct add_to_cart events which are then successfully registered in Firebase Analytics
-
-
--- …
> fix(analytics): Use correct add_to_cart event name

- packages/storage/ios/RNFBStorage/RNFBStorageCommon.m
It seems that the metadata coming back from firebase is occasionally nil, which throws an exception in NSDictionary, so this probably just hides a deeper problem. But, it's better than crashing!
- use Storage putFile on iOS, should not see a crash related to `nil at object[1]`
- this was about a 1/5 bug for me, so reproducing might be tricky
[IOS     ][BUGFIX    ] [Storage] - fix occasional crash when uploading file with putFile
---
- 👉 …
> fix(storage,ios): Handle null Storage metadata values

- packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobInterstitialModule.java
- packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobRewardedModule.java
This fixes issue #2912 
Ideally, `interstitialLoad()` and `rewardedLoad()` would return a promise that can be rejected in case that the Activity is null (or any other required condition is not met). I did not want to make any API changes though, so, for now, I've resorted to dispatching an error event with a custom message when the Activity is null.
I've already tested the code and it's being used in a production app. If `getCurrentActivity()` returns null, both "load" calls send the error event correctly, and both "show" calls reject the promise correctly and then exit the method.
---
- 👉 Donate via [Open …
> fix(admob): add null checks for getCurrentActivity() usages

- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
hasPermission checked if alert notification enabled and returned false on iOS 12 and up when provisional permission granted or Notification Center is enabled. This PR changes hasPermission to check authorizationStatus is equal to or above UNAuthorizationStatusAuthorized (value is 2), because it might be a UNAuthorizationStatusProvisional(value is 3).
Previously, on iOS 12 requestPermission would return true, but hasPermission returned false. This PR fixes it, and both return true.
See https://developer.apple.com/documentation/usernotifications/asking_permission_to_use_notifications
---
- 👉 Donate via [Open …
> fix(messaging,ios): hasPermission checks authorizationStatus

- .github/ISSUE_TEMPLATE/Bug_report.md
For v6 I really need to see firebase.json and package.json  or I don't know what versions people are running anymore as they aren't in the other files
> Add JS in bug report for package.json/firebase.json

- packages/auth/lib/index.d.ts
This one had me confused for quite a bit myself.
> docs(auth): fix incorrect auth credential example

- packages/app/lib/common/index.js
This export is not valid when being parsed by typescript or webpack. The updated version is equivalent.
> Fixes default re-export syntax

- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/auth/lib/index.d.ts
- packages/auth/lib/index.js
- packages/auth/lib/providers/AppleAuthProvider.js
Implements Apple Authentication support for Firebase Authentication, tested usage via our [`@invertase/react-native-apple-authentication`](https://github.com/invertase/react-native-apple-authentication) package.
Fixes #2884.
Test code:
```js
import appleAuth from '@invertase/react-native-apple-authentication';
import { firebase } from '@react-native-firebase/auth';
// ...
const appleAuthRequestResponse = await auth.performRequest({
requestedScopes: [
AppleAuthRequestScope.EMAIL, 
AppleAuthRequestScope.FULL_NAME
],
});
const { nonce, identityToken } = appleAuthRequestResponse;
if (identityToken) {
const appleCredential = firebase.auth.AppleAuthProvider.credential(identityToken, nonce);
const userCredential = await firebase.auth().signInWithCredential(appleCredential); …
```
> feat(auth): add initial support for Apple auth provider

- packages/messaging/README.md
This PR just updates the README.md of the Messaging package to fix the link to the product on the firebase page.
> docs(messaging): fix broken Firebase link

- docs/storage/index.md
This is a suggested way to improve the error documentation of this package. I've talked more about my feelings about the current state of the error documentation in #3033
I've also suggested some enhancements to the [NaticeFirebaseError doc page](https://invertase.io/oss/react-native-firebase/v6/app/reference/nativefirebaseerror) that will hopefully come through sooner or later.
> Improved error documentation of Clouds module - Fixes #3033

- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- tests/package.json
`keyDynamicLinkDomain` in the `actionCodeSettings` is already a string, no need to cast it to string again.
Fixes #3085
> fix(auth,ios): remove unnecessary string cast

- docs/perf/quick-start.md
#2886 and other users (including me!) copied and pasted the quick start example and started modifying away into my project, and then all my HTTP requests started throwing rejections. Turns out, I didn't read the module docs correctly - a metric must be started before you can use it!
This docfix should hopefully help prevent some frustrated googling.
Thanks for an amazing library :blue_heart:
N/A
N/A
[INTERNAL][minor] [perf] - Quick start documentation update for HTTP metrics
(I don't know if this is needed for doc updates!)
---
:fire:
> docs(perf): Add HTTP metric.start command to example

- pages/quick-start/ios-firebase-credentials.md
update `ios-firebase-credentials` docs: should open `.xcworkspace` if using Pods and in reverse, open `.xcodeproj`
> chore(docs): select the right xcode project/workspace to open

- docs/crashlytics/quick-start.md
I believe there should also be a place in the documentation that should explicitly explain that the firebase.json file is and where it should go.
Any idea where I should put that?
> docs(crashlytics): improve Crashlytics docs in response to #2724

- docs/in-app-messaging/android.md
In build, error occurred below.
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Project with path ':@react-native-firebase_in-app-messaging' could not be found in project ':app'.
```
So, I fixed document.
> docs(iam): fix gradle settings path in manual linking docs

- docs/functions/ios.md
Fix naming conflict
- [x ] Supports `iOS`
[IOS][BUGFIX] [Pods]
> docs(functions): fix ios manual linking typo

- packages/messaging/lib/index.d.ts
- packages/messaging/type-test.ts
It wasn't specified that it should actually return a promise.
If it doesn't return a promise, you start to get `cannot resolve .then of undefined` errors.
> fix(messaging) fix typescript signature for setBackgroundMessageHandler

- pages/quick-start/new-project.md
Getting started guide claims one can start new RN project with react-native-firebase integrated with next template:
`npx @react-native-community/cli init --template=@react-native-firebase/template <name>`
Latest react-native cli init will try running pod install automatically.
In case user performing install has not updated cocoapods repo index for a while, pod install will fail due to latest Firebase modules version are not found in current cocoapods repo.
@mikehardy filed an issue  to _cli_ repo https://github.com/react-native-community/cli/issues/752
until its resolved, we can update docs with extra step that solves the issue.
Solution is to run 'pod update' or 'pod install --repo-update' manually after 'cli init' fails
- [x ] Updated the documentation in the [docs …
> docs(ios): extra Pod repo update step incase 'cli init' fails

- pages/quick-start/ios-firebase-credentials.md
`@import Firebase` requires enabling Modules in Xcode. By using this syntax `#import <Firebase.h>` it would save some time for people not to google why `@import` is not working.
---
> docs(*): change `@import Firebase` to `#import <Firebase.h>`

- packages/auth/lib/ConfirmationResult.js
- packages/auth/lib/providers/OAuthProvider.js
'types' can only be used in a .ts file.
> fix(types): remove types in ConfirmationResult.js

- src/index.d.ts
Fixes #3129 
See description of #3129.
[TYPES] [ENHANCEMENT] [MESSAGING] - Change `RemoteMessage.data` property type from `Object` to `{ [key: string]: string }`.
---
> fix type of RemoteMessage data property

- packages/auth/lib/index.d.ts
In the docs for auth the signOut() function is called by doing `firebase.auth().currentUser.signOut()`
This is supposed to be ` firebase.auth().signOut()` 
I think the docs on the websites are based on these comments so I fixed it here.
> docs(auth): fixes wrong signOut method call in types

- packages/database/lib/index.d.ts
There was formally no actual use of the .push method in it's documentation example snippet.
> docs(database): added missing use of .push() type docs

- docs/remote-config/quick-start.md
In the quick start section of the Remote Config docs, getValue is called as if it's asynchronous, which I don't believe it is.
> docs(remote-config): remove unnecessary await in example

- docs/messaging/quick-start.md
requestPermission example is missing `await` keyword.
> docs(messaging): add await keyword requestPermission

- packages/messaging/ios/RNFBMessaging/RNFBMessagingAppDelegateInterceptor.m
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
This PR fixes the logic on `registerForRemoteNotifications` and a race condition that caused issue #2657.
The native call to `registerForRemoteNotifications` shouldn't be aborted even if `isRegisteredForRemoteNotifications` returns `true`. This is because after successful registration on the first boot, on successive boots the app `isRegisteredForRemoteNotifications` will return true, and then `registerForRemoteNotifications` won't be called again and therefore the APNSToken will never be set (because it is only set on the `didRegisterForRemoteNotificationsWithDeviceToken` swizzled by the `FIRMessagingRemoteNotificationsProxy`). If the APNSToken is null when calling getTokens, then the call to `[[FIRInstanceID instanceID] tokenWithAuthorizedEntity] ` on `getToken` fails.
This is what the …
> Fix 2657 error getting remote notifications tokens

- ios/RNFirebase/database/RNFirebaseDatabase.m
I came across a race condition while working on our app: https://github.com/celo-org/celo-monorepo/tree/master/packages/mobile
The exception raised is `createRepo called for Repo that already exists.` in `FRepoManager.m`
It happens when using a transaction and db listener at the same time after initializing firebase.
https://github.com/celo-org/celo-monorepo/blob/833c2d3d2341185dc141aec901c9b2828e776de6/packages/mobile/src/firebase/firebase.ts#L21
<details>
<summary>Exception stacktrace</summary>
<pre>
Exception 'createRepo called for Repo that already exists.' was thrown while invoking on on target RNFirebaseDatabase with params (
"[DEFAULT]",
"https://celo-org-mobile-int.firebaseio.com/",
{
appName = "[DEFAULT]";
eventType = value;
hasCancellationCallback = 0;
key = …
> Fix exception caused by a race condition in the database module on iOS

- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
Fixes #2657
This pull request solves the problems with `request permission` and `registerForRemoteNotifications` in messaging module.
When these methods are called, they simply fail without throwing any warnings or errors. Because of this, it was impossible to get the FCMToken.
The problem was that ` [[UIApplication sharedApplication] registerForRemoteNotifications];` should be called after `[[UNUserNotificationCenter currentNotificationCenter] requestAuthorizationWithOptions` as described in the [documentation](https://developer.apple.com/documentation/usernotifications/unusernotificationcenter/1649527-requestauthorizationwithoptions?language=objc)
There is some **code duplication** in this commit, but I think that is better for now, to help the reviewers.
After calling `request …
> requestAuthorizationWithOptions before registerForRemoteNotifications

- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingHeadlessService.java
This PR fixes https://github.com/invertase/react-native-firebase/issues/2592
#2592 is caused by race condition. While current logic [only executes this code after checking app is not in foreground](https://github.com/invertase/react-native-firebase/blob/f429699990b6d521d996479f2bed96b52bbdb8d8/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingService.java#L72), it's possible that app gets foreground when execution reached [here](https://github.com/facebook/react-native/blob/b55146f7763e4e9d6cc2fd54dde62d4e4289721f/ReactAndroid/src/main/java/com/facebook/react/jstasks/HeadlessJsTaskContext.java#L103) 
(See also 
https://github.com/invertase/react-native-firebase/issues/2592#issuecomment-584190439 ) for how to reproduce.
Fix is rather …
> fix(messaging): allow RNFirebaseMessagingHeadlessTask to run in foreground

- packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksModule.m
Fix bug for DynamicLinks for v6 on iOS: short dynamic links type never worked.
---
> fix(dynamic-links,ios): links options not correctly applied

- android/src/main/java/io/invertase/firebase/messaging/RNFirebaseBackgroundMessagingService.java
Same as https://github.com/invertase/react-native-firebase/pull/3311 but for v5.x branch. Below is copy from #3311 (class name is different but issue and fix is same)
This PR fixes https://github.com/invertase/react-native-firebase/issues/2592
#2592 is caused by race condition. While current logic [only executes this code after checking app is not in foreground](https://github.com/invertase/react-native-firebase/blob/f429699990b6d521d996479f2bed96b52bbdb8d8/packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingService.java#L72), it's possible that app gets foreground when execution reached [here](https://github.com/facebook/react-native/blob/b55146f7763e4e9d6cc2fd54dde62d4e4289721f/ReactAndroid/src/main/java/com/facebook/react/jstasks/Headless …
> Fix for 5.x - allow RNFirebaseBackgroundMessagingService to run in foreground

- packages/admob/RNFBAdMob.podspec
- packages/analytics/RNFBAnalytics.podspec
- packages/app/RNFBApp.podspec
- packages/auth/RNFBAuth.podspec
- packages/crashlytics/RNFBCrashlytics.podspec
- packages/database/RNFBDatabase.podspec
- packages/dynamic-links/RNFBDynamicLinks.podspec
- packages/firestore/RNFBFirestore.podspec
- packages/functions/RNFBFunctions.podspec
- packages/iid/RNFBIid.podspec
- packages/in-app-messaging/RNFBInAppMessaging.podspec
- packages/messaging/RNFBMessaging.podspec
- packages/ml-natural-language/RNFBMLNaturalLanguage.podspec
- packages/ml-vision/RNFBMLVision.podspec
- packages/perf/RNFBPerf.podspec
- packages/remote-config/RNFBRemoteConfig.podspec
- packages/storage/RNFBStorage.podspec
- packages/template/project/ios/Podfile
- tests/ios/Podfile
- tests/ios/Podfile.lock
First pass at addressing #3253 to allow release in 6.4.0 - there is no breaking changes as the default is currently `false`
For v7.0.0 we should make the default value `true` along with the RN min version set to 0.61.x +
`pod install` logs show flag being detected and used correctly;
---
> feat(ios): allow static_framework usage via Podfile global

- packages/functions/android/src/reactnative/java/io/invertase/firebase/functions/ReactNativeFirebaseFunctionsModule.java
Fixes #3326 
Makes the error thrown by Functions when a network IO error occurs consistent between iOS and Android.
N/A
[ANDROID][BUGFIX] [FirebaseFunctions] - change network IO errors to use code=UNAVAILABLE (matching iOS)
---
> fix(functions): throw UNAVAILABLE code on network IO errors

- docs/database/usage/index.md
I struggled a while with finding out how to switch the database URL for the [DEFAULT] firebase instance during runtime.
With version 5 it was very easy with simply passing the databaseURL to the database module.
The docs did not help unfortunately, so I tried a lot of ways which are documented in this ticket:
https://github.com/invertase/react-native-firebase/issues/3049
This PR shall help other people with the same situation too.
Furthermore, I hope to get valid feedback if the proposed implementation documented in this PR is actually correct.
It's a documentation update
> docs: update database usage with switching database URL

- .spellcheck.dict.txt
- docs/messaging/notifications.md
- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
Puts a safe check around #3463
> fix(messaging): add activity check to getInitialNotification

- docs/messaging/usage/index.md
Fix typo on [docs/messaging/usage/index.md](https://github.com/invertase/react-native-firebase/blob/master/docs/messaging/usage/index.md)
---
> docs(messaging): code typo on docs/messaging/usage/index.md

- docs/auth/social-auth.md
I was receiving developer_error with the instructions here. Following this suggestion fixed it: https://github.com/react-native-community/google-signin/issues/224#issuecomment-599171322 . In that video at this time the correct webClientId is visible on the top of the screen and it would not work otherwise for me: https://youtu.be/AHVaxhcoY98?t=2557
Could not find any here. This is relevant, however: https://github.com/react-native-community/google-signin/issues/224
- [ x] Yes
---
Think `react-native-firebase` is great? Please consider supporting the project with …
> docs(auth): fixed google sign-in with correct webClientId

- docs/admob/displaying-ads.md
The change is simple. I just found it right to propose a correction for the documentation. 
In the specific example the adUnitId variable is not used in the Banner's properties as it should be. So i replace the TestIds.BANNER with the unused variable adUnitId.
> docs(ads): replaces TestIds.BANNER with adUnitId in the Banner's props

- .spellcheck.dict.txt
- docs/analytics/screen-tracking.md
The `componentDidAppear` event is better suited than the `command` event, which doesn't fire when popping a screen natively (Android back button, iOS swipe back gesture) and in some other edge cases (e.g. `setRoot` with two components in the stack)
In addition, the componentId (usually auto-generated) is quite useless as a screen name, and componentName should be used instead.
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) …
> docs(analytics): refined react-native-navigation setCurrentScreen example

- packages/admob/RNFBAdMob.podspec
- packages/analytics/RNFBAnalytics.podspec
- packages/app/RNFBApp.podspec
- packages/auth/RNFBAuth.podspec
- packages/crashlytics/RNFBCrashlytics.podspec
- packages/database/RNFBDatabase.podspec
- packages/dynamic-links/RNFBDynamicLinks.podspec
- packages/firestore/RNFBFirestore.podspec
- packages/functions/RNFBFunctions.podspec
- packages/iid/RNFBIid.podspec
- packages/in-app-messaging/RNFBInAppMessaging.podspec
- packages/messaging/RNFBMessaging.podspec
- packages/ml-natural-language/RNFBMLNaturalLanguage.podspec
- packages/ml-vision/RNFBMLVision.podspec
- packages/perf/RNFBPerf.podspec
- packages/remote-config/RNFBRemoteConfig.podspec
- packages/storage/RNFBStorage.podspec
…xcept Analytics which should continue to reference Core.
iOS does not allow applications in the Kids category to collect Firebase analytics. Firebase has refactored their libraries to utilize the CoreOnly module instead of Core to accommodate this. Currently RNFirebase pods rely on Firebase/Core. Pull request updates RNFirebase pod files to utilize CoreOnly instead of Core (except Analytics)
Fixes #3570
Ran e2e tests without errors. Tested libraries I use locally in my application (app, auth, database).
---
Think `react-native-firebase` is great? Please consider supporting the …
> feat(ios): podspecs now utilize CoreOnly instead of Core

- docs/auth/phone-auth.md
Fixes a typo in the documentation for Phone Auth
:fire:
> docs(auth): fix typo in Phone Auth description

- docs/app/usage.md
I struggled a lot with simply switching the database URL within the [DEFAULT] app instance during run time.
I documented my solution in this ticket: https://github.com/invertase/react-native-firebase/issues/3049
This PR shall reflect my further findings when switching app instances.
It's a documentation update.
> docs: update usage of secondary app

- packages/storage/lib/index.d.ts
Fixes a typo in the documentation for the `ListResult` interface
:fire:
> docs(storage): fix typo in ListResult.items description

- docs/ml-vision/usage/index.md
Added the rebuild info (pod repo update command) to the Usage page of ML-Vision Kit. 
#3623 
🔥
> docs: add rebuild info to ML-Vision index-page

- packages/messaging/lib/index.d.ts
`messaging().onNotificationOpenedApp` returns a function that can be used for unsubscribing from this listener
currently it's typed as returning `void` and you will get type errors if you try to call the returned function.
🔥
---
> fix(messaging): onNotificationOpenedApp callable return type

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
Error code on Android should be `network-request-failed` when `FirebaseNetworkException` is throw.
Fixes #3654.
---
> fix(auth): use correct code on network exception

- docs/remote-config/usage/installation/android.md
The installation documentation for remote-config in android environment has the wrong import library. It is pointing to io.invertase.firebase.perf. instead of io.invertase.firebase.**config**
update the installation documentation for remote-config
No test required.
---
> docs(remote-config): correct import for android

- packages/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.m
Hi,
Currently receiving notifications with images will crash the app on iOS (Fixes #3447, #3616).
This is only the patch proposed by @actuosus, thanks to him 🙌 https://github.com/invertase/react-native-firebase/issues/3447#issuecomment-618639388
- Fix crash when receiving notification with an image on iOS.
- Simulate a notification on the Firebase console using your device FCM token
- Don't forget to upload a logo
- Profit! 😄
:fire:
> fix(messaging,ios): crash receiving notification with image

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/e2e/phone.e2e.js
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/auth/lib/ConfirmationResult.js
- packages/auth/lib/index.d.ts
BREAKING CHANGE: `confirm(verificationCode)` now return `UserCredentials`
Actually the Phone provider do not follow the Firebase Web SDK.
The [docs](https://firebase.google.com/docs/reference/node/firebase.auth.ConfirmationResult?authuser=0#confirm) said the confirm method should return an `UserCredential` and not only an `User`.
Related to [this issue](https://github.com/invertase/react-native-firebase/issues/2543)
Fixes #2543 
The method now return a UserCredential, but i have a curious issue. When I log the result using for exemple there few lines of code : 
```
const result …
```
> fix!(auth): confirm code returns User instead of UserCredential

- docs/database/usage/index.md
Replaced ';' (semicolon) with '.' (property access method) in examples of realtime listeners to get 'ref' property on 'database' function.
Replaced database();ref() with database().ref()
---
> dpcs: Update Docs for realtime listeners

- packages/messaging/ios/RNFBMessaging/RNFBMessaging+FIRMessagingDelegate.m
On iOS, calling `[FIRInstanceID instanceID] deleteIDWithHandler` causes a crash. I quite like this method since it enables me to drop all tokens generated until now, and make sure we won't send any more messages to this device (use case: user logout).
Not reported.
[messaging] Fixed a crash if the fetched token is null (typically when deleting the cloud messaging instance).
- My change includes tests: **NO** (but maybe it should!)
You can try to call `[FIRInstanceID instanceID] deleteIDWithHandler` in your app code (exposing it as a JS API would be welcome by the way!).
Thanks a lot for this project!
> fix(ios): handle nil messaging token

- packages/iid/RNFBIid.podspec
fixes #3746.
iOS Firebase InstanceId appears to be a dependency on messaging package, but no longer on core. Therefore, it is required as a dependency on RNFBId.
> fix(iid): RNFBid requires dep on instanceID

- package.json
- packages/app/e2e/config.e2e.js
- tests/README.md
- tests/ios/Podfile
- tests/ios/Podfile.lock
- tests/ios/testing.xcodeproj/project.pbxproj
The iOS test setup had steps that could be combined, additionally when you went to update pods FirebaseFirestore pre-compiled framework is pinned to master, so you have to bump the SDK in use to 6.27.0
This combines two test-related pod install steps to one, and moves the SDK so the install works
Additionally there was a test failing locally which I had to disable before local iOS tests worked - it's the separate second commit in case that's unacceptable I can back it out - it was one yak shave too far to fix it
tests: tests:ios:pod:install does full update, use SDK 6.27.0
--- …
> tests: update test project

- tests/android/app/build.gradle
soloader 0.8.0 has problems loading ABI-specific libraries in
universal APKs, this workaround appears effective and allows the
test APK to run on x86 emulators in developer environments
Can likely be removed when moving to react-native 0.63.0
https://github.com/facebook/react-native/issues/25923#issuecomment-594047945
> tests: bump soloader dependency to fix ABI lib load issues

- packages/ml-vision/ios/RNFBMLVision/RNFBMLVisionFaceDetectorModule.m
- tests/e2e/mocha.opts
fixes #3585 
I couldn't recreate the error reported by the users, but I do agree that the wrong type was being called for each of the face detecting options.
I also removed the unnecessary type casting for each if statement condition as it is already an integer.
Also, removed type casting to `CGFloat` as it is just a `typedef` for a `double` anyway.
> fix(ml-vision): convert options to correct type

- docs/storage/usage/index.md
The `putFile` docs reference the wrong variable in the first example.
Must be `taskSnapshot.totalBytes` instead of `task`.
---
> docs(storage): fix minor typo in storage docs

- packages/app/ios/RNFBApp/RNFBUtilsModule.m
The Catalyst SDK does not support `assets-library://` URLs (see #2698), which have been deprecated for many years. This patch fixes the build failure when compiling with the Catalyst SDK; requests for such assets will fail and log (the first time).
Fixes #2698 
Fixes compilation failures when targeting macOS Catalyst.
1. Initialize a new React Native app with `react-native init`
2. Integrate `@react-native-firebase/app`
3. Check the "macOS" platform box in Xcode to add Catalyst support.
4. Build for macOS.
🔥
> fix(app,ios): Build fails when targeting Mac (Project Catalyst)

- docs/index.md
Makes explicit that you need to be on the project root to run `npx react-native run-ios`
> docs: improve autolinking & rebuilding steps

- docs/messaging/usage/index.md
The [Clound Messaging > Usage](https://rnfirebase.io/messaging/usage#ios---requesting-permissions) docs on the Clound Messaging > page contain wrong code example, compared with the dedicated [Clound Messaging > iOS Permissions](https://rnfirebase.io/messaging/ios-permissions#reading-current-status) page.
Obsoletes #3761, #3849
Fix docs for Cloud Messaging: iOS - Requesting permissions
none
> docs(messaging): fix example for iOS - Requesting permissions

- packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m
This PR ensures that original delegate is always called when intercepting a notification response, even if the notification has been handled by RNFirebase.
> feat(messaging): Call original delegate when intercepting notification response on iOS

- packages/app/lib/utils/index.js
Previously was calling the incorrect native API from JS
With thanks to @Bardiamist for reporting
Fixes #3864
fix(android): call correct androidResolutionForPlayServices API (#3864)
---
> fix: correct androidResolutionForPlayServices API

- packages/dynamic-links/e2e/dynamicLinks.e2e.js
- packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksModule.m
Current implementation does not cover the case where `[[FIRDynamicLinks dynamicLinks] handleUniversalLink:linkURL completion:completion]` can return  `NO` without calling the completion block at all. ([See native iOS SDK method here](https://github.com/firebase/firebase-ios-sdk/blob/master/FirebaseDynamicLinks/Sources/FIRDynamicLinks.m#L443)).
`resolveLink()` promise never gets resolved when using a non-dynamic link. Android behaves correctly.
Test just hangs forever without the fix.
> fix(dynamic-links,ios): resolveLink() does not always resolve

- packages/messaging/lib/index.d.ts
it was already sent and correctly serialized / showing up, just not
available in typescript
https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage#public-long-getsenttime
fix(types): add sentTime to FirebaseMessagingTypes.RemoteMessage
I'm using the change directly via patch-package to access the sentTime property in a typescript project, it works
--- …
> fix(types): add sentTime to FirebaseMessagingTypes.RemoteMessage

- docs/crashlytics/android-setup.md
Title in the installation docs still mentioned fabric. Updated now.
> docs(crashlytics): remove reference to fabric

- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreSerialize.java
I have a brownfield use case where I do some firestore things in native code while doing most in Javascript.
For best code re-use in the app I sometimes want to send objects to the native code for further decoration before persisting to Firestore
Being able to re-use the existing serializer for that would be fantastic, and it's just two "public" markings away...
feat(firestore, android): allow FirestoreSerializer native re-use in brownfield apps
Using it already in my project via patch-package
---
Think `react-native-firebase` is great? Please consider supporting the project …
> feat(firestore, android): allow FirestoreSerializer native use

- packages/messaging/lib/index.d.ts
setBackgroundMessageHandler isn't an Android-only function.
> docs: setBackgroundMessageHandler isn't Android-only

- docs/storage/usage/index.md
Turns out that the bucket name isn't specified via `storage` directly but through the app instance
---
> doc(storage): fix multiple buckets example

- packages/firestore/e2e/Transaction.e2e.js
- packages/firestore/lib/FirestoreTransactionHandler.js
fixes #3830 
Firestore update: For every document you read in a transaction, you do not have to update/set. This is true for iOS, Android & web.
- Removed test.
> chore(firestore): remove check that each read document also needs to be written for a transaction

- docs/crashlytics/usage/index.md
There was a part of the Crashlytics documentation which was outdated as of the latest release (`8.1.1`).
Fixes #3908
> Removed references to `setUserName` and `setUserEmail` in Crashlytics docs

- docs/dynamic-links/usage/index.md
Burned hours of my time trying to figure out why my custom domain's deep link wasn't working. Finally found it was because it was not added to the info.plist file. Hope this helps others :)
---
> docs(links): add instructions on setting up Xcode for dynamic links with custom domains

- .github/ISSUE_TEMPLATE/Bug_report.md
Apparently github won't show a template with an about that is more than 200 chars
So our main bug report template was not showing up
---
> chore: update issue template "about" field

- docs/admob/displaying-ads.md
You guys forgot to add the AdEventType
you guys forgot to add the `AdEventType` without that it will throw errors that it can't find it.
- [X ] Yes
- [X ] `Android`
- [X ] `iOS`
- [X ] No
---
> add AdEventType

- docs/remote-config/usage/index.md
It has been used `asNumber` instead of `asBoolean` in the `resolves value to boolean` section.
This can lead to confusion.
>  docs: should be asBoolean instead of asNumber

- packages/messaging/lib/index.d.ts
I believe the `from` property was accidentally omitted from the `FirebaseMessagingType.RemoteMessage` interface. I've added it following the standards set by the rest of the properties.
> fix(messaging): added missing `from` property in Remote Message type

- packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java
Timezone.getOffset() provides result in milliseconds, but was being adjusted as if it were in seconds
Fixes #4053 with issue noticed and fix provided by @AidanHost
fix(android, timezones): timezone offset already in millis, do not adjust it
I am literally making this change directly in the github web UI and relying on the automated test to handle it.
The documentation linked appears very clear cut and the change is so small so that seems reasonably unreasonable
---
- 👉 Star …
> fix(android, timezones): timezone offset already millis, do not adjust it

- packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java
Correcting the timezone offset and timestamp conversion calculation
Follows on from #4055
---
> fix(core): timezone offset issue in util

- docs/index.md
Lots of the versions were very old, I pinned them to current stable
The most important one is the google services plugin to 4.3.3 though, it has
lots of serious issues in the 4.2.0 version specified
docs(core, README): update versions in install docs
---
> docs: update versions in install docs

- packages/iid/android/build.gradle
IID will fail if included / used directly (instead of as transitive dependency) because they stopped publishing the IID version in the BoM
This is being tracked upstream and I put breadcrumbs in the code that should help maintainers during version bumps
#3918 
https://github.com/firebase/firebase-android-sdk/issues/1077
build(android, iid): workaround iid version missing in upstream BoM
CI will blow up completely since it's a compile fail, if this doesn't work
---
- 👉 Star …
> fix(android,iid): workaround IID version missing in BOM w/concrete version

- .github/workflows/tests_e2e.yml
Android E2E is flaky, trying to isolate it
This increases logging for Android E2E and also puts a delay on the generated click stream as that appeared to be one failure mode
#4058
---
> Add Android E2E logging, delay tap input stream

- tests/android/app/build.gradle
- tests/android/build.gradle
- tests/android/settings.gradle
- tests/patches/detox+16.7.2.patch
Still working on de-flaking Android E2E
Even with the tap stream delayed, the extra logging from the previous merge showed the React Native UIManager's dispatch queues are sometimes permanently non-empty, blocking Detox from signalling it is ready on the app/detox-testee side.
This commit switches Detox to a compile dependency (from AAR) so we can patch-package it, then I hack out the UIManager espresso idle resource waiter completely.
This would potentially be a disaster in normal apps, but for our testing app is inconsequential since we perform no UI activities (and thus they should *never* block)
#4058 …
> tests: use Detox as compile reference, ignore UIManager queues

- packages/firestore/e2e/Query/onSnapshot.e2e.js
Noticed firestore collection snapshot listener unsubscribe test was flaky in CI, not sure why - quarantining it
#4058 
Picked it up here:
- https://github.com/invertase/react-native-firebase/pull/3751#issuecomment-674191390
- https://github.com/invertase/react-native-firebase/pull/4078#issuecomment-674190258
---
> tests(firestore): disable flaky onSnapshot unsubscribe e2e test

- .github/workflows/docs.yml
- .github/workflows/linting.yml
- .github/workflows/tests_e2e.yml
- .github/workflows/tests_jest.yml
Codecov continues to have transient failures, causing timeout and workflow failures
This updates all of the actions that I know have version bumps, but more importantly all the code coverage uploads are wrapped with the retry action which has proven to work so far
#4058 
---
> chore(github actions): update action versions, wrap codecov with retry

- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsModule.m
`assert(no)` was the original method recommended by Firebase but it turns out that it doesn't actually work (see https://github.com/firebase/firebase-ios-sdk/issues/6028 for more detail). They've subsequently updated the official doc:
https://firebase.google.com/docs/crashlytics/test-implementation?platform=ios
While no fixing https://github.com/invertase/react-native-firebase/issues/4026 completely, it's one step closer.
--- …
> fix: use the new recommended way to manually crash

- packages/dynamic-links/RNFBDynamicLinks.podspec
- packages/in-app-messaging/RNFBInAppMessaging.podspec
- packages/messaging/RNFBMessaging.podspec
- packages/remote-config/RNFBRemoteConfig.podspec
Removed remaining analytics dependencies from IOS podspecs. Analytics cannot be used in the IOS apps in the kids category. FirebaseCore no longer pulls analytics. Analytics can still be added separately and interop correctly with these modules.
Fixes #4072 
Ran jest and e2e tests successfully.
---
> fix(ios, analytics): remove now-optional analytics dependencies

- packages/crashlytics/RNFBCrashlytics.podspec
`@react-native-firebase/crashlytics` was still bringing in `Firebase/Analytics` pod on iOS which disqualifies apps from being in the kids category on the App Store
This came from the remaining `Firebase/Core` pod dep in `RNFBCrashlytics.podspec`, which is no longer necessary - `Firebase/CoreOnly` is sufficient and that dependency is satisfied transitively by `RNFBApp.podspec`
#4072 - initial issue
#4131 - initial PR that fixed almost all the modules
Interested parties @pabloearg and @dlockwo 
Title of PR
I overhauled my demonstrator script so that it could run in a '--no-idfa' …
> fix(ios, crashlytics): allow Crashlytics inclusion w/o Analytics

- packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
This should be viewed as a temporary fix.
A lot of people are reporting that the background data messages on iOS are not being delivered. The app wakes up, but the background listener doesn’t receive the message. Some apps that have a lot of JS apparently need more than the 2s timeout to be ready. So what happens is - app is started, 2s elapse, RNFBMessaging sends the message to the js handler, but the JS handler is not ready yet and misses the message. We mitigate this by delaying the delivery of the message to the JS side.
This solution however is not optimal becasue we are sending a completionHandler after about 25s which means that our JS code would have only 16 to do something with the data message.
A correct fix would be to figure out how to dispatch the message once the JS side is …
> fix: undelivered background data message ios

- docs/enabling-multidex.md
Fix typo 'sectino' at enabling-multidex.md. 
There is not a related issue.
Fix typo 'sectino' at enabling-multidex.md. 
It's not necessary tests
> docs: Typo correction at enabling-multidex.md

- packages/app/CHANGELOG.md
I believe peerDependencies are all set correctly so this should not be revelatory, but could save people time
A spot check of peer dependencies indicates yes, they are set correctly: https://github.com/invertase/react-native-firebase/blob/8fc2baa396441a2f1cfb5f56776eff96cb560358/packages/admob/package.json#L30
Not sure what else we can do?
#4154
--- …
> docs(app, CHANGELOG): Add note about upgrading all packages

- docs/remote-config/usage/index.md
- packages/remote-config/ios/RNFBConfig/RNFBConfigModule.m
- packages/remote-config/lib/index.d.ts
Updated iOS to match Android & Web. Updated types as well as documentation. 
[Web](https://firebase.google.com/docs/reference/js/firebase.remoteconfig.RemoteConfig#fetchandactivate) documentation & [Android](https://firebase.google.com/docs/reference/android/com/google/firebase/remoteconfig/FirebaseRemoteConfig#returns_4) documentation indicate:
- `fetchAndActivate` - should return `false` when local config values are up to date with backend config values.
- `activate` - should return `false` when all local config values are already activated.
fixes #2767
-  `fetchAndActivate` 
- Previous behaviour returned a boolean indicating if config values were activated
- New behaviour returns a boolean indicating if any config values were fetched remotely.
- `activate`
- Previous behaviour returned …
> fix(remote-config)!: fetchAndActivate API & activate API update

- packages/remote-config/lib/index.d.ts
A commit just to get a breaking change notice in the commit log for auto-population on semantic release.
Related #4157
```
BREAKING CHANGE:
fetchAndActivate
Previous behaviour returned a boolean indicating if config values were activated
New behaviour returns a boolean indicating if any config values were fetched remotely.
activate
Previous behaviour returned a boolean indicating if config values were activated
New behaviour returns a boolean indicating if any local config values were activated.
```
---
Think `react-native-firebase` is great? Please consider supporting the …
> docs(remote-config)!: update docs to be explicit about new behavior

- .github/workflows/tests_jest.yml
The retry sleep on coverage upload (a proven flake) was longer than the aggregate workflow timeout, which does not make sense of course...
chore(tests, jest): add time to jest test workflow timeout
---
> chore(tests, jest): add time to jest test workflow timeout

- packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreModule.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreModule.java
- packages/firestore/e2e/firestore.e2e.js
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreModule.m
- packages/firestore/lib/index.d.ts
- packages/firestore/lib/index.js
Support waitForPendingWrites() API
- Supports waitForPendingWrites() API
---
> feat(firestore): support waitForPendingWrites() API

- .github/workflows/linting.yml
Just noticed another tuning issue (via a workflow failure) where the extra time taken by the new retries was larger than the total time allowed for the workflow, which defeats the purpose. So this tunes up the timing on the linting workflow
---
> chore(lint): allow enough total time for retries to work

- packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
This PR is needed to fix problem reported in this issue https://github.com/invertase/react-native-firebase/issues/4104 .
https://github.com/invertase/react-native-firebase/issues/4104#issuecomment-683411140
Fixes #4104 
- [x ] Yes
- [ x] `iOS`
- [x ] No
Nothing to add.
> fix(ios, messaging): register background handler task

- .github/workflows/create_test_patches.yml
PR proposals will scale with the size of the community and it's engagement
The need for PR testing thus scales with size of community
Maintainer count does *not* scale with size of community though.
PR testing then needs to be done by the community
PR testing has barriers though, especially in a monorepo - it takes significantly more time to get set up to test then performing the actual test
This PR aims to close the loop from community PR proposals to the community being able to test PRs, by eliminating the setup barrier for community testers
Every PR now will have a set of patch-package patches generated, so they may be downloaded and exercised by anyone.
A future PR will post the artifact download link to the PR (and perhaps linked issues) along with copy-pastable shell script that …
> chore: create patch-packages artifact vs published release

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
Add apple.com Oauth Provider support for Android.
Motivation
There are several libraries around that support Apple Sign In for Android. The provider for Apple was not enabled, making it imposible to sign in with Firebase and Apple id_token as it requires a different credential builder. See https://firebase.google.com/docs/auth/android/apple#java_9
AppleAuthProvider support for Android.
Tested in conjunction with other Apple SIgn In library. I was able to sign in with Firebase using Apple id_token.
---
Think `react-native-firebase` is great? Please consider supporting the …
> feat(auth,android): Apple Oauth provider support for Android

- docs/app/utils.md
`utils` export from firebase/app is a function, not an object. So `utils.playServicesAvailability` resolve to undefined.
`utils` source code is [here](https://github.com/invertase/react-native-firebase/blob/master/packages/app/lib/utils/index.js)
If you follow the [documentation](https://rnfirebase.io/app/utils#android---checking-play-services) and check for Google Play Services availability, the example does not work on latest RNF version because the `utils` is a function, not a plain object where you can retrieve the `playServicesAvailability` key. 
- Fix  playServicesAvailability documentation example …
> docs(app): Fix playServicesAvailability documentation example

- packages/remote-config/package.json
Fixes #4197 - a 404 from npm package url
> fix: remote config repo url in package.json

- .github/workflows/tests_e2e.yml
It is in a race with the simulator itself booting, and 10
seconds was mostly losing the race. 30 seconds should be fine?
#4058 
---
> chore: delay ios simulator logging a bit more

- packages/in-app-messaging/android/src/main/java/io/invertase/firebase/fiam/UniversalFirebaseFiamModule.java
- packages/in-app-messaging/android/src/reactnative/java/io/invertase/firebase/fiam/ReactNativeFirebaseFiamModule.java
- packages/in-app-messaging/e2e/fiam.e2e.js
- packages/in-app-messaging/ios/RNFBFiam/RNFBFiamModule.m
- packages/in-app-messaging/lib/index.d.ts
- packages/in-app-messaging/lib/index.js
I want to use the  programmatic event triggering feature in Firebase In App Messaging described here
https://firebase.google.com/docs/in-app-messaging/modify-message-behavior?platform=android#trigger_in-app_messages_programmatically
No issues.
Support for In App Messaging's programmatic event triggering
It's not obvious how we can test whether the event was triggered.
There are no existing jest tests in the inappmessaging module
I'm not sure how to test this ...
> feat(inappmessaging): add support for triggering custom events

- docs/messaging/usage/index.md
Explain that only predefined colours can be used for `messaging_android_notification_color` property in `firebase.json` and add example of how to use a custom colour defined in the application
https://github.com/invertase/react-native-firebase/issues/3559#issuecomment-686754748
---
> docs(messaging): document how to use custom notification colour on Android

- packages/auth/lib/index.d.ts
You need to specify null when you want to remove the current user's photo
Currently, if you want to remove a profile photoURL, you need to specify NULL, but typescript will complain about it.
N/A
Fix: add missing type when removing profile photo
- [x ] Yes
- [ x] `iOS`
- [x ] I have updated TypeScript types that are affected by my change.
- [x ] No
N/A
--- …
> fix: Add missing null to profile update

- packages/remote-config/lib/index.d.ts
Clarify docs for config().fetch()
This is related to the recent API harmonization - `activate`/`fetchAndActivate` return booleans if-and-only-if they actually activated new values (not if a fetch failed or if nothing changed), and nothing else returns boolean
> docs(remote-config): fetch returns Promise<void>, not boolean

- packages/app/ios_config.sh
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsModule.m
PR spawned from discussion here https://github.com/invertase/react-native-firebase/discussions/4227
By my reckoning, I think there may be some behavior that is _maaaaybe_ not working as expected, and I also think there is some behavior that is _definitely_ not working as I'd expect it.
_Sorry if this is verbose, but some of this is very new for me so I wanted to be explicit. Also, apologies if I'm way off base on any of this_
> By default, Crashlytics automatically collects crash reports for all your app's users. [[1]](https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=ios)
App developers using Crashlytics can go out of their way to set `FirebaseCrashlyticsCollectionEnabled` to `false` to turn off automatic crash collection in their apps. Why would a dev do …
> fix(crashlytics,ios): Explicitly set crash collection setting to opt in or out for iOS

- docs/analytics/usage/index.md
According to `FirebaseAnalyticsTypes` `logSelectContent()` and  `logEvent()` are async functions.
---
> docs(analytics): analytics() methods are async

- docs/app/usage.md
Added a section + example under __Secondary Apps__ to highlight the need to use the credentials relevant to the platform.
Fixes #4272 
🔥
> docs(app): note about multiple platforms for secondary app

- packages/admob/RNFBAdMob.podspec
- packages/analytics/RNFBAnalytics.podspec
- packages/app/RNFBApp.podspec
- packages/auth/RNFBAuth.podspec
- packages/crashlytics/RNFBCrashlytics.podspec
- packages/database/RNFBDatabase.podspec
- packages/dynamic-links/RNFBDynamicLinks.podspec
- packages/firestore/RNFBFirestore.podspec
- packages/functions/RNFBFunctions.podspec
- packages/iid/RNFBIid.podspec
- packages/in-app-messaging/RNFBInAppMessaging.podspec
- packages/messaging/RNFBMessaging.podspec
- packages/ml-natural-language/RNFBMLNaturalLanguage.podspec
- packages/ml-vision/RNFBMLVision.podspec
- packages/perf/RNFBPerf.podspec
- packages/remote-config/RNFBRemoteConfig.podspec
- packages/storage/RNFBStorage.podspec
- scripts/_TEMPLATE_/RNFB_Template_.podspec
- scripts/_TEMPLATE_/ios/RNFB_Template_.podspec
On Xcode 12 some wild build errors occur when trying to build a React Native app. This is because the `'React'` pod is only an umbrella pod. See: https://github.com/facebook/react-native/issues/29633
See: https://github.com/facebook/react-native/issues/29633
* Uses 'React-Core' instead of 'React' pod in podspecs
> fix(ios, podspec): depend on React-Core instead of React

- packages/dynamic-links/lib/index.d.ts
Using the previously documented example style results in a symbol not found
---
> docs(types, dynamic-links): ShortLinkType is accessible via statics

- docs/analytics/screen-tracking.md
The reference to `NavigationController` should be `NavigationContainer`
- I read the [Contributor Guide](../blob/master/CONTRIBUTING.md) and followed the process outlined there for submitting PRs.
> docs(analytics): correct NavigationController to `NavigationContainer`

- packages/app/ios/RNFBApp/RNFBUtilsModule.m
As it stands, firebase app causes compilation errors in Mac OS, I believe this is the way to fix it. There does seem to be an attempt to solve it I think currently but standard conditionals would not get evaluated at compile time (Cue someone with more than 5 hours worth of Objective C experience.
---
> fix(app, ios): avoid photo API not present on Catalyst 

- .github/workflows/publish.yml
This is the one workflow where cancellation can become a real problem. Two publish actions are spawned for each workflow run (one is dispatched manually, the second is triggered), and if auto-cancellation is in the workflow then the second one kills the first one
Fixes #4283
> fix(publish): never auto-cancel publish workflow

- package.json
- packages/admob/__tests__/admob.test.ts
- packages/admob/lib/index.d.ts
- packages/analytics/lib/index.d.ts
- packages/app/lib/index.d.ts
- packages/auth/lib/index.d.ts
- packages/crashlytics/lib/index.d.ts
- packages/database/lib/index.d.ts
- packages/dynamic-links/lib/index.d.ts
- packages/firestore/lib/index.d.ts
- packages/functions/lib/index.d.ts
- packages/iid/lib/index.d.ts
- packages/in-app-messaging/lib/index.d.ts
- packages/messaging/lib/index.d.ts
- packages/ml-natural-language/lib/index.d.ts
- packages/ml-vision/lib/BarcodeDetectorTypes.d.ts
- packages/ml-vision/lib/index.d.ts
- packages/ml-vision/type-test.ts
- packages/perf/lib/index.d.ts
- packages/remote-config/lib/index.d.ts
- packages/storage/lib/index.d.ts
- scripts/_TEMPLATE_/lib/index.d.ts
- tsconfig.json
- website/package.json
- website/scripts/generate-typedoc.js
Fixes #2614 
Also see #2732 , #3728
I :heart: `skipLibCheck: false`! The issues it catches are often non-trivial.
This PR changes the following:
1. Updates the TypeScript definition structure to allow `skipLibCheck: false` compatibility
* Avoids errors like:
* `Import declaration conflicts with local declaration of 'ReactNativeFirebase'`
* `Exports and export assignments are not permitted in module augmentations.`
* `Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.`
1. Enabling the "libCheck" also uncovered some issues with the existing types, so these issues have been fixed with a **minimal-change** approach.
* For example, the `SetCheckoutOptionEventParameters` interface was missing, so it acted as `any`.
* This PR changes the type to `any`, …
> fix(types): enable TypeScript libCheck & resolve type conflicts

- .github/workflows/create_test_patches.yml
Fixes #4331
:wave: Hi @mikehardy!
The patch-package failure was being caused by incomplete npm publish tasks. (repo versions higher than `npm` versions) (Related: #4283)
Looks like #4330 did not fix the issue
I've detailed that in a new issue #4343, and I suppose if that is fixed, then #4331 becomes a non-issue, but still, I've taken a self-contained approach based on the following assumptions:
1. The generated patches should **always** be for the latest npm version, **regardless of repo state**.
2. patch-package does not work well with `package.json`, so we can safely ignore package.json changes in the patches.
In the patch generation task, the `package.json` from the "live" version is now preserved.
N/A
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process …
> chore(ci): when generating patches, keep package.json from latest npm version

- packages/messaging/CHANGELOG.md
something about the publishing not working great meant the changelog generation was also not great.
Related https://github.com/invertase/react-native-firebase/pull/4317#issuecomment-701888668
---
> docs(messaging, changelog): fix changelog for messaging 7.8.10

- docs/messaging/usage/index.md
- packages/messaging/ios/RNFBMessaging/RNFBMessaging+NSNotificationCenter.h
- packages/messaging/ios/RNFBMessaging/RNFBMessaging+NSNotificationCenter.m
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
- packages/messaging/lib/index.d.ts
- packages/messaging/lib/index.js
- Fixes: https://github.com/invertase/react-native-firebase/issues/4233
Motivation: for projects using react-native-navigation injecting appProperties for each screen makes it very difficult to actually stop screens from getting mounted.
Fixes #4233 
- Added getIsHeadless to get isHeadless on demand (imperatively)
---
> feat(ios, messaging): add getIsHeadless method to access iOS launch state

- docs/ml-vision/text-recognition.md
Went through a long debugging process only to find out that ml-vision text recognition only supports image files and not pdf files. Updated verbiage so others don't go down the rabbit hole.
https://github.com/invertase/react-native-firebase/issues/4334
- [x ] Yes
- [x ] `iOS`
- [x ] No
---
> docs(ml-vision): text-recognition accepts only image file types :fire:

- website/src/components/Link.tsx
This PR fixes #4357 and #4220
Before links pointing to "/" were converted to links pointing to "" which rendered them useless. This was caused by the custom link component which is supposed to remove trailing slashes from internal links. This PR adds a check for the "/" edge case.
> fix(docs): prevent trailing slash removal from links to root

- .spellcheck.dict.txt
I believe the proper procedure to get spell check to think something unexpected valid is to add it to the list of items in the spellcheck file
This is intended to allow 'launchProperties' to be used without warning in CI
---
> docs(spellcheck): add launchProperties to spellcheck file

- docs/faqs-and-tips.md
- docs/index.md
While troubleshooting `InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device`, it seems you need Google Play services installed. As a React Native newbie, I don't recall seeing this included in any instructions and I think this might be the best place.
None in this repository, but there were a lot of random results when I [searched](https://www.google.com/search?q=firebase_auth_api+is+not+available+on+this+device) for the error.
Documentation change
- Not applicable to documentation change
- ~~[ ] `e2e` tests added or updated in `packages/\*\*/e2e`~~
- ~~[ ] `jest` -tests added or updated …
> docs(setup): Add instructions for using Firebase in an emulator

- docs/index.md
Correction of the documentation, the overriding of android firebase BoM needs to be in the `/android/build.gradle` file
Fixes #4400
---
> fix(docs): Fix overriding android sdk in the documentation

- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsModule.m
The current exception won't be reported to crashlytics in both debug and release builds for now. Though I guess it was working at that time. (same as #4421)
I found a working solution from Sentry, I've also tested it, and I checked it is working for crashlytics.
https://github.com/getsentry/sentry-cocoa/blob/7e2fff30271712bbf68747af1b198dfadf48e1a3/Sources/Sentry/SentryClient.m#L180-L183
The important thing about this approach is that there is no room for runtime to catch
If this PR is decided as okay, I can abandon #4421.
#4374
#4126
#4421
---
Think `react-native-firebase` is …
> fix(crashlytics): hard crash using SIGSEGV.

- docs/messaging/usage/index.md
Missing this attribute caused an error during bundle release "tools not bound"
- [ + ] Yes
- [ + ] `Android`
- [ - ] `iOS`
- [ - ] `e2e` tests added or updated in `packages/\*\*/e2e`
- [ - ] `jest` tests added or updated in `packages/\*\*/__tests__`
- [ - ] I have updated TypeScript types that are affected by my change.
- [ - ] Yes
- [ + ] No
--- …
> fix(docs, messaging): tools schema declaration required for notification color override

- docs/in-app-messaging/usage/installation/android.md
In the second paragraph the project name is correct. Without the correct name the project fails compiling.
---
> fix: Android in app messaging manual linking setup

- packages/analytics/__tests__/analytics.test.ts
- packages/analytics/lib/index.js
I added a validation to check the length for `name` of `analytics().logEvent(name, params)`: 1-40 alphanumeric
Fixes #4496 
---
> fix(analytics): added a validation for length in analytics().logEvent(name, params)

- packages/crashlytics/react-native.config.js
I commit to this repository for the first time.
I'm sorry if there is a wrong way.
Put the Build Phase setting of iOS when pod install.
https://firebase.google.com/docs/crashlytics/get-started?hl=ja#initialize-crashlytics
I want to add Input Files.
`${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}`
`$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)`
Discussion #4519 
--- …
> feat(crashlytics ios): put input files when pod install.

- packages/firestore/lib/FirestoreTimestamp.js
For parity with JS SDK, and also to make comparisons work as expected.  Copied from https://github.com/firebase/firebase-js-sdk/blob/7c1c7f182b59e0fc7d175f53e5e2360cdee0ccab/packages/firestore/src/api/timestamp.ts#L162-L182.
I just copied and pasted without testing or modification, so please lmk if this is something you'd be interested in including, and I'd be happy to add a unit test / clean / add type info to proper place
---
- 👉 Follow …
> feat(firestore): add toJSON() and valueOf() to FirestoreTimestamp

- packages/storage/e2e/StorageTask.e2e.js
- packages/storage/e2e/storage.e2e.js
- packages/storage/lib/utils.js
- tests/e2e/mocha.opts
Fix for issue https://github.com/invertase/react-native-firebase/issues/2753.
When extracting the url, regex currently excludes appspot.com. This has now been included so that the domain is included.
Format changed from {bucket} to {bucket}.appspot.com
> fix(storage): Changed refFromUrl regex to exclude appspot.com

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
This fixes an issue with Apple sign on Android. iOS was fixed with this commit. iOS was fixed with this PR https://github.com/invertase/react-native-firebase/pull/4359. Note the solution is different. On iOS, it looks like we bubble the auth credentials back to js land and then retry login. Here, we attempt another login on auth collision errors
Also, note this deviates from the iOS solution. I am unable to grab the actual credentials from the AuthCredential object and return an error. So, instead, I proceed with a login
Fixes #3952 on Android
Call `signInWithCredential` with updated credential when `linkWithCredential` throws `FirebaseAuthUserCollisionException`
- My change …
> fix(auth, android): fixed issue with apple sign-in on android

- packages/firestore/e2e/Query/where.e2e.js
Query validators are ineffective when using a where clause after an order by clause. This PR investigates and adds tests cases to prove the logic.
See issue https://github.com/invertase/react-native-firebase/issues/3220
> fix(firestore): Added test case for orderby before where query

- docs/firestore/usage/index.md
The link to android manual installation was missing a `/`, guiding the user to [a 404](https://rnfirebase.io/firestore/usage/firestore/usage/installation/android). 
No related issue AFAIK
N/A
I've just added the `/` before the android link copying the behaviour of the iOS link that works fine.
iOS link is working fine: `/firestore/usage/installation/ios` is resulting in https://rnfirebase.io/firestore/usage/installation/ios
Android link is not working: `firestore/usage/installation/android` is resulting in https://rnfirebase.io/firestore/usage/firestore/usage/installation/andro …
> docs(cloud firestore): fix cloud firestore manual installation link for android

- packages/firestore/lib/FirestoreTimestamp.js
- packages/firestore/lib/index.d.ts
As noticed by @davidstott in https://github.com/invertase/react-native-firebase/pull/4439#issuecomment-725010712 - the new methods in FirestoreTimestamp were missing a constant from the top of their origin file from firebase-js-sdk
While repairing that I noticed they still had some typescript-isms and the correlating typescript definition file here was missing docs for those methods
Original PR for the new feature this polishes up #4439
fix(firestore): add missing MIN_SECONDS constant to FirestoreTimestamp
---
Think `react-native-firebase` is great? Please consider supporting …
> fix(firestore): add missing MIN_SECONDS constant to FirestoreTimestamp

- packages/app/RNFBApp.podspec
- packages/app/package.json
- tests/ios/Podfile
- tests/ios/Podfile.lock
Hot on the heels of the forward port from firebase-ios-sdk v6 to v7, v7.1.0 is out
passes tests locally
forward port that got us to v7 #4471 
feat(app, ios): bump firebase-ios-sdk to 7.1.0 from 7.0.0
---
> feat(app, ios): bump firebase-ios-sdk to 7.1.0 from 7.0.0

- packages/admob/e2e/consent.e2e.js
- tests/e2e/mocha.opts
This one might be flaky, but I'd like to leave it enabled and de-flake it if possible,
versus having it disabled. Prepare for follow-ons to do exactly that as it happens.
> test(admob, e2e): re-enable e2e testing for admob

- packages/app/android/build.gradle
According to the [firebase release notes](https://firebase.google.com/support/release-notes/android), the `firebase-core` for Android is no longer needed.
Fixes #4593
Remove firebase-core from Android dependencies.
- `@react-native-firebase/analytics`
- `@react-native-firebase/app`
- `@react-native-firebase/crashlytics`
- `@react-native-firebase/messaging`
- `@react-native-firebase/perf`
--- …
> fix(app, android): remove firebase-core from dependencies

- packages/analytics/android/src/reactnative/java/io/invertase/firebase/analytics/ReactNativeFirebaseAnalyticsModule.java
- packages/analytics/e2e/analytics.e2e.js
- packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m
- packages/analytics/lib/index.d.ts
- packages/analytics/lib/structs.js
This pull request addresses the problem of not being able to pass the quantity parameter when trying to log any of these events:
- add_to_cart
- add_to_wishlist
- remove_from_cart
- view_cart
- refund
According to the [documentation](https://firebase.google.com/docs/analytics/measure-ecommerce#swift_7) for the aforementioned events one must or can pass the quantity parameter, but currently the library will reject such parameters, since quantity is not mentioned in the Item struct.
:fire:
> fix(analytics): added missing quantity parameter to the Item structure

- packages/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.m
APS badging information was being pulled from the wrong JSON chunk, this moves it to align with docs
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/generating_a_remote_notification
Fixes #4559
---
> fix(ios, badge): use new JSON location for FCM badge information

- packages/crashlytics/e2e/crashlytics.e2e.js
- packages/crashlytics/lib/handlers.js
- packages/crashlytics/lib/index.d.ts
- packages/crashlytics/lib/index.js
- Add ability to override the error message. Bringing back the `record custom error`.
- Alerting will be more usefull in firebase as well, it's sad to receive an Email with `index.bundle:123192038123:1239810238` 
- Easier triage in the the crashlytics dashboard 
- Add an initial line to the stack (the one that will be printed in the crashlytics UI, the aggregation works with this custom string as well)
- Alleviate the pain of not having sourcemap support in crashlytics
https://github.com/invertase/react-native-firebase/issues/2327
https://github.com/invertase/react-native-firebase/issues/1783
- I made the parameter optional should not introduce any breaking change
- My change …
> feat(crashlytics): add custom message ability to javascript stack traces

- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java
I am in a situation where I need to manually send events through `ReactNativeFirebaseEventEmitter`. See discussion https://github.com/invertase/react-native-firebase/discussions/4577 
In order to properly do so, I'd like to use the functions present in `ReactNativeFirebaseMessagingSerializer`. 
This PR just adds the public access modifier to that class and to the functions that build events.
> chore: make ReactNativeFirebaseMessagingSerializer + events builder functions public

- packages/app/lib/internal/NativeFirebaseError.js
- packages/functions/lib/HttpsError.js
This is a rebased carry-over from an existing PR by @BlaShadow, all information is contained there:
#3751
It has passed local testing on my machine after being rebased to tip of current master
> fix(app): convert NativeFirebaseError.getStackWithMessage to static to fix crash

- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
`ReactNativeFirebaseMessagingModule -> onNewIntent` is not checking the messaging store for remote messages (like `getInitialNotification` does).
Steps to reproduce the bug:
1. Receive a notification but don't open it (the remote message is added to `ReactNativeFirebaseMessagingReceiver.notifications`).
2. Open the app and then kill it (`ReactNativeFirebaseMessagingReceiver.notifications` is reseted).
3. Open the app again and bring it to background state.
4. Press the notification (`ReactNativeFirebaseMessagingReceiver.notifications` is empty).
This results in `onNewIntent` is unable to get the remote message because it is not checking in the persisted store.
I have not submitted an issue for this problem and I have not found any other issues.
- I read the [Contributor …
> fix(messaging): get remote message from messaging store on new intent

- tests/ios/Podfile
The test podfile was pointing at master, but that can cause problems if the newest ios release is different then the one under test. They must be the same, so use the tag on firebase-ios-sdk-frameworks at the specified version vs master
Noticed while developing #4471 as it caused test app compile errors during baseline as master was 7.0.0 while I was still on 6.x.x originally
named with conventional commit
It actually *is* a test, so the test app either compiles or it doesn't, but with this change it will compile reliably
---
Think `react-native-firebase` is great? Please …
> test(Podfile): use firestore-ios-framework version vs master

- website/scripts/source-reference.js
- website/scripts/utils.js
The links on the "Edit Page" or "Jump to code" are broken. See [this page](https://rnfirebase.io/reference/admob/adsconsentdebuggeography) for instance.
It was working previous to this [PR](https://github.com/invertase/react-native-firebase/pull/4306), according to the Vercel preview, although I couldn't figure out what broke it.
--- …
> fix(docs): correct path to source code

- .sonarcloud.properties
Sonar cloud is currently not utilised in our CI. 
This can be removed as code coverage is covered with Codecov
> chore(ci): removed sonar cloud code coverage

- packages/remote-config/ios/RNFBConfig/RNFBConfigModule.m
As per documentation, apps must be very gentle when it comes to fetching from the Firebase Remote Config storage. By default, it happens not more often than once in 12 hours. For that the library provides a selector: `fetchWithCompletionHandler:` that doesn't have the time interval parameter and uses the value from settings and the second one `fetchWithExpirationDuration:completionHandler:` that allows to override this configuration. In JS it is exposed as a single method of signature `fetch(expirationDurationSeconds?: number): Promise<void>;`. When `expirationDurationSeconds` is undefined, -1 is passed to the native module and then treated as follows:
```
if (expirationDuration == @(-1)) {
[[FIRRemoteConfig remoteConfigWithApp:firebaseApp] fetchWithCompletionHandler:completionHandler];
} …
```
> fix(remote-config,ios): fixed fetch throttling issue

- packages/admob/android/build.gradle
- packages/admob/e2e/consent.e2e.js
- packages/admob/e2e/rewarded.e2e.js
- packages/admob/lib/index.d.ts
- packages/analytics/android/build.gradle
- packages/app/android/build.gradle
- packages/app/package.json
- packages/auth/android/build.gradle
- packages/auth/e2e/auth.e2e.js
- packages/crashlytics/android/build.gradle
- packages/database/android/build.gradle
- packages/database/e2e/reference/transaction.e2e.js
- packages/dynamic-links/android/build.gradle
- packages/firestore/android/build.gradle
- packages/firestore/e2e/Query/where.e2e.js
- packages/firestore/e2e/QuerySnapshot.e2e.js
- packages/firestore/e2e/helpers.js
- packages/functions/android/build.gradle
- packages/iid/android/build.gradle
- packages/in-app-messaging/android/build.gradle
- packages/messaging/android/build.gradle
- packages/messaging/e2e/messaging.e2e.js
- packages/ml/android/build.gradle
- packages/perf/android/build.gradle
- packages/remote-config/android/build.gradle
- packages/storage/android/build.gradle
- tests/android/build.gradle
- tests/android/gradle/wrapper/gradle-wrapper.properties
- tests/ios/Podfile
- tests/ios/Podfile.lock
Bumping test app dependencies to current while troubleshooting a build issue
> chore: dependency updates 20201203

- packages/storage/e2e/StorageTask.e2e.js
- packages/storage/lib/utils.js
This is pulled from / Obsoletes #3691 by @dackers86 
The goal is to get the storage work from that PR with none of the other e2e entanglements
:crossed_fingers: it passes e2e in the current state of e2e
---
> test(storage, e2e): fix pause/cancel tests, re-enable them

- packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobInterstitialModule.java
Hi, just got a null-pointer exception while using AdMob in my app:
```
java.lang.NullPointerException: 
at io.invertase.firebase.admob.ReactNativeFirebaseAdMobInterstitialModule.lambda$interstitialShow$1 (ReactNativeFirebaseAdMobInterstitialModule.java:132)
at io.invertase.firebase.admob.-$$Lambda$ReactNativeFirebaseAdMobInterstitialModule$HC0J2W104AWtZIk60UVqQO1y4sE.run (Unknown Source:6)
at android.os.Handler.handleCallback (Handler.java:888)
at android.os.Handler.dispatchMessage (Handler.java:100)
at android.os.Looper.loop (Looper.java:213)
at android.app.ActivityThread.main (ActivityThread.java:8178)
at java.lang.reflect.Method.invoke (Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main …
```
> fix(admob,android): add null checks for interstitialAd object

- packages/storage/ios/RNFBStorage/RNFBStorageCommon.m
This fix resolves a crash that occurs when pathExtension returns NULL, failing to detect file extension. This was detected as a result of a simulator bug with Apple Silicon Macs where pathExtension returns NULL only iOS14 (works as expected on iOS13).
This bug would probably surface on any device if file extension could not be detected when calling mimeTypeForPath, this could be used to verify the fix on intel Macs.
Fixes #4661 
Verified mimeTypeForPath function on Apple Silicon with iOS14 sim to return @"application/octet-stream". Verified CFRelease is being called on iOS13 …
> fix(ios, storage): handle nil file extension from ios14 M1 emulators

- packages/storage/e2e/StorageReference.e2e.js
- packages/storage/ios/RNFBStorage/RNFBStorageModule.m
When calling `listAll` on a forbidden directory, the promise is rejected then RNFirebase tries to resolve it with an empty result, which leads to the following Exception (which I believe would crash the app in production):
```
Invariant Violation: No callback found with cbID 256 and callID 128 for  RNFBStorageModule.listAll - most likely the callback was already invoked. Args: '[{"nextPageToken":null,"items":[],"prefixes":[]}]'
2020-12-18 11:45:24.318162+0100 ExampleApp[40550:189312] [native] Running surface LogBox ({
initialProps =     {
};
rootTag = 11;
})
```
The root cause is the lack of a `return`on this line of the Firebase iOS SDK : https://github.com/firebase/firebase-ios-sdk/blob/14764b8d60a6ad023d8fa5b7f81d42378d92e6fe/FirebaseStorage/Sources/FIRStorageReference.m#L417
This …
> fix(storage, ios): resolve listAll promise once and only once on error

- packages/analytics/android/build.gradle
- packages/analytics/android/src/main/AndroidManifest.xml
- packages/app/ios_config.sh
- tests/firebase.json
This adds support for the [documented](analytics_auto_collection_enabled) but not implemented `analytics_auto_collection_enabled` in `firabase.json`.
I've aligned this with how `messaging_auto_init_enabled` is implemented.
Fixes #4473
I've asserted that both platforms log that analytics collection gets disabled:
* iOS: `[Firebase/Analytics][I-ACS023013] Analytics collection disabled`
* Android: `FA` `Event not sent since app measurement is disabled`
> feat(analytics): add support for analytics_auto_collection_enabled in firebase.json

- packages/ml/android/build.gradle
Fixes [issue](https://github.com/invertase/react-native-firebase/discussions/4750) of unnecessary dependencies in @react-native-firebase/ml
[discussion](https://github.com/invertase/react-native-firebase/discussions/4750)
> fix(ml, android): removed unnecessary face models

- packages/admob/android/build.gradle
- packages/analytics/android/build.gradle
- packages/app/android/firebase-json.gradle
- packages/messaging/android/build.gradle
This fixes the case where firebase.json existed but the key being
query was missing. Previously the config system would silently fail on
the missing key and return false even though the default for some keys
should be true
In particular this caused analytics auto collection to be disabled
if you had a firebase.json but no analytics_auto_collection_enabled = true entry,
even though the default should have been true
Credit to @WadhahEssam for discovery, diagnosis, and general solution
Fixes #4784 
Obsoletes #4786 (different API shape, same solution though)
I tested:
- …
> fix(app, android): require default firebase.json boolean key

- .spellcheck.dict.txt
- docs/dynamic-links/usage/index.md
I added a missing step in the documentation, where the user has to add the URLs scheme in the AndroidManifest.xml file.
---
> docs(links, android): added intent block for url scheme for android

- packages/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java
This PR addresses two issue:
1. `getInitialLink ` link is returned more than once.
2. `getInitialLink ` returns null.
* The Android SDK doesn't seem to clear the dynamic link after calling getDynamicLink in `getInitialLink`.  
(as stated in the official docs: `Calling getDynamicLink() retrieves the link and clears that data so it is only processed once by your app.`)  
This causes the link to be retrieved even when returning to the app from the Overview screen after backgrounding the app using the back button, which leads to unwanted results such as deep links being handled more than once.
* When `getInitialLink` is called before the host is resumed, `getCurrentActivity` will be null and `getInitialLink` will return null instead of trying to `getDynamicLink`.
Fixes #3990 
Fixes #3027 
- I …
> fix(dynamic-links,android): getInitialLink returned more than once, and sometimes returned null

- docs/functions/usage/index.md
The documentation shows the usage of `useFunctionsEmulator` as `functions().useFunctionsEmulator('http://localhost:5000');` however this will only work when the phone is running on an emulator. Added a comment reminding that when used on a real device, non localhost URLs should be used.
Fixes (Solves)  #4827 
- [x ] No
--- …
> docs(functions): updated instructions for using useFunctionsEmulator

- packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobBannerAdViewManager.java
- packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobCommon.java
- packages/admob/lib/index.d.ts
This pull request adds support for adaptive banners in Android.
Added adaptive banner support for Android.
> feat(admob, android): add adaptive banner support 

- docs/index.md
> docs: Replace semi-colon with comma in sentence "...therefore to use other Firebase services, each of the modules..."

- docs/dynamic-links/usage/index.md
- docs/in-app-messaging/usage/index.md
- docs/remote-config/usage/index.md
- packages/dynamic-links/package.json
- packages/in-app-messaging/package.json
- packages/remote-config/package.json
Turns out that analytics is actually required for certain modules, or you get startup crashes - #4821
When analytics is optional the documents say so, [like crashlytics](https://firebase.google.com/docs/crashlytics/get-started?platform=ios)
> For an optimal experience with Firebase Crashlytics, we recommend enabling Google Analytics in your project by adding the Firebase pod for Analytics to your app as well
But for these ones it is not listed as optional, and a crash was observed
- iOS: https://firebase.google.com/docs/dynamic-links/ios/create#set-up-firebase-and-the-dynamic-links-sdk
- Android: https://firebase.google.com/docs/dynamic-links/android/create#set-up-firebase-and-the-dynamic-links-sdk
- iOS: https://firebase.google.com/docs/remote-config/use-config-ios
> Note: When …
> fix: add analytics peerDependency to remote-config, dynamic-links, in-app-messaging

- packages/auth/__tests__/auth.test.ts
- packages/auth/lib/index.d.ts
- packages/auth/lib/index.js
- packages/firestore/lib/index.d.ts
- packages/firestore/lib/index.js
- packages/functions/lib/index.d.ts
- packages/functions/lib/index.js
For developer experience, we remap localhost / 127.0.0.1 on android to the
canonical android emulator IP address for the host machine. This is best most
of the time but is quite unexpected if you run on a real device and try to do
adb reverse port mapping for the emulator port and use localhost, only to find
that you can't connect to the emulator because of this remapping
This PR adds a note to the docs and a console.log so developers are aware of
the behavior
Fixes #4810
---
> fix(emulator): add notice on localhost URL remapping for android

- packages/app/ios_config.sh
- packages/perf/android/build.gradle
- packages/perf/android/src/main/AndroidManifest.xml
- tests/firebase.json
More or less clones https://github.com/invertase/react-native-firebase/commit/9a24ecd2826bfa8ab30657287432ccaeff8b7c7c
---
Checking that firebase performance is disabled on app start when this flag is set.
> feat(perf): support "perf_auto_collection_enabled" flag in firebase.json

- packages/admob/lib/ads/InterstitialAd.js
- packages/admob/lib/ads/MobileAd.js
- packages/admob/lib/ads/RewardedAd.js
**`loaded: Whether the advert is loaded and can be shown.`**
If `_loaded` is changed to `true` when `load()` is called, the meaning of `loaded` getter becomes ambiguous.
If the goal is to prevent multiple calls, it would be better to use other variables for this.
> fix(admob): improve defense logic to prevent multiple calls

- .spellcheck.dict.txt
- docs/in-app-messaging/usage/index.md
- packages/auth/android/build.gradle
- packages/ml/android/build.gradle
Android dependencies in ML were still pulling in an on-device library, unnecessarily bloating APKs, #4750 / #4871 
Auth module depends on androidx.browser for reCAPTCHA flow but it is not included transitively from upstream, this leads to crashes so including a workaround here while upstream issue resolves seems reasonable, #4744 / https://github.com/firebase/firebase-android-sdk/issues/2164
This should be re-base merged, each commit has a correct commit title
---
- 👉 Star …
> fix(android, dependencies): remove vestigial ml dependencies, add browser dep to auth

- packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java
- packages/auth/e2e/user.e2e.js
In Android, JWT's iat and exp are now converted to correctly UTC time in strings.
Unnecessary offsets were being added to the timestamps, causing them to be converted to the wrong UTC time in strings.
I have tested the following:
- The JWT iat was correctly converted to UTC time.
- The JWT exp was correctly converted to UTC time.
--- …
> fix(auth, android): do not timezone offset when getting UTC timestamp

- packages/dynamic-links/package.json
Per @nfcampos analytics is actually optional for dynamic links
This information is not mentioned in main documentation but present in some supporting docs
https://github.com/invertase/react-native-firebase/pull/4850#issuecomment-776516887
#4850
PR title
---
> fix(dynamic-links, dependencies): analytics is optional

- docs/crashlytics/usage/index.md
- packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/Constants.java
- packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsInitProvider.java
- packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsModule.java
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.h
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsModule.m
- packages/crashlytics/lib/handlers.js
- tests/firebase.json
Currently, the crashlytics react-native package generates an additional non-fatal issue on JS crashes that might cause issues duplication and absence of collected logs for original exceptions. This PR introduces an option in firebase.json to prevent the module from generating that additional error.
Fixes #4772 
---
> improvement: Make additional non-fatal error generation on JS exception optional

- docs/auth/social-auth.md
There is an extra word in the docs for google auth setup
:fire:
> docs(auth): remove unnecessary word from google auth guide

- packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksModule.m
the iOS firebase-ios-sdk handleUniversalLink completion handler
correctly handles all of the error conditions by resolving or rejecting
the passed in react-native promise as needed, but was incorrectly
then testing success status and rejecting again on unfound links
e2e tests were already probing this case to verify correct behavior
at the javascript level but the native-level double-reject went
unnoticed until now
Ironically resolveLink was my own code and it demonstrates exactly why I am so cautious around Objective-C. The tests I wrote at least already covered the case to …
> fix(dynamic-links, ios): remove double-reject on resolveLink

- website/package.json
- website/src/components/Mdx.tsx
- website/src/styles.css
Paragraph readability is poor in documentation. It is to light, so contrast is not enough for good readability. Also font weight is too thin to be used for a paragraph text.
Also I removed `nodegit` from dependencies, because it is not used in documentation. 
Fixes #4908 
Improve Readability of documentation website
Below are screenshots of website, before and after changes
Before, Win10 Surface pro
Before, Macbook
After, Win10 Surface pro
After, Macbook
🔥
> docs(common): Improve paragraph readability

- packages/admob/lib/ads/MobileAd.js
`_setAdEventHandler` method return a wrong unsubscribe function. It should remove js listener, but instead it unsubscribe ad instance from native events and _onAdEventHandler is still could be used by the instance
RewardedAd instance onAdEvent method uses _setAdEventHandler of it's superclass. Logically it should return function that will unsubscribe listener that we add, but instead it unsubscribe instance from native events.
It's not possible to use different listeners for load and show ad because after first unsubscribe ad intance doesn't receive any native events anymore
```
const rewarded = RewardedAd.createForAdRequest(TestIds.REWARDED, {
requestNonPersonalizedAdsOnly: true,
})
const loadAd = () => {
if ([AdLoadStatus.InProgress, AdLoadStatus.Loaded].includes(adLoadStatus)) {
return …
```
> fix(admob): AdEventHandler returns javascript (not native) unsubscribe function

- packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobInterstitialModule.java
- packages/admob/android/src/main/java/io/invertase/firebase/admob/ReactNativeFirebaseAdMobRewardedModule.java
Fix Admob crash from UnityAds with Admob Mediation.
Seems like a regression from https://github.com/invertase/react-native-firebase/pull/1892
Fixes https://github.com/invertase/react-native-firebase/issues/1792
#1792 
#1892
---
> fix(admob, android): unity ads require Activity Context

- packages/app/RNFBApp.podspec
- packages/app/package.json
- tests/ios/Podfile
- tests/ios/Podfile.lock
A small package of individual commits that clean up firestore-ios-sdk versioning and bump us to v7.7.0
1- there is no valid tested fallback for the SDK version if resolving it from package.json fails
2- the SDK version should be specified as a fixed version since that is what we test (you can still override)
3- the SDK version in the test app must be programmatically resolved
4- bump to v7.7.0
#4950 currently has an iOS CI E2E failure because of item 3 above, after this merges, #4950 should rebase against master or merge it
Supercedes #4951  - the test app should not need manual bumps, we should bump our main SDK dep in app and tests should simply consume it
This should be rebase-merged, each commit is correct by itself (if git bisect is needed later) and has a correct commit message
- I …
> feat(ios, sdk): bump firebase-ios-sdk to v7.7.0

- packages/app/e2e/app.e2e.js
- packages/app/lib/index.d.ts
previously was `FirebaseApp` so it seemed sync vs async
Fixes #4979 
PR title
All of the E2E tests in the area have been enabled and tested
(by purposefully modifying expected output to not match) to fail
as expected, and pass with correct expected output
---
> fix(app, types): initializeApp returns Promise<FirebaseApp>

- packages/firestore/lib/index.d.ts
straightforward, thank you
---
> docs(firestore): fix typo in FieldValue example

- packages/app/android/src/reactnative/java/io/invertase/firebase/utils/ReactNativeFirebaseUtilsModule.java
Fix crash on first run on Android-11 when `context.getExternalFilesDir(null);` returns null
Fixes #4979 
PR title
---
> fix(app, android): fixes possible crash on first launch

- .github/workflows/tests_e2e.yml
- packages/auth/__tests__/auth.test.ts
- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/e2e/auth.e2e.js
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/auth/lib/User.js
- packages/auth/lib/index.d.ts
- packages/auth/lib/index.js
- tests/package.json
When I working on the firebase auth, I found I can't set tenant id which is quite critical for working with Google Identity platform. In the repository discussion channel. there are 2 questions related with this also.
1. https://github.com/invertase/react-native-firebase/discussions/4462
2. https://github.com/invertase/react-native-firebase/discussions/4964
Then  I checked the[ Firebase iOS SDK,](https://github.com/firebase/firebase-ios-sdk/pull/6142) which actually provided tenantId for user to set it. So I created this PR to open this capability to React native Lib users.
No
Support set tenant it in Firebase auth module.
- My …
> feat(auth, multi-tenant): add multi-tenant (tenantID) support

- docs/crashlytics/usage/index.md
- packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsNativeHelper.java
- packages/crashlytics/ios/RNFBCrashlytics.xcodeproj/project.pbxproj
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsNativeHelper.h
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsNativeHelper.m
This change allows to log non-fatal exception in Firebase Crashlytics, handled on the native side.
[Discussion](https://github.com/invertase/react-native-firebase/discussions/5010)
🔥 
---
> feat(crashlytics, native): add non-fatal exception logger for 3rd party native code use

- packages/app/package.json
https://firebase.google.com/support/release-notes/ios#version_781_-_march_12_2021
Analytics fixed an issue where references to retrieveAdTrackingConsentStatus caused kids' apps to be rejected during App Store review
commit message
Just CI, if it passes I'll release v11.1.1
---
> fix(app, firebase-ios-sdk): bump to firebase-ios-sdk v7.8.1 for analytics fix

- .gitattributes
- .github/workflows/tests_e2e.yml
- package.json
- packages/auth/lib/PhoneAuthListener.js
- packages/database/lib/DatabaseSyncTree.js
- tests/.editorconfig
- tests/android/app/build.gradle
- tests/android/app/src/debug/AndroidManifest.xml
- tests/android/app/src/main/AndroidManifest.xml
- tests/android/app/src/main/res/values/styles.xml
- tests/android/build.gradle
- tests/android/gradle.properties
- tests/ios/LaunchScreen.storyboard
- tests/ios/Podfile
- tests/ios/Podfile.lock
- tests/ios/testing.xcodeproj/project.pbxproj
- tests/ios/testing/AppDelegate.m
- tests/metro.config.js
- tests/package.json
- yarn.lock
This is a forward-port of react-native-firebase to react-native 0.64 (there was a breaking change that affected us), as well as an update of the tests module to react-native 0.64 to prove it works
Specifically, the react-native event emitter dropped the `.once()` API, and as react-native-firebase extends and uses that API we needed to port to the suggested analog of addListener/on-handler-that-self-removes-listener
The forward-port is definitely working based on my E2E testing so the patch-package should be testable
the tests module update is a bit more iffy. Works on android, I'm having trouble on iOS
Fixes #5027 
Each commit is conventional, rebase merge should be used
- My …
> fix: react-native 0.64 compatibility

- packages/database/lib/index.d.ts
This does not change the underlying implementation which should still be correct with
the updated types, it only copies in the type definitions from firebase-js-sdk so we
stay in sync with them
Related #5027 - the type-related part of that issue
PR title
`yarn tsc:compile`, `yarn tests:jest` plus comparison to firebase-js-sdk and code inspection of the underlying DatabaseQuery.js implementation
--- …
> fix(database, types): harmonize on/once/off types with firebase-js-sdk

- .github/workflows/create_test_patches.yml
- .github/workflows/docs.yml
- .github/workflows/linting.yml
- .github/workflows/pr_title.yml
- .github/workflows/tests_e2e.yml
- .github/workflows/tests_jest.yml
This updates to node v14 and JDK11 to track ecosystem minimum requirements that are coming into force, and updates action versions in the process
Each commit is conventional, rebase merge should work
It's all github actions work, CI passes or it doesn't :-)
---
> chore: bump action versions and build toolchain versions

- packages/firestore/lib/index.d.ts
They were missing, and since all other methods stand out thanks to markup, I was wondering if I could call `set()` on my transaction
This PR adds backticks around the `set()` method in the `Transaction` documentation introduction
DOC: Add code marks around the transaction's set method
- My change includes tests - N/A
N/A
---
> docs: Add code marks around the transaction's set method

- packages/admob/RNFBAdMob.podspec
Upstream release note "Updated Consent SDK to use WKWebView"
None logged, noticed it while triaging #5102 
Commit message is conventional
CI only, it's a minor version bump of a low-velocity dependency that is used a lot, and has been out nearly 2 months. Should be safe...
---
> fix(admob, ios): bump PersonalizedAdConsent to 1.0.5

- packages/analytics/lib/index.js
- packages/crashlytics/lib/handlers.js
Crashlytics backend is working on better integration with interpreted languages
This change should work with changes in the backend to transform errors to a style that enables better reporting in both crashlytics and analytics
The commit title
There is a specific `__DEV__` test which means this will never work in dev mode.
Analytics and Crashlytics must both be installed for a full test.
There is no easy way to mock out the functions and verify the attribute is correct
So a manual unhandled javascript crash should be attempted in release mode and then the results should be …
> feat(crashlytics): flag fatal errors for crashlytics and analytics

- packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsInitProvider.java
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m
This is a continuation of the good work from @waqas19921 - I tried to do a polishing commit on PR #5113 and inadvertently pushed incorrect contents, requiring a new PR to fix
Related #5113 
Fixes #4793
PR title
Verified via inspection of newly added DLog commands in iOS it worked, code inspection on android
---
> fix(crashlytics, debug): Disable Crashlytics in debug mode by default

- packages/app/RNFBApp.podspec
cocoapods has needed a minimum version of 1.10 for quite some time, so this
is not actually a breaking change, the breaking change was before v10 I think,
this just makes it much more obvious with good messaging, versus previous subtle
error behavior
Related #5070 - where cocoapods minimum version was not being enforced and complicated troubleshooting
PR and commit are conventional, rebase merge should work
--- …
> fix(app, ios): formally note cocoapods v1.10+ requirement in podspec

- tests/ios/Podfile
- tests/ios/Podfile.lock
The tests project would sometimes fail to build on iOS because the pre-compiled firestore-ios-sdk-frameworks podspec could not determine whether leveldb should be included or not
I diagnosed that in the other repo as the Pod::Config.instance being nil and it seemed racy so I just added a flag in that repo to make it explicit, and I use that flag here.
https://github.com/invertase/firestore-ios-sdk-frameworks/issues/2
https://github.com/invertase/firestore-ios-sdk-frameworks/pull/30
test-only, but commit message is conventional
---
Think `react-native-firebase` is great? Please …
> test(iOS): avoid intermittent leveldb duplicate symbol build failure

- babel.config.js
- package.json
- packages/app/package.json
- tests/android/build.gradle
- tests/ios/Podfile.lock
- tests/package.json
- yarn.lock
- update all the javascript dependencies
but more importantly (for me)
- update to firebase-ios-sdk 7.10.0 which allows
- update tests to use new firestore-ios-sdk-frameworks leveldb exclude flag so my local test builds always work
Finally!
Each commit does one thing, with a conventional commit message, rebase merge
--- …
> chore: dependency updates 20210408

- packages/database/lib/index.d.ts
This builds on the work both upstream and in this repo of @SCasarotto
Fixes #4545
Supercedes #4550
Upstream firebase-js-sdk https://github.com/firebase/firebase-js-sdk/issues/4250
commit message is conventional, rebase merge
---
> fix(database, types): harmonize database.on() w/firebase-js-sdk

- packages/app/android/src/reactnative/java/io/invertase/firebase/utils/ReactNativeFirebaseUtilsModule.java
- packages/app/lib/index.d.ts
[NullPointerException Firebase Crashlytics](https://github.com/invertase/react-native-firebase/issues/4706)
The exported constant value for key KEY_DOCUMENT_DIRECTORY will be missed in ReactNativeFirebaseUtilsModule when Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT and  externalDirectory == null
Fixes [#4706](https://github.com/invertase/react-native-firebase/issues/4706)
--- …
> fix(android, utils): fix rare crash getting documents directory

- docs/app/usage.md
The raw links to modules do not work but if you add usage to the URL the links should work
No issue logged, noticed while troubleshooting #5134
conventional commit message
Check vercel test build after it renders
---
> docs(app, secondary-apps): fix links to other modules

- packages/app/react-native.config.js
Previously there was no dependency stated on Info.plist, so occasionally we would "lose the race"
and attempt to interpolate values prior to it existing
Since ads requires the Info.plist admob ids in the Info.plist, this resulted in crashes on startup occasionally
for users of the admob module
Noticed this occasionally in CI E2E plus during local testing it was very frustrating!
Fixes #5152
conventional commit message
--- …
> fix(app, ios-plist): make sure Info.plist exists before processing

- packages/app/e2e/app.e2e.js
- packages/app/ios/RNFBApp/RNFBAppModule.m
- packages/app/lib/internal/registry/app.js
- tests/ios/testing.xcodeproj/project.pbxproj
Previously the exceptions were swallowed, meaning that initialization failures
were very difficult to diagnose, leading to developer confusion
Fixes #5134
conventional commit message
A great deal of manual testing
---
> fix(app, secondary): reject if initializeApp fails on iOS

- docs/dynamic-links/usage/index.md
Update iOS troubleshooting section for Dynamic Links doc to explicitly mention the necessity of URL-encoding for deep link parameter. Seems like Android works fine even with unencoded deep link, which makes this problem trickier to catch, hence the explicit mention.
Should help with some cases of #3450
:fire:
> docs(dynamic-links): URL-encoding for iOS

- .github/workflows/create_test_patches.yml
- .github/workflows/docs.yml
- .github/workflows/linting.yml
- .github/workflows/tests_e2e.yml
- .github/workflows/tests_jest.yml
- cancel workflow action to 0.9.0 + all_but_latest flag
- java workflow updated, specify adopt flavor JDK
Will have to see how the actions behave once merged - should work?
---
> test(workflows): update workflow actions

- .github/workflows/tests_e2e.yml
- package.json
Trace level logging was interesting while troubleshooting sync problems, but is no longer interesting, and is overwhelming if not needed, remove it
Fixes #5008
Inspect action output from e2e action on iOS
---
> test(detox): remove trace level logging

- docs/index.md
Fixed a type in the documentation. `its` instead of `it's`.
- My change includes tests; 
-  n/a
> docs(app): fix typo in expo integration docs

- docs/migrating-to-v6.md
add note about subscribeToTopic not including "/" in topic
---
> docs(messaging, v6-migration): subscribeToTopic must not include '/'

- packages/admob/android/build.gradle
With the BoM it was apparently still possible for the admob library
to go across the breaking change v19->v20 boundary
Example was seen in #5127 and https://stackoverflow.com/questions/67114004/app-is-crashing-while-calling-interstitialad-load-method-in-react-native/67137688
This uses a gradle forced dependency until we forward-port
Related is #5150 - tracks the actual forward port, it will be breaking though as it will require a new BoM
Conventional commit
I tried a few things and my success criteria was that `./gradlew :app:dependencies` output could be examined and ads …
> fix(admob, android): force admob dependency to compatible v19

- packages/admob/android/build.gradle
- packages/analytics/android/build.gradle
- packages/app/android/build.gradle
- packages/auth/android/build.gradle
- packages/crashlytics/android/build.gradle
- packages/database/android/build.gradle
- packages/dynamic-links/android/build.gradle
- packages/firestore/android/build.gradle
- packages/functions/android/build.gradle
- packages/iid/android/build.gradle
- packages/in-app-messaging/android/build.gradle
- packages/messaging/android/build.gradle
- packages/ml/android/build.gradle
- packages/perf/android/build.gradle
- packages/remote-config/android/build.gradle
- packages/storage/android/build.gradle
- scripts/_TEMPLATE_/android/build.gradle
- tests/android/build.gradle
Only remaining jcenter usage is in our tests app, not used by
library consumers, where we must retain it until react-native itself
is jcenter-free
Also bumped everything in the template to current and bumped kotlin in tests app to 1.4.32 from 1.4.31 but no one will notice or care ;-)
Tracking remaining usage: https://github.com/react-native-community/releases/issues/221#issuecomment-822024961
It's a conventional commit message
I ran `yarn tests:build:test` to make sure everything still built after. It still builds, unless you comment out the final jcenter line, then it fails …
> fix(all, android): purge jcenter() from android build

- package.json
- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java
- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStore.java
- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreImpl.java
When deserializing saved notifications from the store on Android, this pull will include the notification object as well.  Previously the code used the Firebase RemoteMessage class, but that does not allow setting the notification object.  This uses writablemaps instead.
This is an Android only issue.
Fixes #5167
After following the reproduction steps in the linked issue, I can now get the notification object on start:
LOG  {"ttl":2419200,"from":"557990742577","to":"0:1618554006404925%26d15a5d26d15a5d","data":{},"sentTime":2147483647,"messageId":"0:1618554006404925%26d15a5d26d1 …
> fix(messaging): Missing notification on restart

- packages/app/android/src/main/java/io/invertase/firebase/common/TaskExecutorService.java
Related to : #4981 
[TaskExecutorService](https://github.com/invertase/react-native-firebase/blob/v11.3.2/packages/app/android/src/main/java/io/invertase/firebase/common/TaskExecutorService.java#L104) is using API level 24 Collection functions such as `removeIf`, `forEach`.
This can cause build failure or crash under Android 7.
I'm sure it needs to be modified to work with the lower minSdkVersion.
None
> fix(android): Resolve a crash under Android 7

- packages/database/e2e/reference/update.e2e.js
- packages/database/lib/DatabaseReference.js
As pointed out by @daveGregorian firebase-js-sdk allows empty objects
while the code here was enforcing that the objects had at least one key
Fixes #5218
Conventional commit message
Verified (with investigation in linked issue) that firebase-js-sdk allows empty objects through), added an e2e test that verifies firebase-ios-sdk and firebase-android-sdk handle empty objects, and those work, so removing the check in our javascript layer should be fine
--- …
> fix(database, update): allow empty objects in ref.update()

- packages/analytics/lib/index.js
This is an easy PR. I updated `../../app/lib/common` by '@react-native-firebase/app/lib/common'
- App does not crash when it's opened
---
> fix(analytics): import using package name not relative path

- packages/app/android/src/main/java/io/invertase/firebase/common/TaskExecutorService.java
- packages/app/e2e/config.e2e.js
- tests/app.js
The new TaskExecutor code in #4981 is great but it is new and had a concurrency issue causing a redbox on CatalystInstance shutdown, which shows up as a redbox in dev when you reload the app
Fixes #5225
Related #5233 - redbox detection was flaky and I don't want to delay this fix, split it to separate PR
Each commit is separate with a conventional commit message
Redbox was reproducible in E2E suite after Detox reloaded the app, but the tests continued running under the redbox, so it passed CI. Fixed root cause of the initial bug and locally have redbox detection working but …
> fix(app, android): fix TaskExecutor ConcurrentModificationException

- .spellcheck.dict.txt
- docs/analytics/usage/index.md
- packages/admob/RNFBAdMob.podspec
- packages/analytics/RNFBAnalytics.podspec
- packages/app/package.json
- tests/ios/Podfile
- tests/ios/Podfile.lock
Allow use of new Analytics subspec that gets you Analytics without the Ad Id usage (thus no need for Apple App Transparency Tracking)
Discussion here https://github.com/invertase/react-native-firebase/discussions/5223
2 conventional commits, can be rebase merged
- test with firebase-ios-sdk 7.10.0 and using new podspec variable (should fail, does fail :heavy_check_mark: )
- test with firebase-ios-sdk 7.11.0, using new variable, with admob too (should fail, does fail :heavy_check_mark: )
- test with firebase-ios-sdk 7.11.0 using new variable, no admob (should use new subspec, …
> feat(analytics, ATT): allow use of AnalyticsWithoutAdIdSupport pod

- packages/analytics/e2e/analytics.e2e.js
- packages/analytics/lib/index.d.ts
- packages/analytics/lib/structs.js
This pull request addresses the problem of not being able to pass the price parameter when trying to log `view_item_list`
But as described in the official [documentation](https://firebase.google.com/docs/analytics/measure-ecommerce#web-v8_1) it must be possible.
🔥
> fix(analytics): added missing price parameter to the Item structure

- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
WritableNativeMap has a check to see if it is consumed or not when it is used,
to prevent resolving a Promise in native code then attempting to modify it.
We may use the same WritableNativeMap object twice though when handling deferred
initial notifications. Crash repair is to store a copy so the Maps are distinct
Fixes #5231
Hard to test - will rely on @xxsnakerxx for reports on whether it happens or not, they appear to have a customer with a reproduction case
---
Think `react-native-firebase` is great? Please consider supporting the project with any of …
> fix(messaging, android): repair crash handling remote notifications

- packages/app/android/src/reactnative/java/io/invertase/firebase/common/ReactNativeFirebaseJSON.java
- packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java
- packages/app/firebase-schema.json
- tests/firebase.json
This is entirely based off the good work from @danwhite-ipc on #5228 - just doing a branch here so I can push one final change to it - I don't have write powers on that branch
From that PR:
> Allow for configuration of background native activities to allow for the handling of background messages when a native activity is visible and the react native app is dead.
Supercedes #5228 but verified the CLA was signed.
Fixes #5219
PR title is conventional, squash merge
Relying on @danwhite-ipc to indicate it works for them :-), I added a test array key to the test app firebase.json …
> feat(app, android): support list of Activities to ignore when detecting AppState

- tests/ios/Podfile
- tests/ios/Podfile.lock
Auto-detection of whether to include or exclude leveldb is flaky for me
Use the deterministic exclude-leveldb subspec
invertase/firestore-ios-sdk-frameworks#32
This is based on #5239 and will be rebased once that lands
Then it's a single conventional commit and should be rebase-merged
The linked issue has the full test plan, but for the purposes of RNFB, if CI passes while using this, it's good to go
--- …
> test(e2e, ios): deterministically exclude leveldb

- packages/analytics/__tests__/analytics.test.ts
- packages/analytics/android/src/main/java/io/invertase/firebase/analytics/UniversalFirebaseAnalyticsModule.java
- packages/analytics/android/src/reactnative/java/io/invertase/firebase/analytics/ReactNativeFirebaseAnalyticsModule.java
- packages/analytics/e2e/analytics.e2e.js
- packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m
- packages/analytics/lib/index.d.ts
- packages/analytics/lib/index.js
Adding feature for setting default event parameters. As described [here](https://firebase.google.com/docs/reference/kotlin/com/google/firebase/analytics/FirebaseAnalytics#setdefaulteventparameters) in Firebase docs.
Added `setDefaultEventParameters`. It adds default event parameters that will be send in every event.
--- …
> feat(analytics): Adding default event parameters

- .github/workflows/tests_e2e_ios.yml
This was my hoped-for goal with the buildcache work - to have it be a trivial-to-use action that could span across all the Xcode builds Invertase touches. I think it's all working and here is the test integration
#5239 
The whole thing is a test :-), but the action itself is well-tested during development, and was based on the well-tested proof of concept here
--- …
> test(e2e, ios): buildcache via an action vs in situ

- packages/analytics/lib/index.d.ts
Function description for logSelectItem was copy pasted from select_content, but the two events are different.
Replacing the function description with the one from Firebase:
https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event#SELECT_ITEM
- [x ] Yes
- [x ] `iOS`
- [x ] No
:fire:
> docs(analytics): correct logSelectItem documentation

- .github/workflows/linting.yml
- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- .github/workflows/tests_jest.yml
The workflows were not uploading fresh caches after runs
I learned a lot about github caching while working on buildcache-action,
implementing better caching key usage here to implement the knowledge...
It turns out github caches are immutable so if there might be updates of any kind you
really want to specify a deterministically unique key as the cache key, with a generic fallback
If your key is generic in any way, then even if the directory contents change a fresh cache won't
upload because the key is the comparison for "should it upload or not", as opposed to "are the directory
contents fresh or not" - directory contents are not taken into account
None
- …
> test: improve caching in workflows

- docs/firestore/usage/index.md
`transaction.set` does not return a promise, there is no need to `await` it. This could lead to a confusion among users since `await` usually indicates a promise.
#5087 
doc(firestore): remove await before transaction.set
This is a doc-only change, no need for testing
> docs(firestore): remove await before transaction.update

- .github/workflows/tests_e2e_ios.yml
- package.json
- tests/ios/Podfile.lock
- tests/package.json
- yarn.lock
this includes bump to react-native 0.64.1 for test app so
that it works with Xcode 12.5
passes both e2e runs locally (ios and android)
required for my local environment before I can do other things since I'm on Xcode 12.5 now
---
> chore: update javascript dependencies

- .github/workflows/create_test_patches.yml
- .github/workflows/linting.yml
- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- .github/workflows/tests_jest.yml
- had a typo in one of the usages: restore-key -> restore-keys
- the versioning in the cache key should be before disambiguating key components
- all keys need something disambiguating or they never update (e.g., ios firestore emulator)
No related issues - just a stream of quite a few PRs recently...
I'm discovering these things by actually reading the action run output, that's the continued test plan - checking output
---
> test: more cache key/restore-keys work

- packages/admob/lib/index.d.ts
BannerAd callbacks were not marked optional in Typescript. However, they are presented as optional in the documentation and the implementation checks for their existance before attempting calls.
- Fixes #5180 
I tested this minor change locally and made sure `yarn lint` and `yarn tests:jest` pass.
---
> fix(admob): mark BannerAd callbacks as optional

- packages/firestore/e2e/GeoPoint.e2e.js
- packages/firestore/lib/FirestoreGeoPoint.js
> fix(firestore): GeoPoint latitude error message incorrectly used 'longitude'

- docs/admob/european-user-consent.md
The Admob [European User Consent](https://rnfirebase.io/admob/european-user-consent#delaying-app-measurement) still include the `admob_app_id` config key which  has been replaced with `admob_android_app_id` and `admob_ios_app_id`. This PR fixes the usage of the outdated config keys. (I made sure this was the last place they were used).
- Related to #2611
I formatted the edited file and looked at the compiled the docs.
--- …
> docs(admob, consent): admob_app_id config key gone, note platform-specific keys

- packages/app/firebase-schema.json
Fixes #5295 - credit @DoctorJohn thanks!
Commit message says it all, more details in linked issue if needed
---
> fix(app, json-schema): admob_delay_app_measurement_init type is boolean

- tests/e2e/init.js
currently Detox is force killing the app before Firestore finishes and returns
---
> test(e2e, android): sleep a bit / use right path for coverage file

- docs/index.md
4.3.6 was non-functional, code was updated but docs weren't
Credit to @marqroldan for spotting it, thanks!
https://github.com/invertase/react-native-firebase/commit/d97587b33aa4c092a0d34291e24491ca66f9bcaa#r50879443
Tests already using suggested version, known working
---
> docs(app, android): suggest 4.3.8 of google-play-services plugin

- .spellcheck.dict.txt
- docs/crashlytics/usage/index.md
I write a blog post on how to verify crashlytics installations but never linked it in the crashlytics docs
https://github.com/invertase/react-native-firebase/discussions/5318
conventional commit title / PR title
---
> docs(crashlytics, install): add link to crashlytics install/verify blog

- jest.setup.ts
- packages/firestore/__tests__/firestore.test.ts
- packages/firestore/e2e/firestore.e2e.js
- packages/firestore/lib/FirestoreDocumentReference.js
- packages/firestore/lib/FirestoreQueryModifiers.js
- packages/firestore/lib/FirestoreTransaction.js
- packages/firestore/lib/FirestoreWriteBatch.js
- packages/firestore/lib/index.d.ts
- packages/firestore/lib/index.js
- packages/firestore/lib/utils/serialize.js
Add the firestore ignoreUndefinedProperties setting, per all the information on #5312 
This is a breaking change. We used to allow undefined and they would result in nulls in the database.
You will need to set ignoreUndefinedProperties to true in firestore settings to restore the old behavior if you want it
This was done because the other SDKs throw on undefined, specifically firestore-js-sdk which we attempt to mimic as much as possible including in error conditions
This supercedes the fantastic work done by @jmif on #5312 - I don't have rights to push to that repo but I wanted to re-shape how the testing was done (most of it seemed like a better fit for unit tests - something we are trying to convert to more in the repo) and it was the perfect moment, but that seems like a bit of a drag …
> feat(firestore)!: ignore undefined properties setting, with tests

- package.json
- packages/database/e2e/query/on.e2e.js
- packages/database/e2e/query/once.e2e.js
- packages/firestore/e2e/QuerySnapshot.e2e.js
- tests/e2e/init.js
Always trying to have more testing and more reliable testing...
Related #4058
conventional commits - rebase merge
Nothing but tests
---
> test(e2e): de-flake tests

- .github/workflows/scripts/start-firebase-emulator.sh
- packages/app/android/src/reactnative/java/io/invertase/firebase/common/ReactNativeFirebaseModule.java
- packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java
- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/database/android/src/main/java/io/invertase/firebase/database/UniversalFirebaseDatabaseCommon.java
- packages/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreTransactionModule.java
- packages/storage/android/src/main/java/io/invertase/firebase/storage/ReactNativeFirebaseStorageCommon.java
- packages/storage/android/src/main/java/io/invertase/firebase/storage/ReactNativeFirebaseStorageModule.java
- tests/android/build.gradle
- tests/android/lint.xml
Lots of items picked off from #5324 as they were seen while in the area but were separate
Fixes #3917 (I think, issue has a request for feedback already)
Fixes #4097 
conventional commits - rebase merge
Tested locally e2e on android (it's a batch of android fixes) and CI will check it
---
> fix(android): misc fixes: storage crashes, auth error messages, lint

- .github/workflows/scripts/start-firebase-emulator.sh
Last script edit was perfect for CI but did not get the *non*-CI case correct, so it would re-spawn after exit
Now in non-CI environments it will correctly exit when the emulator is done
Original commit was in PR #5335 
---
> test(e2e, emulator): correctly handle exit in non-ci environments

- .github/workflows/scripts/firebase.json
- .github/workflows/scripts/start-firebase-emulator.sh
- .github/workflows/scripts/storage.rules
- jest.setup.ts
- packages/app/lib/index.d.ts
- packages/app/lib/internal/constants.js
- packages/storage/__tests__/storage.test.ts
- packages/storage/android/src/main/AndroidManifest.xml
- packages/storage/android/src/main/java/io/invertase/firebase/storage/ReactNativeFirebaseStorageModule.java
- packages/storage/e2e/StorageReference.e2e.js
- packages/storage/e2e/StorageTask.e2e.js
- packages/storage/e2e/helpers.js
- packages/storage/e2e/storage.e2e.js
- packages/storage/ios/RNFBStorage/RNFBStorageModule.m
- packages/storage/lib/StorageReference.js
- packages/storage/lib/index.d.ts
- packages/storage/lib/index.js
- packages/storage/lib/utils.js
- tests/app.js
- tests/package.json
- yarn.lock
Each commit has it's own informative title and notes
Turn off your network and run e2e tests with the storage emulator running or
turn off the emulator and try to run e2e tests
Right now those show Android and iOS is using the emulator and it's all working
There are a few platform-specific issues marked FIXME, that need  followup with firebase repos
- metadata issues
- permission issues
--- …
> feat(storage): support storage.useEmulator, and md5hash metadata on upload

- packages/auth/android/build.gradle
Previous versions of firebase-android-sdk did not express their dependency
on androidx.browser library but used it for reCAPTHCA flow, leading to crashes.
We had to temporarily add a dependency here/downstream to work around.
Upstream has the dependency now, verified via `./gradlew :app:dependencies`
Fixes #4744
---
> fix(auth, android): remove browser dependency, upstream includes now

- .spellcheck.dict.txt
- docs/crashlytics/android-setup.md
- docs/releases/index.md
- packages/app/package.json
- tests/android/build.gradle
- tests/ios/Podfile.lock
- fix up a spelling dictionary lint thing
- bump SDK versions, especially for firebase-ios-sdk 8.1.1 to avoid app store rejections
https://github.com/firebase/firebase-ios-sdk/issues/8222
conventional commits, should result in v12.1.0 here
Passed e2e testing on local device, should pass CI as well
---
> feat(app): bump SDKs: firebase-android-sdk 28.1.0 / firebase-ios-sdk 8.1.1

- .eslintignore
- .github/workflows/linting.yml
- package.json
- packages/storage/e2e/StorageTask.e2e.js
Two small lint fixes, this allows lint test to pass - without these it failed
none logged
---
> style(lint): ignore typescript compilation artifacts, fix lint in storage e2e test

- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- package.json
- tests/ios/Podfile.lock
CI Speedups
- ccache 4.3 *should* fix the problem with Xcode always seeming to "use multiple source files" causing cache miss
- podfile.lock was out of date
- metro bundler cache could be better and firebase-tools didn't need a separate install
This batch shaves about 10 minutes off iOS E2E and 5-6 minutes off Android E2E best case, no harm worst case
No release needed, commits follow angular conventional commit guidelines
It's made of tests.
---
- 👉 Star this repo on GitHub …
> test: fix docs lint, update tests Podfile.lock, switch to ccache

- docs/auth/social-auth.md
Facebook is recommending this new (-next) library and on your page the old one is linked:
New library: https://www.npmjs.com/package/react-native-fbsdk-next
See here the official Facebook note 'https://github.com/facebookarchive/react-native-fbsdk'
> docs(auth, facebook): update fbsdk link to fbsdk-next repo

- docs/crashlytics/android-setup.md
- packages/app/package.json
- tests/android/build.gradle
- tests/ios/Podfile.lock
Standard bump to native SDK versions, with conventional commit message that is terse but correct
Native SDK bumps are minor versions. It passed local testing, and CI should further validate
---
> feat(app, sdks): use firebase-ios-sdk 8.2.0 / firebase-android-sdk 28.2.0

- packages/storage/ios/RNFBStorage/RNFBStorageModule.m
Noticed crashes originating from RNFBStorage regarding `Collection <__NSDictionaryM: XXXXXXX> was mutated while being enumerated.`.  This appears to be addressed in some of the other packages already.
https://github.com/invertase/react-native-firebase/issues/3736
> fix(storage, ios): do not enumerate on dictionary being mutated

- docs/crashlytics/android-setup.md
- tests/android/app/build.gradle
Historically it has been difficult to configure crashlytics to upload symbols for native libraries but there's a style now confirmed from the community to work
Fixes #4253 
`cd tests/android && ./gradlew assembleRelease` and it worked
---
> docs(crashlytics, android): show configuration for native libs

- packages/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.m
When NotificationIOS only contains badge, it's not serialized... So I fixed it
Fixed an issue with iOS notification serializing, fixing some missing keys in some edge cases
> fix(messaging): Refactor code to avoid bugs

- packages/database/e2e/query/on.e2e.js
- packages/database/lib/DatabaseSyncTree.js
The cancellation/error callback is not being triggered using the following api
```
ref.on('value', (val) => ... , (err) => { ... })
```
Digging through the code, I noticed the listener is being wrapped but not called. I noticed there is a test for this...but not sure how that is passing.
Fixes #5370 
- [X ] Yes
- [ x] No
--- …
> fix(database): call cancellation callback when using ref.on

- script.sh
> chore: Added ignore build step for next deployments

- packages/app/package.json
Standard native SDK bump
Conventional commit / PR title
CI only
---
> feat(ios): bump firebase-ios-sdk dependency to 8.4.0

- jest.setup.ts
- packages/firestore/__tests__/firestore.test.ts
- packages/firestore/e2e/DocumentReference/set.e2e.js
- packages/firestore/e2e/firestore.e2e.js
- packages/firestore/lib/utils/serialize.js
- tests/ios/Podfile.lock
- tests/ios/testing.xcodeproj/project.pbxproj
The previous change to add ignoreUndefined support and operate like firebase-js-sdk (#5321) did not take into account nested undefined values in arrays, this PR repairs that
Fixes #5437 
2 commits with conventional commit titles, rebase merge should work
I added unit and e2e tests for it, I will request testing from the affected parties via patch-package
--- …
> fix(firestore): accept nested undefined in arrays if ignoreUndefined set

- website/script.sh
Further research shows the build issues may be based on the location of the bash script.
The master branch is based on the `website` directory in Vercel.
This fix looks to move the script here so the `next` branch does not fail it's deployments when running master deployments.
> build(vercel): moved master branch script to website directory

- website_modular/script.sh
The next branch uses `website-modular` as the main entry point for the website.
Adding this in master will allow that deployment to see this configuration when running a `master` branch deployment
> build: added website_modular build script

- docs/messaging/usage/index.md
This change documents the 8 second delay in the delivery of background notifications so developers are aware of the minimum time it will take for a notification do make it to the application in a background state and not have to wonder why it's taking so long.
4144
- [X ] No
Documentation change
---
> docs(messaging): Document the 8 second delay introduced by the earlier mitigation to Issue 4144

- .spellcheck.dict.txt
I merged a PR with a properly-used bit of jargon that was not in the spellcheck dictionary, fixing
> style(spelling): add setBackgroundMessageHandler to dictionary

- .spellcheck.dict.txt
- docs/crashlytics/android-setup.md
- docs/crashlytics/usage/index.md
- docs/index.md
- docs/perf/usage/index.md
Follow-up of #5480, answer to the https://github.com/invertase/react-native-firebase/pull/5480#issuecomment-885475091
Updated documentation about Expo installation steps. I'm not sure how it should look like to be maximum simple and user-friendly. This is how it currently looks like (click to enlarge):
- [Homepage: **Expo** section](https://rnfirebase.io/#expo)
- [Performance Monitoring - Android installation](https://rnfirebase.io/perf/usage#add-the-performance-monitoring-plugin)
- [Crashlytics: Usage - installation section](https://rnfirebase.io/crashlytics/usage#installation)
- [Crashlytics: Android installation page](https://rnfirebase.io/crashlytics/android-setup) - in case someone missed the note in "Usage" page
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the …
> docs: Updated Expo installation steps

- packages/firestore/__tests__/firestore.test.ts
- packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreModule.java
- packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreStatics.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreCollectionModule.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreCommon.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreDocumentModule.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreQuery.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreSerialize.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreTransactionModule.java
- packages/firestore/e2e/firestore.e2e.js
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCollectionModule.m
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.h
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.m
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreDocumentModule.m
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreModule.m
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreSerialize.h
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreSerialize.m
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreTransactionModule.m
- packages/firestore/lib/index.d.ts
- packages/firestore/lib/index.js
This is 100% from @JanErikFoss - just carried his commits into this PR after clobbering #5514
Implements serverTimestampBehavior as a firestore setting.
It's currently impossible to implement SnapshotOptions as they work in the javascript sdk, this is the next best option in my opinion.
#5514
Squash-merge - PR title is conventional
--- …
> feat(firestore): serverTimestampBehavior

- packages/app/.npmignore
- packages/crashlytics/.npmignore
- packages/perf/.npmignore
I noticed that the whole `plugin` directory is published to NPM. The only subdirectory really needed is `plugin/build`, others (src, tests) can be npm-ignored to make the package smaller.
The `plugin/build` dir is generated from `plugin/src` during `npm prepare` step. Its content is required by the `app.plugin.js` file.
🤷 
---
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) …
> fix(expo): Do not publish plugin tests and sources to NPM

- docs/analytics/screen-tracking.md
Updating screen tracking example documentation to include full example. Also removed ``state`` and ``getActiveRouteName`` as you need to create that function to extract active route name from the state. The idea is for someone to quickly use the example without trying to figure out what does ``getActiveRouteName`` and where is it defined.
--- …
> docs: Updating screen tracking example

- packages/app/plugin/src/android/copyGoogleServices.ts
Looks like `fs.promises` was introduced even in Node 10: https://nodejs.org/dist/latest-v10.x/docs/api/fs.html#fs_fspromises_copyfile_src_dest_flags
Node 12 doesn't have `fs/promises` import. But [according to the docs](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fspromises_copyfile_src_dest_flags), the `fs.promises` was introduced in Node 10.
I prefer the asynchronous approach because of better error handling.
Resolves #5584
CI tests
--- …
> fix(app, expo): Missing `fs/promises` import in Node 12

- tests/app.js
it is not currently compatible with App Check
https://github.com/firebase/firebase-tools/issues/3663
The whole thing is made of test work (but to be specific, all CI should pass, especially e2e on android)
---
> test(e2e, android): avoid database emulator on android

- babel.config.js
- docs/index.md
- package.json
- packages/app/package.json
- packages/app/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- packages/crashlytics/package.json
- packages/firestore/__tests__/firestore.test.ts
- packages/perf/package.json
- tests/android/build.gradle
- tests/package.json
- tsconfig.json
- yarn.lock
Some updates
Conventional commits
Lots of e2e runs locally, CI will check it as well
---
> build(deps): dependency updates

- packages/app/plugin/src/ios/appDelegate.ts
https://github.com/invertase/react-native-firebase/issues/5584#issuecomment-898088052
I feel bad at myself not double-checking this earlier. 🤦 
#5584
This time checked that it is the only occurrence of `fs/promises` in **published v12.5.0**:
```
mkdir rnfb_fs_promises && cd rnfb_fs_promises
yarn init
yarn add @react-native-firebase/app @react-native-firebase/perf @react-native-firebase/crashlytics
grep -r fs/promises node_modules
```
The grep output:
```
~/dev/temp/rnfb_fs_promises » grep -r fs/promises node_modules
node_modules/@react-native-firebase/app/CHANGELOG.md:- **app, expo:** Use `fs/promises` in Node 12 compatible way ([#5585](https://github.com/invertase/react-native-firebase/issues/5585)) ([64f569a](https://github.com/invertase/react-native-firebase/commit/64f569acd2cea284baa30 …
```
> fix(app): Fix Node 12 `fs/promises` error in `AppDelegate` Expo plugin

- packages/app/android/src/main/AndroidManifest.xml
- packages/app/android/src/reactnative/AndroidManifest.xml
local inspection of merged manifest indicated they were not being included as thought,
moving them to this manifest shows they are being included
This means that prior to this I do not believe react-native-firebase was ever registering with the native SDK
I do believe that iOS is registering successfully but I'm investigating that separately.
#3766
Conventional commit
1. Do the build `yarn tests:android:build`
2. Find the merged manifest `find tests/android |grep AndroidManifest.xml|grep merged|grep -v androidTest`
3. Inspect the manifest to make sure the definitions you …
> fix(app, android): put app init provider / registrar in correct manifest

- packages/auth/e2e/rnReload.e2e.js
- packages/dynamic-links/e2e/dynamicLinks.e2e.js
- packages/perf/e2e/HttpMetric.e2e.js
- packages/perf/e2e/Trace.e2e.js
- tests/android/app/build.gradle
- tests/android/app/src/main/AndroidManifest.xml
- tests/ios/testing/Info.plist
Trying very very hard to test some dynamic-link issues, and I was able to increase testing here a lot but not really pinpoint the iOS getInitialLink problems
I believe it will have to run on device to really be a good test, which requires all sorts of setup for Xcode signing etc, and doesn't work with Detox in an automated way.
I may have to handle it like the crash buttons and just setup a couple buttons in the test app so that when installed on a real device testing is still possible
Unfortunately - neither of these fixed here - just trying to probe them, not successfully:
#2660 - iOS getInitialLink fails, while Linking.getInitialLink() will return the link for resolution !?
#2631 - on iOS getInitialLink will return same link: open app w/link (correct), background, open again (old link) …
> test(e2e): fix up auth + perf test platform exclusions, increase dynamic-links e2e testing

- packages/app-check/android/build.gradle
- packages/app/e2e/app.e2e.js
- packages/app/firebase-schema.json
- packages/app/ios/RNFBApp/RNFBAppModule.h
- packages/app/ios/RNFBApp/RNFBAppModule.m
- packages/app/lib/index.d.ts
- packages/app/lib/internal/registry/app.js
- packages/app/lib/internal/registry/namespace.js
- tests/firebase.json
Now you may set the firebase log level from firebase.json or via JS
This is very interesting in some cases, like when you need the AppCheck debug token
on iOS, to test AppCheck SafetyNet during development
#5346 - mentioned release build error https://github.com/invertase/react-native-firebase/discussions/5346#discussioncomment-1193672
#5581
conventional commits - rebase merge...
--- …
> feat(app, config): implement setLogLevel API

- packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
- packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m
This prevents `onMessage` from firing on a notification tap when `contentAvailable` is set and the app is in a quit-state,
Currently, the library causes the notification to display twice - once when the app is quit, and again when the notification is tapped to open the app
It's in both apple and firebase docs, that `didReceiveRemoteNotification` can be triggered when  :
[Firebase](https://firebase.google.com/docs/cloud-messaging/ios/receive#handle_silent_push_notifications) :
```
// If you are receiving a notification message while your app is in the background,
// this callback will not be fired till the user taps on the notification launching the application.
```
[Apple](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623013-application?language=objc):
`If the …
> fix(messaging, ios): only call onMessage handler if message is data-only or undelivered

- docs/app-distribution/usage/index.md
The App Distribution usage documentation mentions `app-check` which, I assume, is a copy-paste error.
N/A
:fire:
> docs(app-distribution): remove incorrect reference to app-check

- packages/analytics/lib/index.d.ts
Fixing issue on https://rnfirebase.io/reference/analytics/earnvirtualcurrencyeventparameters - the commented out code in the types incorrectly appears as a comment on the reference for the interface below.
**Before**:
https://rnfirebase.io/reference/analytics/earnvirtualcurrencyeventparameters
**After**:
https://react-native-firebase-git-analytics-ref-docs-issue-invertase.vercel.app/reference/analytics/earnvirtualcurrencyeventparameters
---
- 👉 …
> docs(analytics): fix incorrect docs appearing on reference page

- packages/app-distribution/android/src/main/java/io/invertase/firebase/appdistribution/ReactNativeFirebaseAppDistributionPackage.java
- packages/app/android/src/reactnative/java/io/invertase/firebase/app/ReactNativeFirebaseAppModule.java
- packages/app/e2e/events.e2e.js
- packages/app/lib/internal/RNFBNativeEventEmitter.js
- tests/ios/Podfile.lock
As discovered by @wfern we appear to have a missing couple of APIs needed by react-native 0.65
This will hopefully fix that
Hopefully someone can try the patch set (available from  this URL - https://github.com/invertase/react-native-firebase/suites/3536859145/artifacts/84635700 - grabbed from the "artifacts" dropdown from the details link on the patches action  below :point_down: ) - integrate it with https://github.com/ds300/patch-package and should work?
Fixes #5614 
conventional commits --> rebase merge
---
Think `react-native-firebase` is great? Please consider supporting …
> fix(app, android): react-native 0.65 compatibility

- packages/app-check/android/settings.gradle
- packages/app-distribution/android/settings.gradle
- packages/app-distribution/android/src/main/java/io/invertase/firebase/appdistribution/ReactNativeFirebaseAppDistributionModule.java
- packages/app-distribution/e2e/app-distribution.e2e.js
- packages/in-app-messaging/android/settings.gradle
- tests/ios/Podfile.lock
I noticed while test-integrating the new modules that app-distribution didn't even load on android, which is unexpected
It is not supported on android yet, but the module should at least load
rnfbdemo is my test-integration test bed, it failed without this, and I was able to probe it in e2e
If CI passes, we're good
--- …
> fix(app-distribution, android): implement react methods so module loads

- docs/functions/writing-deploying-functions.md
The current curl command in writing-deploying-functions.md doesn't work. Firebase Callable functions expect a POST method and the body must contain a field called data.
(See: https://firebase.google.com/docs/functions/callable-reference)
> docs(writing-deploying-functions): Given curl command doesn't work

- docs/messaging/server-integration.md
A little typo fix in the Server Integration page of the messaging docs.
- [] No
🔥
> docs(messaging): a little typo fix

- docs/analytics/usage/index.md
Just a fix for the anchor link in the Analytics documentation.
I've checked all the other anchor links in the markdown files. The others are correct.
None.
🔥
> docs(analytics): fix anchor link to predefined and custom events

- packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
- packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m
Reverts invertase/react-native-firebase#5604
From additional testing, fixes the duplication issue but causes another issue where apple throttle `willPresentNotification` with the presence of `mutableContent` in the payload
I will be pursuing other solutions as the duplicate notification bug causes a big issue in apps
> fix(messaging, ios): revert "fix(messaging, ios): only call onMessage handler if message is data-only or undelivered"

- packages/app-distribution/ios/RNFBAppDistribution/RNFBAppDistributionModule.m
On iOS device crashes when called `firebase.app().appDistribution().checkForUpdate()`.
This happens when `release.releaseNotes` is nil. Because the current implementation is assigned to an NSDictionary even if `release.releaseNotes` is nil.
This PR has been changed to return NSNull if it is nil.
https://github.com/invertase/react-native-firebase/blob/600dee0547423e3a9e1cce2451aad5f95c5e28dd/packages/app-distribution/ios/RNFBAppDistribution/RNFBAppDistributionModule.m#L96-L102
In addition, it fixes the issue of `resolve` being called twice.
N/A
---
Think `react-native-firebase` …
> fix(app-distribution, ios): avoid crash when releaseNotes is nil

- packages/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java
If a null intent is passed to `FirebseDynamicLinks.getInstance().getDynamicLink(currentIntent)`, it crashes with the following error: 
`Attempt to invoke virtual method 'java.lang.String android.content.Intent.getDataString()' on a null object reference.`
To avoid that, I added a check for null currentIntent. Of it's null, resolve the promise and return early (same as the check above it for null currentActivity).
:fire:
> fix(dynamic-links, android): check for null currentIntent in getInitialLink to avoid crash

- packages/app-distribution/ios/RNFBAppDistribution/RNFBAppDistributionModule.m
I found a bug that downloadURL was not being passed.
I have reviewed the implementation, and it seems that the `NSURL` is directly passed to `resolve`, and becomes `null` when it is serialized by RN.
`NSURL` is converted to String by accessing the `absoluteString` property, so this bug is fixed.
---
> fix(app-distribution, ios): missing downloadURL

- packages/app/react-native.config.js
The issue was discussed a little [here](https://github.com/invertase/react-native-firebase/discussions/5513). I've been using a patch with this change for a while already and haven't seen this issue so far.
The path used in the script is `_TARGET_PLIST="${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}"`, but the path specified as "input files" was `$(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)`. This caused that sometimes values from `firebase.json` were not taken into account on iOS, because build step "Processing Info.plist" could be executed after "[RNFB] Core Configuration" and it could overwrite the `Info.plist` file.
- My change …
> fix: correct path to 'Info.plist' in ios build script input

- docs/firestore/emulator.md
I got warn 'host in settings to connect with firestore emulator is deprecated. Use useEmulator instead.' So I propose to update with part.
---
> docs(firestore): update emulator usage example with new 

- jest.setup.ts
- packages/analytics/__tests__/analytics.test.ts
- packages/analytics/e2e/analytics.e2e.js
- packages/analytics/lib/index.d.ts
- packages/analytics/lib/index.js
There are cases where the actual limit is more than the default 25, for instance with upgrade analytics plans, 100 may be the actual limit.
See https://github.com/invertase/react-native-firebase/discussions/5676
Conventional commits
The limit was only enforced in the javascript code, native would take whatever javascript validated.
So I added a jest test for the positive and negative cases of setting and using the limit.
--- …
> fix(analytics): allow more than 25 event parameters

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
When doing "linkWithCredential" in Android and the users exists, it makes relogin with this new user instead of launch exception:
Error: [auth/credential-already-in-use] This credential is already associated with a different user account.
---
> fix(auth, android): linkWithCredential will not attempt to upgrade from anon user (matches iOS)

- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- tests/package.json
Just noticed that the detox / e2e build commands were still sometimes doing custom commands instead of using the yarn run scripts. This makes it hard to change/improve things as there are multiple command styles in use
With this change the e2e scripts are now all using yarn run scripts for everything I think
If CI passes, it's good
---
> build(e2e): centralize build commands to use all yarn run scripts

- docs/messaging/usage/index.md
Document the behavior of background notifications on iOS when the app is returning from the Quit state.
> docs(messaging): Correct documentation delay in iOS background notification delivery

- docs/index.md
It appears that checking `[FIRApp defaultApp] == nil` will log an error message,
and I'm not sure how it could ever be called twice (which would throw an exception instead)?
Conforms with [upstream documentation](https://firebase.google.com/docs/ios/setup#objective-c)
Fixes #5739
---
> docs(app, ios): remove nil check prior to configure

- packages/app/package.json
- tests/ios/Podfile.lock
Standard firebase-ios-sdk bump, this one appears to diminish some flakiness seen in my Detox upgrade attempt #5734 which is just about ready to go
This passes local e2e tests for me, CI will check it as well
---
> feat(sdk): bump firebase-ios-sdk to 8.8.0

- package.json
- packages/app/RNFBApp.podspec
- tests/ios/Podfile.lock
- tests/package.json
- yarn.lock
This matches underlying firebase-ios-sdk v8.8.0 requirement
---
> fix(ios, app): minimum cocoapods version is 1.10.2, not just 1.10.0

- packages/app/package.json
- tests/ios/Podfile
- tests/ios/Podfile.lock
- tests/package.json
- also includes a test bump to react-native 0.67.0-rc.2 but no one
sees that outside of the repo...
#5803
---
> feat(ios, sdks): bump firebase-ios-sdk to 8.9.0

- docs/analytics/usage/index.md
- packages/analytics/lib/index.js
This PR updates the docs and code with the current reserved event name list from https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics.Event
I didn't understand the reserved analytics event name `ad_activeiew` in the docs and when I checked it against the list I found that it was spelt wrong, it's meant to be `ad_activeview`. While checking that I also realised that the reserved event name list has changed and more items are now included.
I'm not 100% sure if I should have marked this as a breaking change or not. I haven't changed the `logEvent` function's parameters itself but the function will now `throw Error` in some situations where a previous version of the library wouldn't (although, I assume if someone had previously logged with one of …
> feat(analytics): Updated reserved event name list

- docs/crashlytics/android-setup.md
- docs/index.md
- packages/app/package.json
- packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- tests/android/build.gradle
- tests/ios/Podfile.lock
- yarn.lock
- increase our compatibility up to target/compile SDK 31 - this has no impact on library consumers
- increase firebase-android-sdk to v29, this is a breaking change and requires consumers to update their apps to minSdkVersion 19 (as required in underlying react-native 0.64+)
Conventional commits on each one, carefully set up so the breaking change version and notes should go out automatically with useful details
Each commit tested locally, should work in CI as well
---
- 👉 …
> feat(sdks, android)!: firebase-android-sdk v29 / minSdkVersion API19 / target+compile API31

- packages/app/package.json
- tests/ios/Podfile.lock
A simple bump of the iOS SDK to 8.9.1 from 8.9.0
> fix(ios, sdks): bump firebase-ios-sdk to 8.9.1

- tests/android/app/src/debug/AndroidManifest.xml
- tests/android/app/src/main/AndroidManifest.xml
- tests/android/build.gradle
- tests/patches/detox+18.23.1.patch
It was proposed in #5834 that the modules did not work with Android 12
I showed in https://github.com/mikehardy/rnfbdemo/commit/218f551c831c3df4d0034b9783459e833ec880e5#diff-3e27ae623577d0c559bd8ab973a0c34af8cc65ef9beb9868a9cdb029854f8078 that it could work
...but forward-porting our own internal test app to api31 is the best way to show it works
It was seemless except for Detox relying on non-Android12 compatible transitives
Required a patch to Detox, tracked here:
https://github.com/wix/Detox/pull/3055
It works locally, if it passes CI it's good
--- …
> test(e2e, android): forward-port test app to targetSdkVersion 31

- packages/remote-config/__tests__/remote-config.test.ts
- packages/remote-config/e2e/config.e2e.js
- packages/remote-config/lib/index.js
previously if you incorrectly called getAll before setting defaults or fetching any
remote config, we would crash.
Now we initialize values as an empty object, so we have a graceful failure
confirmed via code inspection that this matches expecations from firebase-js-sdk
https://github.com/firebase/firebase-js-sdk/blob/acc58102d4429ce0593ec22192e76018e9d16ed7/packages/remote-config/test/remote_config.test.ts#L333-L335
Fixes #5854
rebase merge the conventional commits
I refactored the remote config tests to put the non-native ones in a jest config and verified those worked
I …
> fix(remote-config, getAll): init with empty config

- jest.setup.ts
- packages/app/firebase-schema.json
- packages/app/lib/internal/FirebaseModule.js
- packages/auth/lib/index.js
- packages/firestore/lib/index.js
- packages/functions/lib/index.js
- tests/firebase.json
I came accross a problem with emulators and the way they are handling `localhost` addresses, described [here](https://github.com/invertase/react-native-firebase/issues/4810).
I would love to see [this](https://reactnative.dev/docs/running-on-device) work with firebase emulators, when running and testing apps on real devices.
I started a discussion [here](https://github.com/invertase/react-native-firebase/discussions/5816)
--- …
> feat(android, emulator): add firebase.json config element to bypass localhost remap

- docs/database/offline-support.md
- packages/database/lib/index.d.ts
`setPeristenceEnabled` and `setPersistenceCacheSizeBytes` are sync calls, which do not return a promise.
Currently the examples expect a promise. This fixes them to expect a sync call.
[]
https://github.com/invertase/react-native-firebase/issues/5886
---
> docs(database, offline): setPersistence* methods are sync not async

- docs/auth/social-auth.md
Fixed a typo, making the whole documentation consistent.
> docs: fixed authentication typo

- docs/auth/phone-auth.md
- [ x] Yes
- [ x] No
No tests, just adding some documentation
---
> docs(auth, phone): add link to upstream android setup instructions

- packages/firestore/__tests__/firestore.test.ts
- packages/firestore/lib/index.d.ts
This is a fix for Typescript types to remove the following two errors:
```ts
type BarType = {
myDate: FirebaseFirestoreTypes.Timestamp;
};
const docRef = firebase.firestore().doc<BarType>(`${COLLECTION}/bar`);
await docRef.set({
myDate: new Date(), // TS2739 Type 'Date' is missing the following properties from type 'Timestamp', [...]
});
await docRef.set({
myDate: firestore.FieldValue.serverTimestamp(),// TS2739 Type 'FieldValue' is missing the following properties from type 'Timestamp', [...]
});
```
fix(firestore): Adjust types to allow setting FieldValues and allow Date in place of Timestamp 
- This is …
> fix(firestore, types): allow FieldValues, Date and Timestamp in doc set and update

- packages/messaging/e2e/messaging.e2e.js
- packages/messaging/lib/index.js
On iOS, `getInitialNotification` in `RNFBMessaging+UNUserNotificationCenter.m` can be `nil` so `getInitialNotification` can be `undefined`. However TS definition says it is `Promise<RemoteMessage | null>`.
I first was thinking of correcting this type definition, however as it will be a breaking change, fixed the proxy layer instead.
None.
None.
Automated tests should cover already.
--- …
> fix(messaging, ios): ensure getInitialNotification returns null vs undefined per types

- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreSerialize.java
- packages/firestore/e2e/issues.e2e.js
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreSerialize.m
- packages/firestore/lib/utils/serialize.js
- packages/firestore/lib/utils/typemap.js
Fixes #3004.
- call `firestore.collection('myCollection').where('myField', 'in', [0])` and confirm that correct results are being returned
> fix(firestore)!: fix Long/Double conversion issues #3004

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/e2e/phone.e2e.js
- packages/auth/lib/PhoneAuthListener.js
@Avishayy noticed in #5917 that our e2e phone auth tests were false-positive and the implementation was in fact broken during the once/on event changeover for one of the recent RN version updates
This fixes the e2e testing and repairs the code
Fixes #5917
All conventional commits
Lots of e2e testing on this one. I'm still not satisfied with the error case but I have seen it work and it follows the same code pattern as the success callback which is definitely working. Needs wider testing
---
Think `react-native-firebase` is great? Please consider supporting the project with any …
> fix(auth, phone): call verifyPhoneNumber callbacks correctly

- packages/app/plugin/__tests__/__snapshots__/iosPlugin.test.ts.snap
- packages/app/plugin/__tests__/fixtures/AppDelegate_fallback.m
- packages/app/plugin/__tests__/fixtures/AppDelegate_sdk44.m
- packages/app/plugin/__tests__/iosPlugin.test.ts
- packages/app/plugin/src/ios/appDelegate.ts
See https://github.com/invertase/react-native-firebase/issues/5936#issuecomment-994412911
The AppDelegate template for Expo has changed again.
- Updated the existing regex
- _Proposed_ a fallback regex, if the line matched by the previous regex ever changes again (hope not!). It matches for `- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:`, but surprisingly is less stable than the previous one. Why? It can be multiline (e.g. the method opening bracket `{` can be in the same or new line). And `mergeContents()` from `@expo/config-plugins` doesn't support multiline matchers. 😒 So I left this solution as a second chance.
> I am leaving it here for further discussion / reference.
Hopefully not. Interestingly, the line that broke SDK 44, actually was part of a …
> fix(app, expo): Update AppDelegate config plugin for Expo SDK 44

- .github/workflows/scripts/firebase.json
- .github/workflows/scripts/functions/.gitignore
- .github/workflows/scripts/functions/package.json
- .github/workflows/scripts/functions/src/exports.ts
- .github/workflows/scripts/functions/src/index.ts
- .github/workflows/scripts/functions/src/sample-data.ts
- .github/workflows/scripts/functions/src/testFunctionCustomRegion.ts
- .github/workflows/scripts/functions/src/testFunctionDefaultRegion.ts
- .github/workflows/scripts/functions/tsconfig.json
- .github/workflows/scripts/start-firebase-emulator.sh
- packages/functions/e2e/functions.e2e.js
- tests/app.js
- tests/ios/Podfile.lock
We were relying on some unpublished function code running in the cloud to verify functions behavior, and not verifying the emulator
Now the functions code is visible in our test harness's emulator directory, and we're using the emulator
#5462 was having a problem with custom regions, now we exercise that and it seems fine
conventional commits per usual
It is literally made of testing
--- …
> test(functions, e2e): use functions emulator in e2e harness

- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsModule.m
Using `crashlytics` in a Expo SDK 44 (latest version) project fails. This is because expo patches the react podspec for swift compatibility reasons (https://github.com/expo/expo/pull/15299) and that causes old style imports to not work.
I fixed the issue by changing the import style. 
More information: https://github.com/expo/expo/issues/15622#issuecomment-997141629
```
› Compiling @react-native-firebase/crashlytics Pods/RNFBCrashlytics » RNFBCrashlyticsModule.m
❌  (/Users/yonom/Documents/GitHub/app/node_modules/@react-native-firebase/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsModule.m:40:10)
38 |   NSMutableDictionary *constants = [NSMutableDictionary new];
39 |   constants[@"isCrashlyticsCollectionEnabled"] =
> 40 |       @([RCTConvert BOOL:@([RNFBCrashlyticsInitProvider …
```
> fix(crashlytics): Expo SDK 44 compatibility

- .spellcheck.dict.txt
- docs/crashlytics/crash-reports.md
- packages/app/package.json
I'm updating the latest version of this library in our app so we can collect ANR issues using the latest version of Firebase Crashlytics, so when reading the Firebase Android BoM documentation I saw that they sent a patch yesterday to avoid a crash (NullPointerException) with the previous version of the firebase analytics library:
https://issuetracker.google.com/issues/210908929
So I think it will be wonderful to have the most stable version. 👍🏽 
- firebase-android-sdk 29.0.3
- Add ANR collection support documentation
No breaking changes, only internal changes in the android …
> fix(app, android): firebase-android-sdk 29.0.3 to fix underlying NPE in 29.0.2

- docs/messaging/ios-permissions.md
- packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.h
- packages/messaging/ios/RNFBMessaging/RNFBMessaging+UNUserNotificationCenter.m
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
- packages/messaging/lib/index.d.ts
- packages/messaging/lib/index.js
`providesAppNotificationSettings` is useful to display a button/link in iOS settings to redirect user to in-app notification settings. However the option is not available in `@react-native-firebase/messaging`
[Apple developer documentation | UNNotificationSettings | providesAppNotificationSettings](https://developer.apple.com/documentation/usernotifications/unnotificationsettings/2990404-providesappnotificationsettings?language=objc)
---
- 👉 …
> feat(messaging, ios): add provideAppNotificationSettings iOS permission / handler

- packages/analytics/android/src/reactnative/java/io/invertase/firebase/analytics/ReactNativeFirebaseAnalyticsModule.java
- packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m
This PR modifies the event parameters so that the `extend_session` parameter is cast to the correct value.
```js
analytics().logEvent('event', { extend_session: 1 })
```
From [Firebase documentation](https://support.google.com/firebase/answer/9191807) (under the heading "Adjust app session timeout"):
> An app session begins to time out when an app is moved to the background, but you have the option to extend that session by including an extend_session parameter (with a value of 1) with events you send while the app is in the background. This is useful if your app is frequently used in the background, (e.g. as with navigation and music apps.)
We found in development that the `extend_session` parameter wasn't being respected through react-native-firebase because they were set to the …
> fix(analytics): extend_session parameter

- packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java
- packages/app-check/e2e/appcheck.e2e.js
- packages/app-check/ios/RNFBAppCheck/RNFBAppCheckModule.m
- packages/app-check/lib/index.d.ts
The return type of the `getToken` method is not of type `{ token: string }`, but rather of type `string`.
On the Android side, the task result here is the `AppCheckTokenResult` class.
https://github.com/invertase/react-native-firebase/blob/master/packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java#L85
The `AppCheckTokenResult` class itself has a `getToken` method, which returns a `String`. 
https://github.com/firebase/firebase-android-sdk/blob/6da8617afe903126afac46ef71b1d857dcfe7ef9/appcheck/firebase-appcheck/src/main/java/com/google/firebase/appcheck/internal/DefaultAppCheckTokenResult.java#L55
Since the string is what is resolved in the Promise, the return type of the javascript method bound to this native code should also be a …
> fix(app-check): getToken returns `{token: string}` not `string` matching firebase-js-sdk

- packages/app/package.json
As @mikehardy requested in [this comment](https://github.com/invertase/react-native-firebase/issues/5379#issuecomment-1003750956) I have tested react-native-firebase on projects with minSdk 19 and it works fine for me.
Downgraded default minSdk from 21 to 19 to support more android devices.
It worth mentioning that I'm currently using the cloud messaging package in my project. if anyone is willing to test this PR on the other packages, feel free to clean its project and then apply the same simple change on this PR, and test their packages' functionality, and report the result …
> fix(app, android): minSdk should be 19 to match firebase-android-sdk

- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
There are some warnings while using UNAuthorizationOptionProvidesAppNotificationSettings without version check.
No related issues.
---
> fix(ios, messaging): add ios version guard for `UNAuthorizationOptionProvidesAppNotificationSettings` usage

- packages/messaging/ios/RNFBMessaging/RNFBMessagingSerializer.m
This from key was provided in react-native-firebase v5 and somewhere
along the way it was lost, the iOS SDK now passes this key through the
internal google.c.sender.id key in userInfo, use it as well.
This relates to the missing `from` key on #5987
fix missing message.from key in iOS messaging
Before the change, an iOS data-only message (with data being `{'test': '123'}` on v6 would look like:
```
{
"messageId": "1641319541474655",
"data": {
"test": "123"
},
"contentAvailable": true
}
```
after this fix, it looks like:
```
{
"messageId": "1641319541474655",
"data": {
"test": …
```
> fix(ios, messaging): serialize google.c.sender.id to message.from

- packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m
I would like to reset the analytics user ID when a user logs out of my app. According to the [setUserId documentation](https://rnfirebase.io/reference/analytics#setUserId), calling `analytics().setUserId(null);` should remove a previously assigned ID from analytics. This works on Android, however on iOS I encounter the following log from the native iOS Firebase SDK:
```
[Firebase/Analytics] User property must be NSString. Value: (nil)
```
Fixes #4931 
fix issue resetting user-property values on ios
Currently, the following log is printed when calling …
> fix(analytics, ios): Convert NSNull values to nil

- packages/messaging/lib/index.d.ts
The function now returns an `AuthorizationStatus` instead of a `granted` boolean. Updated the docs accordingly.
---
> docs(messaging): `requestPermission()` returns AuthorizationStatus not boolean

- docs/app/json-config.md
This PR changes the language around the configuring of modules to be ``you can configure *your installed* modules *by* creating....`` instead of just ``you can configure modules creating...`` with the aim to fix awkward wording and make what it's trying to say clearer.
Tweaked grammar on firebase config page
- My change is to docs and thus is not platform specific
- My change is to docs and thus does not include tests
- My changes is to docs and thus only requires one typescript type: ``change: awesome`` (cheesy, I know)
``Not Applicable (As far as I can tell - plus, I promise my grammar tweaks won't break anything! (maybe))``
:fire:
> docs(firebase.json): improved grammar

- docs/app-check/usage/index.md
- package.json
- packages/app-check/android/build.gradle
- packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java
- packages/app-check/e2e/appcheck.e2e.js
- tests/android/app/src/androidTest/java/com/invertase/testing/DetoxTest.java
Debugging react-native applications with AppCheck is problematic on Android:
1. It relies running our code on a real android device; 
2. It also required an added extra step of `$adb logcat | grep DebugAppCheckProvider ` to extract the secret token that must then be pushed to the Firebase console. This token changes often and made the developper experience and operations much more harder.
3. Configuring the secret token on CI relied on pushing code instead of environment variables.
This PR is a solution for that, and here is the summary of the solution:
1. By default, the behaviour is the same as what we had before -- that is default to use the DebugAppCheckProviderFactory.
2. If a FIREBASE_APP_CHECK_DEBUG_TOKEN env var is provided and we're in debug mode -- use that instead of the …
> feat(app-check): android debug token argument for app-check

- packages/messaging/lib/index.js
`messaging.NotificationAndroidPriority.PRIORITY_MIN` was `undefined`
Fixes #6027
---
> fix(messaging): add missing PRIORITY_MIN value it JS part

- packages/app-check/e2e/appcheck.e2e.js
- packages/app-check/ios/RNFBAppCheck/RNFBAppCheckModule.m
- packages/app-check/lib/index.js
- packages/app/lib/internal/registry/namespace.js
- tests/ios/Podfile.lock
- tests/patches/react-native+0.67.1.patch
Clean up some issues in the app-check implementation
Fixes #5981 where @rawatnaresh noticed we were not handling parameters correctly for activate
Fixes #6052 where @birdofpreyru noticed we were not returning correctly from activate on ios
Fixes #6009 where @FakhruddinAbdi noticed the error message we gave on app-check import missing was wrong
all conventional commits, rebase-merge --> release
I added e2e test cases to probe the failures noted by the people logging the issues in order to reproduce their problems, then repaired the code such that the e2e tests passed
---
Think …
> fix(app-check): fix activate parameters and return, and app-check import advice

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/lib/Settings.js
- packages/auth/lib/index.d.ts
At the moment it is only possible to disable the app verification on the iOS platform for testing.
As I wanted to create e2e tests for the android version of my app, I created the necessary code changes to make this flag also possible on the Android platform. 😄
No related Issue as far as I now.
auth: appVerificationDisabledForTesting now also settable for Android platform
:fire:
> feat(auth, android): add android for disable app verification feature

- docs/auth/social-auth.md
- packages/auth/e2e/provider.e2e.js
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/auth/lib/providers/FacebookAuthProvider.js
Add support for [Facebook Limited Login](https://developers.facebook.com/docs/facebook-login/limited-login), as well as some testing and documentation around that feature.
Fixes #5441.
Add support for Facebook Limited Login.
Using this patchset in one of my own apps, login into Facebook w/ and w/o limited login is still functional:
```
userStateChanged to {
"displayName": "Martin Maze",
"email": null,
"emailVerified": false,
"isAnonymous": false,
"metadata": {
"creationTime": 1644870528653,
"lastSignInTime": 1644875913305
},
"phoneNumber": null,
"photoURL": …
```
> feat(auth, ios): Add support for Facebook Limited Login

- packages/analytics/RNFBAnalytics.podspec
Right know it looks only if it is defined and not if it set as true, same error as in older appsflyer-react-native-plugin xD
Fix RNFirebaseAnalyticsWithoutAdIdSupport flag in Podfile
- This is a breaking change; (Hard to decide I would say yes because it will change someones dependencies after upgrade)
> fix(analytics, ios): handle RNFirebaseAnalyticsWithoutAdIdSupport == false Podfile case correctly

- .github/dependabot.yml
starting out to handle top-level of monorepo and github actions
> chore(deps): add dependabot configuration

- packages/remote-config/lib/index.d.ts
Thanks to @jeafgilbert for pointing it out!
> docs(remote-config): ConfigSettings example should use fetchTimeMillis

- packages/app/scripts/genversion-ios.js
Expo 44+ enforces use of new import style for React headers, and they
are supported far enough back in time on react-native versions this should
not be breaking for anyone
Fixes #5965 
single commit, it's conventionsl
It's an iOS import style change, either it compiles or it does not. Compiles in local testing, e2e will check as well of course
--- …
> fix(ios, expo): use modern import style, required by Expo 44+

- packages/storage/ios/RNFBStorage/RNFBStorageModule.m
- tests/ios/Podfile.lock
The whole system appears to build and run just fine as a catalyst app on macOS machines, with the one exception of this build issue here
discovered while working on general react-native catalyst issues - 
https://github.com/facebook/flipper/issues/3117
conventional commit message
E2E tests exercise it a bit, I'm going to check out the test coverage to make sure that these lines were hit on iOS, if they weren't (yet) I'll add a test to make sure they are exercised
---
- 👉 Star …
> fix(storage, ios): fix build failure for catalyst compiles

- .spellcheck.dict.txt
- docs/app-check/usage/index.md
Add explanation on how to configure App Check for testing on android emulators when using EAS expo-dev-client.
This allows people using expo-dev-client on an emulator to use Firebase App Check's Debug provider
Edit docs/app-check/usage/index.md to add explanation for using App Check debugging with expo-dev-client.
Review the doc.
> docs(app-check): expo-dev-client support for App Check docs

- docs/index.md
- package.json
- packages/app/package.json
- tests/ios/Podfile.lock
- tests/package.json
- yarn.lock
Planning a release with just 8.13.0 from firebase-ios-sdk in case people need to triage a problem in different iOS releases
Release with 8.14.0 will follow
firebase-android-sdk update still blocked on triage in #6122 but this gets iOS releases out the door
Full local test runs of E2E, CI will prove it out as well
---
> feat(ios, sdk): bump to firebase-ios-sdk 8.13.0 as independent release

- packages/app/package.json
- tests/ios/Podfile.lock
released independently in case it becomes useful to
triage issues with different versions
Related #6148 - will merge this after that releases
android blocked pending triage on #6122
Full local run of e2e, CI should validate as well
---
> feat(ios, sdk): bump to firebase-ios-sdk 8.14.0

- README.md
Fixes #6186 
In the React-Native Firebase Documentation is the a spelling mistake of **principals** . Instead of principals there will be principles.
Readme Link :  https://github.com/invertase/react-native-firebase
Screenshot for reference :
> docs(README): fix typo #6186

- packages/app/package.json
- packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksAppDelegateInterceptor.m
- packages/functions/ios/RNFBFunctions/RNFBFunctionsModule.m
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
- tests/ios/Podfile.lock
Not new features for react-native-firebase but they went minor version
so will make it a minor version here
This is a speculative PR to see what the build log looks like. I'd like to check for use of some symbols that were newly deprecated upstream and if they are in use it would be good to forward-port away from them before v9 hits
--- …
> feat(ios, sdk): bump firebase-ios-sdk to 8.15.0

- .github/workflows/pr_title.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>
> chore: Set permissions for GitHub actions

- packages/firestore/lib/index.d.ts
Apparently increment fieldvalue can drop writes!
https://github.com/invertase/react-native-firebase/discussions/5914
---
> docs(firestore, increment): add warning about possible lost writes

- docs/messaging/ios-permissions.md
- docs/messaging/usage/index.md
- docs/messaging/usage/ios-setup.md
- docs/sidebar.yaml
The ios extra setup instructions were linked from the main usage doc but warrant their own sidebar entry I think, since they are vital to module usage on iOS (unlike the manual linking instructions which are not vital for anyone anymore)
Fixes #6214 - @taylorkline - if you could check the Vercel deploy on this and see if it was what you were thinking (once it is disployed) that would be great!
--- …
> docs(messaging, ios): slice the ios-setup doc into sidebar

- packages/app/package.json
- packages/app/plugin/__tests__/__snapshots__/iosPlugin.test.ts.snap
- packages/app/plugin/__tests__/fixtures/AppDelegate_sdk45.mm
- packages/app/plugin/__tests__/iosPlugin.test.ts
- packages/app/plugin/src/ios/appDelegate.ts
- packages/crashlytics/package.json
- packages/perf/package.json
- yarn.lock
Expo SDK 45 will be based on React Native 0.68, which has AppDelegate written in Objective-C++ (Renamed `AppDelegate.m` -> `AppDelegate.mm`). The file content changes are fortunately insignificant for us.
- Bumped `@expo/config-plugins` to `4.1.1` which already supports Objective-C++ App delegates ([commit](https://github.com/expo/expo-cli/commit/d4a3c6c2b975fc4aa632a33a4331a1048a8c7a92))
- **The only significant change in the plugin code**: `if (language === 'objc')` changed to `if (['objc', 'objcpp'].includes(language))`
- Rest of the PR are the tests - did a small refactor and added some tests to check proper language support.
> Hopefully no more changes are required for plugins to work with upcoming SDK 45, but I'll keep an eye on it
- Expo iOS plugin now supports React Native 0.68 …
> fix(app, expo): Support RN 0.68 Obj-C++ AppDelegate

- packages/app/plugin/__tests__/__snapshots__/iosPlugin.test.ts.snap
- packages/app/plugin/src/ios/appDelegate.ts
Expo SDK 45, which is now in beta, has switched to using `objcpp` for `AppDelegate` on iOS. The current import syntax, using `@import`, is incompatible with this. Therefore, SDK 45 beta users using the config plugin are experiencing build issues. This change is backwards compatible with `cpp`, Firebase switched to it 2 years ago (https://github.com/firebase/FirebaseUI-iOS/issues/875 and the linked PR in that issue).
Fixes #6221 
---
- 👉 Follow …
> fix: update Expo plugin to be compatible with objcpp

- packages/app/ios_config.sh
macOS 12.3 (released March 24, about a month ago) removed the python2 installation (binary of `python`)
Our ios config script depended on that binary existing and silently failed / false-positived if it did not exist, with symptom being that on ios the config used all default values.
I do a check for python3 existence now and forward-ported the python2 code to python3 so our firebase.json parsing works again. Likely needs the same thing for react-native-google-mobile-ads...
This was only visible on macOS 12.3 machines running our e2e harness (where this functionality is probed) or by eagle-eyed developers who noticed the problem. A related change will move CI to macos-12 runners (just now available!) to make sure it fails on them, then I'll rebase against this to make sure it works... …
> fix(ios, app): macOS 12.3 removed python, use python3

- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
this should probe the python2/python3 failure in ios config infra
Related #6226 
Related #6203 
Also this is a pre-requisite for firebase-ios-sdk v9, since it requires Xcode 13.3+, and that transitively requires macos-12
---
> test: move CI to macos-12 runners

- packages/firestore/android/build.gradle
firebase-android-sdk 29.2.0 has a problem with firestore reconnecting after being in the background, fixed in firestore versions included in bom 29.2.1 and higher
Unfortunately we have an auth emulator issue where we cannot access the 29.2.1 or higher boms yet
So we will temporarily bump firestore to a specific / non-bom version - the newest one before bom 30.0.0 to fix #6158 until upstream issue with auth emu is resolved
Fixes #6158 until we can use a newer firebase-android-sdk
See https://github.com/firebase/firebase-android-sdk/issues/3557
Added the …
> fix(firestore, android): temporarily use newer-than-bom firestore

- packages/app-check/android/build.gradle
- packages/app-distribution/android/build.gradle
- packages/app/package.json
- packages/firestore/android/build.gradle
- tests/android/app/build.gradle
- tests/android/app/jacoco.gradle
- tests/android/build.gradle
Update the native SDKs and javascript dependencies, pretty normal, except...
~~This is not working because of https://github.com/firebase/firebase-android-sdk/issues/3526~~
I expect a 29.2.1 or similar from firebase-android-sdk as soon as they determine root cause + fix
Fixes #6158
> fix(android): firebase-android-sdk 30.0.1

- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
- packages/messaging/lib/index.d.ts
- packages/messaging/lib/index.js
Adds `projectId` and `senderId` token options to set messaging instance to use with FCM (see attached issue)
Fixes #6173
Adds options for `getToken()` to use specific messaging instances. NOTE: BREAKING ARGUMENTS from prior v11 authorizedEntity/scope.
---
> fix(messaging, getToken): add options for messaging instance

- docs/dynamic-links/usage/index.md
- packages/dynamic-links/e2e/dynamicLinks.e2e.js
- packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksModule.m
- packages/dynamic-links/lib/index.d.ts
- packages/dynamic-links/lib/index.js
Noticed while triaging an issue that there was an easy to cover API for firebase-ios-sdk to show dynamic link diagnostics
Output looks like:
```
---- Firebase Dynamic Links diagnostic output start ----
Firebase Dynamic Links framework version 8.15.0
System information: OS iOS, OS version 15.2, model iPhone
Current date 2022-05-26 01:05:05 +0000
Device locale en-US (raw en_US), timezone America/Guayaquil
WARNING: iOS Simulator does not support Universal Links. Firebase Dynamic Links SDK functionality will be limited. Some FDL features may be missing or will not work correctly.
ERROR: Specified custom URL scheme is io.invertase.testing but Info.plist do not contain such scheme in CFBundleURLTypes key.
performDiagnostic detected 1 ERRORS.
---- Firebase Dynamic Links diagnostic output end …
```
> feat(dynamic-links, ios): performDiagnostics API for troubleshooting

- packages/app/package.json
Apparently a pretty serious crash bug that evades crashlytics in 30.0.1
> fix(android, sdk): bump firebase-android-sdk to 30.0.2

- packages/analytics/lib/index.js
ad_impression events are allowed through by the native SDKs despite being reserved words, and this is the recommended way to track ad impressions on certain platforms per upstream docs
Fixes #6307
Supercedes, thus closes #6312
Conventional commit
Reporting user made change locally and tested it - reserved word passes cleanly through native SDKs and shows up in analytics
--- …
> fix(analytics): allow manual tracking of ad_impression

- packages/app/android/src/main/AndroidManifest.xml
- packages/messaging/android/src/main/AndroidManifest.xml
@gustavoggs Noticed in #6288 that we did not have exported status specified in our app service
We do not have any intent-filters on the service, so it is not strictly required (and thus this is not fixing a bug per se) but it is best to explicit
https://developer.android.com/about/versions/12/behavior-changes-12#exported
Additionally, app is directBootAware - this mirrors upstream definition:
https://github.com/firebase/firebase-android-sdk/blob/ad135d8c3c1243b4c673e17bc032ee1052fb2a22/firebase-common/src/main/AndroidManifest.xml#L10-L12
There was a service in messaging that defaulted to false because it had no intent-filter before either, specifying it explicitly as well
Supercedes and thus closes #6288
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed …
> fix(android): specify that android services are not exported

- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
- packages/storage/android/src/main/java/io/invertase/firebase/storage/ReactNativeFirebaseStorageCommon.java
- packages/storage/android/src/main/java/io/invertase/firebase/storage/ReactNativeFirebaseStorageModule.java
- packages/storage/android/src/main/java/io/invertase/firebase/storage/ReactNativeFirebaseStorageUploadTask.java
- packages/storage/e2e/StorageReference.e2e.js
- packages/storage/ios/RNFBStorage/RNFBStorageCommon.h
- packages/storage/ios/RNFBStorage/RNFBStorageCommon.m
- packages/storage/ios/RNFBStorage/RNFBStorageModule.m
- packages/storage/lib/index.d.ts
- packages/storage/lib/utils.js
- tests/app.js
StorageMetadata.customMetadata is an interesting beast. This PR resolves a number of problems with it so that we behave the same way as web, despite android and ios platforms differing in their behavior.
The basic idea is that customMetadata is typed as `Map<String, String>` on web, meaning you may never send a null in there, which implies that you may not use a null value to indicate a single key/value pair should be removed.
Rather, you update the customMetadata all at once as a single unit, passing in the whole map of customMetadata you want to keep as part of the update. Any keys you omit will be removed, and sending in null for customMetadata removes the whole map.
iOS used to allow per-key null to remove keys, but with v9 they are enforcing non-null with Swift so that doesn't work. …
> fix(storage, android)!: android now updates customMetadata as a group

- package.json
- packages/analytics/RNFBAnalytics.podspec
- packages/analytics/__tests__/analytics.test.ts
- packages/analytics/e2e/analytics.e2e.js
- packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m
- packages/analytics/lib/index.d.ts
- packages/analytics/lib/index.js
- tests/ios/Podfile
There is a new privacy-sensitive method for checking conversion apparently? So I added an implementation for it
https://firebase.google.com/support/release-notes/ios#analytics_1
https://support.google.com/google-ads/answer/12119136
Fixes #6321
Related https://github.com/invertase/react-native-firebase/discussions/6264
I checked the sub-pod inclusion via setting the variable toggle in `tests/Podfile` to both true and false, and not including it
It was not included by default (:heavy_check_mark:), not included when false (:heavy_check_mark:), but included when true …
> feat(analytics, ios): implement on-device conversion

- docs/crashlytics/android-setup.md
- docs/index.md
- packages/app/package.json
- packages/app/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- tests/android/build.gradle
https://firebase.google.com/support/release-notes/android#2022-06-23
- includes new crashlytics and google-services android plugins
`yarn tests:android:test` run locally, appears to work fine
---
> feat(android, sdk): use firebase-android-sdk 30.2.0

- docs/messaging/usage/index.md
Updated document to include Background App Refresh manual toggle on iOS devices. My understanding is in this scenario, `setBackgroundMessageHandler` would not trigger and the app will fallback to QUIT state's flow.
resolves #5656
Updated document to include Background App Refresh manual toggle on iOS devices.
---
> docs(messaging, ios): add Background App Refresh / message handler interaction note

- packages/crashlytics/RNFBCrashlytics.podspec
Crashlytics uses headers from this extension cocoapod, but it is only brought-in
automatically by Storage and Functions currently. Depend on it directly
https://github.com/invertase/react-native-firebase/issues/6322#issuecomment-1168902482
Hoping for user feedback from @brascene if adding this in the podspec works in place of pulling in functions or storage packages just for this workaround
--- …
> fix(ios, crashlytics): depend on FirebaseCoreExtension

- packages/analytics/RNFBAnalytics.podspec
When RNFirebaseAnalyticsWithoutAdIdSupport is set to false in Podfile, there should be no warning printed.
There is a warning that is printed anytime this variable is undefined or not true. That is helpful when the variable is undefined, but there's no reason to print the warning if a dev has explicitly set it to false.
N/A
Only print RNFirebaseAnalyticsWithoutAdIdSupport warning if it is not defined
> chore(ios): Prevent warnings when RNFirebaseAnalyticsWithoutAdIdSupport is false

- .spellcheck.dict.txt
- docs/releases/v6.4.0.md
We appear to have suffered some sort of entropy in the spellcheck area, this fixes it
https://github.com/invertase/react-native-firebase/actions/workflows/docs.yml
---
> docs(spellcheck): fix spellcheck issues

- packages/firestore/e2e/GeoPoint.e2e.js
- packages/firestore/lib/FirestoreGeoPoint.js
- packages/firestore/lib/index.d.ts
Adds a `toJSON()` method to a `GeoPoint` instance.
> feat: add GeoPoint toJSON() method

- packages/messaging/RNFBMessaging.podspec
Messaging is having a build failure currently, it needs a direct dependency on the FirebaseCoreExtension pod apparently, if you use the pod without storage, functions or `@react-native-firebase/crashlytics` (which has the dep already)
This may affect other RNFB modules as well, no attempt has been made yet to triage other modules built in isolation (that is, with `@react-native-firebase/app` only)
Fixes #6403
Related #6352
Perhaps @LozytskyiA can check the result of the patch-package action here
---
Think `react-native-firebase` is great? Please consider supporting the project …
> fix(ios, messaging): depend directly on FirebaseCoreExtension pod

- packages/firestore/lib/utils/index.js
_*merge* option is being set to true, even if false is passed! This can result in unexpected results!_
As per documentations, [SetOptions](https://rnfirebase.io/reference/firestore/setoptions) merge can be one of "undefined", "true" or "false". But in the current implementation the false(boolean) value is mistreated as true only!
Fixed the SetOptions *merge* to handle false value.
> fix: *merge* setting to true irrespective of value passed

- packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
This carries over the fantastic work from and supercedes #6392 from @glesperance 
It eliminates a race between auth and messaging on probe notifications, as documented in that PR
squash merge / PR title for conventional commits / semantic release
Apparently in use in production per discussion related PR, received a look from firebase-ios-sdk maintainers as well
--- …
> fix(messaging, ios): eliminate auth/messaging notification race

- docs/index.md
- packages/app/package.json
- tests/ios/Podfile.lock
patch release ingestion of firebase-android-sdk to fix an issue here that blocks Huawei folks (and some Play store) folks from using crashlytics on android
Related: https://github.com/firebase/firebase-android-sdk/issues/3826
Fixes #6327
---
> fix(app, sdk): firebase-android-sdk 30.3.1 / firebase-ios-sdk 9.4.0

- .github/workflows/create_test_patches.yml
- .github/workflows/docs.yml
- .github/workflows/linting.yml
- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- .github/workflows/tests_jest.yml
- packages/messaging/e2e/messaging.e2e.js
- packages/storage/e2e/StorageReference.e2e.js
- tests/ios/Podfile.lock
- tests/package.json
- tests/patches/detox+19.9.1.patch
- yarn.lock
test-only changes - adoption of a new firebase-tools release with a fix for a storage emulator bug, allowing us to re-enable a storage e2e test
at the same time, needed to disable a messaging android setBackgroundMessageHandler issue that was flaky in CI and started flaking locally as well
https://github.com/firebase/firebase-tools/issues/4547 resolved, allowing some forward progress on a storage emu issue
Includes a patch-package addition for https://github.com/wix/Detox/pull/3551 
Includes a tweak to iOS Xcode caching
It's all test-related...
---
Think …
> test: dependency updates for tests app

- docs/index.md
I've been going through upgrading our app to the latest version of react native (from 0.63 to 0.69.4) and saw the note about `use_frameworks` not being supported. The link to the patch workaround is no longer valid and the fix has been merged in. This PR updates to the note to show the release where it was fixed and notes that `Flipper` is still not supported
--- …
> docs(getting-started): update note about `use_frameworks`

- docs/messaging/ios-permissions.md
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
- packages/messaging/lib/index.d.ts
- packages/messaging/lib/index.js
Adds support for the authorization status `UNAuthorizationStatusEphemeral` that was introduced with iOS 14. This status can be returned for App Clips, and means that notifications are allowed for a limited amount of time. See https://developer.apple.com/documentation/app_clips/enabling_notifications_in_app_clips
---
> fix(messaging, ios): Support Ephemeral authorization state

- packages/app/plugin/__tests__/iosPlugin.test.ts
- packages/app/plugin/src/ios/appDelegate.ts
This PR fixes a regression introduced in #6223 and reported in #6477.
Fixes #6477
I added a test that fails without the changes and succeeds with them :)
---
> fix(expo, ios): expo plugin added import multiple times

- packages/auth/lib/index.d.ts
Function verifyPasswordResetCode does return the email address string if valid, therefore, update the TypeScript definition to match.
verifyPasswordResetCode does return string result, without the correct typing, we are forced to ignore the linting warning.
n/a
n/a
---
> fix(auth, types): verifyPasswordResetCode returns Promise<string> with email address

- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
- packages/messaging/e2e/messaging.e2e.js
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.h
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
- packages/messaging/lib/index.d.ts
- packages/messaging/lib/index.js
We have had very specific requirements to send out push notifications using FCM and have implemented an in-house solution using the Firebase Admin SDK. However, we don't get access to the message delivery information in the Firebase Console anymore and want to use BigQuery to analyse this information.
Reading through [the documentation](https://firebase.google.com/docs/cloud-messaging/understand-delivery?platform=android#enable-message-delivery-data-export) we found that the message delivery data export needs to be enabled on the device (after asking for consent of course) and both [ios](https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Classes/FIRMessagingExtensionHelper#-exportdeliverymetricstobigquerywithmessageinfo:) and …
> feat(messaging): add support for setDeliveryMetricsExportToBigQuery

- packages/app-distribution/android/build.gradle
- packages/app/package.json
- packages/app/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- packages/perf/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- tests/android/build.gradle
Bumping android dependencies since they can still move within the release constraints of the v14 branch here
one conventional commit...
`yarn tests:jest` && `yarn tests:android:test`
---
> feat(android): bump firebase-android-sdk to 30.5.0 + gradle plugins

- docs/index.md
A couple of things have been highlighted in the related issue:
1. The expo installation guide did not clarify bare vs managed workflow clearly enough.
2. The expo installation step was not managed in one place (one required iOS step was up in the other section).
Fixes #6443
Clarify Expo Bear vs Managed workflow installation steps.
--- …
> docs(getting-started): Expo Bear vs Managed workflow clarification

- packages/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java
- packages/dynamic-links/e2e/builder.otherplatform.e2e.js
- packages/dynamic-links/ios/RNFBDynamicLinks/RNFBDynamicLinksModule.m
- packages/dynamic-links/lib/builder.js
- packages/dynamic-links/lib/builders/otherPlatform.js
- packages/dynamic-links/lib/index.d.ts
- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
Firebase Dynamic-Links supports an "ofl" parameter, a URL to be opened on platforms other than Android and iOS.
This is useful to specify a different behavior on desktop in the event that the website does not have the capability to handle a deep link intended for mobile apps only.
documentation: https://firebase.google.com/docs/dynamic-links/create-manually
The Firebase iOS SDK exposes methods for setting [other platform parameters](https://firebase.google.com/docs/reference/swift/firebasedynamiclinks/api/reference/Classes/DynamicLinkOtherPlatformParameters), and this commit brings that capability into the react-native-firebase package.
The Firebase Android SDK does NOT have the same other platform parameters, but I was able to work around it by appending the "ofl" parameters to the end …
> feat(dynamic-links): support other platform parameters (OFL)

- docs/auth/social-auth.md
For google authentication Google Play store is required to be installed and updated to prevents errors like [Error: A non-recoverable sign in failure occurred]
On emulator this error are common **[Error: A non-recoverable sign in failure occurred]**  and this can be caused by the emulator not supporting Google Play Service. 
To Resolve this ensure the emulator supports Google Play Service and is updated 
Bug  **[Error: A non-recoverable sign in failure occurred]** 
Google Pay Service is required by react-native-google-signin library
- [ X] Yes
- [ X] `Android`
---
Think …
> docs(auth, social): Play Store APIs required for google sign in

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/database/android/src/main/java/io/invertase/firebase/database/UniversalFirebaseDatabaseCommon.java
- packages/database/ios/RNFBDatabase/RNFBDatabaseModule.m
- packages/firestore/android/src/main/java/io/invertase/firebase/firestore/UniversalFirebaseFirestoreModule.java
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreModule.m
- packages/storage/android/src/main/java/io/invertase/firebase/storage/ReactNativeFirebaseStorageModule.java
- packages/storage/ios/RNFBStorage/RNFBStorageModule.m
- tests/ios/Podfile.lock
Most of the useEmulator calls (except functions?) are "call once only" with the native SDKs throwing errors or otherwise being upset by second calls
However, javascript bundles hot-reload so they cannot determine if they have already called useEmulator or not 
Noted in the specific commits targeted
Fixes #5860
Fixes #5650
Fixes #5723
a bunch of `fix` conventional commits
---
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) …
> fix(emulator): protect against double useEmulator calls natively

- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreCollectionModule.java
- packages/firestore/e2e/Aggregate/count.e2e.js
- packages/firestore/e2e/Query/startAt.e2e.js
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCollectionModule.m
- packages/firestore/lib/FirestoreAggregate.js
- packages/firestore/lib/FirestoreQuery.js
- packages/firestore/lib/index.d.ts
https://firebase.google.com/docs/firestore/query-data/aggregation-queries
e2e tests
---
> feat(firestore, count): implement AggregateQuery count() on collections

- docs/index.md
- packages/app/package.json
- tests/ios/Podfile.lock
Fix the crashlytics upstream crash bug by including new patch release
---
> fix(app, android): use firebase-android-sdk 31.0.1

- packages/functions/android/src/main/java/io/invertase/firebase/functions/UniversalFirebaseFunctionsModule.java
- packages/functions/android/src/reactnative/java/io/invertase/firebase/functions/ReactNativeFirebaseFunctionsModule.java
- packages/functions/e2e/functions.e2e.js
- packages/functions/ios/RNFBFunctions/RNFBFunctionsModule.m
- packages/functions/lib/index.d.ts
- packages/functions/lib/index.js
- tests/app.js
- tests/ios/Podfile.lock
Implemented the new `getCallableFromUrl(url)` method (currently only in firebase-js-sdk@9 but the API is easy enough)
This is a requirement currently for those playing with v2 functions since they publish on non-standard URLs
Fixes #6622
Fixes #6543
Conventional commits
Developed the feature using e2e rig as a testbed, so it's got built in tests
--- …
> feat(functions): implement getCallableFromUrl(url) 

- docs/auth/multi-factor-auth.md
- docs/auth/phone-auth.md
- docs/firestore/usage/index.md
- docs/sidebar.yaml
- packages/app/android/src/reactnative/java/io/invertase/firebase/common/ReactNativeFirebaseModule.java
- packages/auth/__tests__/auth.test.ts
- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/e2e/helpers.js
- packages/auth/e2e/multiFactor.e2e.js
- packages/auth/ios/RNFBAuth/RNFBAuthModule.h
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/auth/lib/MultiFactorResolver.js
- packages/auth/lib/PhoneMultiFactorGenerator.js
- packages/auth/lib/User.js
- packages/auth/lib/getMultiFactorResolver.js
- packages/auth/lib/index.d.ts
- packages/auth/lib/index.js
- packages/auth/lib/multiFactor.js
At Kyan Health we are using `react-native-firebase` for our mobile apps. We plan to roll out multi-factor authentication to our users soon. After implementing the necessary code on the web (using the original Firebase libraries) we were missing multi-factor support for the apps.
I'm aware that there are a few small todos left in the code. Nonetheless I'd appreciate some early feedback from the maintainers to see how we can get the PR merged. :)
* I'm not sure if I'm supposed to add a license header to new files. Let me know and I'm happy to copy the existing header into the newly created files.
*  I'm running into a lot of trouble with testing the iOS part against the Firebase emulator. I marked these tests with `:android:`. I have the feeling that this is not properly implemented on …
> feat(auth): Add multi-factor support for the sign-in flow

- docs/app-distribution/usage/index.md
- docs/index.md
- packages/app/package.json
- tests/android/build.gradle
- tests/ios/Podfile.lock
use new SDKs
...also a bump to the app-distribution gradle plugin, but we only see that in the test app
Fixes #6638 
One conventional commit
---
> fix(app, sdks): firebase-ios-sdk 10.1.0 / firebase-android-sdk 31.0.2

- .github/workflows/create_test_patches.yml
- .github/workflows/docs.yml
- .github/workflows/linting.yml
- .github/workflows/pr_title.yml
- .github/workflows/publish.yml
- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- .github/workflows/tests_jest.yml
- package.json
- tests/ios/Podfile.lock
- tests/package.json
- yarn.lock
I was in another repo fixing workflow actions and remembered they were out of date here as well
Gave them some TLC
Also turns out we were still depending (transitively) in Android on jcenter via jet which appears to be conducting a brownout today (which surfaces these kind of problems...), so fixed that in jet repo with v0.8.2 of jet and bringing that in here so Android CI should pass
non-releasing conventional commits for rebase merge
Watch github actions output to make sure they're good
---
> chore: update workflow actions / codecov uploader / workflow concurrency management

- packages/dynamic-links/package.json
This pull request adds missing build commands from #6650 
#2660 
#4548
https://github.com/invertase/react-native-firebase/issues/4548#issuecomment-1252028059
chore(dynamic-links): add build commands to package.json
To test, add the @react-native-firebase/dynamic-links plugin to the list of RNFB plugins, and verify the AppDelegate has been modified.  
Functionally, real world dynamic link matching is inherently hard to test due to the end-to-end nature of the app install process.  My best recommendation for testing here is
* generate a dynamic link that points to your app that …
> chore(dynamic-links): add build commands to package.json

- packages/auth/lib/index.d.ts
- tests/android/build.gradle
First commit: Android builds broke 'round the world, here's the workaround the community decided on after quite a bit of iteration
Second commit: Fixes #6661 - multi-factor auth types were not complete
> fix(auth, types): augment multi-factor auth types

- packages/database/android/src/main/java/io/invertase/firebase/database/UniversalFirebaseDatabaseCommon.java
- tests/android/build.gradle
2 commits -
1- move to current "best known solution" for telling gradle where to get react-native dep
2- Fixes #6665 by reverting android portion of double-emulator prevention for database, it caused a regression
---
Test plan:
1- android builds or it doesn't - it builds so this fix is good
2- user reporting #6665 verifies that the fix works when applied locally via patch-package
---
> fix(database, android): revert android database double-emulator protection

- packages/firestore/e2e/Aggregate/count.e2e.js
- packages/firestore/lib/FirestoreQuery.js
- packages/firestore/lib/index.d.ts
keeps us closer to JS API, Fixes #6654
I added a test based on existing e2e count tests to make sure the API functions, it does
---
> fix(firestore, count): add countFromServer API, delegates to count

- packages/dynamic-links/plugin/__tests__/__snapshots__/iosPlugin.test.ts.snap
- packages/dynamic-links/plugin/src/ios/appDelegate.ts
The dynamic links workaround on iOS applying `[RNFBDynamicLinksAppDelegateInterceptor sharedInstance];` in `didFinishLaunchingWithOptions` is not properly injected when used along `@react-native-firebase/app` expo plugin because the header tag is the same.
Related to https://github.com/invertase/react-native-firebase/issues/4548#issuecomment-1252028059 as it allows to use with expo the given workaround mentioned by the doc
fix dynamic-links expo plugin
---
- 👉 Star this repo …
> fix(dynamic-links): expo config plugin conflict with main firebase app plugin

- docs/auth/multi-factor-auth.md
- packages/auth/e2e/helpers.js
- packages/auth/e2e/multiFactor.e2e.js
- packages/auth/lib/index.d.ts
- packages/auth/lib/index.js
- packages/auth/lib/multiFactor.js
- tests/ios/Podfile.lock
The original implementation of multifactor auth worked beautifully, but during review I should have noticed the methods were statics when they should have been off the auth() module
Granted, firebase-js-sdk does not support MFA in it's v8/chained API, however this lines the API up with the rest of the APIs on modules such that they will transform v9/modular API
This also fills in a missing type as noticed + requested in #6672
Fixes #6672
THERE IS ONLY CONVENTIONAL COMMITS :laughing: 
Dropping the deprecated version will be a semver major later though
I checked it incrementally …
> fix(auth, multifactor): put multiFactor and getMultiFactorResolver on auth()

- .github/workflows/scripts/functions/package.json
- docs/app-distribution/usage/index.md
- docs/index.md
- package.json
- packages/app/package.json
- packages/messaging/android/build.gradle
- tests/android/build.gradle
- tests/ios/Podfile.lock
- tests/package.json
- yarn.lock
Standard SDK dependency bump
none logged - there was an upstream issue we had a workaround for that we may drop now
conventional as ever
Local run of ios and android e2e
---
> fix(app, android): firebase-android-sdk 31.1.0

- .spellcheck.dict.txt
- docs/index.md
This has come up for a few people - that firebase-ios-sdk now requires Xcode 13.3+ / macOS 12+ - noting it in the pre-requisites just in case
Related #6490
It is a docs only change - I contemplated putting a test for Xcode version into our config shell script (or maybe in the podspec) but decided against it for complexity vs benefit reasons compared with a simple docs change
For future posterity, this appears to work on my machine though, and would just need some parsing and a comparison with the versions desired 
https://apple.stackexchange.com/a/384291/288316
```bash
if …
```
> docs(ios): note Xcode 13.3 / macOS 12 minimum requirement

- docs/messaging/usage/index.md
In the original notification color example the name provided `my-custom-color` will result in an error because '-' is not a valid resource name character. I have updated the example color name to use underscores `my_custom_color` to resolve this.
Error resulting from using an underscore:
`Resource and asset merger: '-' is not a valid resource name character`
Made corrections to cloud messaging notification color documentation.
:fire:
> docs(messaging): Made corrections to notification color example.

- docs/crashlytics/usage/index.md
The NDK link was old, updating it and noting that symbol upload will likely need more config as described in link
Related #6747 
Just a docs change but I'll check the vercel pre-publish to make sure it is correct (and CI will lint the thing)
---
> docs(crashlytics, android): fix link for NDK configuration

- docs/index.md
- packages/app/package.json
- packages/dynamic-links/e2e/dynamicLinks.e2e.js
- tests/ios/Podfile.lock
there are some features in the iOS SDK but they are not exposed here, so just the patch-level version bump is appropriate
This should help those affected by #6725 
conventional commits rule the land
Local runs of e2e tests
---
> fix(app, sdks): ios-sdk 10.3.0 / android-sdk 31.1.1

- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreQuery.java
- packages/firestore/e2e/DocumentSnapshot/get.e2e.js
- packages/firestore/e2e/Query/where.e2e.js
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreQuery.m
- packages/firestore/lib/FirestoreDocumentSnapshot.js
- packages/firestore/lib/FirestoreQuery.js
- packages/firestore/lib/FirestoreQueryModifiers.js
- packages/firestore/lib/utils/index.js
Instead of always transforming the orderBy into a String, I allow the bridge to keep the reference to a FieldPath in order to be able to use FieldPath in native also.
closes #6602
---
> fix(firestore): fix an issue where using `FieldPath` in `orderBy` would lead to a native error being thrown

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreQuery.java
It appears on android that we may crash due to non-threadsafe iteration on user provider data while
serializing the information for javascript listeners
This PR attempts to fix that by creating a shallow copy of the provider data prior to iteration, then working
against the shallow copy
Fixes #6798
E2e tests should exercise it reasonably well, and I'll call for testers on the patch
--- …
> fix(auth, android): use a safe copy of auth provider info to avoid crash

- docs/functions/writing-deploying-functions.md
- 'faker' library was destroyed by the author ([link 🔗](https://stackoverflow.com/questions/21866285/cannot-find-module-faker-after-npm-install-save-dev))
- so I replaced it with `@faker-js/faker`.
- it works.
---
> docs(functions): replace deprecated 'faker' with '@faker-js/faker'

- docs/functions/usage/index.md
- The `useFunctionsEmulator` is deprecated ([link 🔗](https://firebase.google.com/docs/functions/local-emulator#web-version-9))
- I replaced it with an 'useEmulator`.
- The position of the paragraph "Using an emulator" has been moved to the front in the same article.
- Most people who practice following documents will do this in a test environment.
- The paragraph has been moved forward because the explanation section that sets this is at the end, causing confusion.
---
- 👉 …
> docs(functions): replace deprecated 'useFunctionsEmulator' with 'useEmulator'

- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
- packages/messaging/e2e/messaging.e2e.js
- packages/messaging/e2e/messaging.modular.e2e.js
- packages/messaging/e2e/remoteMesssage.modular.e2e.js
- packages/messaging/lib/index.d.ts
- packages/messaging/lib/index.js
- packages/messaging/modular/index.js
- tests/app.js
- tests/e2e/globals.js
- tsconfig.json
1. What to do about the `GetTokenOptions.serviceWorkerRegistration` value. We could pull in this Type: https://www.npmjs.com/package/@types/serviceworker and implement in the `index.d.ts` file?
2. What to do about the `isSupported()` API? I created a new function in existing code but it perhaps it shouldn't be there?
1. If it is supposed to be there, we have to pass in `messaging` as the first argument which isn't the same as the Firebase Web JS SDK v9. 
3. Should we put `icon`, `image` & `title` on their own separate `web` object like `android` & `ios` for `Notification` payload?
4. I've also modularised a bunch of API that have no corresponding API on the Firebase Web JS SDK v9. I assume they are fine as they simply wrap around existing.
```js
export declare function …
```
> feat(messaging): Expose modular API that matches the Firebase web JS SDK v9 API

- CONTRIBUTING.md
- packages/firestore/e2e/Query/where.e2e.js
- packages/firestore/lib/FirestoreQuery.js
- packages/firestore/lib/FirestoreQueryModifiers.js
Retrieving all documents with field not equal to null doesn't work. Example:
```
firestore().collection("USERS").where("address", "!=", null);
```
Returns
```
firebase.firestore().collection().where(_, _, *) 'value' is invalid. You can only perform equals comparisons on null
```
I've looked into  `FirestoreQuery.js` and only equality comparison is allowed. 
```
if (isNull(value) && !this._modifiers.isEqualOperator(opStr)){...}
```
Is there any specific reason for it? Is there anything else I need to change, that I'm not aware of ? 
I've run tests locally and everything passes. …
> fix(firestore): support not equals null query

- docs/app-check/usage/index.md
docs(app-check): Added context for registering app. Added Additional references and context for registering App Check with iOS apps. This step was not previously called out and could cause confusion.
Existing documentation skipped over steps for creating keys and registering with app check apps. 
N/A
docs(app-check): Added context for registering app
N/A
---
:fire:
> docs(app-check): Added context for registering app

- packages/database/lib/index.d.ts
There was an error in the type definition of transactions of the realtime database. When using transactions with non-object values like number or boolean, tsc threw an error `(TS2345: Argument of type '(data: object) => number' is not assignable to parameter of type '(currentData: object) => object'.   Type 'number' is not assignable to type 'object'.)`. When comparing the type definition of react-native-firebase with the one of the official firebase documentation here: https://firebase.google.com/docs/reference/js/v8/firebase.database.Reference#transaction you can see the difference. I changed the type definitions accordingly. 
fixed typedefinition for realtime database transactions
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for …
> fix(database,typescript): transaction update types

- docs/perf/usage/index.md
- packages/messaging/lib/index.d.ts
- packages/perf/android/src/main/java/io/invertase/firebase/perf/ScreenTrace.java
- packages/perf/android/src/main/java/io/invertase/firebase/perf/UniversalFirebasePerfModule.java
- packages/perf/android/src/reactnative/java/io/invertase/firebase/perf/ReactNativeFirebasePerfModule.java
- packages/perf/e2e/perf.e2e.js
- packages/perf/lib/ScreenTrace.js
- packages/perf/lib/index.d.ts
- packages/perf/lib/index.js
- tests/ios/Podfile.lock
The Firebase Android SDK automatically records screen traces ( janky / slow / frozen frames) for activities and fragments. However, these traces do not include information about what Javascript side screen the user is on. Users are left trying to triage which screen introduced a slowdown into their application. In large applications this is nearly impossible. This PR adds support for custom screen rendering traces. They can be used ad hoc however the user wishes. We plan to start them on screen mount in react native and end them on screen cleanup. 
For the most part I've followed the existing patterns in this area of the project. I'm not a big fan of ES6 classes but I implemented using an ES6 class just to stay consistent. 
Performance considerations: because there is no data being …
> feat(perf): add custom screen rendering traces for android

- docs/messaging/usage/index.md
Fix note about android permissions always being TRUE. Is now conditional on being pre api level 33
> docs(messaging, android): add note about permissions on API33+

- docs/messaging/usage/index.md
Since React Native updated to 0.71, code in the `AppDelegate.m` has evolved to rely more on the base implementation provided by the `RCTAppDelegate` class.
0.71.1 added an `initialProps` property to this base class to make it easy to pass initial properties to the initial UIView.
This PR updates the documentation of Firebase Messaging to show how to take advantage of this for injecting the `isHeadless` prop into the app
> docs(messaging): document how to inject isHeadless prop into the app

- .github/workflows/tests_e2e_ios.yml
There were some cleanups during the build and some cache misses on what should have been a clean run, so we are bumping up against size constraints again.
Check the last part of the build iOS app phase of iOS e2e tests and the statistics will show if we have cleanups + misses. There should not be any misses and zero cleanups is best
--- …
> test(ios): increase ccache from 1024M to 1500M

- packages/remote-config/lib/index.js
I fixed the docs and noticed that one of the condition was incorrect so I updated that as well 😓. 
---
> fix(remote-config): incorrect if condition statement & inline documentation update

- packages/app-check/lib/index.d.ts
After the recent update to AppCheck types in 17.2.0, there is still an issue with configuring ReactNativeFirebaseAppCheckProvider when attempting to follow https://rnfirebase.io/app-check/usage:
The issue is due to a mismatch in the TypeScript declaration file.
`ReactNativeFirebaseAppCheckProvider` takes in a single options object:
https://github.com/invertase/react-native-firebase/blob/main/packages/app-check/lib/ReactNativeFirebaseAppCheckProvider.js#L6
while the type declaration indicates it takes in 4 separate objects for each platform:
https://github.com/invertase/react-native-firebase/blob/main/packages/app-check/lib/index.d.ts#L139-L142
Fixes #6886 
- Update ReactNativeFirebaseAppCheckProvider options type
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the …
> fix(app-check, types): Correct ReactNativeFirebaseAppCheckProvider options type

- docs/index.md
- I fixed the frequently asked issue (#6853) after looking `https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh` by @mikehardy 
- according to `make-demo.sh`, I updated the documentation (iOS setup part in `getting started`)
#6853
---
> docs(app): clarify iOS setup instructions, especially around use_frameworks

- packages/app-check/e2e/appcheck.modular.e2e.js
- packages/app-check/lib/index.js
- packages/app-check/lib/modular/index.js
- tests/app.js
- tests/e2e/globals.js
> feat(app-check): Expose modular API that matches the Firebase web JS SDK v9 API

- docs/crashlytics/android-setup.md
- docs/index.md
- packages/app/package.json
- packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
Standard SDK update - app JSON version bump, docs, plugins (not always needed, this had one), plugin test fixture for expo plugin
Fixes #6930
---
> fix(app, android): adopt firebase-android-sdk 31.2.2 w/crash fixes

- packages/auth/lib/index.d.ts
https://github.com/invertase/react-native-firebase/pull/6574 added support for the `OIDCProvider` provider, but it was not added to the typescript declaration file.
cc: @Babsvik @mikehardy 
- auth: add missing `OIDCProvider` to typescript declaration
---
> fix(auth, types): add `OIDCProvider` to typescript declaration

- packages/app/plugin/src/ios/appDelegate.ts
- packages/dynamic-links/plugin/src/ios/appDelegate.ts
The AppDelegate file has changed in the latest React Native release. Native code must be manually added to the AppDelegate file for React Native Firebase to work. In the case of Expo, this is done using config plugins that use a regex to find the right place in the AppDelegate file and add the required code. With the latest changes in React Native, the regex does not find a match, so no code is added to the AppDelegate file. This pull request updated the regex to find a match in the latest version of the AppDelegate.
https://react-native-community.github.io/upgrade-helper/?from=0.70.5&to=0.71.3 -> see AppDelegate.mm
The regex was extended to find this line: self.moduleName = @"RnDiffApp"; where any string can be the moduleName
Without this change react native firebase will not initailize …
> fix(expo): extend expo config plugin regex to match latest version of AppDelegate

- docs/messaging/usage/index.md
I fixed a typo in the docs on Android Permissions in Cloud Messaging.
> docs(messaging): fix typo in android permissions example

- docs/index.md
- packages/app-distribution/android/build.gradle
- packages/app/package.json
- tests/android/build.gradle
- tests/ios/Podfile.lock
Also includes remnants from prior firebase-android-sdk 31.2.3 release - specifically the app-distribution plugin bump was missed before (apologies)
There does not appear to be anything remarkable about this SDK version bump for us at all (excellent!) so just going to leave it pending on CI
> fix(sdk): ios 10.7.0 / android 31.3.0

- docs/crashlytics/android-setup.md
- packages/app/package.json
- packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- tests/ios/Podfile.lock
There have been multiple reports of problems with android release builds recently, looks like root cause is upstream
Recommending people use the 2.9.2 version of the crashlytics gradle plugin until upstream issue is resolved
Related #6983 / #7000 
I used my make-demo script to reproduce the failure and the success after backing plugin version down to 2.9.2 https://github.com/mikehardy/rnfbdemo/blob/main/make-demo.sh
---
- 👉 …
> fix(crashlytics, android): use v2.9.2 of crashlytics android plugin

- docs/app-check/usage/index.md
A user noted that Play Integrity works, but only with Play Store distribution
https://github.com/invertase/react-native-firebase/discussions/7007#discussioncomment-5466678
---
> docs(app-check, android): note that Play Integrity requires Play Store distribution

- packages/app-check/ios/RNFBAppCheck/RNFBAppCheckProvider.m
- tests/ios/Podfile
- tests/ios/Podfile.lock
- tests/package.json
- yarn.lock
This PR updates a couple dependencies on the way to testing + fixing the AppCheck error mentioned in #7014
Root cause of the build error there is a silly (in my opinion, related to my own code...) coding error where I was using `new` vs `alloc` despite that being marked as off limits from firebase-ios-sdk
So, I switched from new to alloc, *which I was using correctly in the same context later in the code already* 🤦 
So this should get people moving as they upgrade their Xcode to 14.3
Fixes #7014 
conventional commits, as ever
`yarn tests:ios:test` after making the changes + …
> fix(app-check, ios): Xcode 14.3 compatibility fix

- packages/app/package.json
- packages/auth/package.json
- packages/crashlytics/package.json
- packages/dynamic-links/package.json
- packages/perf/package.json
- yarn.lock
Expo doctor (npx expo-doctor) warns about rnfirebase packages using outdated expo config plugin dependencies. This PR aligns the dependencies used by rnfirebase config plugins with [the latest expo recommendations](https://docs.expo.dev/home/config-plugins/development-and-debugging/). They now recommend having expo as an optional peer dependency. It also says:
> For simple config plugins that depend on core, stable APIs, such as a plugin that only modifies AndroidManifest.xml or Info.plist, you can use a loose dependency [...]
I verified that's the case for all five config plugins.
- This is a breaking …
> fix(expo): update dependencies of config plugins

- docs/app-check/usage/index.md
Additional modifications to AppDelegate.mm are required in order to load the RNFBAppCheckModule.  Without initializing the AppCheckModule before calling [FIRApp configure], the setup of a custom provider will fail.
Fixes #7044
Fixes #6934 
- [✅] Yes
- [✅ ] `iOS`
- [✅ ] No
---
> docs(app-check, ios): update installation steps

- packages/app-check/lib/index.d.ts
fix: the `configure` method on the `ReactNativeFirebaseAppCheckProvider` does not return, yet the type declaration file said it returns a Promise
---
:fire:
> fix(app-check, types): ReactNativeFirebaseAppCheckProvider.configure returns void not Promise<void>

- docs/auth/phone-auth.md
Add missing useEffect import
---
> docs(auth, phone): add missing useEffect import in sample code

- packages/firestore/lib/index.d.ts
- packages/firestore/lib/index.js
When using the firestore document queries, typescript types seem to ignore the Filter object. Filter is already supported and well documented at https://rnfirebase.io/firestore/usage#filtering.
The documentation example does not compile when using typescript:
```ts
const snapshot = await firestore()
.collection('Users')
.where(Filter('user', '==', 'Tim'))
.where('email', '==', 'tim@example.com')
.get();
```
Adding type support for Filter constraints on document queries.
> fix(firestore, types): add types for Filter constraints on Queries

- packages/firestore/e2e/Query/where.and.filter.e2e.js
- packages/firestore/e2e/Query/where.e2e.js
- packages/firestore/e2e/Query/where.filter.e2e.js
- packages/firestore/e2e/Query/where.or.filter.e2e.js
- packages/firestore/lib/FirestoreQueryModifiers.js
Since late april queries containing `in` and `array-contains-any` together are supported as queries with multiple `in` statements, given that the number of generated `or` queries in normal form is below 30. Since `@react-native-firebase/firestore` is currently blocking any of these queries, this PR aims at removing that block, leaving the check for the normal form limit to the underlying firestore engine.
This is the relevant firebase docs on these limitations: https://firebase.google.com/docs/firestore/query-data/queries#limitations_3
Please note: I do not have a history of the changes available, I know this change has been added with the `or` operator support.
None
Allow the use of `in` and `array-contains-any` in the same query.
- I read the [Contributor Guide](../CONTRIBUTING.md) and …
> fix(firestore): Allow queries with combined in and array-contains-any

- docs/auth/phone-auth.md
- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/lib/Settings.js
- packages/auth/lib/index.d.ts
Add support for the Android-only [`forceRecaptchaFlowForTesting`](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthSettings#forceRecaptchaFlowForTesting(boolean)) method.
---
> feat(auth, android): add forceRecaptchaFlowForTesting API

- packages/auth/lib/index.d.ts
unterminated tag was breaking Vercel docs build, I should have caught that on the PR review, it was obvious in hindsight
Fixes #7166 
Originally caused by #7148 but obviously not on purpose, it was a trivial error that correctly triggered status failures etc
no package release, just a docs change, but Vercel will build + deploy which is all I want
Run of `cd website && yarn` then repeats of  `yarn build` with some instrumentation until I located the issue
---
- 👉 Star this …
> docs(auth): fix docs render issue in AuthSettings

- packages/dynamic-links/README.md
The README in the dynamic-links package pointed to an outdated firebase URL.
:fire:
> docs(dynamic-links): Fix link to firebase docs

- docs/index.md
- packages/app/package.json
- packages/remote-config/e2e/config.e2e.js
- packages/remote-config/lib/index.js
- tests/ios/Podfile.lock
New firebase-ios-sdk / remove remote-config realtime update workarounds
All the upstream + here stuff about realtime updates in remoteconfig needing a couple tweaks
Conventional Commits: This Is The Way
CI should demonstrate them, the testing was a huge part of the whole process
---
> fix(app, ios): incorporate firebase-ios-sdk 10.12.0

- packages/analytics/android/src/main/java/io/invertase/firebase/analytics/UniversalFirebaseAnalyticsModule.java
- packages/analytics/android/src/reactnative/java/io/invertase/firebase/analytics/ReactNativeFirebaseAnalyticsModule.java
- packages/analytics/e2e/analytics.e2e.js
- packages/analytics/e2e/analytics.modular.e2e.js
- packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m
- packages/analytics/lib/index.d.ts
- packages/analytics/lib/index.js
- packages/analytics/modular/index.js
Firerbase Analytics SDKs provide an getSessionId method, and getting this value can help app developers to do cross environment trackings (e.g. Posting events using Google's measurement protocol).
So I implemented a React Native binding for this method.
analytics: implement getSessionId
I made an demo app to test on devices:
--- …
> feat(analytics): add getSessionId

- docs/auth/social-auth.md
- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/auth/lib/index.d.ts
- packages/auth/lib/index.js
Apple requires apps support revocation of the Sign in with Apple token when a user wants to delete their account. Firebase added this support in the Firebase Auth iOS SDK. This PR adds the JS ReactNative bindings so that it can be called from JS.
N/A
Added support for revoking a Sign in with Apple token
This is the same code that I patched into my own project to revoke Sign in with Apple tokens. I tested it extensively in that app. Unfortunately, I'm not allowed to provide screenshots or videos from that app because it is proprietary.
To make sure this works with your app, …
> feat(auth, revokeToken): sign in with apple revokeToken API

- .github/workflows/tests_e2e_ios.yml
- docs/crashlytics/android-setup.md
- docs/index.md
- packages/app-distribution/android/build.gradle
- packages/app/package.json
- packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- tests/android/build.gradle
- tests/e2e/.mocharc.js
- tests/ios/Podfile.lock
- tests/package.json
This is a fairly standard dependency update intended to adopt the latest upstream native SDKs from the Firebase team
The one part of this that I think will work but may result in feedback from users is the adoption of the crashlytics android gradle plugin 2.9.8. Recent versions of the plugin - starting at version 2.9.2 - have had a variety of issues preventing adoption of the current version. I *think* all of those are resolved with this version based on my testing, so I am adopting 2.9.8 officially now
#7002 - the crashlytics android plugin issue
- passed …
> fix(app, sdks): adopt android-sdk 32.2.2 / ios-sdk 10.13.0

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
At minimum phone OTP auth and perhaps other scenarios may crash on very old react-native, because old react-native used to throw an exception if a map didn't contain a key, whereas newer react-native just returns null
Newer code here related to multi-factor auth relied on that returns-null behavior and did not handle the case where an exception may be thrown if a key didn't exist
Avoid this exception+crash by explicitly checking for our desired key prior to getting its value
Fixes #7304
This one is difficult to test in an automated way, as it will never …
> fix(auth, android): avoid crash on react-native < 0.63

- docs/index.md
- packages/app/package.json
- tests/ios/Podfile.lock
- tests/package.json
- yarn.lock
no user-visible changes but one crash fix in the
underlying SDK
also includes test app bump to react-native 0.72.4 and react-native-device-info 10.8.0 - neither of which are user visible
none logged
Passes tests locally
---
> fix(app, sdks): adopt firebase-ios-sdk 10.14.0

- docs/dynamic-links/usage/index.md
Added deprecated warning for firebase dynamic links
> docs(dynamicLinks): added deprecated warning for dynamic links

- .github/workflows/linting.yml
- .github/workflows/publish.yml
- .github/workflows/tests_jest.yml
Minor correction to the linting workflow file around the recent yarn cache work which is intended to work out around the slow macos13 runner issues
> test(ci): fix workflow variable / yarn cache action in lint workflow

- packages/analytics/android/build.gradle
- packages/app-check/android/build.gradle
- packages/app-distribution/android/build.gradle
- packages/app/android/build.gradle
- packages/auth/android/build.gradle
- packages/crashlytics/android/build.gradle
- packages/database/android/build.gradle
- packages/dynamic-links/android/build.gradle
- packages/firestore/android/build.gradle
- packages/functions/android/build.gradle
- packages/in-app-messaging/android/build.gradle
- packages/installations/android/build.gradle
- packages/messaging/android/build.gradle
- packages/ml/android/build.gradle
- packages/perf/android/build.gradle
- packages/remote-config/android/build.gradle
- packages/storage/android/build.gradle
- scripts/_TEMPLATE_/android/build.gradle
Change to support AGP 8 as mentioned here: https://github.com/react-native-community/discussions-and-proposals/issues/671
This does not remove package attribute from AndroidManifest to not lose compatibility with AGP < 8 (React Native < 0.71 versions). 
I don't think it's worth maintaining logic to remove that attribute contitionally since it will [only cause a warning to users on AGP 8](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1607191009) and above. 
[See Kudo's comment on AGP 8 issues with BuildConfig and setting JVM versions.](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1677632448)
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for submitting …
> chore(android): add support for AGP 8 

- packages/storage/lib/index.js
The _android_bypass_emulator_url_remap_ flag is not being validated on the storage package. It works as expected on the packages for functions and authentication but this one in specific remaps the hosts anyway.
The code added was copied from the working code on the functions packasge.
> fix(storage, android): honor android_bypass_emulator_url_remap flag

- packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java
- packages/app-check/lib/index.d.ts
- packages/app-check/lib/index.js
Implement app check token change listener only for android ( as the sdk don't support for iOS )
`onTokenChanged` function will be trigger with object contain `token, expireTimeMillis, appName`
```js
const onAppCheckTokenChanges = (result) => {
console.log("onAppCheckTokenChanges: ",result)
}
React.useEffect(() => {
const subscriber = appCheck().onTokenChanged(onAppCheckTokenChanges)
return subscriber
}, [])
```
> feat(app-check, android): Implement app check token change listener

- docs/index.md
- packages/app/package.json
- tests/ios/Podfile.lock
also includes a bump to play-services-auth 20.7.0
these are feature releases for upstream (primarily to add the new firestore local persistent cache index manager) but those are new symbols and if we adopted them here it would be a breaking change as it would transitivey require users that are overriding the SDK versions to use these new SDKs as a minimum. We will defer that
a single conventional commit
Run the full e2e test suite locally - everything works ✅ 
---
- 👉 Star …
> fix(app, sdks): adopt ios sdk 10.15.0 / android sdk 32.3.1

- packages/auth/e2e/auth.e2e.js
- packages/auth/e2e/emailLink.e2e.js
- packages/auth/e2e/multiFactor.e2e.js
- packages/auth/e2e/phone.e2e.js
- packages/auth/e2e/provider.e2e.js
- packages/auth/e2e/rnReload.e2e.js
- packages/auth/e2e/user.e2e.js
- packages/auth/lib/index.js
- packages/auth/lib/modular/index.js
- packages/auth/lib/providers/PhoneAuthProvider.js
- tests/app.js
- tests/e2e/globals.js
https://github.com/invertase/react-native-firebase/issues/6705
---
> feat(auth): Expose modular API that matches the Firebase web JS SDK v9 API

- docs/index.md
In a few communities there is confusion between using RNF with RN CLI vs. Expo.
This PR puts some clarifying tweaks at the start of the page and promotes the Expo section up one level out of the "Miscellaneous" section.
Hopefully Expo users will no longer jump into the "Installation" steps before realizing that is for RN CLI projects only.
--- …
> docs(app, expo): clarify Expo install docs

- docs/index.md
- This point is not mentioned in the official document or other answers available on platforms like stack overflow.
---
> docs(install, android): emphasize both app signing keys required in firebase console

- packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java
- packages/storage/e2e/StorageReference.e2e.js
- tests/patches/detox+19.12.6.patch
There was an older branch I noticed that had two exploratory test cases I used to collaborate with firebase-ios-sdk in order to work through some upstream issues. They are fixed upstream and released now, so we can adopt the tests in our main branch
Patched them up to work with the new modular e2e files since that happened in the interim
----
Includes 2 random commits that help local testing and don't deserve a separate PR:
- a detox fix that is backwards-compatible but allows me to test things easily locally now that I've got Xcode 15 / iOS 17 in use in some local environments
- a java lint fix from a previous PR since android lint silently fails in CI at the moment
https://github.com/firebase/firebase-ios-sdk/pull/10370
https://github.com/firebase/firebase-ios-sdk/issues/10463 …
> test(storage, ios): enable tests after upstream bug fixes released

- packages/storage/ios/RNFBStorage/RNFBStorageModule.m
On iOS the download URL returned as '443' port in it, which differs from android and web and makes the package non-platform-independent, contrary to the platform independent goal
This removes ':443' from the URL returned, if it is present
Fixes #7363 
One conventional commit
Made sure e2e tests run correctly (which now include downloadURL tests on iOS after re-enabling it in #7361 !)
--- …
> fix(storage, ios): remove '443' port from iOS download URLs

- docs/messaging/usage/ios-setup.md
Attempting to clarify that modern simulators on modern macs may actually get APNs tokens and receive messages now. This was confusing before as the feature was announced earlier as part of breaking changes in react-native-firebase v17 but there was still some documentation around stating exactly the opposite
#6893
docs, no release
Just docs, but if there was a typo or something, CI will find it...
--- …
> docs(messaging, ios): clarify that some simulators may get FCM messages now

- packages/ml/e2e/ml.e2e.js
- packages/ml/lib/index.js
- packages/ml/lib/modular/index.d.ts
- packages/ml/lib/modular/index.js
- tests/app.js
- tests/e2e/globals.js
> feat(ml): add modular API

- .spellcheck.dict.txt
- docs/index.md
- packages/analytics/android/build.gradle
- packages/app-check/android/build.gradle
- packages/app-distribution/android/build.gradle
- packages/app/android/build.gradle
- packages/auth/android/build.gradle
- packages/crashlytics/android/build.gradle
- packages/database/android/build.gradle
- packages/dynamic-links/android/build.gradle
- packages/firestore/android/build.gradle
- packages/functions/android/build.gradle
- packages/in-app-messaging/android/build.gradle
- packages/installations/android/build.gradle
- packages/messaging/android/build.gradle
- packages/ml/android/build.gradle
- packages/perf/android/build.gradle
- packages/remote-config/android/build.gradle
- packages/storage/android/build.gradle
- scripts/_TEMPLATE_/android/build.gradle
- tests/android/app/build.gradle
- tests/android/build.gradle
- tests/package.json
- tests/patches/detox+19.12.6.patch
- yarn.lock
A collection of android gradle plugin 8 compatibility fixes
- Fixes all the remaining instances where react-native-firebase modules weren't compatible yet (we were mostly there, thankfully)
- Sends a PR upstream for detox https://github.com/wix/Detox/pull/4229 - although we're currently stuck on an old version, they'll need this I think, and our local patch is updated for AGP8
- adopts just released version of invertase/jet where I patched+released it for AGP8
- updates the test app here to use AGP8 to show the whole thing works...
---
Think `react-native-firebase` is great? …
> fix(android): required compatibility for android gradle plugin 8

- docs/index.md
- packages/app-distribution/android/build.gradle
- packages/app/package.json
Bump of firebase-android-sdk, nothing to change at the user level that I'm aware of
I want to stage this after a release of #7412 since that one is pretty critical and I'm having bad luck recently with new upstream SDK versions - don't want to have something critical for users released after something that may not work, meaning people won't be able to rollback without losing the critical fix...
there is only conventional commits, this is the way
local e2e test runs, CI will run it as well
---
Think `react-native-firebase` is great? Please consider supporting the project with …
> fix(app, sdk): adopt firebase-android-sdk 32.4.0

- docs/index.md
The links and descriptions of how to create a new Expo app and how to install RNF were incorrect.
These updates push more responsibility to the Expo docs themselves and reduce the amount that RNF needs to document.
---
> docs(expo): improve links and instructions for expo managed workflow

- docs/auth/usage/index.md
1. Fixed a typo where `signin` should be `signout`
2. Added additional info about signing out completely with `GoogleSignin.revokeAccess()`
This was mentioned on #1956
Additional signout information on docs
> docs(auth): fix sign in/out typo + add info about GoogleSignin.revokeAccess()

- docs/messaging/server-integration.md
- Deprecated API: [sendToDevice](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.messaging.md#messagingsendtodevice)
- Use [sendEachForMulticast](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.messaging.md#messagingsendeachformulticast) instead for sending messages to multiple devices.
- Correct `Message` field names:
- fcm_options -> fcmOptions
- image -> imageUrl.
Just docs.
:fire:
> docs(messaging, server-integration): document new / non-deprecated APIs / JSON fields

- docs/index.md
There seems to be an incompatibility between react-native's gradle setup in versions < 0.72 and the google-services-plugin > 4.4.0 - it fails to parse the google-services.json file and generate the correct android/app/.../res/...values.xml files
https://github.com/invertase/react-native-firebase/discussions/7462
docs only
Determined with an rn71 build branch on my demonstrator: https://github.com/mikehardy/rnfbdemo/commit/eb99638b1d11a470c25b94e6a6a178c02031acae
---
> docs: note incompatibility between react-native < 0.72 and google services plugin > 4.3.15

- docs/remote-config/usage/index.md
The docs for remote config `onConfigUpdated` had the incorrect check for the error condition, @JasonPan noticed it should check for `undefined` not `null`
PR from Jason is basically the same but CLA was unsigned so could not merge, just reposting it here so it can save future devs time
* Supercedes #7438
Docs - CI will lint
--- …
> docs(remote-config): onConfigUpdated error check for undefined not null

- .spellcheck.dict.txt
- docs/faqs-and-tips.md
- docs/messaging/usage/index.md
Adding to docs a note about notifee v7 release impacting react native firebase getInitialNotification and onNotificationsOpenedApp. See https://notifee.app/react-native/docs/release-notes#700
---
🔥
> docs(messaging): added note about notifee v7 notification event handling

- docs/auth/social-auth.md
In the latest [PR#7443](https://github.com/invertase/react-native-firebase/pull/7443) I [noticed ](https://github.com/invertase/react-native-firebase/pull/7443/files#r1406164140) that we deleted a section in the docs. So, I've rewritten and returned that deleted section. I've also added quote from the docs for people to understand when they need to use it.
- Yes
- No
🔥
> docs(auth): Link Multiple Auth Providers to a Firebase Account

- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
GHA artifacts are already compressed using zip, no need to compress them twice
> test(ci): do not pre-compress logs sent to upload-archive action

- packages/app/react-native.config.js
- packages/crashlytics/react-native.config.js
- tests/ios/Podfile
- tests/ios/Podfile.lock
- tests/ios/testing.xcodeproj/project.pbxproj
A couple small tweaks to our run scripts so they operate more smoothly + quietly
* https://www.rubydoc.info/gems/cocoapods-core/Pod/Podfile/DSL#script_phase-instance_method
* https://github.com/react-native-community/cli/pull/2182
Checked behavior of the `always_out_of_date` attr locally, plus you can see in the pod-generated xcodeproj that it was carried through correctly.
Checking the build log confirms that the previous warnings about the run script phase always running are no longer present
---
Think `react-native-firebase` is great? Please consider …
> build(ios): specify script runs every time, fix crashlytics input file path

- packages/messaging/app.plugin.js
- packages/messaging/package.json
- packages/messaging/plugin/__tests__/androidPlugin.test.ts
- packages/messaging/plugin/__tests__/fixtures/application-example.ts
- packages/messaging/plugin/__tests__/fixtures/expo-config-example.ts
- packages/messaging/plugin/src/android/index.ts
- packages/messaging/plugin/src/android/setupFirebaseNotifationIcon.ts
- packages/messaging/plugin/src/index.ts
- packages/messaging/plugin/tsconfig.json
- yarn.lock
This PR adds support for Firebase Messaging in Expo projects via a config plugin. This is mainly achieved by setting the appropriate keys (`com.google.firebase.messaging.default_notification_icon` and `com.google.firebase.messaging.default_notification_color`) in the AndroidManifest of the Android project during the build stage. The addition of this plugin will automatically enable Firebase Messaging support for developers using `@react-native-firebase/messaging` in their Expo projects which have the necessary notification configuration.
Displaying notifications correctly on Android requires setting a pure white icon. By default, the system uses the app's own icon as the notification icon, which usually isn't purely white. Therefore, it's necessary to specify a notification icon. If no …
> feat(messaging): Adding support for Firebase Messaging via Expo config plugin.

- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- docs/index.md
- packages/app/package.json
- tests/package.json
Nearly trivial change for the SDK, definitely trivial for us, but best practice to have current SDKs available
I ran e2e tests on android and ios locally, all green
---
> fix(sdk, android): adopt firebase-android-sdk 32.7.0

- packages/auth/lib/index.d.ts
Just fixing some documentation
- [🔥] Yes
I didn't change any code.
> docs(auth): un-cross docs for two states in PhoneAuthState enum

- docs/messaging/notifications.md
You cannot use `useNavigation` hooks from outside of `NavigationContainer` The properly way is to implement `linking` props of `NavigationContainer`. Reference document: https://reactnavigation.org/docs/navigation-container#linkingsubscribe
The previous document was invalid for at least React Navigation v6.
React Navigation won't let you use `useNavigation` hooks from the outside of `NavigationContainer` scope.
Need a real device (for iOS) and emulator/real device for Android to test.
Use FCM to push a notification with these data: `navigationId: required` and `postId: …
> docs(messaging): update notification example for react-navigation v6

- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
Sometimes the `hint.factorID` (in the `firebaseUserToDict` function) is retuning `nil` value and this could cause app crash. I've tried to described my journey with this issue in [this comment](https://github.com/invertase/react-native-firebase/issues/7080#issuecomment-1870635173)
Fixes #7080 
Auth module - nil check in the getJSFactorId function
🔥
> fix(auth, ios): factorId nil check

- packages/firestore/e2e/Query/where.and.filter.e2e.js
- packages/firestore/e2e/Query/where.e2e.js
- packages/firestore/e2e/Query/where.filter.e2e.js
- packages/firestore/e2e/Query/where.or.filter.e2e.js
- packages/firestore/lib/FirestoreQuery.js
Increased amount of maximum disjunctions in firebase from 10 up to 30
- Fixes #7542
---
> fix(firestore): increase amount of maximum disjunctions in firebase

- packages/firestore/lib/index.d.ts
Commit to fix #7147 
Taking `string` type from `@google-cloud/firestore` types: https://github.com/googleapis/nodejs-firestore/blob/22ac90f0a043e493f89834604bd249f69c5dc036/types/firestore.d.ts#L1719
Also the same on `firebase-js-sdk`:
https://github.com/firebase/firebase-js-sdk/blob/991fa271c867d59e2bed44c69c0512fdeb54bbb4/packages/firestore/src/lite-api/query.ts#L478
and the documentation for the `firebase-js-sdk`:
https://github.com/firebase/firebase-js-sdk/blob/991fa271c867d59e2bed44c69c0512fdeb54bbb4/common/api-review/firestore.api.md?plain=1#L473
> fix: typing for firestore `orderBy`

- package.json
Issue: https://github.com/invertase/react-native-firebase/issues/7551
`node` should not be there (AFAICT)
> fix: tests:packager:jet-reset-cache 'Cannot find module' - issue/7551

- .spellcheck.dict.txt
- docs/index.md
Fixed a few formatting issues & divided the section into subsections for clarity in following the steps.
Motivation: people (mainly newcomers to Expo) in the Firebase community struggling to understand the guidance for Expo.
---
> docs(index.md): Expo / EAS updates and fixes

- docs/index.md
Fix wording of Expo configuration section.
Additional fixes to previous PR #7502
Read the doc
> docs(app, expo): fixed wording for the example Expo configuration

- packages/firestore/lib/index.d.ts
The comment above this change even gives an example of a dot notation string.
Taking string type from @google-cloud/firestore types: https://github.com/googleapis/nodejs-firestore/blob/22ac90f0a043e493f89834604bd249f69c5dc036/types/firestore.d.ts#L1587
Also the same on firebase-js-sdk:
https://github.com/firebase/firebase-js-sdk/blob/991fa271c867d59e2bed44c69c0512fdeb54bbb4/packages/firestore/src/lite-api/snapshot.ts#L359
Fixes #7592 
Fix the typing for `DocumentSnapshot.get` to allow dot notation object values
---
Think `react-native-firebase` is great? Please consider …
> fix: Add string type to `DocumentSnapshot.get`

- packages/app/package.json
- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
There is was/is a bug in the firebase sdk(12th of january 2024) that prevents multifactor login from being completed with a secondary app instance, but after that is updated, secondary instances should work with mfa
- Related issue upstream: [#12265](https://github.com/firebase/firebase-ios-sdk/issues/12265)
- Fixes #7339
---
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) …
> fix(auth): use correct app instance (vs always default) in multifactor and phone auth

- docs/index.md
useFrameworks property is not allowed in `ios:{...}` outside of the plugins. Updated app.json config.
---
> docs(app, expo):  updating app.json related to useFrameworks

- docs/analytics/usage/index.md
- docs/analytics/usage/installation/ios.md
- packages/analytics/RNFBAnalytics.podspec
- tests/ios/Podfile
- tests/ios/Podfile.lock
See https://firebase.google.com/support/guides/analytics-adsupport
Ads the ability to define '$RNFirebaseAnalyticsEnableAdSupport' in order to handle the linking for you to get the optional features.
For example, in. Podfile near the top, you may do this and it should Just Work:
```ruby
$RNFirebaseAnalyticsEnableAdSupport = true
```
Note that this will only work with the AdId support enabled, it is mutually exclusive with `RNFirebaseAnalyticsWithoutAdIdSupport` Podfile toggle, as it makes no sense to link the `AdSupport` framework while linking the Firebase Analytics pod that does not contain AdId support
Fixes
- #7027
- My change supports the following …
> feat(analytics, ios): add Podfile toggle to optionally link AdSupport

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
Use `promiseRejectAuthException` and add logging consistent with other methods.
**Before**
```
Error: [auth/unknown] The verification code from SMS/TOTP is invalid. Please check and enter the correct verification code again.
NativeFirebaseError: [auth/unknown] The verification code from SMS/TOTP is invalid. Please check and enter the correct verification code again.
```
**After**
```
Error: [auth/invalid-verification-code] The verification code from SMS/TOTP is invalid. Please check and enter the correct verification code again.
NativeFirebaseError: [auth/invalid-verification-code] The verification code from SMS/TOTP is invalid. Please check and enter the correct verification code again.
```
Arguably a breaking change since the errror codes thrown change.
Errors thrown by …
> fix(auth, android)!: correct error messages for finalizeMultiFactorEnrollment

- docs/index.md
- package.json
- packages/app/package.json
Since yesterday, we have been getting errors when trying to create an iOS build:
```
(/Users/expo/workingdir/build/packages/app/ios/Pods/FirebaseStorage/FirebaseStorage/Sources/Storage.swift:73:12)
71 |     let provider = ComponentType<StorageProvider>.instance(for: StorageProvider.self,
72 |                                                            in: app.container)
> 73 |     return provider.storage(for: Storage.bucket(for: app))
|            ^ value of optional type '?' must be unwrapped to refer to member 'storage' of wrapped base type 'any StorageProvider'
74 |   }
75 | 
76 |   /**
```
It seems that this issue has already been fixed in the Firebase iOS SDK.
See: https://github.com/firebase/firebase-ios-sdk/commit/1ed6d66b2010539bf21abf66b942dcf89384bd75
```swift
guard let provider …
```
> fix(storage): bump iOS SDK to v10.22.0

- docs/app-check/usage/index.md
- packages/app-check/app.plugin.js
- packages/app-check/package.json
- packages/app-check/plugin/__tests__/README.md
- packages/app-check/plugin/__tests__/__snapshots__/iosPlugin.test.ts.snap
- packages/app-check/plugin/__tests__/fixtures/AppDelegate_bare_sdk43.m
- packages/app-check/plugin/__tests__/fixtures/AppDelegate_fallback.m
- packages/app-check/plugin/__tests__/fixtures/AppDelegate_sdk42.m
- packages/app-check/plugin/__tests__/fixtures/AppDelegate_sdk44.m
- packages/app-check/plugin/__tests__/fixtures/AppDelegate_sdk45.mm
- packages/app-check/plugin/__tests__/iosPlugin.test.ts
- packages/app-check/plugin/src/index.ts
- packages/app-check/plugin/src/ios/appDelegate.ts
- packages/app-check/plugin/src/ios/index.ts
- packages/app-check/plugin/tsconfig.json
- yarn.lock
App Check needs [additional setup](https://rnfirebase.io/app-check/usage#initialize) in `AppDelegate` to work which is difficult in a managed Expo workflow.
Created a Expo config plugin similar to other `react-native-firebase` packages such as the one found in [Dynamic Links](https://github.com/invertase/react-native-firebase/tree/main/packages/dynamic-links/plugin). The pull request code is also modeled after the Dynamic Links config plugin.
Added support for Expo config plugin.
Tests have passed. Verified in iOS builds that the new config plugin will add lines as described …
> feat(app-check): Add support for Expo config plugin

- packages/app-check/package.json
This PR fixes the `CommandError: Cannot find module './plugin/build'` error that appears when `expo prebuild` command is executed. It builds the config plugin after the `@react-native-firebase/app-check` package is installed.
* Fixes #7703
---
> fix(app-check): build config plugin

- packages/app/package.json
May fix crash seen but not reproduced upstream
- https://github.com/firebase/firebase-android-sdk/issues/5768#issuecomment-2020388078
Local run of e2e test + CI
---
> fix(app, android): bump google play-services-auth to 21.0.0

- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- .github/workflows/tests_jest.yml
- docs/index.md
- packages/app/package.json
- tests/ios/Podfile.lock
Two small test-only changes as described in summary
One big change in the firebase-ios-sdk update - it's non-breaking but the signed frameworks are a big deal to meet Apple privacy requirements coming in force shortly.
Long road getting to this point on the iOS privacy requirements!
- Fixes #7743 
- verify codecov uploaded in ios, android, and jest workflows
- verify the API27 emulator run worked
- run of ios e2e locally, verify it runs in CI
---
> feat(deps): firebase-ios-sdk 10.24.0 / codecov ci action / android e2e use 29 for min api

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
The `signInWithProvider`, `linkWithProvider`, and `reauthenticateWithProvider` calls break when attempting to use a second firebase project since it initializes the provider using the default project while signing in with the secondary project.
Note: this already works correctly on iOS
Fixed the `signInWithProvider`, `linkWithProvider`, and `reauthenticateWithProvider` implementations when using multiple Firebase projects
Checked the network logs before and after this change to confirm that the library is sending the correct project configuration.
---
Think …
> fix(auth,android): Pass firebaseAuth into OAuthProvider.newBuilder(...)

- packages/auth/lib/multiFactor.js
the typescript definitions specify it as `enrolledFactors` reflecting that it is an array, but the javascript was actually setting it as `enrolledFactor` at runtime.
the original `enrolledFactor` property is kept for backwards compatibility, but could be removed in a future major version.
ref:
- typings: https://github.com/invertase/react-native-firebase/blob/main/packages/auth/lib/index.d.ts#L568
- android: https://github.com/invertase/react-native-firebase/blob/main/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java#L2476
- ios: https://github.com/invertase/react-native-firebase/blob/main/packages/auth/ios/RNFBAuth/RNFBAuthModule.m#L1681
- web sdk: https://github.com/firebase/firebase-js-sdk/blob/master/packages/auth/src/mfa/mfa_user.ts#L34 …
> fix: enrolledFactors rather than enrolledFactor

- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
rename `enrollmentDate` -> `enrollmentTime` on iOS to match Android/Web (ref: https://firebase.google.com/docs/reference/js/auth.multifactorinfo)
keep `enrollmentDate` around on ios for backwards compatibility, mark as deprecated.
ref:
- https://github.com/invertase/react-native-firebase/blob/main/packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java#L2500
- https://github.com/invertase/react-native-firebase/blob/main/packages/auth/lib/index.d.ts#L483
BREAKING CHANGE: `enrollmentDate` renamed to `enrollmentTime` on iOS
split from #7565
- This is a breaking …
> fix: ios enrollmentDate -> enrollmentTime

- packages/analytics/__tests__/analytics.test.ts
- packages/analytics/lib/index.d.ts
- packages/analytics/lib/structs.js
Hello, Firebase Web SDK allows these extra params: [begin_checkout](https://github.com/firebase/firebase-js-sdk/blob/b74d8a2115b757d73bd7bf6dba27f9516b380366/packages/analytics/src/api.ts#L350), [purchase](https://github.com/firebase/firebase-js-sdk/blob/b74d8a2115b757d73bd7bf6dba27f9516b380366/packages/analytics/src/api.ts#L480).
Used the solution from a previous similar PR for screen_view events https://github.com/invertase/react-native-firebase/pull/5811
This is useful for easily tracking conversion rates depending on some parameters.
Allow custom event parameters for begin_checkout and purchase events …
> feat(analytics): allow custom event parameters for begin_checkout and purchase events

- packages/functions/lib/index.d.ts
… httpsCallable and httpsCallableFromUrl functions
> feat(functions): typescript definitions for httpsCallable and httpsCallableFromUrl

- docs/messaging/ios-notification-images.md
Adding:
```
use_frameworks! :linkage => :static
```
Because we use it on our main target and it solve this error:
```
[!] Unable to integrate the following embedded targets with their respective host targets (a host target is a "parent" target which embeds a "child" target like a framework or extension):
- XXX (true) and ImageNotification (false) do not both set use_frameworks!.
```
--- …
> docs(messaging): add `use_frameworks` to notification images Podfile code snippet

- .github/workflows/create_test_patches.yml
react-native 0.74+ tries to init a git repository which doesn't work well for us in CI
react-native 0.74+ uses yarn3+ by default which has 3 problems with our usage:
- it needs `--dev` not `--save-dev` to install a devDependency
- you have to turn off immutability (on by default in CI) for it to init a project like we do
- it does not handle executable bits correctly of our ios_config.sh scripts during the `pack` of our modules
Extensive testing during development. After merge, should rebase this out of #7565 and #7774 where pieces of it are also present …
> build(ci): fix patch set generation to handle modern react-native / yarn

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
You can now upgrade anonymous users using phone auth on Android. Credit to @Shaninnik.
Fixes:
- Fixes: #4911
> fix(auth, android): return credential for signin if phone auth has link collision

- .github/workflows/tests_e2e_android.yml
- .github/workflows/tests_e2e_ios.yml
- packages/messaging/e2e/messaging.e2e.js
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
- tests/e2e/init.js
- tests/ios/Podfile.lock
There has been a very troublesome issue with requests to register for notifications hanging infinitely in recent iOS versions
it was narrowed down by users (thank you!) to missing permissions, and even more specifically to a difference in behavior between requesting the permissions via react-native-permissions or the `requestPermission` method in this library
Two related fixes are present here to avoid the infinite hang in all cases, and to correctly function in the normal case:
- the hang avoidance is a new delayed async task that checks for registration completion after 10 seconds, and rejects with a hopefully-useful message for developers about likely missing permissions if the registration was going to hang
- the fix for the likely case is that a successful grant via the …
> fix(messaging, ios): avoid hang on notification registration

- packages/app/lib/internal/registry/nativeModule.js
When trying to use `@react-native-firebase/app` with the new architecture and bridgeless mode on (react-native version 0.74.0-rc.3), the user is faced with an unhandled promise rejection 
Very similar case to https://github.com/react-native-netinfo/react-native-netinfo/pull/717
----
This error happens because of the following code inside nativeModule.js
https://github.com/invertase/react-native-firebase/blob/b40d44c57e81a4110cbb4e6204c400cb8f78b00a/packages/app/lib/internal/registry/nativeModule.js#L62-L79
Currently we cannot copy functions  directly from the React Native's NativeModules object, given that the module object is a host object.
After this change everything works as expected and the compatibility layer allows `@react-native-firebase/app` to be used with bridgeless mode on
Add …
> fix(app): react-native 0.74 bridgeless mode compatibility

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/e2e/multiFactor.e2e.js
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/auth/lib/index.d.ts
Expose `phoneNumber` on the MFA hints to JS.
`MultiFactorInfo` has two sub-classes in the underlying SDK's - one for TOTP and one for Phone, where the Phone one additionally includes the `phoneNumber` registered to the factor.
Before login the `phoneNumber` is redacted, and after login it is unredacted.
This is useful for showing the user a hint as to which phone number they should check, or distinguishing between multiple phone factors.
Additionally rename `enrollmentDate` -> `enrollmentTime` on iOS to match Android/Web (ref: https://firebase.google.com/docs/reference/js/auth.multifactorinfo)
- If we'd rather avoid the breaking change here, perhaps we could keep `enrollmentDate` as deprecated on iOS?
ref:
- https://firebase.google.com/docs/reference/ios/firebaseauth/api/reference/Classes/ …
> feat(auth): include phoneNumber from PhoneMultiFactorInfo

- docs/index.md
- packages/app-distribution/android/build.gradle
- packages/app/package.json
- packages/app/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- tests/android/build.gradle
- tests/ios/Podfile.lock
Pretty standard update, however the android tests are failing for me locally, so I expect an e2e android test failure here, in the database test suite
If that occurs obviously will need to investigate for root cause, and even if it does not occur then I will need to determine what the environmental difference is such that it fails for me locally but not in CI
We'll see...
> feat(app): ios sdk 10.27.0 / android sdk 33.1.0

- .spellcheck.dict.txt
- docs/messaging/usage/index.md
Since Expo SDK51, Notifications entitlement is no longer always added to iOS projects during prebuild
See : [SDK51 changelog](https://expo.dev/changelog/2024/05-07-sdk-51#deprecations-renamings-and-removals)
> docs(notifications): iOS entitlements

- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.h
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m
configureWithApp is scheduled for removal upstream, the initialization logic we need to execute appears to operate fine in componentsToRegister
@ncooke3 - it can't really be this easy can it? I'm immediately suspicious, but...the logic seems to execute just fine - the logic we execute is idempotent as well, so it's okay if it executes more than once so long as it executes at least once...
Fixes:
- Fixes #4241
If you see "RNFBCrashlyticsInit initialization successful" in the iOS log file while running `yarn tests:ios:test` with this change, the …
> fix(crashlytics, ios): init w/componentsToRegister vs configureWithApp

- .github/workflows/scripts/firestore.indexes.json
- packages/firestore/e2e/Query/where.and.filter.e2e.js
- packages/firestore/e2e/Query/where.e2e.js
- packages/firestore/e2e/Query/where.filter.e2e.js
- packages/firestore/e2e/Query/where.or.filter.e2e.js
- packages/firestore/lib/FirestoreQueryModifiers.js
fixes: https://github.com/invertase/react-native-firebase/issues/7845
---
> fix(firestore): remove exception throw on inequality queries on different fields

- .github/workflows/scripts/firebase.json
- .github/workflows/scripts/functions/src/fetchAppCheckToken.ts
- .github/workflows/scripts/functions/src/index.ts
- packages/app-check/e2e/appcheck.e2e.js
- packages/app-check/lib/index.d.ts
- packages/app-check/lib/index.js
- packages/app-check/lib/web/RNFBAppCheckModule.android.js
- packages/app-check/lib/web/RNFBAppCheckModule.ios.js
- packages/app-check/lib/web/RNFBAppCheckModule.js
- packages/app-check/type-test.ts
- packages/app/lib/internal/web/firebaseAppCheck.js
- tests/app.js
- tests/globals.js
> feat(Other): add App Check support

- packages/database/android/src/reactnative/java/io/invertase/firebase/database/ReactNativeFirebaseDatabaseCommon.java
- packages/database/e2e/snapshot/snapshot.e2e.js
- packages/database/ios/RNFBDatabase/RNFBDatabaseCommon.m
- packages/database/lib/DatabaseDataSnapshot.js
fixes: https://github.com/invertase/react-native-firebase/issues/7719
---
> fix(database): set priority on child snapshot if available

- .github/workflows/scripts/storage.rules
- packages/storage/android/src/main/java/io/invertase/firebase/storage/ReactNativeFirebaseStorageModule.java
- packages/storage/e2e/StorageReference.e2e.js
- packages/storage/e2e/helpers.js
- packages/storage/ios/RNFBStorage/RNFBStorageModule.m
- packages/storage/lib/index.js
- tests/app.js
fixes https://github.com/invertase/react-native-firebase/issues/7717
---
> fix(storage): ensure emulator is used for different storage buckets

- packages/analytics/lib/index.d.ts
> fix(analytics): update the typing for Item

- packages/remote-config/__tests__/remote-config.test.ts
- packages/remote-config/lib/index.d.ts
- packages/remote-config/lib/index.js
- packages/remote-config/lib/modular/index.d.ts
- packages/remote-config/lib/modular/index.js
> test(remote-config): ensure modular API are exported properly

- packages/database/__tests__/database.test.ts
- packages/database/e2e/DatabaseStatics.e2e.js
- packages/database/lib/index.d.ts
- packages/database/lib/modular/index.d.ts
- packages/database/lib/modular/query.d.ts
- packages/database/lib/modular/transaction.d.ts
Fixes exports of modular imports, this logic is already implemented in other packages.
Without this fix, this is how I get VSCode to import modular:
```ts
import { getDatabase, ref } from "@react-native-firebase/database/lib/modular";
import {
Unsubscribe,
onValue,
set,
} from "@react-native-firebase/database/lib/modular/query";
```
fix(database): fixes exports of modular imports
---
- 👉 Star this repo …
> fix(database): fixes modular imports exports

- packages/app-check/__tests__/appcheck.test.ts
- packages/app-check/lib/index.d.ts
- packages/app-check/lib/index.js
- packages/app-check/lib/modular/index.d.ts
- packages/app-check/lib/modular/index.js
> test(app-check): ensure modular API are exported properly

- docs/crashlytics/usage/index.md
- docs/database/usage/index.md
- docs/messaging/usage/index.md
- docs/migrating-to-v6.md
- docs/releases/v6.0.0.md
PR fixes a couple of typos.
---
> fix(docs): typos

- packages/analytics/__tests__/analytics.test.ts
- packages/analytics/e2e/analytics.e2e.js
- packages/analytics/ios/RNFBAnalytics/RNFBAnalyticsModule.m
- packages/analytics/lib/index.d.ts
- packages/analytics/lib/index.js
- packages/analytics/lib/modular/index.d.ts
- packages/analytics/lib/modular/index.js
Add support for on-device measurement hashed values
N/A
Added support for on-device measurement initiation with hashed phone number or email address.
---
> feat(analytics): initiate on device measurement with sha256-hashed values

- docs/index.md
I wanted to mention `npx expo prebuild` in the docs because it's an important step in making sure that the config plugins are applied.
---
> docs: update expo guide

- packages/firestore/RNFBFirestore.podspec
Upstream firestore-ios-sdk-frameworks issue is fixed and the Firestore binary distribution now directly depends on nanopb as it should, so we should remove the workaround here.
This tangentially fixes compile of InAppMessaging which was specifying a mutually exclusive nanopb version range
No related issue, noticed it while checking rnfbdemo repo for compile on Xcode 16
the commit is a single conventional commit and a rebase-merge should work, generating a successful release later
rnfbdemo compile tests this to make sure it works, it appears to work fine …
> fix(firestore, ios): remove nanopb transitive dep from podspec

- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m
firebase-ios-sdk v11+ removed one of the parameters from their component initialization API, we must remove it here to use firebase-ios-sdk v11+
The fix for the Xcode build failures on Xcode 16+ require using firebase-ios-sdk v11+, which requires this:
- #8020 
This is a conventional commit so should be possible to rebase merge
**NOTE THAT package.json needs firebase bumped to 11.2.0 as a commit before this one works - however, that is not a breaking change, if you bump package.json to 11.2.0 for firebase-ios-sdk, and merge this PR plus #8021 then react-native-firebase appears to work fine**
- This is a …
> fix(crashlytics, ios): dependencies init param removed upstream in v11+

- .gitignore
- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingSerializer.java
- packages/messaging/lib/index.d.ts
messages may be sent as high priority but downgraded to normal priority on
delivery and it is very important for applications to know this
if a priority is downgraded from high to normal, the application may not
start foreground services and the app will crash if a foreground start is
attempted
These are android-specific types not present on web, so I followed the pattern of other non-web typescript types by making them optional / warned they could be undefined
The two properties:
https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage#getPriority()
https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage#getOriginalPriority()
The java IntDef that drives the typescript enum definition: …
> feat(messaging, android): add priority + originalPriority to RemoteMessage

- packages/analytics/RNFBAnalytics.podspec
- packages/app-check/RNFBAppCheck.podspec
- packages/app-distribution/RNFBAppDistribution.podspec
- packages/app/RNFBApp.podspec
- packages/auth/RNFBAuth.podspec
- packages/crashlytics/RNFBCrashlytics.podspec
- packages/database/RNFBDatabase.podspec
- packages/dynamic-links/RNFBDynamicLinks.podspec
- packages/firestore/RNFBFirestore.podspec
- packages/functions/RNFBFunctions.podspec
- packages/in-app-messaging/RNFBInAppMessaging.podspec
- packages/installations/RNFBInstallations.podspec
- packages/messaging/RNFBMessaging.podspec
- packages/perf/RNFBPerf.podspec
- packages/remote-config/RNFBRemoteConfig.podspec
- packages/storage/RNFBStorage.podspec
- tests/ios/Podfile.lock
some were slipping out to 11.4.0 and causing compilation failures while the majority of the system was still on 11.3.0
we can't set exact versions because some pods don't version while others do (a previous issue) but we *can* set a max for compatibility reasons
Fixes:
- #8073 
A single conventional commit
Simply being able to build (and pass the build) in CI should be a proof there was no regression
--- …
> fix(ios, sdk): constrain transitive dependencies more tightly

- docs/perf/axios-integration.md
This PR addresses an issue with the `newHttpMetric` function in the Firebase Performance Monitoring documentation. According to the documentation, when tracking HTTP request performance (e.g., using Axios), the HTTP method needs to be passed in uppercase. However, the `config.method` from Axios returns the method in lowercase, causing the following error:
```
[Error: firebase.perf().newHttpMetric(_, *) 'httpMethod' must be one of CONNECT, DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT, TRACE.]
```
As a result, this error prevents the use of `httpMetric` in response monitoring.
The issue was resolved by adding the `toUpperCase()` method to the HTTP method before passing it to `newHttpMetric`. The documentation has been updated to reflect this requirement.
None
- I read the [Contributor …
> docs: Update axios-integration.md

- docs/auth/social-auth.md
Fixed documentation: Google sign in result type in the latest version of @react-native-google-signin/google-signin has changed
When setting up a new app I encountered this type error when copy pasting the code, I realised that the google sign in result has changed and ID token is under result.data instead if on result itself.
--- …
> fix: social auth Google sign in result

- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsNativeHelper.h
- packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsNativeHelper.m
user request, useful for "brownfield" apps that have custom native code and want to use crashlytics native methods from their own native code
Fixes:
- Fixes #8093
one conventional commit, rebase merge
native helper methods don't have tests, compiling correctly (which it does) should be adequate as it simply copies the previous method that has reports of user success, and does nothing but copy the SDK method signature then delegate to the SDK
--- …
> feat(crashlytics, ios): add native helper log / setCustomValue methods

- docs/index.md
- packages/app/package.json
- tests/ios/Podfile.lock
underlying fixes but nothing visible for / necessary from library consumers
Nothing logged, but:
- android updated protobuf to solve a security CVE
- the saga of FirebaseCoreExtension is what drove the iOS SDK patch releases - unfortunately we can't really do a 11.4.2 release because firestore did not actually bump except some of it's internal/transitives, so firestore-ios-sdk-frameworks won't generate a release, it will have to wait for 11.5.0
a single conventional commit, rebase merge + release should do the trick
Incorporated in my rnfbdemo build tests successfully, CI will …
> fix(app, sdk): firebase-android-sdk 33.5.1

- packages/analytics/__tests__/analytics.test.ts
- packages/analytics/lib/index.d.ts
- packages/analytics/lib/structs.js
We wanted to add custom parameters to the items for ecommerce events. Firebase supports it (https://developers.google.com/analytics/devguides/collection/ga4/item-scoped-ecommerce), but it was not yet supported by react-native-firebase. 
This MR is inspired by https://github.com/invertase/react-native-firebase/pull/5811
I added a test case.
--- …
> feat(analytics): allow custom event parameters for Item in events

- packages/analytics/RNFBAnalytics.podspec
- packages/app-check/RNFBAppCheck.podspec
- packages/app-check/ios/RNFBAppCheck/RNFBAppCheckProvider.m
- packages/app/RNFBApp.podspec
- packages/app/package.json
- packages/auth/RNFBAuth.podspec
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/crashlytics/RNFBCrashlytics.podspec
- packages/database/RNFBDatabase.podspec
- packages/firestore/RNFBFirestore.podspec
- packages/functions/RNFBFunctions.podspec
- packages/in-app-messaging/RNFBInAppMessaging.podspec
- packages/installations/RNFBInstallations.podspec
- packages/ml/RNFBML.podspec
- packages/perf/RNFBPerf.podspec
- packages/remote-config/RNFBRemoteConfig.podspec
- packages/storage/RNFBStorage.podspec
This supercedes:
- #8109
It is based on that PR from @adamkoch but I can't push to that branch and I have done a series of little fixups on it
Discussion:
- https://github.com/invertase/react-native-firebase/discussions/5722#discussioncomment-11125191
This should be a squash merge, the PR title should serve for release as conventional commit message
The base of the PR style-wise is adding the platform to package.json then using it in podspecs, that is tested already by library consumer so should work
The compile ifdefs will be tested on iOS at least and that should be …
> feat: add tvOS support

- packages/analytics/RNFBAnalytics.podspec
- packages/app-check/RNFBAppCheck.podspec
- packages/app-distribution/RNFBAppDistribution.podspec
- packages/app/RNFBApp.podspec
- packages/app/package.json
- packages/auth/RNFBAuth.podspec
- packages/crashlytics/RNFBCrashlytics.podspec
- packages/database/RNFBDatabase.podspec
- packages/dynamic-links/RNFBDynamicLinks.podspec
- packages/firestore/RNFBFirestore.podspec
- packages/functions/RNFBFunctions.podspec
- packages/in-app-messaging/RNFBInAppMessaging.podspec
- packages/installations/RNFBInstallations.podspec
- packages/messaging/RNFBMessaging.podspec
- packages/perf/RNFBPerf.podspec
- packages/remote-config/RNFBRemoteConfig.podspec
- packages/storage/RNFBStorage.podspec
- tests/ios/Podfile
- tests/ios/Podfile.lock
Note to reviewer: review commit by commit, the diffs are all tiny with hopefully useful messages
With #8127 I discovered that my fix for the temporary build error with firebase-ios-sdk 11.4.1 (in #8074) had a negative side effect - it constrained versions to not slip upwards but it allowed old versions to stay in place.
That is not okay, as we depend on updated versions to bring us new APIs that we use (which was the problem in #8127)
So, with this commit I'm reverting that change as the cure was worse than the disease and there is no other good way to specify the versions since `=` breaks integration with firestore-ios-sdk-frameworks (I tested it, I was surprised and disappointed)
I take the opportunity in separate commits to:
- clean old warnings that are obsolete
- adopt 11.5.0 now …
> fix: Refix firebase ios sdk dependencies / adopt firebase-ios-sdk 11.5.0

- packages/firestore/__tests__/firestore.test.ts
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreCollectionModule.java
- packages/firestore/e2e/Aggregate/AggregateQuery.e2e.js
- packages/firestore/e2e/Aggregate/count.e2e.js
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCollectionModule.m
- packages/firestore/lib/FirestoreAggregate.js
- packages/firestore/lib/index.d.ts
- packages/firestore/lib/modular/index.d.ts
- packages/firestore/lib/modular/index.js
- packages/firestore/lib/web/RNFBFirestoreModule.js
- packages/firestore/lib/web/query.js
- Support for [getAggregateFromServer()](https://firebase.google.com/docs/reference/js/firestore_.md?_gl=1*1d4sq9b*_up*MQ..*_ga*MTE3MTA3NTY0NC4xNzMwOTEyNDk0*_ga_CW55HF8NVT*MTczMDkxMjQ5NC4xLjAuMTczMDkxMjQ5NC4wLjAuMA..#getaggregatefromserver_2073a74). Modular support only.
closes https://github.com/invertase/react-native-firebase/issues/8027
--- …
> feat(firestore): support for aggregate queries including `sum()` & `average()`

- packages/app/__tests__/app.test.ts
- packages/app/lib/FirebaseApp.js
- packages/app/lib/common/index.js
- packages/app/lib/internal/registry/app.js
A quick take on reducing boilerplate - I wasn't sure it would even work so it was easier to just try it vs try to explain it, since if it didn't work it wasn't worth explaining but the code itself was just the work of a few minutes
> refactor: de-duplicate deprecation warning calls and tests

- .spellcheck.dict.txt
- docs/faqs-and-tips.md
Noted on socials that New Architecture status wasn't documented anywhere but we have worked on it and we are tracking an upstream issue that breaks background messaging on android
https://bsky.app/profile/softwareandcoffee.bsky.social/post/3lau3vwdl4c2f
Nothing logged, user mentioned outside github
docs commit only
--- …
> docs(faq): note new architecture status

- packages/app-check/android/src/main/java/io/invertase/firebase/appcheck/ReactNativeFirebaseAppCheckModule.java
- packages/app/android/src/reactnative/java/io/invertase/firebase/common/RCTConvertFirebase.java
- packages/app/android/src/reactnative/java/io/invertase/firebase/common/ReactNativeFirebaseModule.java
- packages/app/android/src/reactnative/java/io/invertase/firebase/common/SharedUtils.java
- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/database/android/src/reactnative/java/io/invertase/firebase/database/ReactNativeFirebaseDatabaseQueryModule.java
- packages/dynamic-links/android/src/main/java/io/invertase/firebase/dynamiclinks/ReactNativeFirebaseDynamicLinksModule.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreCollectionModule.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreDocumentModule.java
- packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreTransactionModule.java
- packages/perf/android/src/reactnative/java/io/invertase/firebase/perf/ReactNativeFirebasePerfModule.java
- packages/remote-config/android/src/main/java/io/invertase/firebase/config/UniversalFirebaseConfigModule.java
- packages/remote-config/android/src/reactnative/java/io/invertase/firebase/config/ReactNativeFirebaseConfigModule.java
- packages/storage/android/src/main/java/io/invertase/firebase/storage/ReactNativeFirebaseStorageModule.java
- tests/.detoxrc.js
- tests/android/app/jacoco.gradle
I noticed while attempting to reproduce #7819 that react-native-firebase was still using `onCatalystInstanceDestroy` for it's module teardown, even though that no longer exists. Fixed already in Notifee and others, but not here
This implements the new `invalidate` hook for hot reload that should be used as of react-native 0.74 but leaves the old hook in place (delegating to this new implementation) for people still on react-native <= 0.73
Also fixed a few other deprecations I was aware of while I was in there
Related:
- Fixes #7819 
a bunch of conventional commits ready for rebase-merge, per usual
- This …
> fix: forward port a bunch of deprecations / fix android hot reload

- packages/app/__tests__/app.test.ts
- packages/app/lib/FirebaseApp.js
- packages/app/lib/common/index.js
- packages/app/lib/common/unitTestUtils.ts
- packages/app/lib/internal/registry/app.js
- packages/app/lib/modular/index.js
- packages/crashlytics/e2e/crashlytics.e2e.js
There is also a `utils()` method on FirebaseApp: https://rnfirebase.io/reference/app#utils
Not sure whether to leave it or to remove.
---
> chore(core): deprecation warning for v8 API ahead of future major release

- docs/index.md
- packages/app/RNFBApp.podspec
When there are build breaks like happened with firebase-ios-sdk 11.4.1, people need to override the firebase-ios-sdk value, but it is not easy to do in a managed / no-native-code environment like Expo where you cannot easily modify the Podfile
It easy to send an environment variable through though, so I checked overriding it that way, and not only does it work but it is sufficient to do so in the RNFBApp.podspec alone
No config plugin needed, no dangerous Podfile mod needed
I also took the opportunity to make the risk of overriding the SDK versions much more specific, since users are still surprised by build errors when we adopt new SDK semver minors and start using the new symbols, while users with overrides don't get the new SDK and have a build error
- Fixes #8079 
Some conventional …
> feat(app, sdk): allow env var override of firebase-ios-sdk value

- docs/index.md
this was confusing to users because the install notes are very specific about how to do initialization with the firebase config on the native platforms, but there was no mention of the completely different style needed for "other" / web
- Related: #8056 
conventional commits ready for rebase-merge as ever
Just review for working, docs only at current
--- …
> docs(app, other): add a note about dynamic initialization on other

- packages/analytics/lib/index.js
- packages/analytics/lib/struct.js
- packages/analytics/lib/structs.js
- packages/analytics/package.json
- packages/app/package.json
- yarn.lock
> fix(analytics): update superstruct dependency

- packages/app/lib/common/index.js
- packages/app/lib/common/unitTestUtils.ts
- packages/app/lib/internal/registry/namespace.js
- packages/crashlytics/__tests__/crashlytics.test.ts
- packages/crashlytics/lib/index.js
- packages/crashlytics/lib/modular/index.js
- [Use a proxy on each module instance](https://github.com/invertase/react-native-firebase/pull/8155/files#diff-9ff7cea15720b293add3d0104cbf7419c1d2b2373e08b435fb3b044be1cd07bfR280-R297), allows us to have all deprecation warnings in one place and to keep a map of deprecated methods and the corresponding modular method if available. 
- For testing,  I have mocked the [underlying FirebaseModule](https://github.com/invertase/react-native-firebase/pull/8155/files#diff-5a987a25aa0a47b4a3dfd8c5867efd9f2ae304aaf3b6c68ddddd61dac249042eR95-R102) and proxied every get request on native object which should hopefully speed up writing tests. I had a battle on firestore unit tests mocking the query instance, and this should make it a lot easier.
- Also updated tests to [check the actual …
> chore(crashlytics): refactor deprecation implementation

- docs/messaging/ios-notification-images.md
This PR is sort of follow up for #8184. This PR adds Swift version of the same steps described in the document so others don't have to convert the example steps manually like I did.
docs: added a Swift version example of the `ios-notification-images.md` doc
Run the steps in the doc, build the app, check that the image shows up
> docs: create a Swift version example of the ios-notification-images doc

- docs/messaging/ios-notification-images.md
This PR fixes an issue in the `ios-notification-images.md` doc, the doc tells to update VERSION_NUMBER but there's no version set in the example. In the gif below the image you can see the VERSION_NUMBER being set if you are fast enough.
The text:
> Make sure to change the version number VERSION_NUMBER with the currently installed version (check your Podfile.lock)
Screenshot from the gif:
As per discussions, we removed the `VERSION_NUMBER` example from the docs
docs: removed VERSION_NUMBER example in the `ios-notification-image.md` docs
Follow the guide, add the version number …
> docs: remove version_number example in ios-notification-images docs

- packages/auth/plugin/__tests__/__snapshots__/iosPlugin_openUrlFix.test.ts.snap
- packages/auth/plugin/__tests__/__snapshots__/iosPlugin_urlTypes.test.ts.snap
- packages/auth/plugin/__tests__/fixtures/AppDelegate_bare_sdk43.m
- packages/auth/plugin/__tests__/fixtures/AppDelegate_fallback.m
- packages/auth/plugin/__tests__/fixtures/AppDelegate_sdk42.m
- packages/auth/plugin/__tests__/fixtures/AppDelegate_sdk44.m
- packages/auth/plugin/__tests__/fixtures/AppDelegate_sdk45.mm
- packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts
- packages/auth/plugin/__tests__/iosPlugin_urlTypes.test.ts
- packages/auth/plugin/src/index.ts
- packages/auth/plugin/src/ios/index.ts
- packages/auth/plugin/src/ios/openUrlFix.ts
- packages/auth/plugin/src/ios/urlTypes.ts
- packages/auth/plugin/src/pluginConfig.ts
*Summary*:
Fix [#7258: @react-native-firebase/auth (phone auth) + Expo Router - Redirected to appScheme://firebaseuth/link after resolving recaptcha in ios simulator](https://github.com/invertase/react-native-firebase/issues/7258)
*Problem*:
When using `@react-native-firebase/auth` and `expo-router` in the same application, the phone number login method on iOS fails in some scenarios. In particular, when Firebase uses its ReCAPTCHA verifier (e.g. when running in the iOS simulator), the application ends up navigating away from the login page to a new route `/firebaseauth/link`. 
*Cause*:
After the user has completed the captcha challenge, the WebView redirects back to the application using an iOS deep link of the form `${googleServiceJson.REVERSED_CLIENT_ID}://firebaseauth/link?${queryParam …
> fix(auth, iOS): Expo plugin: skip expo-router for auth URLs

- .github/workflows/create_test_patches.yml
Noticed on latest PR that the patch-package generation failed, due to a deprecation
`npx react-native init` deprecated, `npx @react-native-community/cli init` current
One conventional commit, rebase merge should be fine, will not trigger a release
Very difficult to test workflows.
This should either work though, or will at worst need a slight tweak and a force-push with the tweak to accept the temp install of the package non-interactively
---
- …
> test: update cli package used for patch generation

- docs/app-distribution/usage/index.md
- packages/app-distribution/app.plugin.js
- packages/app-distribution/package.json
- packages/app-distribution/plugin/__tests__/README.md
- packages/app-distribution/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- packages/app-distribution/plugin/__tests__/androidPlugin.test.ts
- packages/app-distribution/plugin/__tests__/fixtures/app_build.gradle
- packages/app-distribution/plugin/__tests__/fixtures/project_build.gradle
- packages/app-distribution/plugin/src/android/applyPlugin.ts
- packages/app-distribution/plugin/src/android/buildscriptDependency.ts
- packages/app-distribution/plugin/src/android/constants.ts
- packages/app-distribution/plugin/src/android/index.ts
- packages/app-distribution/plugin/src/index.ts
- packages/app-distribution/plugin/tsconfig.json
- packages/app/package.json
- tests/ios/Podfile.lock
- yarn.lock
This pull request is intended to add an expo config plugin for @react-native-firebase/app-distribution which does not currently have an Expo plugin :fire:. https://rnfirebase.io/app-distribution/usage#add-the-app-distribution-plugin
None
Add Expo config plugin for App Distribution 
---
> feat(app-distribution): add Expo config plugin for App Distribution

- .github/workflows/tests_e2e_ios.yml
- .github/workflows/tests_e2e_other.yml
- docs/index.md
- packages/app/package.json
Standard SDK updates for the native SDKs, if CI passes I'll assume they're good
I haven't seen problems with them as I build test them in make-demo.sh anyway
This may fix user-reported StoreKit2 in-app-purchase logging discussed here:
- #8077
Additionally this switches our apple CI to use `macos-15-xlarge` vs previous `macos-14-xlarge` to avoid a toolchain installation issue on the macos-14 runners:
- https://github.com/actions/runner-images/issues/11335
single conventional commit all ready for rebase + release
local build testing looked good
CI will chew on it and render a …
> fix: adopt firebase-ios-sdk 11.7.0 / firebase-android-sdk 33.7.0

- packages/auth/lib/index.d.ts
previously 'new' on OAuthProvider returned AuthProvider which had none of the necessary OAuthProvider interface methods
Our types stray pretty far from firebase-js-sdk here, they do not allow you to `new` an OAuthProvider, however, their OAuthProvider does participate in a type inheritance chain that goes to BaseOAuthProvider, to FederatedAuthProvider which implements AuthProvider. So this change at least brings us slightly more into harmony
https://github.com/firebase/firebase-js-sdk/blob/144bc370942f1bdd00f482b40df2581e7ed83a0a/packages/auth/src/core/providers/oauth.ts#L63-L65
Discussed
- https://github.com/invertase/react-native-firebase/discussions/8230
single conventional commit
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for …
> fix(auth, types): instantiating OAuthProvider returns OAuthProvider

- packages/analytics/lib/web/api.js
Requests to Google analytics for web aren't setting no-cors so requests are triggering CORS preflight and subsequently failing.
See the following discussion for more details: https://github.com/invertase/react-native-firebase/discussions/7982#discussioncomment-11878809
- [x ] Yes
- [ x] No
Tested manually in Chrome. I verified that no CORS preflight is sent and that I received an HTTP 204 response from my Google analytics request.
---
- 👉 Follow …
> fix(analytics,web): sets no-cors on analytics requests for web

- docs/auth/social-auth.md
After trying to use the docs to create a google sign in. I realized that  `GoogleSignin.signIn()` gives back an object that looks like this
> {"data": {"idToken": "{idToken}", "scopes": ["openid", "https://www.googleapis.com/auth/userinfo.email", "https://www.googleapis.com/auth/userinfo.profile"], "serverAuthCode": "{authCode}", "user": {userInfo}}, "type": "success"}
I realized that the docs stated that I should create a google credential with data.token and not data.idToken
```javascript
// Create a Google credential with the token
const googleCredential = auth.GoogleAuthProvider.credential(signInResult.data.token);
```
This would give you an error because googleCredential has some undefined params.
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined …
> Fix code example for Google Social Auth in docs.

- docs/analytics/usage/index.md
- docs/dynamic-links/usage/index.md
Event parameters must be correct to generate events in google analytics, but validation is problematic so is basically not performed at any layer, resulting in silent failure
This documents that and warns developers to be careful
Came up in discussion on an issue and documentation appears to be the best solution
Also fixed one bit of invalid markdown in use in dynamic-links, unrelated really but related in that I was trying to generate a warning box there the same way as I was here. It showed up as an example but was wrong.
Fixes
- #8239 
semantic release compatible commits will auto-generate changelog
- …
> docs(analytics): note possible problems with event parameters

- packages/firestore/__tests__/firestore.test.ts
This needs merging to fix this: https://github.com/invertase/react-native-firebase/actions/runs/13052719427/job/36416387337?pr=8236
---
> test(firestore): fix jest tests

- packages/app/__tests__/app.test.ts
- packages/app/lib/FirebaseApp.js
- packages/app/lib/common/index.js
- packages/app/lib/common/unitTestUtils.ts
- packages/app/lib/internal/registry/app.js
- packages/app/lib/internal/registry/namespace.js
- packages/app/lib/modular/index.js
- packages/crashlytics/__tests__/crashlytics.test.ts
- packages/crashlytics/e2e/crashlytics.e2e.js
- packages/crashlytics/lib/index.js
- packages/crashlytics/lib/modular/index.js
- packages/firestore/__tests__/firestore.test.ts
- packages/firestore/e2e/WriteBatch/commit.e2e.js
- packages/firestore/lib/FirestoreDocumentChange.js
- packages/firestore/lib/FirestoreDocumentReference.js
- packages/firestore/lib/FirestoreQuery.js
- packages/firestore/lib/FirestoreQuerySnapshot.js
- packages/firestore/lib/FirestoreStatics.js
- packages/firestore/lib/FirestoreTransaction.js
- packages/firestore/lib/index.js
- packages/firestore/lib/modular/index.d.ts
- packages/firestore/lib/modular/index.js
- packages/firestore/lib/modular/query.js
- packages/firestore/lib/modular/snapshot.js
These have all been well-reviewed and are the core of a couple follow-on PRs even
main keeps moving along though and this branch attracts entropic failures, so in discussion with Russell we're going to land these three commits then rebase the further v8-deprecation work off main
No related issues, but the v8 APIs need to be removed and we have to follow a deprecation cycle to do so
3 conventional commits, semantic release will handle them nicely
So much testing - all Russell's work on the jest area 💪 
---
Think `react-native-firebase` is great? Please consider supporting the …
> chore: deprecate v8 / non-modular methods prior to next major release

- packages/firestore/__tests__/firestore.test.ts
- packages/firestore/e2e/Aggregate/AggregateQuery.e2e.js
- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCollectionModule.m
- tests/ios/Podfile.lock
Fixes https://github.com/invertase/react-native-firebase/issues/8253
---
> fix(firestore, ios): account for filters in getAggregateFromServer with collection groups

- README.md
- packages/analytics/README.md
- packages/app-check/README.md
- packages/app-distribution/README.md
- packages/app/README.md
- packages/auth/README.md
- packages/crashlytics/README.md
- packages/database/README.md
- packages/dynamic-links/README.md
- packages/firestore/README.md
- packages/functions/README.md
- packages/in-app-messaging/README.md
- packages/installations/README.md
- packages/messaging/README.md
- packages/ml/README.md
- packages/perf/README.md
- packages/remote-config/README.md
- packages/storage/README.md
- scripts/_TEMPLATE_/README.md
- tests/README.md
- website/src/components/Footer.tsx
Update Invertase logo across all touch points
> chore: Update Invertase logo

- packages/app-check/__tests__/appcheck.test.ts
- packages/app-check/lib/modular/index.d.ts
- packages/app-check/lib/modular/index.js
- packages/app/lib/common/index.js
- packages/app/lib/common/unitTestUtils.ts
> chore(app-check): deprecation warning for v8 API ahead of future major release

- packages/auth/lib/modular/index.d.ts
- packages/database/lib/index.d.ts
- packages/functions/lib/modular/index.d.ts
- packages/messaging/lib/modular/index.d.ts
- packages/ml/lib/modular/index.d.ts
- packages/perf/lib/modular/index.d.ts
- packages/remote-config/lib/modular/index.d.ts
- packages/storage/lib/modular/index.d.ts
Fixes https://github.com/invertase/react-native-firebase/issues/8276
---
> fix(auth): resolve type issue when migrating to v9

- .spellcheck.dict.txt
- docs/index.md
- docs/migrating-to-v22.md
- docs/sidebar.yaml
- docs/typescript.md
- packages/app/lib/common/index.js
> docs: deprecation guide for moving to firebase-js-sdk modular API

- docs/migrating-to-v22.md
- packages/app/lib/common/index.js
- packages/crashlytics/e2e/crashlytics.e2e.js
Two tiny commits that I will merge+release as soon as CI agrees:
- a warning message cleanup - one was changed to "modular" language, one was not, so crashlytics testing failed
- a docs and global variable name cleanup - removing "V8" in favor of "modular" for disable var
Both are aimed at using "modular" and "namespaced" exclusively in user messaging, so we don't have any "version number" confusion, since "v8" is ambiguous in a react-native-firebase context
None logged, but tests are failing on main currently after I merged #8279 
The PR is aimed at *fixing* tests, so if e2e …
> fix: deprecation warning / documentation / test cleanups

- packages/analytics/lib/modular/index.js
- packages/app-check/lib/modular/index.js
- packages/app-distribution/lib/modular/index.js
- packages/auth/lib/modular/index.js
- packages/crashlytics/lib/modular/index.js
- packages/database/lib/modular/index.js
- packages/dynamic-links/lib/modular/index.js
- packages/firestore/__tests__/firestore.test.ts
- packages/firestore/lib/modular/index.js
- packages/functions/lib/modular/index.js
- packages/in-app-messaging/lib/modular/index.js
- packages/installations/lib/modular/index.js
- packages/messaging/lib/modular/index.js
- packages/ml/lib/modular/index.js
- packages/perf/lib/modular/index.js
- packages/remote-config/lib/modular/index.js
- packages/storage/lib/modular/index.js
Use modular `getApp` (and app `setLogLevel` in firestore...) calls from the modular module code, otherwise they recursively trigger the deprecation warning, implying you can never quiet *all* deprecation warnings even with full migration to modular APIs
That's the whole change. These module inits are exercised everywhere since they are fundamental to modular method usage, so it is a fundamental change but also well-tested in CI
Comment on related migration issue:
- https://github.com/invertase/react-native-firebase/issues/8282#issuecomment-2645818363
one conventional commit
I …
> fix: the init calls for modular should use modular getApp()

- packages/remote-config/__tests__/remote-config.test.ts
- packages/remote-config/android/src/main/java/io/invertase/firebase/config/UniversalFirebaseConfigModule.java
- packages/remote-config/android/src/reactnative/java/io/invertase/firebase/config/ReactNativeFirebaseConfigModule.java
- packages/remote-config/e2e/config.e2e.js
- packages/remote-config/ios/RNFBConfig/RNFBConfigModule.m
- packages/remote-config/lib/modular/index.d.ts
- packages/remote-config/lib/modular/index.js
- packages/remote-config/lib/web/RNFBConfigModule.js
- Support is for modular only.
- There are discrepancies between native SDKs. iOS will throw if you pass in wrong type (a dictionary is passed in as CustomSignals), I can't see any incorrect type handling on JS (although you ought to get TS warning if incorrect type I think), and android enforces a CustomSignal type which only allows long, double, string and null values. Therefore, we throw exception early if not number, string or null to keep some form of consistency.
---
- 👉 …
> feat(remote-config): support for custom signals

- packages/analytics/.npmignore
- packages/app-check/.npmignore
- packages/app-distribution/.npmignore
- packages/app/.npmignore
- packages/auth/.npmignore
- packages/crashlytics/.npmignore
- packages/database/.npmignore
- packages/dynamic-links/.npmignore
- packages/firestore/.npmignore
- packages/functions/.npmignore
- packages/in-app-messaging/.npmignore
- packages/installations/.npmignore
- packages/messaging/.npmignore
- packages/ml/.npmignore
- packages/perf/.npmignore
- packages/remote-config/.npmignore
- packages/storage/.npmignore
While test-integrating the patch set from #8307 I noticed that the patches were huge!
The functional change was miniscule though.
On investigation I discovered the patchset was huge because the unit test changes I made were showing up as diffs, because we have been shipping unit tests with our released packages for everything but functions and one other.
I made sure `__tests__` was in `.npmignore` for all the packages (including a commit I tacked on the vertexai PR #8236) so those aren't shipped anymore and won't show up in package diffs when generating patch-package sets
While test-integrating this patch and auditing the resulting node_modules package contents I noticed 4 of the packages still shipped types tests as well. Added a second commit that ignores those
Noticed in 
- #8307 …
> fix: do not ship unit tests in released packages

- jest.setup.ts
- packages/analytics/__tests__/analytics.test.ts
- packages/app-check/__tests__/appcheck.test.ts
- packages/app-distribution/__tests__/app-distribution.test.ts
- packages/auth/__tests__/auth.test.ts
- packages/crashlytics/__tests__/crashlytics.test.ts
- packages/crashlytics/lib/index.js
- packages/database/__tests__/database.test.ts
- packages/database/lib/index.js
- packages/firestore/__tests__/firestore.test.ts
- packages/functions/__tests__/functions.test.ts
- packages/in-app-messaging/__tests__/inappmessaging.test.ts
- packages/installations/__tests__/installations.test.ts
- packages/messaging/plugin/__tests__/androidPlugin.test.ts
- packages/ml/__tests__/ml.test.ts
- packages/perf/__tests__/perf.test.ts
- packages/remote-config/__tests__/remote-config.test.ts
- packages/storage/__tests__/storage.test.ts
- packages/storage/lib/index.js
@lorenc-tomasz reported a deprecation message still popping up despite correct API usage in crashlytics
Review this commit by commit or you'll go crazy.
In particular turning on "ignore whitespace" for the commit where I refactored the namespace tests to all be in namespace suite looks trivial that way but mind-boggling with whitespace showing up
This PR takes a pretty thorough approach to silencing these since it was the second deprecation message that popped up (see #8304) - indicating it was a "class" issue, not a one-off, so we needed to be more thorough
- go through jest test setup and quiet all non-deprecation logs that we expect
- filter out android emulator remap messages
- ⚠️ ❗  **Realize database did not respect the emulator remap bypass flag! Repair that while there**
- expo …
> fix(crashlytics): avoid deprecation warning during correct API usage

- packages/database/e2e/reference/update.e2e.js
- packages/functions/e2e/functions.e2e.js
- tests/patches/react-native+0.76.5.patch
Unsure what changed between new architecture and old architecture in react-native, but it has affected how nulls are handled when we attempt to remove them, and shows up in two specific places:
1- functions, our function test is showing object differences between expected and actual, in all the cases where nulls are sent inside objects (but not in arrays!)
2- database - we can't set a null to clear an item anymore, as seen in  and probed in 
There are probably other areas that people just haven't seen yet! Like, what about setting null to clear a user id for analytics? That's supposed to work. Other areas where we send null through similar to 1 and 2 above? There are likely more so we should search once we find a pattern
- Fixes #8144 - this PR should close this issue once we determine …
> fix: handle nulls correctly in react-native new architecture

- packages/app/plugin/__tests__/__snapshots__/iosPlugin.test.ts.snap
- packages/app/plugin/__tests__/fixtures/AppDelegate_sdk45.swift
- packages/app/plugin/__tests__/iosPlugin.test.ts
- packages/app/plugin/src/ios/appDelegate.ts
- **Support Swift in expo plugin for @react-native-firebase/app**
- **Remove fallback tester as we have no example code that would require it currently**
- **Add tests for swift appdelegate**
RN 0.77 uses swift, so for this package to continue working in Expo we now need to patch an AppDelegate.swift file
Apply necessary patches for Expo to work on RN 0.77
--- …
> feat(app): Support AppDelegate.swift in @react-native-firebase/app on Expo

- packages/dynamic-links/lib/modular/index.d.ts
- packages/dynamic-links/type-test.ts
Addresses issue raised by user here: https://github.com/invertase/react-native-firebase/discussions/8311#discussioncomment-12114750
---
> fix(dynamic-links): pass dynamic links into getInitialLink()

- packages/messaging/lib/modular/index.d.ts
Wrong type for messaging module in the modular types.
Import the `getMessaging` function.
---
> fix(messaging, types): export correct module types

- docs/index.md
Expo is now the recommended framework for use in React-Native projects.  Even the RN team [recommends that people use Expo](https://reactnative.dev/docs/environment-setup).
So Expo should be the initial/default docs people use.  If people want to continue using RN CLI, the difference is more obvious than before.
This should reduce a number of issues seen in both Expo and Firebase communities regarding setup and use of RNF.
> docs(homepage): make Expo initial instructions

- docs/auth/social-auth.md
- packages/remote-config/android/src/main/java/io/invertase/firebase/config/UniversalFirebaseConfigModule.java
- packages/remote-config/android/src/reactnative/java/io/invertase/firebase/config/ReactNativeFirebaseConfigModule.java
- explicitly point to the new Expo-specific instructions on the new  react-native-google-signin docs site
- sorted social auth providers alphabetically (i.e. moved Twitter to the end)
> docs(auth, google-signin): add expo-specific instructions

- packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
- packages/messaging/ios/RNFBMessaging/RNFBMessagingModule.m
switched from dispatch_async + global queues to dispatch_get_main_queue -  should make race conditions impossible, in case that was the cause for a recent crash
https://github.com/invertase/react-native-firebase/pull/8349/files?diff=unified&w=1
note that the 25 second timeout block did *not* execute in testing if the completion handler was called - the app went back to sleep immediately, so no create_dispatch_block / dispatch_block_cancel was needed
- Fixes #8347 
single conventional commit
I used my rnfbdemo app with "send silent notification" buttons in combination with the …
> fix(messaging, ios): serialize access to background handler state

- .github/workflows/linting.yml
- package.json
- yarn.lock
Russell mentioned that the lint:android run script had poor reporting leading to confusion over whether it was working or not
This combined with poor exit status handling resulted in poor overall experience
I cleaned all that up
None logged
One non-release-generating semantic commit
yarn lint and yarn lint:android a few times locally, both with and without improperly formatted files
CI will check the change there as well
--- …
> test(ci): updated lint:android package script w/better messaging, better status reporting

- packages/firestore/e2e/Bytes.e2e.js
- packages/firestore/e2e/DocumentSnapshot/data.e2e.js
- packages/firestore/lib/FirestoreBlob.js
- packages/firestore/lib/modular/Bytes.d.ts
- packages/firestore/lib/modular/Bytes.js
- packages/firestore/lib/utils/serialize.js
Firestore e2e tests had a problem with `Bytes`, and in general it was not possible to get rid of `Bytes`-related deprecation messages
I'm not 100% happy with this PR though, I'm posting it as a single separate commit because I need a second set of eyes on it
- deprecation warnings were still emitted because internally Bytes and Blob were confused
- now if you get a DocumentSnapshot from a DocumentReference, and there is "blob" data it will be typed as Bytes if using modular API, but remain Blob if namespaced API
I accomplished this by parameterizing some of the internals and signaling from way high in the call chain all the way down to the firestore serializer whether we are in namespace (undefined param) or modular (boolean true param) so it can serialize / de-serialize the write type. …
> fix(firestore, bytes): return Bytes for modular API usage, fix deprecation

- packages/crashlytics/lib/handlers.js
previously the handler accessed analytics using the namespaced API
The e2e suite for crsahlytics is now "modular-clean" so I'm unaware of any other crashlytics issues besides this one
- Fixes: #8326
single conventional commit, rebase merge
Discovered from user - can only be seen during crash when you have crashlytics and analytics both installed
--- …
> fix(crashlytics): convert internal API usage to modular

- .github/PULL_REQUEST_TEMPLATE.md
- tests/app.js
- tests/patches/react-native-macos+0.77.0.patch
- integrating upstream fix via patch-package
- can drop that patch hunk likely with react-native-macos 0.77.1
- Upstream Issue https://github.com/microsoft/react-native-macos/issues/2376
- Upstream PR https://github.com/microsoft/react-native-macos/pull/2375
test only, no release
Re-ran `yarn test:macos:test-cover` after integrating the patch and disabling the workaround, it worked
--- …
> test(macos): upstream has a fix for the logbox now

- docs/index.md
- packages/app/package.json
- tests/android/build.gradle
- tests/ios/Podfile.lock
Nothing more and nothing less than the title, SDK bumps
There are a few issues logged about database connections and listeners being lost on iOS, and this release should help those as it switches back to SocketRocket on iOS, which was last used in firebase-ios-sdk 10.27.0 and appears to have better reconnection behavior
single conventional commit
Going to trust CI on this one
--- …
> fix(app, sdks): firebase-ios-sdk 11.9.0 / firebase-android-sdk 33.10.0

- packages/remote-config/lib/modular/index.js
fixes copy-paste docs text error from the `reset` method which *is* android-only
- Fixes #8380 
docs only update, no release
CI will check grammar and such, not a functional change
---
> docs(remote-config, ios): remove android-only marker on setConfigSettings

- packages/firestore/ios/RNFBFirestore/RNFBFirestoreCommon.m
We were seeing new firestores instances being constantly generated instead of being cached.
- Tested that instances are cached and accessed correctly
---
> fix(firestore): use correct key to cache instance

- .gitignore
- packages/vertexai/__tests__/test-utils/convert-mocks.ts
Attempting to run e2e tests locally this morning, hit a snag with the vertexai package, it appears they have updated their test repository and we need to forward-port slightly:
- has a new v7 on the end, so update gitignore
- moved responses to subdirectory, add new subdir to dir lookup
Fixes:
- Fixes #8409 
single conventional commit with test tag so will not trigger a release
The whole PR is about tests, so if the tests pass for vertexai, it works
--- …
> test(vertexai): handle new vertexai mock responses version

- docs/index.md
- packages/app/package.json
- tests/ios/Podfile.lock
Simple adoption of updated firebase-ios-sdk
Note that there were/are publishing problems for the firestore-ios-sdk-frameworks artifacts, however, despite the build over there not completing successfully, the artifacts it created appear to have been published enough to function:
- Related https://github.com/invertase/firestore-ios-sdk-frameworks/issues/121
Single conventional commit
This appears to work in my local testing, if it passes CI it should be good to go
---
- 👉 Star …
> fix(ios): adopt firebase-ios-sdk 11.10.0

- packages/storage/lib/modular/index.d.ts
- packages/storage/lib/modular/index.js
Match JS Docs: https://firebase.google.com/docs/reference/js/storage.md#getstorage_25f3a57
---
> fix(storage): Type defs storage

- packages/auth/__tests__/auth.test.ts
- packages/auth/lib/modular/index.d.ts
- packages/auth/lib/modular/index.js
- packages/auth/lib/providers/FacebookAuthProvider.js
- packages/auth/type-test.ts
Added and edited type definitions to match Firebase JS-SDK with tests for definitions. Furthermore, this should fix this [issue](https://github.com/invertase/react-native-firebase/discussions/8311) 
Closes https://github.com/invertase/react-native-firebase/issues/8368
Closes https://github.com/invertase/react-native-firebase/discussions/8311
--- …
> fix(auth): Fix auth type definitions and add more

- docs/index.md
Was in the area while doing something unrelated and once again realized how out of date some of our install docs sections are, plus there were some errors like a dangling internal page anchor
Fixed them all with separate commits so it's easy to review commit by commit - not that it is a huge PR anyway
none logged, fixed rapidly while working on other things
docs commit tag(s), no release triggered
can squash merge
if lint passes, it should be good to go
---
- 👉 Star this repo …
> docs(app): install doc preening

- packages/crashlytics/lib/handlers.js
- tests/app.js
- tests/ios/Podfile.lock
- tests/local-test-component.jsx
- tests/local-tests/.gitignore
- tests/local-tests/crash-test.jsx
- tests/local-tests/index.example.js
- tests/package.json
- yarn.lock
This PR reverts a commit that moved the analytics usage in crashlytics to modular API but inadvertently created a hard dependency on analytics from crashlytics vs a dynamic one where it was okay if analytics wasn't installed
In addition I enhanced our test app to make it easy to add little local manual tests, I needed that to turn our e2e app into a crash-testing dummy as you can only do that with a manual button.
- Fixes #8381
2 of the commits are `fix` and should trigger a release
Unbelievable amount of build/test runs, with surprising results, until I finally just had to …
> fix(crashlytics): crashlytics should not have hard dep on analytics

- packages/auth/__tests__/auth.test.ts
- cleanly split between namespace / modular - some sections were mixed
- remove empty block avoiding test
- fix double-nesting on ActionCodeSettings
> test(auth): re-structure auth unit test file

- tests/patches/@firebase+rules-unit-testing+4.0.1.patch
Doing some dependency upgrades and I always look to trim the count of patches we carry, attempting to upstream this one now and the PR I proposed (after testing it...) is more minimal than our current in-tree patch, synching it here
works in testing, is minimal compared to previous
See:
- https://github.com/firebase/firebase-js-sdk/pull/8861
Test-only code, no release
Most of the database e2e tests uses the `database/e2e/helpers.js::seed` function, which uses this rules-unit-testing feature requiring the patch, if database e2e passes this works - and it passes for me locally …
> test: tighten rules-unit-testing patch, matches upstream PR attempt

- packages/auth/lib/modular/index.d.ts
- packages/auth/type-test.ts
This PR fixes that the `user` argument of the `onAuthStateChanged` method's callback was `any` in the modular API. The reason for that was that `AuthListenerCallback` was not correctly imported from the `FirebaseAuthTypes` namespace.
I updated the `type-test.ts` file of the `auth` package and verified, that the test fails without this PR and passes with this PR.
:fire: 
--- …
> fix(auth): fix faulty AuthListenerCallback import

- packages/app/lib/modular/index.d.ts
`initializeApp` in the modular API is annotated is returning the app directly, but like in the namespaced API it actually returns a promise
- My change includes tests; N/A
N/A
> fix(app): annotate initializeApp return as a promise

- docs/index.md
- packages/app/package.json
- tests/ios/Podfile.lock
Simple SDK update of underlying native SDKs
No related issues, however I also ran a publish on firestore-ios-sdk-frameworks so that this would work (since our e2e tests depend on the pre-compiled version)
Single conventional commit that would trigger a patch release by itself
Checked the e2e tests locally with this, they seem to work
--- …
> fix(app): firebase-ios-sdk 11.11.0 / firebase-android-sdk 33.12.0

- .spellcheck.dict.txt
- docs/messaging/usage/index.md
- packages/app/firebase-schema.json
- packages/messaging/android/build.gradle
- packages/messaging/android/src/main/AndroidManifest.xml
- packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java
- packages/messaging/e2e/messaging.e2e.js
- packages/messaging/lib/index.d.ts
- packages/messaging/lib/index.js
- packages/messaging/lib/modular/index.d.ts
- packages/messaging/lib/modular/index.js
- tests/firebase.json
In Android Q+ with current Google Play Services, play services has started installing itself as a default "notification delegation proxy" for remote notifications sent via FCM REST v1 APIs
That sounds good, except the application affect is that on Android the message handlers are no longer called when the user interacts with these delegated notifications
So there is an immediate need to disable these by default for most people, though just in case some use cases for some people require this, we also implement a firebase.json toggle and programmatic APIs to enable it in case people need it.
A future PR could or should follow after investigating *why* the message handlers are not called in response to delegated FCM, so that the root cause can be fixed …
> feat(messaging, android): implement notification delegation APIs, disable by default

- packages/app-check/lib/modular/index.d.ts
- packages/app-check/lib/modular/index.js
https://firebase.google.com/docs/reference/js/app-check.md#gettoken_39fc1b3
closes https://github.com/invertase/react-native-firebase/issues/8361
---
> fix(app-check): type def fixes

- package.json
- tests/test-app/README.md
- tests/test-app/examples/vertexai.js
- tests/test-app/index.js
- tests/test-app/metro.config.js
> chore: example test app for users to run. Initialised VertexAi example 

- docs/index.md
- packages/app/package.json
Standard native SDK updates, but this one is slightly special because of this:
BREAKING CHANGE: firebase-ios-sdk 11.12.0 requires Xcode 16.2+
No related issues
one conventional commit including the `BREAKING CHANGE` notice required for semantic-release automation, ready for a rebase merge
My build demonstrator is already updated and appears to work, CI will sort the rest
---
- 👉 Follow [`React Native Firebase`](https://twitter.com/rnfirebase) …
> feat(app, sdks)!: firebase-ios-sdk 11.12.0 / firebase-android-sdk 33.13.0

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/e2e/emailLink.e2e.js
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/auth/lib/index.d.ts
- packages/auth/lib/index.js
- packages/auth/lib/modular/index.d.ts
- packages/auth/lib/modular/index.js
- packages/auth/lib/web/RNFBAuthModule.js
Use native version of isSignInWithEmailLink instead.
> feat(auth)!: use native for isSignInWithEmailLink / BREAKING CHANGE: return type now `Promise<boolean>` not `boolean`

- packages/firestore/e2e/CollectionReference/add.e2e.js
- packages/firestore/e2e/DocumentReference/delete.e2e.js
- packages/firestore/e2e/DocumentSnapshot/properties.e2e.js
- packages/firestore/e2e/SecondDatabase/second.Transation.e2e.js
- packages/firestore/e2e/Transaction.e2e.js
- packages/firestore/e2e/WriteBatch/commit.e2e.js
- packages/firestore/lib/FirestoreDocumentSnapshot.js
- packages/firestore/lib/FirestoreQuery.js
closes https://github.com/invertase/react-native-firebase/issues/8460
Just as @mikehardy says, JS documentation states exists() is a method returning true or false.
https://firebase.google.com/docs/reference/js/database.datasnapshot.md#datasnapshotexists
Very small breaking change, users just need to change snapshot.exists to snapshot.exists().
To be shipped with other breaking changes.
--- …
> fix(firestore)!: Make DocumentSnapshot.exists() a method rather than a property (BREAKING CHANGE)

- packages/auth/plugin/__tests__/__snapshots__/iosPlugin_openUrlFix.test.ts.snap
- packages/auth/plugin/__tests__/fixtures/AppDelegate_noOpenURL_sdk53.swift
- packages/auth/plugin/__tests__/fixtures/AppDelegate_sdk53.swift
- packages/auth/plugin/__tests__/iosPlugin_openUrlFix.test.ts
- packages/auth/plugin/src/ios/openUrlFix.ts
With Expo SDK 53 forthcoming, they have moved to an AppDelegate.swift file. The auth Expo config plugin currently only supports an objective-c AppDelegate file. This PR adds support for the swift AppDelegate file.
Fixes #8487 
<details><summary>Test results:</summary>
```sh
PASS  packages/database/__tests__/database.test.ts
PASS  packages/crashlytics/__tests__/crashlytics.test.ts
PASS  packages/app-check/__tests__/appcheck.test.ts
PASS  packages/vertexai/__tests__/stream-reader.test.ts
PASS  packages/vertexai/__tests__/schema-builder.test.ts
PASS …
```
> feat(auth, expo): add support for AppDelegate.swift

- packages/app/plugin/src/ios/appDelegate.ts
Hey @mikehardy, we just talked about it in https://github.com/invertase/react-native-firebase/pull/8495 and it happened. The template change got merged. 
Expo SDK 53.0.1 is already out and I think there is no need to keep the change we merged a couple of hours ago.
I updated the mod. In the future, we could think about using [AppDelegate subscriber](https://docs.expo.dev/modules/appdelegate-subscribers/) instead. These dangerous mod are annoying :D
--- …
> fix(app, expo): SDK 53 config plugin

- packages/messaging/e2e/messaging.e2e.js
- packages/messaging/e2e/remoteMessage.e2e.js
- packages/messaging/lib/modular/index.js
- tests/ios/Podfile.lock
@pilotpirxie asserts in https://github.com/invertase/react-native-firebase/issues/8372#issuecomment-2835379229 on #8372 that the `getMessaging()` still needs a deprecation fix, this PR is the result of testing the assertion a fix is needed
A fix is not needed for that issue
However, there was an issue with `getToken()` / `deleteToken()` where options were incorrectly and specifically not passed to the underlying delegate namespaced methods
**Reviewers: only the second commit contains a functional change**
- Closes #8372 
3 conventional-release compatible semantic versioning commits ready for rebase merge …
> fix(messaging): correctly pass options in modular getToken/deleteToken

- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/e2e/emailLink.e2e.js
- packages/auth/lib/index.d.ts
- packages/auth/lib/modular/index.d.ts
@Willham12 pointed out multiple problems with our sign in link handling, and even submitted a PR that handled part of the problem already - this PR handles the remaining two aspects of the problem - a docs update and a native error handling fix
Specifically, the native android signInWithEmailLink method throws an error outside it's Task continuation failure handling, which was unexpected and unhandled in our code. This PR handles that correctly now
- Fixes #8360
two conventional commits ready for a rebase and a semantic release
Subtle to fix, but correctness was enforced …
> fix(auth, android): handle native exception in signInWithEmailLink

- packages/auth/__tests__/auth.test.ts
- packages/auth/lib/modular/index.d.ts
This PR fixes that the `PhoneMultiFactorGenerator` class was not properly exported via the modular API.
- follows what has been done in #8323 for other types
- I noticed the missing export while working on #8327
I updated the auth package's jest tests and verified they pass/fail with/without the relevant code changes.
:fire: 
--- …
> fix(auth): missing PhoneMultiFactorGenerator export

- packages/auth/plugin/__tests__/__snapshots__/iosPlugin_openUrlFix.test.ts.snap
- packages/auth/plugin/src/ios/openUrlFix.ts
We currently have some javascript code being added via the new `swift`-based plugin. This simply fixes the `swift` code.
```
❌  (ios/Gizmo/AppDelegate.swift:46:17)
44 |   ) -> Bool {
45 | // @generated begin @react-native-firebase/auth-openURL - expo prebuild (DO NOT MODIFY)
> 46 |     if url.host.toLowerCase() == "firebaseauth" {
|                 ^ value of type 'String?' has no member 'toLowerCase'
47 |       // invocations for Firebase Auth are handled elsewhere and should not be forwarded to Expo Router
48 |       return false
49 |     }
```
I have yet to run the tests …
> fix(auth, expo): lowercase `String?` in swift using `.lowercased()`

- docs/auth/multi-factor-auth.md
- docs/auth/oidc-auth.md
- docs/auth/phone-auth.md
- docs/auth/social-auth.md
- docs/auth/usage/index.md
This PR updates the authentication docs to use the modular API.
I just finished migrating an app to the modular API and put my insights into this PR hoping the next person can benefit from it.
I'll wait for the Vercel preview and then read the docs again. I already cross-checked the edits I made with my own code after the migration.
:fire: 
--- …
> docs(auth): update examples to use modular API

- packages/auth/lib/index.d.ts
This pull request clarifies the behavior of `fetchSignInMethodsForEmail` in the context of Firebase Authentication when **Email Enumeration Protection** is enabled (which is the default setting in Firebase).
The updated JSDoc comment explains that:
- The method may return an empty array even for existing users,
- Especially when called from an unauthenticated context,
- This behavior is by design to prevent email enumeration attacks.
The goal is to help developers understand the limitations of this method and avoid using its result for direct user feedback about account existence, which could lead to security vulnerabilities.
None reported, but this clarification aligns with security considerations discussed in [firebase/firebase-js-sdk#4514](https://github.com/firebase/firebase-js-sdk/iss …
> docs(auth): clarify fetchSignInMethodsForEmail behavior with email enumeration protection

- packages/auth/lib/index.d.ts
This PR improves the JSDoc comment for `signInWithEmailAndPassword` by adding a note about how **Email Enumeration Protection** (enabled by default in Firebase) affects the returned error codes.
Specifically:
- When enabled, Firebase returns a **generic** `auth/invalid-login-credentials` error for login failures, instead of revealing whether the user does not exist (`auth/user-not-found`) or the password is incorrect (`auth/wrong-password`).
- The update warns developers that if they want to rely on detailed error codes, they need to explicitly disable this protection — and that doing so introduces potential security risks (enumeration).
This helps developers understand why error behavior might differ and promotes secure usage patterns.
_No open issue directly related, but improves …
> docs(auth): clarify signInWithEmailAndPassword error behavior under email enumeration protection

- packages/app-check/plugin/__tests__/fixtures/AppDelegate_sdk53.swift
- packages/app-check/plugin/__tests__/iosPlugin.test.ts
- packages/app-check/plugin/src/ios/appDelegate.ts
Adding  support for Swift AppDelegate for the new version of Expo SDK (53) for Firebase AppCheck.
**Unit Tests:**
Test Suites: 39 passed, 39 total
Tests:       1 skipped, 789 passed, 790 total
Snapshots:   31 passed, 31 total
Time:        3.848 s
**E2E Tests:**
PASS  e2e/firebase.test.js (556.894 s)
Jet Tests
✓ runs all tests (527266 ms)
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        556.965 s
Ran all test suites.
---
🔥
> feat(app-check): add Swift AppDelegate support for Expo SDK53+

- packages/app-check/__tests__/appcheck.test.ts
- packages/app-check/lib/modular/index.d.ts
These types were missed before - they *worked* in practice, at the javascript layer, but typescript didn't have them as exports in modular usage
- Fixes #8512
> fix(app-check, types): modular exports of ReactNativeFirebaseAppCheckProvider types

- packages/storage/lib/modular/index.d.ts
This is a TypeScript Type Only change. The type declarations for the storage module were missing the union type that aggregates the string literal values of the `StringFormat` "enum" object. Without this type, the `uploadString` function's 3rd parameter expects an Object (corresponding to the StringFormat interface) instead of a string that specifies the format of the uploaded data. This causes a TypeScript compile/check error, but does not otherwise affect the functionality of the function implementation.
This PR adds the appropriate type declaration to satisfy type checking as described in [Firebase docs](https://firebase.google.com/docs/reference/js/storage.md#stringformat_2)
- Fixes #8524 
- I read the [Contributor Guide](../CONTRIBUTING.md) and followed the process outlined there for …
> fix(storage): add missing type for StringFormat object values

- packages/auth/plugin/__tests__/__snapshots__/iosPlugin_openUrlFix.test.ts.snap
- packages/auth/plugin/src/ios/openUrlFix.ts
I have a universal link that has nothing to do with firebase. but when i link into the url, the link has nil url host and falls into the generated expo prebuild linking code and returns NO. which is inappropriate and needed that url to pass to the very bottom of the linking delegate code.
you can test with url with nullable(nil) url host. in my case, i tested with a custom universal link that has nothing to do with firebase app
---
- 👉 Follow …
> fix(auth, ios): fixes inappropriate linking when host is nil

- packages/app-check/plugin/src/ios/appDelegate.ts
This resolves an issue where AppCheck does not work in iOS simulators even when following the documentation around `ReactNativeFirebaseAppCheckProvider`
#6934
#6184
---
> fix(app-check, expo): init app-check shared instance before firebase in plugin

- docs/index.md
This pull request updates the documentation to add a warning in the Expo installation section, clarifying that when `expo-dev-client` is installed, native crashes (such as those triggered by `crashlytics().crash()`) will **not** be reported to Firebase Crashlytics during development. This is because `expo-dev-client` provides a custom error overlay that catches and displays errors before they are sent to Firebase. The warning helps developers avoid confusion when testing crash reporting in development builds.
Fixes #8561 
Added a documentation warning about the interaction between `expo-dev-client` and Firebase Crashlytics, to clarify that native crash reporting is suppressed in development builds using the custom error overlay.
- I read the [Contributor Guide](../CONTRIBUTING.md) and …
> docs: warning about expo-dev-client preventing native crash reporting to Firebase

- packages/firestore/__tests__/firestore.test.ts
- packages/firestore/lib/modular/FieldPath.d.ts
- packages/firestore/lib/modular/FieldPath.js
- packages/firestore/lib/modular/index.d.ts
- packages/firestore/lib/modular/query.d.ts
- packages/firestore/lib/modular/query.js
- packages/firestore/lib/modular/snapshot.d.ts
- packages/firestore/lib/modular/snapshot.js
> fix(firestore): type definitions

- packages/app/lib/common/index.js
- packages/functions/__tests__/functions.test.ts
- packages/functions/e2e/functions.e2e.js
- packages/functions/lib/modular/index.js
> chore(functions): deprecation warnings for v8 API ahead of future major release

- packages/app/lib/common/index.js
- packages/installations/__tests__/installations.test.ts
- packages/installations/lib/modular/index.js
> chore(installations): deprecations for v8 API ahead of future major release

- packages/app/lib/common/index.js
- packages/perf/__tests__/perf.test.ts
- packages/perf/lib/modular/index.js
> chore(perf): deprecations for v8 API ahead of future major release

- packages/app/package.json
- packages/firestore/lib/index.js
- packages/firestore/package.json
- tests/.jetrc.js
- tests/e2e/firebase.test.js
- yarn.lock
> fix(app): firebase-js-sdk bump 11.3.1 > 11.10.0

- packages/firestore/e2e/firestore.e2e.js
- packages/firestore/lib/index.js
- packages/firestore/lib/modular/index.js
Adds support for initalizing firestore with a non-default database
Fixes #8456 
- [x ] `Other` (macOS, web)
> feat(firestore): added support for non-default databases

- packages/analytics/RNFBAnalytics.podspec
- tests/ios/Podfile.lock
Fix issue on app assembling, when option `$RNFirebaseAnalyticsWithoutAdIdSupport = true` in Podfile.
---
> fix(analytics, ios): `FirebaseAnalytics/Core` is always needed

- docs/index.md
- docs/migrating-to-v23.md
- packages/analytics/lib/web/RNFBAnalyticsModule.js
- packages/app/android/src/reactnative/java/io/invertase/firebase/common/RCTConvertFirebase.java
- packages/app/ios/RNFBApp/RCTConvert+FIROptions.m
- packages/app/ios/RNFBApp/RNFBAppModule.m
- packages/app/ios/RNFBApp/RNFBSharedUtils.m
- packages/app/lib/index.d.ts
- packages/app/lib/internal/web/RNFBAppModule.js
- packages/app/package.json
- tests/globals.js
- tests/ios/Podfile.lock
`trackingId` has been removed from firebase-ios-sdk: https://firebase.google.com/support/release-notes/ios#version_1200_-_july_15_2025
I've kept the `gaTrackingId` API in the JS code because it appears android still uses it: https://firebase.google.com/docs/reference/android/com/google/firebase/FirebaseOptions?_gl=1*dtmd6b*_up*MQ..*_ga*MzIzOTI0NDg4LjE3NTM5NjIwMjM.*_ga_CW55HF8NVT*czE3NTM5NjQxOTMkbzIkZzAkdDE3NTM5NjQxOTMkajYwJGwwJGgw#gaTrackingId()
Although we could possibly update it to match firebase-js-sdk which would be `measurementId`?
- This is …
> feat!: bump firebase-ios-sdk to `12.0.0`

- docs/crashlytics/android-setup.md
- docs/index.md
- docs/perf/usage/index.md
- packages/app/package.json
- packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- packages/perf/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- tests/android/build.gradle
Adopts the latest firebase-android-sdk 34.1.0 release - appears to be a bugfix-only release
- updated a couple docs spots that were missed in the last android SDK bump for gradle plugin versions
> fix(app, android): adopt firebase-android-sdk 34.1.0

- packages/ai/e2e/fetch.e2e.js
- packages/app-check/lib/index.js
- packages/app/lib/common/index.js
- packages/auth/lib/index.js
- packages/remote-config/e2e/config.e2e.js
- packages/remote-config/lib/index.js
I noticed my last merge to main had a crash failure, and it appeared to be near remote-config but not exactly in it, it was in an unknown block?
https://github.com/invertase/react-native-firebase/actions/runs/17158027065/job/48679779113#step:18:3686
```
Fri, 22 Aug 2025 14:45:10 GMT        onConfigUpdated on supported platforms
Fri, 22 Aug 2025 14:45:10 GMT          - adds a listener and receives updates
Fri, 22 Aug 2025 14:45:10 GMT          - manages multiple listeners
Fri, 22 Aug 2025 14:45:10 GMT          - handles react-native reload
Fri, 22 Aug 2025 14:45:10 GMT        setCustomSignals()
Fri, 22 Aug 2025 14:45:10 GMT          ✔ should resolve with valid signal value; `string`, `number` or `null`
Fri, 22 Aug 2025 14:45:10 GMT          ✔ should reject with invalid signal value
Fri, 22 …
```
> fix: validate listenerOrObserver callbacks in auth, app-check, remote-config

- .spellcheck.dict.txt
- docs/auth/multi-factor-auth.md
- packages/app/lib/internal/NativeFirebaseError.js
- packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java
- packages/auth/ios/RNFBAuth/RNFBAuthModule.m
- packages/auth/lib/MultiFactorResolver.js
- packages/auth/lib/TotpMultiFactorGenerator.js
- packages/auth/lib/TotpSecret.js
- packages/auth/lib/getMultiFactorResolver.js
- packages/auth/lib/index.d.ts
- packages/auth/lib/index.js
- packages/auth/lib/multiFactor.js
- packages/auth/lib/web/RNFBAuthModule.js
- tests/ios/Podfile.lock
- tests/local-tests/auth/auth-totp-demonstrator.tsx
- tests/local-tests/auth/gcloud-enable-totp-in-project.sh
- tests/local-tests/crash-test.jsx
- tests/local-tests/database/index.js
- tests/local-tests/firestore/onSnapshotInSync.js
- tests/local-tests/index.js
- tests/local-tests/vertexai/vertexai.js
- tests/package.json
- yarn.lock
The aim of these changes is to enable TOTP MFA and the ability to un-enroll from either SMS or TOTP MFA.
The motivation behind doing this was to migrate away from Firebase JS SDK implementation on our existing Expo application which extensively uses multi-factor authentication.
This is my first time ever changing native code like this. My workflow at the moment for making these changes have simply been editing the native modules in the respective code editors (Xcode and Android Studio), then using patch-package and building new development builds each time and testing live against our development environment, so nothing has been emulated.
I tried to link my forked repo locally using `npm/yarn link` and build off that instead but I couldn't get it to work so I had to go the patch-package …
> feat(auth): support TOTP enroll and unenroll

- docs/migrating-to-v23.md
- packages/app-distribution/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap
- packages/app/package.json
closes https://github.com/invertase/react-native-firebase/issues/8689 
https://firebase.google.com/support/release-notes/android
https://mvnrepository.com/artifact/com.google.firebase.appdistribution/com.google.firebase.appdistribution.gradle.plugin
Latest version of App-Distribution-Gradle-Plugin is 5.1.1 and we were using a non-existent version 5.1.2
--- …
> fix(app-distribution, android): use correct app-distribution gradle version 5.1.1

- packages/ai/__tests__/chat-session-helpers.test.ts
- packages/ai/__tests__/response-helpers.test.ts
- packages/ai/lib/constants.ts
- packages/ai/lib/index.ts
- packages/ai/lib/methods/chat-session-helpers.ts
- packages/ai/lib/public-types.ts
- packages/ai/lib/requests/request.ts
- packages/ai/lib/requests/response-helpers.ts
- packages/ai/lib/types/content.ts
- packages/ai/lib/types/enums.ts
- packages/ai/lib/types/imagen/internal.ts
- packages/ai/lib/types/requests.ts
- packages/ai/lib/types/responses.ts
**IMPORTANT** - remember to code attribute when merging. Put this in the commit body on merge:
```
>
>
Co-authored-by: Daniel La Rocque <dlarocque@google.com>
Co-authored-by: hsubox76 <chholland@google.com>
Co-authored-by: Tanzim Hossain <tanzim@google.com>
Co-authored-by: Josh Soref <2119212+jsoref@users.noreply.github.com>
Co-authored-by: DellaBitta <DellaBitta@users.noreply.github.com>
```
--- …
> feat(ai): feature parity for AI package with Web SDK
