invertase/react-native-firebase

firebase.android.js, firebase.ios.js, index.js
Allows flow and other code intelligence tools to follow the import trail into the lib.
=> Remove redundant platform-specific index files

lib/firebase.js, lib/flow.js, lib/modules/auth/index.js, lib/modules/crash/index.js, lib/modules/database/disconnect.js, lib/modules/database/index.js, lib/modules/database/reference.js, lib/modules/database/snapshot.js, lib/modules/database/transaction.js, lib/utils/index.js
The second commit changes a few pieces of logic very slightly to appease flow; hopefully I've kept these changes local to their functions.
=> Fixing various flow errors

ios/RNFirebase/RNFirebaseDatabase.m
removed onDisconnectSetString
renamed onDisconnectSetObject to onDisconnectSet
called Firebase onDisconnectSetValue with props.value
=> fixed onDisconnectSet on iOS

lib/modules/database/reference.js
Add isEqual() method to Reference in accordance with https://firebase.google.com/docs/reference/js/firebase.database.Reference#isEqual
=> [js][database] Add ref().isEqual()

tests/android/build.gradle, tests/android/gradle.properties
Upgrade gradle version and increase daemon memory allocation
=> [TestSuite] Upgrade gradle version and increase daemon memory allocation

docs/installation-android.md
`launchMode` is not a valid property on the [`<application>` element](https://developer.android.com/guide/topics/manifest/application-element.html).
It must be set on the [`<activity>` element](https://developer.android.com/guide/topics/manifest/activity-element.html) instead.
=> launchMode needs to be set on <activity> instead of <application>

docs/modules/cloud-messaging.md, index.d.ts
Small documentation / typescript definition changes.
Thanks for maintaining this module 👍
=> Update the getBadgeNumber documentation and add android hint

ios/RNFirebase.xcodeproj/project.pbxproj, ios/RNFirebase/RNFirebase.m, ios/RNFirebase/RNFirebaseRemoteConfig.h, ios/RNFirebase/RNFirebaseRemoteConfig.m, lib/firebase.js, lib/modules/remoteConfig/index.js
Initial implementation added for feedback
I am not sure how to add tests or android support yet
Also the function documentation format might be broken, it there a doc somewhere on how to write those?
=> Implement Firebase Remote Config for iOS

index.d.ts
See https://github.com/invertase/react-native-firebase/issues/123#issuecomment-305030342
=> Typescript Def: Make path optional for database ref

ios/RNFirebase/config/RNFirebaseRemoteConfig.m
=> Fix incorrect status message when remote config fetch is successful

package.json
Just a small fix to make `package.json` a proper JSON file :)
=> Remove incorrect comma

docs/redux.md
Initial pass at adding a redux example with `react-redux-firebase`. Open to input about improvements.
=> react-redux-firebase example

docs/v2/migration-guide.md
=> Update migration guide to match installation guide

ios/RNFirebase/analytics/RNFirebaseAnalytics.m, ios/RNFirebase/messaging/RNFirebaseMessaging.m
The methods access UIApplication from the RN thread, but it should be called from the main thread.
=> UIApplication methods should only be called from the main thread

index.d.ts
I've tried to add a bit more detail to the TypeScript definitions for database queries. Suggestions/modifications welcome.
=> Update database TypeScript types

docs/installation-ios.md
Without this you will be unable to archive as React will be duplicated
=> Updated docs to fix duplication issue

android/build.gradle
Had a rather large app with a lot of dependencies and this duplicated caused it to fail at compile time.
Thanks!
=> Android fix: Duplicate dependency error.

ios/RNFirebase/messaging/RNFirebaseMessaging.m
=> Fix syntax error in messaging

index.d.ts
Hi, I've simply added new `app` function typing to the root `index.d.ts` file.
=> Missing new app function typing

android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java
=> #505 Retain timezone information while formatting serverTimestamp value

index.d.ts
See https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#setUserId(java.lang.String)
=> Update typings to allow null values to clear Analytics values

android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabase.java, android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabaseReference.java, android/src/main/java/io/invertase/firebase/database/RNFirebaseTransactionHandler.java, ios/RNFirebase/database/RNFirebaseDatabase.h, ios/RNFirebase/database/RNFirebaseDatabase.m, ios/RNFirebase/database/RNFirebaseDatabaseReference.h, ios/RNFirebase/database/RNFirebaseDatabaseReference.m, lib/modules/core/firebase-app.js, lib/modules/database/index.js, lib/modules/database/reference.js, lib/utils/ModuleBase.js, lib/utils/index.js
I've recreated this PR (https://github.com/invertase/react-native-firebase/pull/649) on a branch so that it can be merged and continued to be worked on as it would be nice to get multiple database support in for v3.2.0.
Tagging @Chenjh1992 and @akshetpandey so they're aware of progress.
Implements #634
=> Implement multiple databases

lib/index.d.ts
Typescript support for Dynamic Links
=> Add Typescript definitions for Dynamic Links

lib/index.d.ts
Add missing type declarations for `UserInfo`, `UpdateProfile`, `ActionCodeSettings`, `PhoneAuthSnapshot`, `PhoneAuthError` and `AuthResult`.
Add missing interface definitions for `ConfirmationResult` and `PhoneAuthListener`.
Add missing methods to interfaces `User` and `Auth`.
Update method signatures for interfaces `User` and `Auth`.
Rename type declaration `Credential` to `AuthCredential`.
The typescript declarations should now accurately reflect public method signatures of the code under `lib/modules/auth`
=> Update typings for everything under lib/modules/auth

lib/index.d.ts
I introduced this with my last PR 🙈
=> [typings][typescript]: fix stupid typo that breaks tsc compilation

lib/index.d.ts
Add the missing typings for the firestore module
=> Add Typescript Definitions for Cloud Firestore

android/src/main/java/io/invertase/firebase/messaging/BundleJSONConverter.java
Required to make vibration work for scheduled notifications. May need to add other types also. (Double off the top of my head)
=> Add Integer serialization to JSON converter

android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java
There was an extra parentheses added in the web view which caused the class to fail compilation.
=> [FIX] Syntax error in prior pull request

lib/index.js
=> feat(flow): export NotificationOpen

lib/index.d.ts
Added Notification, NotificationOpen, AndroidNotification, IOSNotification, Channel, ChannelGroup typings and many other derived typings.
=> New typings

android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java
As per this answer: https://stackoverflow.com/a/46634508/306764
=> Allow passing null as a sound

android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java, bridge/e2e/firestore/blob.e2e.js, bridge/helpers/index.js, ios/RNFirebase/firestore/RNFirebaseFirestoreDocumentReference.m, lib/modules/firestore/Blob.js, lib/modules/firestore/index.js, lib/modules/firestore/types.js, lib/modules/firestore/utils/Base64.js, lib/modules/firestore/utils/serialize.js
=> [firestore] Blob support

android/src/main/java/io/invertase/firebase/invites/RNFirebaseInvites.java
Not sure but the Firebase Invites Email was not working for me but this fix did it.
=> [Android] Fix a bug with Android Invites invitationMap email keys

lib/index.d.ts
I've fixed the typings for `PhoneAuthListener`. Let me know if further changes are required. Thanks,
=> Updated typings for PhoneAuthListener

lib/index.d.ts
Added type definition for RemoteConfig module.
Tested on Android and iOS.
=> Add type definition for RemoteConfig module

lib/modules/database/Reference.js
This PR will modify database `Reference.push()` flow type to return `ThenableReference`
=> Flow type: Modifies db Reference push() to return ThenableReference

android/src/main/java/io/invertase/firebase/config/RNFirebaseRemoteConfig.java, ios/RNFirebase/config/RNFirebaseRemoteConfig.m
https://github.com/invertase/react-native-firebase/issues/1288
=> [config][android] Handle remote config error

android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotificationManager.java
Fixes https://github.com/invertase/react-native-firebase/issues/1308
=> [Android] Fix rescheduling notification on phone reboot

android/src/main/java/io/invertase/firebase/Utils.java, android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotifications.java
closes #1336
Open to discussing this.
=> [android] prefer localized title and body to normal title and body

android/src/main/java/io/invertase/firebase/Utils.java, android/src/main/java/io/invertase/firebase/firestore/DocumentSnapshotSerializeAsyncTask.java, android/src/main/java/io/invertase/firebase/firestore/FirestoreSerialize.java, android/src/main/java/io/invertase/firebase/firestore/QuerySnapshotSerializeAsyncTask.java, android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestore.java, android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreCollectionReference.java, android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreDocumentReference.java, android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestorePackage.java, android/src/main/java/io/invertase/firebase/firestore/RNFirebaseFirestoreTransactionHandler.java
Fixes https://github.com/invertase/react-native-firebase/issues/1223.
---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:
- 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
- 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
- 👉  Star this repo on GitHub ⭐️
=> [android][firestore] implement threaded snapshot serialization 

src/index.d.ts
Pretty straight forward, exports a type declaration.
=> Exports the AuthCredential type

.circleci/config.yml, codecov.yml, package.json
Replace coveralls with CodeCov 👌
=> [build] Switch to CodeCov

src/index.d.ts
This cleans up the storage typescript typings by adding and removing methods, including documentation, and consolidating types.
=> [typescript] Update storage typings

android/build.gradle, android/src/main/java/io/invertase/firebase/Utils.java, android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java, ios/RNFirebase/auth/RNFirebaseAuth.m, src/index.d.ts, src/modules/auth/User.js, src/modules/auth/index.js, tests/android/app/build.gradle, tests/e2e/auth/auth.e2e.js, tests/e2e/auth/user.e2e.js, tests/package.json
See https://github.com/invertase/react-native-firebase/issues/1325#issuecomment-410424524
---
Loving `react-native-firebase` and the support we provide? Please consider supporting us with any of the below:
- 👉  Back financially via [Open Collective](https://opencollective.com/react-native-firebase/donate)  
- 👉  Follow [`React Native Firebase`](https://twitter.com/rnfirebase) and [`Invertase`](https://twitter.com/invertaseio) on Twitter 
- 👉  Star this repo on GitHub ⭐️
=> [auth][wip] Deprecate all *AndRetrieveData* methods

android/src/main/java/io/invertase/firebase/Utils.java, android/src/main/java/io/invertase/firebase/auth/RNFirebaseAuth.java, ios/RNFirebase/RNFirebaseUtil.h, ios/RNFirebase/RNFirebaseUtil.m, ios/RNFirebase/auth/RNFirebaseAuth.m, src/index.d.ts, src/modules/auth/User.js, src/modules/auth/types.js, tests/e2e/auth/auth.e2e.js, tests/e2e/auth/user.e2e.js
=> [auth] add getIdTokenResult support

src/index.d.ts
Looks like `functions` is missing from the exports.
Need help with the rest of the steps, should I do `yarn build` or something?
=> Add functions type

ios/RNFirebase/converters/RCTConvert+UIBackgroundFetchResult.m, ios/RNFirebase/firestore/RNFirebaseFirestore.h, ios/RNFirebase/firestore/RNFirebaseFirestore.m, ios/RNFirebase/notifications/RNFirebaseNotifications.m, src/modules/firestore/DocumentSnapshot.js, src/modules/notifications/IOSNotification.js, src/modules/notifications/Notification.js, tests/e2e/firestore/transactions.e2e.js, tests/e2e/notifications/ios.e2e.js, tests/ios/Podfile.lock, tests/ios/testing/AppDelegate.m, tests/package.json
- [ios] Fixed a notifications `completion` handler crash
- [ios] Fixed an issue on Firestore transactions where the native transaction would no longer exist on `dispose` after transaction had completed
- [firestore] fixed failing test caused by regression in ffc2eca6da67edfb90f404d899fbbe51ed81d822
=> Misc v5.1.0 changes

android/src/main/java/io/invertase/firebase/database/RNFirebaseDatabase.java
- [android][database] fix transactions issue in debugger #1503
=> [android][database] fix transactions issue in debugger #1503

src/index.d.ts
Fix IOSNotification badge Typescript types to `number` instead of `string` matching the flow type.
Documentation should also be updated here https://rnfirebase.io/docs/v5.x.x/notifications/reference/IOSNotification#badge
N/A
[TYPES] [BUGFIX] [NOTIFICATIONS] - Change IOSNotification badge type definition to number
---
=> Fix IOSNotification badge type definition

src/index.d.ts, tests/e2e/database/ref/on.e2e.js, tests/e2e/database/ref/query.e2e.js
Add more tests for Realtime Database
Increases test coverage, which should be helpful when starting work on v6.
[TESTING][ENHANCEMENT][Database] - More tests
=> Increase test coverage of Realtime Database

src/index.d.ts
Add setUserProperties to TypeScript typing file.
Source code at https://github.com/invertase/react-native-firebase/blob/master/src/modules/analytics/index.js#L154
[TYPES] [BUGFIX] [ANALYTICS] Add setUserProperties TS typing.
---
=> Add setUserProperties to index.d.ts

src/modules/links/index.js
Using `firebase.links().createShortLink()` returns a promise with a string wrapper object. As far as I can tell, there is no reason it can not be a string literal, witch (to me) seems more logical (it is also the return type of the underlying function call).
Tested locally, works for me. 
[TYPES][ENHANCEMENT] [LINKS] - Corrects flow return type to string literal instead of string wrapper
---
- 👉 Contribute; see …
=> Corrects flow return type

package.json, src/index.d.ts, tests/package.json, yarn.lock
Fixes #1706 
- [TYPESCRIPT] [BUGFIX] Ensure storage statics are exported - fixes #1706 
---
=> [typescript][storage] export storage statics - fixes #1706

src/index.d.ts, src/modules/firestore/DocumentReference.js
Fixes #1708.
- [TYPESCRIPT] [ENHANCEMENT] [FIRESTORE] Improved `onSnapshot` error definitions - fixes #1708.
---
=> [typescript][firestore] improve `onSnapshot` error definitions - fixes #1708

android/build.gradle, src/index.d.ts, src/modules/firestore/DocumentReference.js
Fixes #1697
- [ANDROID] [ENHANCEMENT] [BUILD] Add support for using React Native android sources from the root of `node_modules/react-native` - fixes #1697
---
=> [android][build] add support for android sources from root - fixes #1697

src/index.d.ts
See: https://github.com/invertase/react-native-firebase/blob/619cd17516a88dff8b89b749888461fe91480737/src/modules/messaging/index.js#L129
=> [ts] fix Messaging requestPermission return type

ios/RNFirebase/notifications/RNFirebaseNotifications.m
In iOS when creating notification actions with input, the input is not passed to JS. This PR extracts the user input if available and passes it to JS notification_opened in the results property which now aligns the api with Android.
- [iOS] [ENHANCEMENT] [NOTIFICATIONS] - get user input from notification action
---
=> [iOS] get user input from notification action

CHANGELOG.md, docs/typedoc.json, packages/common/lib/index.js, packages/common/lib/validate.js, packages/config/lib/index.d.ts, packages/crashlytics/lib/index.d.ts, packages/perf/android/src/main/java/io/invertase/firebase/perf/ReactNativeFirebasePerfModule.java, packages/perf/e2e/HttpMetric.e2e.js, packages/perf/e2e/Trace.e2e.js, packages/perf/e2e/perf.e2e.js, packages/perf/ios/RNFBPerf.podspec, packages/perf/ios/RNFBPerf/RNFBPerfModule.h, packages/perf/ios/RNFBPerf/RNFBPerfModule.m, packages/perf/lib/HttpMetric.js, packages/perf/lib/MetricWithAttributes.js, packages/perf/lib/Trace.js, packages/perf/lib/index.d.ts, packages/perf/lib/index.js, packages/perf/lib/index.js.flow, tests/e2e/init.js, tests/e2e/mocha.opts, tests/ios/Podfile.lock, tests/package.json, yarn.lock
Migration and rework of Firebase Performance Monitoring for v6.0.0.
---
=> [v6] Implement Performance Monitoring

.circleci/config.yml, .circleci/scripts/wait-for-avd.sh, packages/fiam/e2e/fiam.e2e.js, packages/perf/e2e/perf.e2e.js
Re-work android emulator to reduce start time/hangs.
=> [ci] re-work android emulator setup

src/index.d.ts
Just adding a type for `Schedule` in `scheduleNotification` so future folks don't need to run to the docs like I did to find out what the object for scheduling a notification at a future date/time looks like.
- ~~**LINK TO DOCS PR HERE**~~
N/A
[TYPES][ENHANCEMENT][NOTIFICATIONS] - Update schedule type for `Notification.scheduleNotification` 
---
🔥
=> [TYPES][ENHANCEMENT][NOTIFICATIONS]: Change 'any' type for Schedule in scheduleNotification method

src/modules/database/index.js
Flow 0.90.0 has the following change which makes the `number` type incompatible with `Date`, so this is just a quick PR to resolve that flow error.
> Removed unsafe rule allowing Date instances to be used as a number
N/A
[TYPES][BUGFIX] - Update flow type for `Database.getServerTime()`
---
=> Fix flow type for Database.getServerTime()

src/index.d.ts, src/modules/firestore/CollectionReference.js, tests/e2e/firestore/collectionReference.e2e.js
Please see https://github.com/invertase/react-native-firebase/issues/2028#issuecomment-486053074 for context. Let me know if I missed anything here
🔥
=> [JS][FEATURE][FIRESTORE] - Implement isEqual in CollectionReference

package-lock.json, package.json, yarn.lock
Simple fix for env-variable to allow building on Windows. This is a common solution and you can see this in many other repos. [Example here](https://github.com/prescottprue/react-redux-firebase/blob/master/package.json#L19)
[JS][BUGFIX] [package.json] - Fix build on Windows (BABEL_ENV error)
=> [JS][BUGFIX] [package.json] - Fix build on Windows (BABEL_ENV error)

src/modules/storage/reference.js
It turns out that we have to keep the "file://" prefix in Android for Firebase uploads to succeed.
---
=> [STORAGE][BUGFIX][ANDROID] - Preserve `file://` prefix

docs/ml-kit/quick-start.md
https://invertase.io/oss/react-native-firebase/v6/ml-kit/quick-start
=> [v6][DOCS] Fix quick-start.md for ml-kit

pages/quick-start/new-project.md
This is the smallest PR ever, so I am rudely skipping your well-constructed PR template :-)
That said, you may still think the proposed wording chunk I added is terrible and reject, fine by me. Might be interesting to note what the ios bundle is called as well but I didn't check (sorry)
=> docs: note the v6 template init java package / ios bundle names

android/src/main/java/io/invertase/firebase/fabric/crashlytics/RNFirebaseCrashlytics.java, ios/RNFirebase/fabric/crashlytics/RNFirebaseCrashlytics.m, src/index.d.ts, src/modules/crashlytics/index.js, tests/e2e/crashlytics/crashlytics.e2e.js
Wanted to help improve crashlytics js reporting so I implemented a variation of react-native-fabric's custom exception.  I also added two missing methods that are in the crashlytics api but were not included in RNFirebaseCrashlytics.
Also, I addressed #1643 in the documentation to hopefully make it more clear how to use this module.
- [ ✔️ ] Supports `Android`
- [ ✔️ ] Supports `iOS`
- [ ✔️ ] `e2e` tests added or updated in [/tests/e2e/\*](/tests/e2e)
- [ ✔️ ] Updated the documentation in the [docs repo](https://github.com/invertase/react-native-firebase-docs)
https://github.com/invertase/react-native-firebase-docs/pull/168
- [ ? ] Flow types updated
Pretty sure I updated those as I searched the entire project for any files related to crashlytics.
- [ ✔️ ] Typescript types updated …
=> [Crashlytics][ENHANCEMENT] v5.x.x

.gitignore, android/src/main/java/io/invertase/firebase/fabric/crashlytics/RNFirebaseCrashlytics.java, ios/RNFirebase/fabric/crashlytics/RNFirebaseCrashlytics.m, src/index.d.ts, src/modules/crashlytics/index.js, tests/e2e/crashlytics/crashlytics.e2e.js
This caused problems in android e2e testing in the database module's beforeEach hook, and I'm not sure why, but I tried to fix it and couldn't and don't want to block forever
The yarn.lock thing is separate but we need to either ignore it or commit it - I vote ignore so I am including it here. But I do not actually care, I just don't like dirty workspaces after install
---
=> revert [Crashlytics][ENHANCEMENT] add recordCustomError/setUserName etc

android/src/main/java/io/invertase/firebase/storage/RNFirebaseStorage.java
Fixes progress events for `putFile` on android which were not being emitted during the upload.
I didn't bother trying to write a test for this since version 6 is approaching anyway.
Test code:
```js
ref.putFile(uri).on(firebase.storage.TaskEvent.STATE_CHANGED, snap => {
console.log(
Math.floor((snap.bytesTransferred / snap.totalBytes) * 100) + '%'
)
})
```
Output before fix:
```
06-12 13:24:35.142  2933  3018 I ReactNativeJS: 100%
06-12 13:24:35.157  2933  3018 I ReactNativeJS: 100%
```
Output after fix:
```
06-12 13:21:44.334 32209  2454 I ReactNativeJS: 0%
06-12 13:21:44.334 32209  2454 I ReactNativeJS: 0%
06-12 13:21:44.607 32209  2454 I ReactNativeJS: 10%
06-12 13:21:45.071 32209  2454 I ReactNativeJS: 32%
06-12 13:21:45.367 32209  2454 I ReactNativeJS: 74% …
```
=> Fix android putFile progress events

android/src/main/java/io/invertase/firebase/fabric/crashlytics/RNFirebaseCrashlytics.java, ios/RNFirebase/fabric/crashlytics/RNFirebaseCrashlytics.m, src/index.d.ts, src/modules/crashlytics/index.js, tests/e2e/crashlytics/crashlytics.e2e.js
Update to PR #1940.
Additional testing performed.
New test results.
=> [Crashlytics][ENHANCEMENT] add recordCustomError/setUserName/setUserEmail update to #1940

android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java, ios/RNFirebase/RNFirebase.m, package.json
Prepare for v5.5.0 - this is live on npm now and you can either merge this (with tag somehow) or temporarily open the branch for merge (protection/CI hooks)
---
=> v5.5.0 release PR

ios/RNFirebase.podspec, ios/RNFirebase/fabric/crashlytics/RNFirebaseCrashlytics.m, tests/e2e/crashlytics/crashlytics.e2e.js
- include `Fabric` and `Crashlytics` as dependencies of a subspec
`Crahslytics` so that includes of <Crashlytics/Crashlytics.h> and
<Fabric/Fabric.h> can properly be resolved by native module
- fix syntax errors in `RNFirebaseCrashlytics.m`
In current setup with cocoapods checks for include in crashlytics-related files will not work and attempt to call `firebase.crahslytics()` in the code will lead to error "You attempted to use a firebase module that's not installed natively on your iOS project....".
[IOS][BUGFIX][CRASHLYTICS] - fix crashlytics integration via cocoapods
---
- 👉 Donate via [Open …
=> [IOS][BUGFIX][CRASHLYTICS] - fix crashlytics pod integration and compile issue

.github/ISSUE_TEMPLATE/Bug_report.md
=> Add android questions & react-native-firebase version

RELEASE_PROCESS.md, android/src/main/java/io/invertase/firebase/ReactNativeFirebaseAppRegistrar.java, ios/RNFirebase/RNFirebase.m, package.json
Release v5.5.4 is out there!
https://rnfirebase.io/docs/v5.x.x/releases/v5.5.x#5.5.4
---
=> Release v5.5.4

ios/RNFirebase/auth/RNFirebaseAuth.m
Fixes #2180 
[IOS][BUGFIX] [AUTHENTICATION] - fixes app crash when you use two or more Firebase projects in the same app.
=> #2180 iOS bug fix: Collection was mutated while being enumerated

docs/auth/social-auth.md
I changed the if (data) to if (!data) because it was throwing error anyways if the data was there.
---
=> Condition handling in Facebook sign-in

ios/RNFirebase.podspec
I believe following commit introduces an issue for cocoapods users (of whom there will be many now as react-native uses cocoapods since v0.60) https://github.com/invertase/react-native-firebase/commit/b85153de6bd92e8112d75d2cb22ee9ccb9fa294e#diff-1b2b06e7c58d8929c91f917ce51a7454R28
The gist of it is that that it introduces back this issue https://github.com/firebase/firebase-ios-sdk/issues/1916
It is due to some header include in gRPC-C++ library that recursive header search will try to include, but won't find, hence causing build error.
cc @MoOx as he authored original PR, I am not sure if removing this will cause any issues, so wanted to discuss it with you.
I tested 5.5.4 and it failed my iOS build, reverting back to 5.5.3 solved that issue. After looking …
=> [v5] Remove recursive header search from ios podspec

android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdMob.java, android/src/main/java/io/invertase/firebase/admob/RNFirebaseAdMobRewardedVideo.java, ios/RNFirebase/admob/RNFirebaseAdMob.m, ios/RNFirebase/admob/RNFirebaseAdMobRewardedVideo.h, ios/RNFirebase/admob/RNFirebaseAdMobRewardedVideo.m, src/modules/admob/RewardedVideo.js
Add new method to admob rewarded for Server Side Verification setCustomData()
- [yes] Supports `Android`
- [yes] Supports `iOS`
I tested 5.5.4 works fine.
---
=> Admob Rewarded setCustomData for SSV

ios/RNFirebase.xcodeproj/project.pbxproj
Fixes #2210
AdMob iOS usage has broken with modern Pods, it seems from [investigation](https://github.com/invertase/react-native-firebase/issues/2210#issuecomment-511187938) by @nadavmos that the SDK code path moved
This adds the new path to the project file and seems to work for me when I use it in my react-native-firebase demonstrator: https://github.com/mikehardy/rnfbdemo/blob/master/make-demo-rn59.sh#L127
I have a demonstrator project that autmoatically builds a react-native-firebase app from scratch.
It failed in the exact way everyone notices with #2210 and after I apply the change (via a sed script) it works. The PR is the same change but made for real instead of via sed
[IOS][BUGFIX][ADMOB] - Add new iOS code path to Xcode project
---
Think …
=> [IOS][BUGFIX][ADMOB] - add new iOS framework search path Fixes #2210

docs/auth/phone-auth.md
=> v6 update phone-auth.md

docs/firestore/quick-start.md
import and function usage was inconsistent. Main import is of firestore, while function calls were from the firebase import.
---
=> Fixed function call to same as import.

packages/firestore/lib/index.d.ts, packages/firestore/lib/index.js.flow
- startAfter
- startAt
There are no types for `startAfter` and `startAt` on `Firestore.Query` interface on neither `TypeScript` nor `Flow`. So I added these to `Firestore.Query` interface.
You could check it via `TypeScript` and`Flow`.
[CATEGORY][type] [LOCATION] - Add `startAfter` and `startAt` methods to `Firestore.Query` interface on `TypeScript` and `Flow`
---
- 👉 Contribute; see our [contributing …
=> Add missing types on Firestore.Query interface

packages/firestore/lib/index.d.ts
Fix types for Statics.
To include static methods, it should be defined with `typeof` keyword. Otherwise, these can't be used.
- before fixing it
- after fixing it
[CATEGORY][type] [LOCATION] - Modify Firestore.Statics interface to include static methods on TypeScript
---
=> Modify Firestore.Statics interface to include static methods on TypeScript

packages/admob/lib/ads/BannerAd.js, packages/admob/lib/index.d.ts
Small fixes that doesn't change much
- `console.log()` seems not necessary anymore
- RewardedAd example had a copy/paste issue
---
=> [v6 - AdMob] Various minor fixes

android/src/main/java/io/invertase/firebase/notifications/DisplayNotificationTask.java, android/src/main/java/io/invertase/firebase/notifications/RNFirebaseNotifications.java
Send a test notification to the device with the app in foreground and `console.log()` the message.
[ANDROID][ENHANCEMENT] [NOTIFICATIONS] - channelId is parsed in remote notifications
[ANDROID][ENHANCEMENT] [NOTIFICATIONS] - imageUrl is parsed in remote notifications
=> [v5] Android: Notifications: add support for channelId & image fields

packages/auth/lib/index.d.ts
Updated typescript definitions for `currentUser`
- [x ] Typescript types updated
[TYPES] [ENHANCEMENT] [AUTHENTICATION] - Update currentUser type
=> fix auth types

packages/messaging/lib/index.d.ts
=> Fix wrong AsyncStorage method name.

docs/auth/social-auth.md
Fix typo in google social auth section. 
<!--
**INTERNAL tagged notes will not be included in the next version's release notes.**
CATEGORY
[----------]      TYPE
[ TYPES    ] [-------------]       LOCATION
[ JS       ] [ BREAKING    ] [------------------]
[ GENERAL  ] [ BUGFIX      ] [ {FirebaseModule} ]
[ INTERNAL ] [ ENHANCEMENT ] [ {Filename}       ]
[ IOS      ] [ FEATURE     ] [ {Directory}      ]   |-----------|
[ ANDROID  ] [ MINOR       ] [ {Framework}      ] - | {Message} |
[----------] [-------------] [------------------]   |-----------|
=> Fix typo in google social auth section

docs/auth/quick-start.md
=> Update quick-start.md auth doc to specify auth package not analytics

packages/firestore/lib/FirestoreQuery.js
=> [firestore] Apply ID cursor when no orders

packages/app/ios/RNFBApp/RNFBAppModule.m, packages/app/ios/RNFBApp/RNFBRCTEventEmitter.h, packages/app/ios/RNFBApp/RNFBRCTEventEmitter.m, packages/auth/ios/RNFBAuth/RNFBAuthModule.m, packages/ml-vision/ios/RNFBMLVision/RNFBMLVisionBarcodeDetectorModule.m
Correctly remove iOS auth handlers when app is reloaded
=> fix(auth): Fix iOS event subscriptions not correctly removing on reload

pages/quick-start/new-project.md
Fix typo in `quick-start/new-project.md`
---
=> type(docs): Fix typo

docs/messaging/ios.md
=> docs(messaging): fix broken link in messaging ios guide

docs/admob/android.md
Fix Import of Admob package
- [ x] Supports `Android`
- [ x] Supports `iOS`
---
=> docs(admob): Fix incorrect import of Admob package

docs/auth/phone-auth.md
Extracting `confirm` method from `ConfirmationResult` object gives error, because `this` reference gets messed up. Fixed example that extracts `confirm`;
issue: #2809
---
=> docs(auth): Update sms code confirmation example

docs/index.md
Broken link fixed for dynamic links docs
---
=> docs(*): Fix broken link in index.md

docs/dynamic-links/quick-start.md, packages/dynamic-links/lib/index.d.ts, packages/in-app-messaging/lib/index.d.ts
Dynamic links had a bunch of missing info
=> Added missing dynamic links info

pages/migrating-to-v6.md
A few of the internal links in the "removing" section we're broken.
---
=> Minor doc update - Fixing broken internal links

packages/storage/ios/RNFBStorage/RNFBStorageCommon.m
Fixes #2722 
Sometime `storageMetadata` is nil and causing app crash.
Manual test in iPhone 7 device
---
=> fix(storage,ios): Handle null Storage metadata values

docs/analytics/quick-start.md
Due to the API change in v6 I stumbled across #1635 and figured that some documentation might help here since it is a popular use case.
=> Add docs about ignoring analytics in TestLab

packages/auth/ios/RNFBAuth/RNFBAuthModule.m
Error described in #2899 is caused on iOS because a values are removed from an NSMutableDictionary in a for loop. Can be fixed by removing all handlers at once after the loop.
The setup as described in #2899 crashes at each reload in debug mode. When this patch is applied no crashes occur anymore. 
[IOS][BUGFIX] [AUTHENTICATION] - Updated handler cleanup to fix crash when using Authentication for multiple Firebase apps.
---
- 👉 Contribute; …
=> Fixes #2899: iOS Bug NSGenericException: Collection was mutated while being enumerated.

docs/database/quick-start.md
Fix small typo `initilizing` -> `initializing`
---
=> docs(database): Fix typo in quick-start.md

docs/analytics/quick-start.md, docs/database/quick-start.md
=> fix package names in documentation

docs/dynamic-links/quick-start.md
Also, I slightly reworded the description of `getInitialLink()`.
None, just doc fixes.
[INTERNAL] [ENHANCEMENT] [./docs] - Fix typos in DynamicLinks Quick Start guide
---
=> [Docs] Fix typos in DynamicLinks Quick Start guide

pages/migrating-to-v6.md
Fix wrong file name of **package-lock.json**
=> docs(migration): Fix package-lock.json name

pages/quick-start/android-firebase-credentials.md
Added note about Analytics module being required for Firebase to complete verification and that you can skip verification and finish adding app.
---
=> close #2911: Verification can be skipped.

packages/auth/lib/index.js
As discussed in #2883 this PR makes the `onAuthStateChanged`, `onIdTokenChanged` and `onUserChanged` trigger callbacks asynchronously
closes #2883 
---
=> Made onAuthStateChanged, onIdTokenChanged and onUserChanged trigger asynchronously

packages/admob/RNFBAdMob.podspec
I believe this is necessary for case-sensitive file systems
This was not failing for me (case-insensitive / standard macOS filesystem) but there was a problem from user dayhaysoos in i-need-help Discord channel related to the Pod not being found, and this appeared to fix it for him
Build error when including pod, resolved by editing the podspec in node_modules like this then re-trying
[IOS][BUGFIX][AdMob] - Use AdMob vs Admob for Pod name
---
- 👉 Star this repo on GitHub …
=> fix(admob,ios): use `AdMob` vs `Admob` for Pod name

packages/crashlytics/ios_config.sh
Fixes #2947 
[IOS][BUGFIX] [Crashlytics] - updated ios_config.sh file to resolved issue #2947
=> fix(crashlytics,ios): use quotes on build script

docs/auth/social-auth.md
Updated Apple sign in docs for social authentication
=> docs(auth): updated social auth docs to include Apple

README.md
I've updated the npm badge in README, since it was still pointing at react-native-firebase v5
[GENERAL][MINOR] [README] - updated npm badge
---
=> docs(*): update npm badge

packages/app/lib/internal/registry/app.js
Fixes #3046 
[JS][BUGFIX] [APP] - Fix a typo
=> fix(app): typo

packages/crashlytics/lib/handlers.js
Fixes #3079
This PR fixes a potential TypeError in `packages/crashlytics/lib/handlers.js` where
currently the variable `fileName` is dereferenced although it might be `undefined`.
I would have liked to add a test, but did not find a test file for `handlers,js`.
[ GENERAL  ] [ BUGFIX      ] [ crashlytics ] - Fixed a potential TypeError
---
=> fix(crashlytics): handle undefined fileName in stack frames

packages/crashlytics/RNFBCrashlytics.podspec, tests/ios/Podfile.lock
Whenever we make a release to TestFlight, Apple sends annoying emails stating that we have a dependency that uses deprecated UIWebView component. This puts our development team into an embarrassing situation because the email distribution list contains upper management who don't really understand what a dependency is, so they need explanations. And also we want to migrate our deprecated libraries ASAP.
When I searched for any libraries that has this component, I saw that crashlytics was the culprit:
I have raised this issue in (https://github.com/invertase/react-native-firebase/issues/3012) and I was asked to propose a PR for it. So here it is.
Upgrade; Crashlytics 3.12.0->3.14.0 & Fabric 1.9.0->1.10.2 in `RNFBCrashlytics.podspec` file.
Reason: To prevent deprecated UIWebView issue. …
=> fix(crashlytics,ios): version bump native ios deps

packages/crashlytics/lib/index.d.ts
Related to #3084 and other user requests about the crash APIs
This is documentation only
Possibly worth mentioning that I frequently advise people "there is an edit button at the top of each docs page" but that's wrong for v6! I wasn't aware that the docs are auto-generated from the types defs but they are I think? Which is why I'm doing a PR against this file
Is there any way to hook up an edit button to go to the types files so my assertion about edit buttons is true again? Otherwise I can give more nuanced advice, but that edit button was a neat trick...
[TYPES][ENHANCEMENT] [Crashlytics] - Add docs noting what traces will look like
---
- 👉 Donate via [Open …
=> docs(crashlytics): notes on what to expect for crashes

docs/iid/quick-start.md
Fix wrong example. 
`iid.get()` to `iid().get()` 
Do not need.
---
=> Fix iid.get() to iid().get()

packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreCommon.java
=> fix(firestore,android): add additional null check to exception handler

packages/perf/android/src/main/java/io/invertase/firebase/perf/UniversalFirebasePerfModule.java, packages/perf/e2e/HttpMetric.e2e.js
=> Performance bug

packages/auth/e2e/auth.e2e.js, packages/auth/ios/RNFBAuth/RNFBAuthModule.m, packages/auth/lib/index.d.ts, packages/auth/lib/index.js, tests/package.json
=> Shared keychain ios

docs/admob/quick-start.md
=> docs(admob) update admob quick start for maxAdContentRating

pages/quick-start/new-project.md
Running npx react-native run-android right after creating a new project will result in a build failure using the latest react-native-firebase template (Version 6.2.0). The build fails because the Android project is expecting the Firebase credentials file to be present, which is added in the next step of this guide.
When I was creating my first project, I got stuck for a long time trying to figure out why my build kept failing even though I was seemingly following the guide.
- [✔] Supports `Android`
--- …
=> docs(*): remove run command from quick start guide

docs/app/ios.md
Fix iOS installation docs for firebase app so they're inline with the quick start iOS docs. 
---
=> updates ios installation docs for app

packages/app/lib/internal/registry/namespace.js
=>  allows users to use redux firestore

packages/dynamic-links/lib/builder.js
=> fix(dynamic-linking): analytics param bug fix

packages/admob/lib/ads/InterstitialAd.js, packages/admob/lib/ads/MobileAd.js, packages/admob/lib/ads/RewardedAd.js
=> fix(admob): set correct loading var

packages/auth/lib/index.js, packages/firestore/e2e/Query/isEqual.e2e.js, packages/firestore/ios/RNFBFirestore/RNFBFirestoreQuery.m, packages/firestore/lib/FirestoreQueryModifiers.js, tests/e2e/init.js
=> @russell/fix fieldpath

packages/admob/android/build.gradle, packages/analytics/android/build.gradle, packages/app/android/build.gradle, packages/auth/android/build.gradle, packages/crashlytics/android/build.gradle, packages/database/android/build.gradle, packages/dynamic-links/android/build.gradle, packages/firestore/android/build.gradle, packages/functions/android/build.gradle, packages/iid/android/build.gradle, packages/in-app-messaging/android/build.gradle, packages/messaging/android/build.gradle, packages/ml-natural-language/android/build.gradle, packages/ml-vision/android/build.gradle, packages/perf/android/build.gradle, packages/remote-config/android/build.gradle, packages/storage/android/build.gradle
While working on android build / CLI issues in #3206 I noticed the work done in https://github.com/invertase/react-native-gradle-plugin/pull/1 was not reflected because the android build wasn't using invertase gradle plugin 1.4 - that is the first commit here
I separately noticed that many of the modules were not using harmonized BoM / version numbers - that is the second commit
The version spray across all the packages is worrisome as I am sure this will skew again unless it's possible to reference the number somehow, meta-program it or add a lint check
Honestly my test plan is to rely on CI and visual inspection - it is possible that some of the versions weren't on consistent BoM for a reason?
[ANDROID][BUGFIX] [BUILD] - Harmonize android dependencies on BoM 24.1.0
---
Think …
=> fix(android,build): use correct plugin & BoM versions

packages/messaging/lib/index.d.ts
I noticed what it looks like a typo in the [Messaging Reference](https://invertase.io/oss/react-native-firebase/v6/messaging/reference/module#onMessageSent). It says `firestore()` when it should be `messaging()`
Nothing to test. Just a typo.
[ GENERAL ] [ BUGFIX ] [ Messaging Module] - Fixes typo in the reference
---
=> docs(messaging): fixed types incorrectly referencing firestore() #3201

packages/admob/android/build.gradle, packages/analytics/android/build.gradle, packages/auth/android/build.gradle, packages/crashlytics/android/build.gradle, packages/database/android/build.gradle, packages/dynamic-links/android/build.gradle, packages/firestore/android/build.gradle, packages/functions/android/build.gradle, packages/iid/android/build.gradle, packages/in-app-messaging/android/build.gradle, packages/messaging/android/build.gradle, packages/ml-natural-language/android/build.gradle, packages/ml-vision/android/build.gradle, packages/perf/android/build.gradle, packages/remote-config/android/build.gradle, packages/storage/android/build.gradle
=> fix(android,build): conditionally check `app` dependency, fixes #3206

docs/messaging/index.md
It's not clear from the [cloud messaging documentation](https://invertase.io/oss/react-native-firebase/v6/messaging) that v6 does not support notificaitons and does not intend to. It took me around 5 minutes of reading to realize that I should just look for another package and that the issue was closed (#2566) and so I shouldn't expect any update.
Added some basic text in to indicate this. Thanks.
---
- …
=> docs(messaging): add note about local notification apis

packages/analytics/e2e/analytics.e2e.js, packages/analytics/lib/index.js
=> bug(analytics): logEvent params can be objects

docs/ml-natural-language/quick-start.md
=> docs(ml-natural-language): JSON lint: quote property keys, no trailing comma

docs/ml-vision/quick-start.md
=> docs(ml-vision): JSON lint: quote property keys, no trailing comma

packages/in-app-messaging/RNFBInAppMessaging.podspec
This was changed in firebase iOS SDK 6.16.0 - https://firebase.google.com/support/release-notes/ios#firebase-in-app-messaging_1
I am unsure on backwards-compatibility of this changed, I am only attempting to build against current (SDK 6.18.0 as I type this)
Without this change iOS does not compile against 6.18.0
---
=> build(ios, in-app-messaging): update firebase sdk pod name

README.md
Spelling mistake corrected in ReadMe file in version 5.x.x
=> docs: spelling mistake corrected.

pages/quick-start/android-firebase-credentials.md
Fixes #3154 part 2 - this time the documentation for integrating existing projects
#3295 did the same but for the template so people get these settings by default
---
=> Suggest users increase memory for android build

.gitignore, packages/auth/e2e/user.e2e.js, packages/auth/lib/User.js, tests/index.android.js
=> fix(auth): user.metadata uses ISO strings

packages/storage/e2e/storage.e2e.js, packages/storage/lib/utils.js, tests/package.json
=> fix(storage): fixed a bug with parsing encoded urls

docs/firestore/usage/index.md, docs/releases/v6.4.0.md, docs/typescript.md, package.json
=> v6.4.0 changelog & md formatting

docs/crashlytics/ios-setup.md
Change **Android** to **iOS** bc this is iOS setup.
fixed typo
=> docs: fixes typo in iOS setup docs

docs/auth/social-auth.md
=> docs(auth): fix syntax error in examples

.gitignore, package.json, packages/dynamic-links/lib/index.js
Added missing dynamic link static types.
=> chore(dynamic-links): add static types

docs/ml-natural-language/usage/index.md
In the documentation the instruction to rebuild android was like `npx react-native run-ios`, I changed it to `npx react-native run-android`.
It's a documentation update.
No tests for this PR
[GENERAL][DOCUMENTATION] [./docs/ml-natural-language/usage] - I changed the rebuild instructions for android
<!--
**INTERNAL tagged notes will not be included in the next version's release notes.**
=> docs: change instructions for android rebuild

docs/messaging/ios-permissions.md
small typo on [ios-permissions.md](/docs/messaging/ios-permissions.md#reading-current-status) doc
---
=> docs(messaging): fix typo in ios-permissions

docs/messaging/usage/index.md
Just a small change in Docs.
- [ *] Yes
=> docs: Update unsubscribeFromTopic method name

docs/enabling-multidex.md
=> docs: fix typo in mulitdex doc

docs/firestore/usage/index.md
Fixes syntax error for code inside docs
=> docs: bootstrap function should be async

docs/ml-vision/face-detection.md
=> docs(ml-vision): update

packages/admob/lib/index.d.ts
fix for a tiny typescript issue I came across
=> Fix RequestOptions ts type

docs/messaging/usage/index.md
Fixes inaccurate documentation concerning usage and return type of messaging().requestPermission.
Not applicable
Not applicable
---
=> docs(messaging): update example

docs/app/usage.md, docs/database/usage/index.md, docs/index.md, docs/migrating-to-v6.md
This PR covers a span of documentation updates PRs that have been approved, but no CLA has been obtained:
https://github.com/invertase/react-native-firebase/pull/3640
https://github.com/invertase/react-native-firebase/pull/3625
https://github.com/invertase/react-native-firebase/pull/3408
https://github.com/invertase/react-native-firebase/pull/3532
https://github.com/invertase/react-native-firebase/pull/3238
=> docs(*): corrections

packages/auth/lib/index.d.ts
There is a **'** after `user.email`.
I just removed a typo.
---
=> docs(auth): fix types example

.github/workflows/tests_e2e.yml, packages/app/e2e/app.e2e.js, tests/android/app/src/main/AndroidManifest.xml, tests/ios/Podfile, tests/ios/Podfile.lock, tests/package.json
https://github.com/invertase/firestore-ios-sdk-frameworks
---
=> ci: use FirebaseFirestore pre-compiled pod ⚡

packages/auth/android/src/main/java/io/invertase/firebase/auth/ReactNativeFirebaseAuthModule.java, packages/auth/e2e/user.e2e.js
*Testing*
Update quote for testing purposes only (reverted once testing has finished)
to
Tests results ran locally return the following...
=> fix(auth,android): too-many-requests code now correctly returned

packages/firestore/android/src/reactnative/java/io/invertase/firebase/firestore/ReactNativeFirebaseFirestoreTransactionHandler.java
Android app is crashed by IllegalMonitorStateException.
Fixes #3747
App controls lock which is not held by the current thread.
---
=> fix(android): fixed IllegalMonitorStateException crashed issue

docs/database/usage/index.md
Database docs updated: how to unsubscribe from events using the `off` method.
Fixes #3812 
---
=> docs(database): using ref.off() to unsubscribe

android/src/main/java/io/invertase/firebase/notifications/RNFirebaseBackgroundNotificationActionReceiver.java
=> #2207 fix Android notification with remote input

docs/index.md
=> docs: correct apply location of gms plugin

docs/messaging/usage/index.md
Added additional information to account for latest APNs requirements
---
=> docs(messaging): add additional APNS information

docs/database/usage/index.md
Fix typo in Realtime Database: Usage docs.
=> docs: fix typo in database usage

packages/dynamic-links/package.json
Just correcting https://github.com/invertase/react-native-firebase/tree/master/packages/links --> To its current home https://github.com/invertase/react-native-firebase/tree/master/packages/dynamic-links
Incorrect link in dynamic-links package.json reflects old name.
- [ .] Yes
- [ .] `Android`
- [ .] `iOS`
- [ .] No
This is really a docs tweak. Not really much of a code tweak.
--- …
=> fix(dynamic-links, package.json_Repo_link)

docs/database/offline-support.md, docs/database/usage/index.md
=> docs(database): persistence is disabled by default

docs/enabling-multidex.md
@Salakar you noticed the MultiDex docs weren't thorough, I attempt to improve them here
docs(android): improve MultiDex documentation for android
---
=> docs(android): improve MultiDex documentation for android

.spellcheck.dict.txt, docs/faqs-and-tips.md
This PR adds a new tip to the faq/tips documentation section. This was suggested by  @mikehardy  in https://github.com/invertase/react-native-firebase/issues/3706.
N/A
N/A
N/A
---
:fire:
=> docs: add tip about hanging CI build while using Fastlane

docs/messaging/server-integration.md
Adding details for using APNS token on iOS (non-firebase integrations)
This library works as a general push notification client, but needs some tweaking on iOS to work with other providers (Amazon SNS, etc), specifically utilizing the APNS token instead of the FCM token. It's documented in the API but not here in the HOWTO. Hopefully this can save someone a few days of frustration as to why iOS devices won't register properly.
---
- 👉 Follow …
=> docs(messaging): update server-integration.md

docs/faqs-and-tips.md
Adds a FAQ and it's answer to solve a possible hangup in CI's like Bitrise
It doesn't fix an issue but addresses https://github.com/invertase/react-native-firebase/issues/3706
=> docs: add CI hangup related FAQ and answer

docs/crashlytics/usage/index.md
This PR will add missing imports and the default export to `Opt-out` code snippet.
---
=> chore(docs): add missing imports to opt-out

docs/storage/usage/index.md
I just want to repair typo in text.
=> docs: typo

docs/messaging/usage/ios-setup.md
Documentation updates included for APNS with FCM
=> docs(messaging): updated iOS APN setup

docs/analytics/usage/index.md
=> docs(analytics): update `setAnalyticsCollectionEnabled` example

docs/storage/usage/index.md
=> Remove unavailable firebase reference

docs/crashlytics/android-setup.md
=> docs(crashlytics, install): bump firebase crashlytics plugin version

docs/messaging/usage/index.md
People continue to try testing FCM on iOS simulators, the docs are not strong enough there
#3069
---
=> docs(messaging): emphasize iOS simulators do not handle FCM

docs/crashlytics/usage/installation/ios.md
Updates the documentation to prevent 404.
Discussed here: https://github.com/invertase/react-native-firebase/pull/3878#issuecomment-679082148
Just a documentation change, will see when it's deployed 😁 
---
=> docs(crashlytics,ios): Remove additional steps from iOS - manual installation guide

website/scripts/utils.js
Fixes https://github.com/invertase/react-native-firebase/issues/4148
=> docs: corrected reference path for docs edit button

docs/messaging/usage/index.md
This PR seeks to replace a misplaced curly brace with a correct parenthesis.
This is a documentation change.
=> docs(messaging): fix example function parenthesis

.spellcheck.dict.txt, docs/faqs-and-tips.md
Added information about https://github.com/invertase/react-native-firebase/issues/4018 to the FAQs.
=> docs: Added information about the 'items' Analytics param in the FAQs

docs/faqs-and-tips.md
This will save Mike Hardy a few breaths 😅
=> docs: Added react-native-clean-project and template app script to tips docs

packages/remote-config/CHANGELOG.md
Markdown formatting from the commit message wasn't great. Something to remember for next time.
---
=> docs(remote-config, CHANGELOG): prettify breaking changes note

docs/analytics/screen-tracking.md
https://github.com/invertase/react-native-firebase/pull/4145
---
=> docs(analytics): add screen_class to navigation screen tracking examples

packages/auth/e2e/auth.e2e.js
Ci tests are currently failing on the auth module. This update should result in all tests passing
=> chore(auth): fixed tests

docs/remote-config/usage/index.md
=> fix(documentation): Update index.md for remote config

packages/messaging/android/src/main/java/io/invertase/firebase/messaging/JsonConvert.java, packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingModule.java, packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingReceiver.java, packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStore.java, packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreHelper.java, packages/messaging/android/src/main/java/io/invertase/firebase/messaging/ReactNativeFirebaseMessagingStoreImpl.java
=> fix(android, messaging): store notifications in prefs ring buffer for initial/open attribution

docs/perf/usage/index.md
Add import to make it consistent to the analytics page (https://rnfirebase.io/analytics/usage#disable-auto-initialization)
Just a minor detail with a missing import
No issue related, only affects documentation
Minor documentation improvement
---
=> docs: add import at code example

docs/iid/usage/index.md
Fixes sample code snippet when retrieving a token
None
Not applicable
Not applicable
---
=> docs: Fixed code snippet

docs/migrating-to-v6.md
=> docs: update manual link URLs in migrating-to-v6.md

docs/migrating-to-v6.md
This PR is just a quick tweak to remove a duplicated link in the V6 migration docs.
---
=> docs: Remove duplicated link in docs

docs/auth/phone-auth.md
Update phone-auth to include MFA flow
A lot of apps require users to verify their phone number after creating an account with an email and password, this documentation would explain how to do that using the verifyPhoneNumber method.
Fixes #4418 
Updates documentation to include a MFA flow, using auth().verifyPhoneNumber method to link a phone number with the currently authenticated user.
- [ x] Yes
- [x ] `Android`
- [x ] `iOS`
- [ x ] No
Example of firebase user verified using this method
---
Think `react-native-firebase` is great? Please consider supporting the project with …
=> docs(authentication): add MFA example

docs/ml-vision/landmark-recognition.md
This is a simple documentation link fix
---
=> docs(ml-vision): Fix link from usage to reference for cloud landmark recognition

docs/auth/social-auth.md
Apple Auth section is still using v1, so I've rewrite the documentation using v2.
Migrate @invertase/react-native-apple-authentication from v1 to v2
---
=> docs: update Apple auth documentation for v2

docs/migrating-to-v6.md
Update readme to include changes needed in v6 migration for Android.
https://github.com/invertase/react-native-firebase/issues/1420
---
🔥
=> docs(v6 migration): missing v6 upgrade for Android

packages/admob/e2e/interstitial.e2e.js, packages/admob/e2e/rewarded.e2e.js, packages/database/e2e/internal/connected.e2e.js, packages/database/e2e/reference/child.e2e.js, packages/database/e2e/reference/transaction.e2e.js, tests/e2e/mocha.opts
=> test: included test directories in matcher pattern

docs/dynamic-links/usage/index.md
Minor grammar/syntax corrections.
Submitting some minor grammar/syntax fixes for the Dynamic Links Usage document. No source code is affected by this.
=> docs(dynamic-links): Update Usage document (Minor grammar/syntax fixes)

docs/messaging/ios-permissions.md, docs/messaging/notifications.md, docs/messaging/server-integration.md
Noticed by @milesibastos (thank you!) but expanded to cover all cases
obsoletes #4748
PR title
---
=> docs(messaging): fix broken usage links

docs/database/usage/index.md
Edit docs to add description for RealtimeDatabase emulator.
Fixes #3957
- Yes
- docs
- [x ] No
=> docs(database): add emulator usage information

.spellcheck.dict.txt, docs/auth/phone-auth.md
=> docs(auth, ios): clarified phone auth app verification setup

packages/app/package.json, tests/ios/Podfile, tests/ios/Podfile.lock
Just tracking underlying SDK versions
Also re-integrated firebase firestore pre-compiled framework
PR title
---
=> feat(app): firebase-ios-sdk 7.4.0 -> 7.5.0, firebase-android-sdk 26.30 -> 26.4.0

docs/app/utils.md
=> docs(app, utils): fix checkPlayServicesExample

tests/README.md
The current instructions do not fully explain how to configure VSCode before debugging. This update shows the preliminary checks needed before starting.
---
=> chore(docs): Updated VsCode debugging instructions

packages/firestore/lib/index.d.ts
Fix `firestore.Settings` type definition to make each field could be optional. As per implementation of `firebase.firestore().settings()`, it was intended to be optional.
And also follows `firebase-js-sdk`'s type definitions: https://github.com/firebase/firebase-js-sdk/blob/master/packages/firestore-types/index.d.ts
--- …
=> fix(firestore): fix firestore settings type definition

docs/faqs-and-tips.md
Added section for "I can't send a test messages from the console. How do I fix this?". 
Suggested by @mikehardy 
Based on issue thread: https://github.com/invertase/react-native-firebase/issues/4991
---
🔥
=> docs(faqs-and-tips): added tips for enabling test on device

docs/index.md
Updates docs about Hermes support.
Relates to #3549 
=> docs(hermes): hermes support

packages/remote-config/lib/index.d.ts
Fix the code formatting of example on this page: https://rnfirebase.io/reference/remote-config/configsettings
---
=> docs(remoteConfig): Fix code formatting of example displayed on docs

CODE_OF_CONDUCT.md
=> docs(CODE_OF_CONDUCT): update link protocol from http to https

docs/admob/usage/index.md
=> docs(admob, usage): updated play store "contains ads" label/location

packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsModule.m
debuggers intercept crashes in iOS, leading to developer confusion.
Related to #5053 - this is part of my series of desired crashlytics DX enhancements
commit has a conventional title
Run it under Xcode and normally, I see the logs on startup I would expect
---
=> fix(crashlytics, ios): warn if debugger will break crashlytics

docs/auth/social-auth.md
I was trying out google signing with a fresh new project, pasted everything from the docs but it didn't work out. Thought the issue is because of the react-native-firebase but later found out I should be using `@react-native-google-signin/google-signin` instead of `react-native-google-signin` if `RN >= 0.60`.
=> docs(auth, social): Update google sign in docs

.spellcheck.dict.txt, docs/crashlytics/android-setup.md, docs/crashlytics/usage/index.md, packages/app/firebase-schema.json, packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/Constants.java, packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsInitProvider.java, packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsModule.java, packages/crashlytics/e2e/crashlytics.e2e.js, packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.h, packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m, packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsModule.m, packages/crashlytics/lib/handlers.js, packages/crashlytics/lib/index.d.ts, tests/app.js, tests/firebase.json, tests/ios/Podfile.lock
- enabling crashlytics in debug really enables it in debug now
- add ability to specify in firebase.json if you want to chain to other (maybe native) handlers
Now that javascript stack traces are more useful since the crashlytics backend will convert them
to fatal crashes, developers should prefer using them
However the default global crash handler we chain to in react-ntaive will also log them, just
as pure native crashes.
This allows developers to specify they do not want the continued exception processing, and
the module will attempt to simply exit cleanly after logging the unhandled crash
Fixes #5053
conventional commit - rebase merge
This PR has a special set of extra things in the checklist
This has now been tested vs the e2e app, and both native and javascript crashes seem to be …
=> feat(crashlytics): add configuration to exception handler chaining behavior

docs/ml/usage/index.md
Remove useless parenthesis in documentation
---
=> docs(ml): remove extraneous parenthesis

docs/analytics/usage/index.md
Slightly tweaked version of @mikehardy's reply in this issue:
https://github.com/invertase/react-native-firebase/issues/5354#issuecomment-848193343
Fixes #5354
---
=> docs(analytics): use clearer wording regarding avoiding IDFA usage

.spellcheck.dict.txt, docs/auth/usage/index.md
Added information about the ID Token which should be used to authenticate with the backend server.
---
=> docs(auth): add note about using user token vs uid

packages/crashlytics/android/src/main/java/io/invertase/firebase/crashlytics/ReactNativeFirebaseCrashlyticsNativeHelper.java
This add additionnal helpers in ReactNativeFirebaseCrashlyticsNativeHelper to call FirebaseCrashlytics native functions
We have a native util class `CrashlyticsUtils.java` that is used to  centralize crashlytics interaction in native side
We would like to ensure this class uses the same crashlytics dependency than the RNFirebase module, via these additionnal helpers
--- …
=> feat(crashlytics): add helper methods for log and setCustomKey

packages/app/package.json, tests/ios/Podfile.lock
bump versions on underlying SDKs
---
=> feat: firebase-ios-sdk 8.3.0 / firebase-android-sdk 28.2.1

packages/app/package.json
Standard native SDK updates, CI will determine if it works or not
=> feat(sdks, android): use firebase-android-sdk 28.3.0, play-services-auth 19.2.0

docs/crashlytics/usage/index.md
The examples do not make it clear how to use the native helper exception recorder. This PR includes the import statements both for iOS and Android examples.
N/A
N/A
- ~~My change includes tests;~~
- ~~[ ] `e2e` tests added or updated in `packages/\*\*/e2e`~~
- ~~[ ] `jest` tests added or updated in `packages/\*\*/__tests__`~~
- ~~[ ] I have updated TypeScript types that are affected by my change.~~
N/A
:fire:
=> docs(crashlytics): Add import statements to examples

tests/package.json, yarn.lock
Related https://github.com/firebase/firebase-tools/pull/3674
Related https://github.com/firebase/firebase-tools/issues/3671
ios and android e2e tests were both failing on this one, I got clean runs locally with the new release, if it passes in CI we're good
---
=> build(deps): firebase emulator 9.16.4 fixes auth token issues

packages/app-distribution/lib/index.d.ts
matches upstream reality / future state
https://github.com/firebase/firebase-ios-sdk/issues/8602
related #5667
Just needs to pass CI for grammar / typing
---
=> docs(app-distribution): AppDistributionRelease.releaseNotes marked as nullable

packages/auth/lib/index.d.ts
It's not clear wether ID Token is a JWT token or not, developer will have to visit [official documentation](https://firebase.google.com/docs/auth/admin/verify-id-tokens) in order to find out.
---
=> docs(auth): more explicitly note that onIdTokenChanged returns a JWT

README.md
Broken contribution link noticed by @mkarkachov - thanks added to the thanks for the useEmulator doc fix
---
=> docs(README): fix contributing link, add installations

docs/perf/axios-integration.md, docs/perf/ky-integration.md, docs/sidebar.yaml, packages/perf/README.md
Added because I just setup this integration and I feel the community could benefit.
https://github.com/invertase/react-native-firebase/discussions/5695
Add docs for ky intergration
(N/A) 
---
🔥
=> docs(perf): Add docs for ky integration & full example

.spellcheck.dict.txt, docs/in-app-messaging/usage/index.md
=> docs: In-app-messaging - add limitation section

docs/index.md
=> docs(app): wrong link to react native docs

docs/auth/social-auth.md
Updated fbsdk to fbsdk-next
More info here -> https://github.com/facebookarchive/react-native-fbsdk#react-native-fbsdk
=> fix: changed fbsdk to updated sdk

docs/messaging/notifications.md, website/adverts.json
Some tweaks around the Notifee bits of the documentation to now directly recommend Notifee.
---
=> docs: tweak wording around Notifee

docs/index.md
Reinforcing some of the more important Expo set up steps so that they're not missed on a quick scan. Adding the exact commands that are required to prevent errors when trying to connect to Firebase.
---
=> docs(expo): emphasize important instructions in Expo set up

docs/crashlytics/crash-reports.md
Links in the [Crashlytics](https://rnfirebase.io/crashlytics/crash-reports) page are broken
---
=> docs(Crashlytics): Fix broken links

packages/installations/e2e/installations.e2e.js
=> test(installations): add missing returns for promises

docs/faqs-and-tips.md
Just adds commentary from @mikehardy's answer here: https://github.com/invertase/react-native-firebase/issues/5683
---
🔥
=> docs(faq): add why react-native-firebase

packages/app/package.json
https://firebase.google.com/support/release-notes/ios
For our purposes it is only a bug fix, the new features are not things we expose via react-native-firebase
=> fix(ios, sdk): bump firebase-ios-sdk to 8.11.0

docs/auth/social-auth.md
=> docs(auth): update docs to handle error 

docs/messaging/usage/ios-setup.md
Small grammar tweaks to iOS setup docs.
=> docs(messaging): small grammar fix to iOS setup

packages/firestore/lib/index.d.ts
A touch-up based on suggestion from @alexstanbury
#5914 / #6208 
conventional commits, but also just a docs change, vercel will get it on merge
---
=> docs(firestore, increment): refine caution warning

docs/firestore/pagination.md
Just noticed a typo and it must not stand
---
=> docs(firestore, pagination): fix typo

docs/app-distribution/usage/index.md, docs/crashlytics/android-setup.md, docs/index.md, packages/app-distribution/android/build.gradle, packages/app/package.json, packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap, tests/android/build.gradle
- handles multi-process apps in crashlytics now
- has some built in screen fragment performance timing features
- app distribution (still beta) has an API + impl split for play store review safety
---
=> feat(android, sdk): firebase-android-sdk 30.1.0

.github/workflows/scripts/firebase.json, .github/workflows/scripts/storage.rules, packages/app/e2e/utilsStatics.e2e.js, packages/storage/e2e/helpers.js, tests/app.js, tests/ios/Podfile.lock, tests/package.json, yarn.lock
These have built up while working on firebase-ios-sdk v9, but none of them are dependent on that PR
Peeling a few off to get them through now so I can reduce the size of the PR(s) in progress as I push that forward
Each commit works on it's own and has it's own commit message
All commits are conventional-commits compliant and none of them will trigger a release
=> chore(misc): a batch of small changes for test execution

.spellcheck.dict.txt, docs/index.md, packages/app/package.json, packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.h, packages/crashlytics/ios/RNFBCrashlytics/RNFBCrashlyticsInitProvider.m, packages/functions/e2e/functions.e2e.js, tests/ios/Podfile, tests/ios/Podfile.lock, tests/ios/testing.xcodeproj/project.pbxproj
This PR forward-ports react-native-firebase to new major version firebase-ios-sdk v9 of underlying SDK
BREAKING CHANGE: firebase-ios-sdk now requires `use_frameworks!` in your Podfile and Xcode 13.3+
BREAKING CHANGE: android works like web+iOS now: customMetadata if passed in will be
updated as a single atomic unit, all keys at once. Any key you want to keep in customMetadata
must be passed in during update; any missing keys will be removed. Set customMetadata to null
in order to remove customMetadata entirely, omit it during update to leave it unchanged.
BREAKING CHANGE: if your firebase functions return custom HttpsError instances, you must not upgrade yet,
custom errors suffered a regression in firebase-ios-sdk 9.0.0 and 9.1.0. The next firebase-ios-sdk release
fixes this regression, …
=> feat(ios, sdk)!: firebase-ios-sdk v9; requires `use_frameworks!` + Xcode 13.3+

packages/app/package.json, tests/ios/Podfile.lock
Update to underlying SDK
Ran it through `yarn tests:ios:test` locally, :100: 
---
=> feat(ios, sdk): update to firebase-ios-sdk 9.2.0

packages/analytics/lib/index.d.ts
Tiny typo fix
#6325 
#6321 
#6264 
just a doc change
---
=> docs(analytics, ios): fix on-device-conversion variable name

docs/app-check/usage/index.md
added "Cloud Firestore" to list of supported services
Docs review
---
=> docs(appcheck) added "Firestore" to list of supported services

docs/messaging/notifications.md
=> docs(messaging): Added a Section for Getting FCM Device Tokens

docs/index.md, packages/analytics/android/build.gradle, packages/app-check/android/build.gradle, packages/app-distribution/android/build.gradle, packages/app/android/build.gradle, packages/app/package.json, packages/app/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap, packages/auth/android/build.gradle, packages/crashlytics/android/build.gradle, packages/database/android/build.gradle, packages/dynamic-links/android/build.gradle, packages/firestore/android/build.gradle, packages/functions/android/build.gradle, packages/functions/e2e/functions.e2e.js, packages/in-app-messaging/android/build.gradle, packages/installations/android/build.gradle, packages/messaging/android/build.gradle, packages/ml/android/build.gradle, packages/perf/android/build.gradle, packages/remote-config/android/build.gradle, packages/storage/android/build.gradle, scripts/_TEMPLATE_/android/build.gradle, tests/android/build.gradle, tests/ios/Podfile.lock
Bump underlying SDKs, and a couple of unrelated house-keeping commits
Run tests locally, seems to pass?
---
=> feat(sdks): firebase-ios-sdk 9.3.0 / firebase-android-sdk 30.3.0

docs/index.md
Fixes #6332
Since this is a documentation only change, I haven't added or ran any tests.
---
🔥
=> docs(all): Update expo-build-properties instructions

.spellcheck.dict.txt, docs/dynamic-links/usage/index.md
Mentioned [uri-scheme](https://www.npmjs.com/package/uri-scheme). Clarified iOS and Android behaviour when opening the link if the app isn’t installed. Removed requirement of testing on a real iOS device; instead added instructions of how to circumvent the limitations on a Simulator. Merged iOS and Android testing instructions.
---
=> docs(dynamic-links): Update testing instructions

docs/crashlytics/android-setup.md, docs/index.md, packages/app-distribution/android/build.gradle, packages/app/package.json, packages/app/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap, packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap, tests/android/build.gradle, tests/ios/Podfile.lock
New native SDKs and gradle plugin versions, nothing huge but staying current, making sure release queue is clear
Ran `yarn tests:ios:test` and `yarn tests:android:test` and `yarn tests:jest` locally, all looks good
---
=> feat(deps): new native SDKs

CONTRIBUTING.md
Just updated the link to the egghead course for contributing to open source, as it was resulting in a 404.
N/A
N/A
N/A
---
=> docs: Updated broken link in the CONTRIBUTING.md

docs/index.md
Came up in https://github.com/mikehardy/rnfbdemo/issues/15
=> docs(ios, use_frameworks): clarify which parts of react-native work and which do not

packages/messaging/lib/index.d.ts
Fix a documentation typo.
---
:fire:
=> docs(messaging): fix typo

website/src/components/Footer.tsx
=> docs(footer): fixed typo twitter link.

docs/dynamic-links/usage/index.md
Add an important note regarding the need for a whitelist for custom domains
See #6744
=> docs(dynamic-links): Whitelisting dynamic links with custom domains

packages/functions/e2e/functions.modular.e2e.js, packages/functions/lib/modular/index.js
=> fix(functions, modular): return instance with or without app argument

docs/messaging/usage/index.md
=> Added a header/title for Android Permissions Section

docs/database/usage/index.md, docs/index.md, packages/app/package.json, tests/ios/Podfile.lock
we are not exposing any new features, so just a fix / point release
Passes e2e tests locally, CI should go green
---
=> fix(app, ios): bump firebase-ios-sdk to 10.6.0

docs/auth/phone-auth.md
added onAuthStateChanged to the signInWithPhoneNumber Example
#530 
- [x ] Yes
- [x ] `Android`
- [ x] No
---
=> docs(auth): added onAuthStateChanged to the signInWithPhoneNumber Example

docs/app-check/usage/index.md
The iOS section is an exact copy of the Android section. I think this is an unintended copy/paste mistake. Please, add a new iOS section.
---
=> docs(app-check): corrected ios config section for debugTokens

docs/index.md, packages/app/package.json
This was causing lots of problems for users, glad the underlying SDK moved to support Play Integrity for phone auth
A couple discussions, no issues I can remember - I have posted in the relevant discussions
e2e tests ran clean locally
---
=> fix(android, auth): phone auth supports Play Integrity now

docs/analytics/usage/index.md
Adding an Android section to "Seeing Events in Firebase Console's DebugView"
- [X ] Yes
- [ X] `Android`
- [X ] No
---
=> docs(Analytics): Adding an Android section to "Seeing Events in Firebase Console's DebugView

docs/messaging/usage/index.md, docs/messaging/usage/messaging-with-xmpp.md, packages/messaging/lib/index.d.ts, tests/ios/Podfile.lock
These are from various PRs with documentation suggestions where the suggestions were good but the PR was not ready to go for whatever reason
Linked in each commit with credit to proposer of the PR
Passes CI (lint, spelling etc)
---
=> docs: a collection of doc tweaks gleaned from various PRs

docs/functions/usage/index.md
Cloud functions can be deployed in various locations/regions. Specifying the location was not documented. So, I added it to the documentation. 
- [X ] Yes
- [ X] `Android`
- [ X] `iOS`
- [ X] No
---
=> docs(functions): Added How Location/Region Cen be Specified

.github/workflows/create_test_patches.yml, .github/workflows/docs.yml, .github/workflows/linting.yml, .github/workflows/publish.yml, .github/workflows/tests_e2e_android.yml, .github/workflows/tests_e2e_ios.yml, .github/workflows/tests_jest.yml
CI actions have some dependency updates, some repository moves, and some timeout issues, this preens the workflow files
conventional commits all set up for a rebase+merge per usual
It is made of testing...
---
=> test(ci): various CI updates

docs/index.md
Same description as #7135 but the CLA wasn't signed there - it's the tiniest change, for expediency instead of doing a bunch of back and forth and notifications for busy people I'm just doing the PR separate to get it through. All hail @byCedric :-)
Supercedes #7135
=> docs(expo): update link to vscode-expo extension

docs/auth/social-auth.md
=> docs(auth): fixed typo in facebook example code

docs/auth/multi-factor-auth.md
Supercedes #7156 - credit to @katayama8000 - contents are the same but the superceded PR was missing CLA and for a one-liner it is more expedient to re-implement + push through
=> docs(auth, multi-factor): correct conditional in code example

package.json, packages/installations/__tests__/installations.test.ts, packages/installations/e2e/installations.modular.e2e.js, packages/installations/lib/index.d.ts, packages/installations/lib/index.js, packages/installations/lib/modular/index.d.ts, packages/installations/lib/modular/index.js, tests/app.js, tests/e2e/.mocharc.js, tests/e2e/globals.js
Adds the Firebase JS Web V9 modular API to RNFB. 
---
=> feat(installations): Firebase JS SDK V9 modular API

docs/index.md, packages/app/package.json, tests/ios/Podfile.lock
the underlying SDK exposes some new features but
they are not exposed here, but we do get the benefit of the underlying bugfixes
conventional commit ready for rebase-merge
e2e tests passed locally, should pas in CI
---
=> fix(app, sdk): adopt firebase-ios-sdk 10.11.0

.github/workflows/scripts/deploy-remote-config-function.sh, .github/workflows/scripts/firebase.json, .github/workflows/scripts/functions/src/index.ts, .github/workflows/scripts/functions/src/testFunctionRemoteConfigUpdate.ts, .spellcheck.dict.txt, docs/remote-config/usage/index.md, jest.setup.ts, packages/remote-config/android/src/reactnative/java/io/invertase/firebase/config/ReactNativeFirebaseConfigModule.java, packages/remote-config/e2e/config.e2e.js, packages/remote-config/e2e/helpers.js, packages/remote-config/ios/RNFBConfig/RNFBConfigModule.m, packages/remote-config/lib/index.d.ts, packages/remote-config/lib/index.js, packages/remote-config/lib/modular/index.js, tests/package.json
=> feat(remote-config): realtime config updates

CONTRIBUTING.md
=> docs(contributing): fix promise typo

packages/app/firebase-schema.json
Since only specified values are allowed, then suggest them as an enum
Add enum for `app_log_level` in json schema
---
:fire:
=> docs(app): Add enum for app log level in json schema

docs/auth/social-auth.md
Added a note about the order of the elements in the `requestedScopes` property (for Apple authentication.)
---
=> docs(auth): a note about the order of the elements in `requestedScopes`

docs/app/usage.md
Add missing dots and replacing commas by dots
---
🔥
=> docs(app): fix typos on dots and commas

.github/workflows/create_test_patches.yml, .github/workflows/docs.yml, .github/workflows/tests_jest.yml
I keep thinking I got them all, but success criteria is a clean slate on CI after running everything, and I keep seeing little things that were missed - they show up as cache save failures
=> test(ci): more yarn cache path fixes

packages/crashlytics/e2e/crashlytics.e2e.js, packages/crashlytics/lib/index.d.ts, packages/crashlytics/lib/index.js, packages/crashlytics/lib/modular/index.d.ts, packages/crashlytics/lib/modular/index.js, tests/app.js, tests/e2e/globals.js
=> feat(crashlytics): Firbase web modular V9 API

packages/in-app-messaging/e2e/fiam.e2e.js, packages/in-app-messaging/lib/index.js, packages/in-app-messaging/lib/modular/index.d.ts, packages/in-app-messaging/lib/modular/index.js, tests/app.js, tests/e2e/globals.js
=> feat(in-app-messaging): Firebase V9 modular APIs

packages/dynamic-links/e2e/builder.analytics.e2e.js, packages/dynamic-links/e2e/builder.android.e2e.js, packages/dynamic-links/e2e/builder.e2e.js, packages/dynamic-links/e2e/builder.ios.e2e.js, packages/dynamic-links/e2e/builder.itunes.e2e.js, packages/dynamic-links/e2e/builder.navigation.e2e.js, packages/dynamic-links/e2e/builder.otherplatform.e2e.js, packages/dynamic-links/e2e/builder.social.e2e.js, packages/dynamic-links/e2e/dynamicLinks.e2e.js, packages/dynamic-links/lib/index.js, packages/dynamic-links/lib/modular/index.d.ts, packages/dynamic-links/lib/modular/index.js, tests/app.js, tests/e2e/globals.js
=> feat(dynamic-links): Firebase web V9 modular APIs

docs/auth/multi-factor-auth.md
=> docs(auth, mfa): fix example code typo

tests/README.md
Make sure our test documentation is ready to go with current tested versions
should not trigger a release with the conventional commit tag I gave it
It's docs, but this is verified against my local testing environment and what we use in CI, so should have fidelity with current practice
---
=> test(docs): update docs with current versions etc

CONTRIBUTING.md, packages/messaging/ios/RNFBMessaging/RNFBMessaging+AppDelegate.m
=> refactor: Fix typos

docs/index.md
react-native template has moved things a bit, and if you follow the previous instructions it no longer works!
Updated to include new wisdom from community members, thank you - related https://github.com/invertase/react-native-firebase/issues/6368#issuecomment-1732251653 with thanks to @little-buddy
docs only
--- …
=> docs(app, ios): update info on Podfile use_frameworks / compatibility

.github/workflows/tests_e2e_android.yml, docs/app-distribution/usage/index.md, docs/index.md, packages/app/package.json, tests/android/build.gradle, tests/ios/Podfile.lock
Simple bumps to the underlying native SDKs
---
=> fix(app): android SDK 32.8.0 / ios SDK 10.23.0

docs/index.md
Minor tweak to an ugly formatting issue in the Expo section of the main page.
Read the main page of the website.
=> docs(expo): minor formatting fix

packages/functions/lib/modular/index.d.ts, packages/functions/lib/modular/index.js
typescript definitions for modular functions API.
---
@mikehardy since you asked.
=> feat(functions): typescript definitions for modular functions API

docs/crashlytics/android-setup.md, docs/index.md, packages/app/package.json, packages/crashlytics/plugin/__tests__/__snapshots__/androidPlugin.test.ts.snap, tests/android/build.gradle
=> fix(app, android): adopt firebase-android-sdk 31.1.1

packages/functions/lib/modular/index.js
=> fix(functions): properly pass the custom URL or region to constructor

packages/app/lib/internal/RNFBNativeEventEmitter.js, packages/app/lib/internal/web/firebaseStorage.js, packages/app/lib/internal/web/utils.js, packages/storage/e2e/StorageReference.e2e.js, packages/storage/e2e/StorageTask.e2e.js, packages/storage/e2e/helpers.js, packages/storage/lib/index.js, packages/storage/lib/web/RNFBStorageModule.android.js, packages/storage/lib/web/RNFBStorageModule.ios.js, packages/storage/lib/web/RNFBStorageModule.js, tests/.jetrc.js, tests/app.js, tests/globals.js, tests/package.json, yarn.lock
=> feat(other): Add Storage support

packages/analytics/e2e/analytics.e2e.js, packages/analytics/lib/index.js, packages/analytics/lib/web/RNFBAnalyticsModule.android.js, packages/analytics/lib/web/RNFBAnalyticsModule.ios.js, packages/analytics/lib/web/RNFBAnalyticsModule.js, packages/analytics/lib/web/api.js, packages/app/lib/index.d.ts, packages/app/lib/internal/web/RNFBAppModule.js, packages/app/lib/internal/web/firebaseInstallations.js, tests/app.js, tests/globals.js
=> feat(other): Add analytics support

.github/workflows/stale.yml
=> ci: update labels for the stale bot

docs/sidebar.yaml
Changing the sidebar so we lower the priority of old migration while still keeping the documentation
closes #7803 
---
=> docs: update the menu layout with a Legacy part

packages/analytics/__tests__/analytics.test.ts, packages/analytics/lib/index.js, packages/analytics/lib/modular/index.d.ts, packages/analytics/lib/modular/index.js
=> test(analytics): ensure modular API are exported properly

packages/dynamic-links/__tests__/dynamic-links.test.ts, packages/dynamic-links/lib/index.d.ts, packages/dynamic-links/lib/index.js, packages/dynamic-links/lib/modular/index.d.ts, packages/dynamic-links/lib/modular/index.js
=> test(dynamic-links): ensure modular API are exported properly

packages/app-distribution/__tests__/app-distribution.test.ts, packages/app-distribution/lib/index.d.ts
=> test(app-distribution): ensure modular API are exported properly

packages/installations/__tests__/installations.test.ts, packages/installations/lib/modular/index.d.ts, packages/installations/lib/modular/index.js
=> test(installations): ensure modular API are exported properly

packages/ml/__tests__/ml.test.ts, packages/ml/lib/index.d.ts, packages/ml/lib/modular/index.d.ts, packages/ml/lib/modular/index.js
=> test(ml): ensure modular API are exported properly

.github/ISSUE_TEMPLATE/Bug_report.md, .github/ISSUE_TEMPLATE/Documentation_issue.md, .github/ISSUE_TEMPLATE/Feature_request.md, .github/ISSUE_TEMPLATE/Other_platforms_bug_report.yml, .github/workflows/issue-labels.yaml, .github/workflows/needs-attention-label.yaml, .github/workflows/stale.yml
=> ci: ensure repo labels matches FlutterFire + label automation

packages/analytics/lib/index.d.ts, packages/analytics/lib/modular/index.d.ts
Fix typo in type declaration 
N/A
Fix typo  in type declarations
---
=> fix(analytics): typo in type declarations

docs/index.md, packages/app/package.json, tests/ios/Podfile.lock
Does exactly what the PR title says, nothing more
=> feat(ios, sdk): adopt firebase-ios-sdk 11.4.0

CHANGELOG.md
Found some typos in CHANGELOG, last time I forgot to sign the CLA in time then the PR closed. Now I resubmit the PR.
---
=> docs: Update CHANGELOG.md, fix typos

docs/index.md
An extra note from Expo folks, posted from user @raxng
Comment here
- https://github.com/invertase/react-native-firebase/issues/8189#issuecomment-2646091097
single conventional commit
If lint passes we're good
---
=> docs(app, expo): add note about uninstalling Expo Go as needed

docs/analytics/usage/index.md, docs/platforms.md, packages/analytics/lib/web/RNFBAnalyticsModule.js, packages/analytics/lib/web/api.js, packages/app/lib/internal/RNFBNativeEventEmitter.js, packages/app/lib/internal/nativeModuleAndroidIos.js, packages/app/lib/internal/nativeModuleWeb.js, packages/storage/e2e/helpers.js, tests/app.js, tests/globals.js
It was not clear how to examine analytics events while developing apps, especially while using "other" platform support
None logged, customer report
single conventional commit, ready for rebase merge
Docs only - passes lint and spellcheck locally
---
=> docs(analytics, other): explain realtime view and debugview usage

packages/remote-config/__tests__/remote-config.test.ts, packages/remote-config/lib/index.js, packages/remote-config/lib/modular/index.d.ts, packages/remote-config/lib/modular/index.js, packages/remote-config/lib/statics.js
=> fix(remote-config): ensure static objects are exposed for modular API

packages/messaging/__tests__/messaging.test.ts, packages/messaging/lib/index.js, packages/messaging/lib/modular/index.d.ts, packages/messaging/lib/modular/index.js, packages/messaging/lib/statics.js
Addresses type issue discussed here: https://github.com/invertase/react-native-firebase/discussions/8311#discussioncomment-12114864
---
=> fix(messaging): 3 statics not correctly exported

packages/storage/__tests__/storage.test.ts, packages/storage/lib/StorageReference.js, packages/storage/lib/StorageStatics.js, packages/storage/lib/StorageTask.js, packages/storage/lib/index.js, packages/storage/lib/modular/index.d.ts, packages/storage/lib/modular/index.js
=> fix(storage): expose static types for modular API

packages/database/lib/modular/index.js
closes https://github.com/invertase/react-native-firebase/issues/8375
---
=> fix(database): fix increment not defined

packages/perf/lib/modular/index.d.ts, packages/perf/lib/modular/index.js
Make it match JS Docs.
https://firebase.google.com/docs/reference/js/performance.md#getperformance_cf608e1
---
=> fix(performance): Made settings parameter options in initializePerformance

docs/index.md, packages/app-distribution/android/build.gradle, packages/app/package.json
- includes bump to app distribution version
Single conventional commit with fix tag to trigger release
Nothing in the release notes looks very interesting at the react-native-firebase level except streamable callable functions (which is tracked in a separate issue #8210 )
If CI passes I will consider this good to go
--- …
=> fix(android): adopt firebase-android-sdk 33.11.0

packages/app/lib/modular/index.d.ts, packages/app/lib/modular/index.js
=> fix(app): App type def fix

docs/index.md
=> docs: Add instructions for iOS AppDelegate.swift on react-native 0.77

.spellcheck.dict.txt, docs/faqs-and-tips.md
note about setBackgroundMessageHandler is outdated, all those fixes are released now after collaboration with core team / release group
none logged
docs update only, no release
formatting + markdown lint passed locally
---
=> docs(tips-n-tricks): update new arch to note no current problems

docs/app-check/usage/index.md
=> docs(app-check): update `initializeApp` example to include proper params

docs/index.md
The previous note wasn't quite accurate / thorough
- Supercedes #8310
just a docs fix
checked lint and spelling locally
---
=> docs(app, expo): clarify note about handling previous Expo dev builds

docs/vertexai/usage/index.md
Keep VertexAI Docs up to date with usage.
---
=> docs: update vertexai instantiation docs

packages/storage/lib/index.d.ts
closes https://github.com/invertase/react-native-firebase/issues/8446 
---
=> docs(storage): cacheControl correct link

packages/auth/plugin/__tests__/iosPlugin_urlTypes.test.ts, packages/auth/plugin/src/ios/urlTypes.ts
=> fix(auth): Make REVERSED_CLIENT_ID optional

packages/auth/plugin/src/ios/urlTypes.ts
=> chore(auth): fix typo in Expo plugin error message

docs/index.md
Altered documentation to describe the right method being changed
---
=> Correct method name

docs/index.md, packages/app/package.json, tests/ios/Podfile.lock
Just SDK updates
One conventional commit that will generate a patch release here if rebase merged + released
Passed e2e tests locally, if it passes CI it should be good to go
---
=> fix(app): firebase-android-sdk 33.14.0 / firebase-ios-sdk 11.13.0

packages/auth/lib/modular/index.d.ts, packages/auth/lib/modular/index.js
Hi,
Just updating the Intellisense JSDoc on `useUserAccessGroup` because I noticed it was wrong haha, it was a copy paste from the above function, happens :)
---
🔥
=> fix(auth, ios): useUserAccessGroup JSDoc description was wrong

docs/migrating-to-v23.md, packages/app/package.json, yarn.lock
=> feat!: bump firebase-js-sdk to `12.0.0`

packages/app/package.json, tests/package.json, yarn.lock
=> fix(app): adopt firebase-js-sdk 12.2.1

README.md, packages/vertexai/README.md
=> chore(vertexai): show deprecation in readme
